<?php
require_once __DIR__ . '/../config/db.php';
echo "=== Inserindo questões de Português 1 ===\n\n";

$questions = [
    // [81] Compreensão e Interpretação de Texto
    [81, 'ENEM 2023', 'Leia o trecho: "A cidade acordou cinza, mas o coração dos seus habitantes pulsava em cores vibrantes, contrastando com o cimento das calçadas." Qual é a ideia principal do texto?', 'A cidade estava coberta de neve.', 'Os habitantes sentiam tristeza profunda.', 'Apesar do ambiente urbano sem cor, as pessoas estavam animadas e cheias de vida.', 'As calçadas foram pintadas de cores vibrantes.', 'O cimento urbano impede a felicidade das pessoas.', 'c', 'O texto contrasta a cor cinza da cidade (física) com as "cores vibrantes" do coração das pessoas, indicando animação apesar do ambiente.', 'fácil', 0],
    [81, 'UNICAMP 2024', 'Considere a manchete: "Governo recua e cancela aumento de impostos após pressão popular." O que se pode inferir sobre o evento?', 'O governo tomou a decisão de forma autônoma e planejada.', 'A população apoiou o aumento dos impostos.', 'A decisão do governo foi influenciada diretamente pela mobilização da sociedade.', 'Os impostos foram aumentados apesar da pressão popular.', 'A pressão popular não teve efeito sobre o governo.', 'c', 'O uso da palavra "após" e "pressão popular" indica uma relação de causa e efeito entre a ação da sociedade e o recuo do governo.', 'médio', 0],
    [81, 'USP (FUVEST) 2023', 'No poema "A máquina do mundo" de Drummond, o eu lírico depara-se com uma revelação universal enquanto caminha por uma estrada de Minas. Essa revelação é:', 'Aceita com alegria e alívio pelo eu lírico.', 'Recusada pelo eu lírico, que prefere seguir seu caminho na ignorância e no cansaço.', 'Compreendida apenas parcialmente, deixando o eu lírico confuso.', 'Compartilhada com outros habitantes da região.', 'Uma ilusão criada pela mente exausta do poeta.', 'b', 'No poema, o eu lírico, tomado pelo cansaço e ceticismo, recusa a oferta da "máquina do mundo", preferindo continuar sua caminhada árida.', 'difícil', 1],
    [81, 'UNESP 2024', 'Ao analisar um cartum em que um homem carrega um relógio gigante nas costas enquanto corre em uma esteira, a crítica principal dirige-se a:', 'A importância de se exercitar diariamente.', 'A escravidão do homem moderno em relação ao tempo e à rotina.', 'A evolução da tecnologia dos relógios.', 'A necessidade de pontualidade no ambiente de trabalho.', 'O sedentarismo da sociedade atual.', 'b', 'O peso do relógio gigante e o ato de correr em uma esteira (sem sair do lugar) simbolizam a opressão do tempo e a rotina exaustiva na modernidade.', 'médio', 0],
    [81, 'ENEM 2022', 'Em uma receita culinária que diz "leve ao forno brando até dourar", a expressão "até dourar" funciona como:', 'Uma instrução de tempo exato em minutos.', 'Uma condição subjetiva baseada no aspecto visual do alimento.', 'Uma restrição sobre o tipo de forno a ser utilizado.', 'Uma garantia de que o prato ficará saboroso.', 'Uma proibição de abrir o forno antes do tempo.', 'b', '"Até dourar" não determina um tempo preciso (minutos), mas indica que o ponto ideal deve ser avaliado visualmente pelo cozinheiro.', 'fácil', 0],

    // [82] Coesão e Coerência Textual
    [82, 'ENEM 2023', 'No período "Estudou muito; logo, foi aprovado", a conjunção "logo" estabelece uma relação de:', 'Causa', 'Condição', 'Oposição', 'Conclusão', 'Adição', 'd', 'A palavra "logo" funciona como conjunção conclusiva, indicando que a aprovação foi o resultado/conclusão do fato de ter estudado muito.', 'fácil', 0],
    [82, 'UNICAMP 2024', 'Assinale a alternativa em que a substituição do conectivo altera o sentido original da frase "Embora chovesse, fomos à praia":', 'Ainda que chovesse, fomos à praia.', 'Conquanto chovesse, fomos à praia.', 'Mesmo que chovesse, fomos à praia.', 'Como chovesse, fomos à praia.', 'Apesar de chover, fomos à praia.', 'd', 'O conectivo "como" introduz causa (já que chovia), alterando a relação original de concessão estabelecida por "embora", "ainda que", "conquanto", "mesmo que" e "apesar de".', 'médio', 0],
    [82, 'USP (FUVEST) 2023', 'No trecho "A menina comprou um livro. Ela leu a obra em dois dias", os termos "Ela" e "a obra" são recursos de coesão, respectivamente:', 'Lexical e gramatical', 'Gramatical (pronominal) e lexical (sinonímia)', 'Lexical e lexical', 'Gramatical e gramatical', 'Elíptica e gramatical', 'b', '"Ela" retoma "A menina" por meio de um pronome (coesão gramatical). "A obra" retoma "livro" por meio de um sinônimo (coesão lexical).', 'médio', 0],
    [82, 'UNESP 2024', 'Qual das frases apresenta um problema de coerência textual?', 'O sol estava muito forte, por isso passamos protetor solar.', 'Ele não tinha dinheiro, portanto comprou o carro à vista.', 'Como estava doente, não foi ao trabalho hoje.', 'Estudou bastante, mas não conseguiu boa nota.', 'Sempre foi vegetariano, de modo que recusou o churrasco.', 'b', 'Há incoerência na frase, pois quem não tem dinheiro não pode realizar uma compra de alto valor "à vista" (pagamento integral no ato).', 'fácil', 0],
    [82, 'ENEM 2023', 'Na frase "O projeto foi cancelado. Isso frustrou a equipe", o pronome "Isso" exerce função coesiva:', 'Catafórica, antecipando o cancelamento.', 'Exofórica, referindo-se a algo fora do texto.', 'Anafórica, retomando toda a oração anterior.', 'Epifórica, repetindo o sujeito.', 'Dêitica, indicando o lugar da ação.', 'c', 'O pronome "Isso" retoma uma ideia já expressa anteriormente no texto (o fato de o projeto ter sido cancelado), caracterizando a coesão anafórica.', 'difícil', 1],

    // [83] Tipologias e Gêneros Textuais
    [83, 'ENEM 2023', 'Um texto que apresenta os passos para a montagem de um móvel pertence predominantemente à tipologia:', 'Narrativa', 'Descritiva', 'Dissertativa-argumentativa', 'Injuntiva', 'Expositiva', 'd', 'A tipologia injuntiva (ou instrucional) caracteriza-se por dar ordens, orientar ou ensinar o leitor a realizar uma ação (ex: manuais, receitas).', 'fácil', 0],
    [83, 'UNICAMP 2024', 'Uma reportagem de revista que relata o aumento do desmatamento e apresenta dados estatísticos para informar o leitor é do gênero e tipo:', 'Notícia e tipologia descritiva.', 'Editorial e tipologia injuntiva.', 'Reportagem e tipologia expositiva.', 'Crônica e tipologia narrativa.', 'Artigo de opinião e tipologia dissertativa-argumentativa.', 'c', 'A reportagem visa informar aprofundadamente sobre um tema. O uso de dados para expor fatos sem necessariamente tentar convencer o leitor caracteriza a tipologia expositiva.', 'médio', 0],
    [83, 'USP (FUVEST) 2023', 'Em um artigo de opinião, o autor não apenas expõe fatos, mas também se posiciona criticamente. A tipologia predominante é:', 'Narrativa', 'Expositiva', 'Dissertativa-argumentativa', 'Injuntiva', 'Dialogal', 'c', 'O artigo de opinião exige a defesa de um ponto de vista com argumentos, o que define a tipologia dissertativa-argumentativa.', 'fácil', 0],
    [83, 'UNESP 2024', 'Qual das características abaixo é essencial ao gênero textual "resenha crítica"?', 'Ausência total de opiniões pessoais.', 'Estrutura em versos e estrofes.', 'Apresentação de uma obra acompanhada de avaliação sobre ela.', 'Uso exclusivo de verbos no imperativo.', 'Relato de acontecimentos do cotidiano de forma humorística.', 'c', 'A resenha crítica difere do resumo por incluir, além da síntese da obra, um julgamento de valor ou avaliação crítica feita pelo autor.', 'médio', 0],
    [83, 'ENEM 2022', 'O conto, a fábula e o romance são gêneros textuais que têm em comum a tipologia predominante:', 'Descritiva', 'Dissertativa', 'Injuntiva', 'Narrativa', 'Expositiva', 'd', 'Todos esses gêneros caracterizam-se por relatar uma sequência de acontecimentos envolvendo personagens no tempo e no espaço, o que define a narração.', 'difícil', 1],

    // [84] Variação Linguística e Preconceito Linguístico
    [84, 'ENEM 2023', 'A fala "Nós vai no mercado amanhã" é um exemplo de variação:', 'Diacrônica (histórica)', 'Diatópica (regional)', 'Diastrática (social)', 'Diafásica (situacional)', 'Diamésica (meio)', 'c', 'A concordância verbal não padrão ("nós vai") está frequentemente associada ao grau de escolaridade ou grupo social, sendo uma variação diastrática.', 'fácil', 0],
    [84, 'UNICAMP 2024', 'Chamar "mandioca" de "aipim" ou "macaxeira" é um fenômeno linguístico classificado como variação:', 'Diatópica (regional)', 'Diastrática (social)', 'Diacrônica (histórica)', 'Diafásica (situacional)', 'Estilística', 'a', 'Diferenças de vocabulário dependendo da região geográfica (ex: Brasil) caracterizam a variação diatópica ou regional.', 'fácil', 0],
    [84, 'USP (FUVEST) 2023', 'O uso da palavra "vosmecê" na literatura de época, que hoje se transformou em "você", ilustra uma variação:', 'Geográfica', 'Social', 'Histórica', 'Situacional', 'Jargão', 'c', 'A mudança de uma palavra ou forma ao longo do tempo (evolução da língua) é chamada de variação diacrônica ou histórica.', 'médio', 0],
    [84, 'UNESP 2024', 'Considerar que uma pessoa é menos inteligente por falar com sotaque nordestino é um exemplo claro de:', 'Variação diafásica', 'Preconceito linguístico', 'Norma-padrão', 'Neologismo', 'Adequação linguística', 'b', 'O preconceito linguístico ocorre quando há discriminação baseada na forma como uma pessoa fala, associando variações (como o sotaque) a falta de intelecto ou status.', 'médio', 0],
    [84, 'ENEM 2023', 'Um advogado utilizando linguagem jurídica rebuscada ao falar com um juiz e linguagem coloquial ao falar com seu filho demonstra o domínio da variação:', 'Diacrônica', 'Diatópica', 'Diafásica', 'Diamésica', 'Lexical', 'c', 'A capacidade de adaptar a linguagem ao contexto ou à situação comunicativa (formal vs. informal) é a variação diafásica ou situacional.', 'difícil', 1],

    // [85] Ambiguidade e Polissemia
    [85, 'ENEM 2023', 'Na frase "O policial prendeu o ladrão em sua casa", a ambiguidade ocorre devido:', 'À polissemia da palavra "prendeu".', 'Ao uso inadequado do artigo.', 'Ao pronome possessivo "sua", que não deixa claro de quem é a casa.', 'Ao verbo no tempo passado.', 'À falta de pontuação.', 'c', 'O pronome "sua" pode se referir tanto ao policial quanto ao ladrão, gerando duplo sentido (ambiguidade estrutural).', 'fácil', 0],
    [85, 'UNICAMP 2024', 'A palavra "banco" pode significar a instituição financeira ou o assento. Esse fenômeno de multiplicidade de sentidos de uma mesma palavra é chamado de:', 'Sinonímia', 'Antonímia', 'Polissemia', 'Paronímia', 'Homofonia', 'c', 'Polissemia é a propriedade de uma mesma palavra ter vários significados relacionados pelo contexto (banco de sentar, banco de dinheiro, banco de dados).', 'fácil', 0],
    [85, 'USP (FUVEST) 2023', 'Leia: "Vi o incêndio do prédio". A ambiguidade dessa frase reside no fato de que:', 'Não se sabe quem viu o incêndio.', 'Pode significar que o prédio estava pegando fogo ou que a pessoa estava dentro do prédio vendo um incêndio lá fora.', 'A palavra "incêndio" é polissêmica.', '"Vi" pode ser o verbo ver ou vir.', 'A frase está no sentido conotativo.', 'b', 'A preposição "do" causa ambiguidade sintática: o prédio pode ser o paciente da ação (está pegando fogo) ou o lugar de onde a ação de ver ocorreu.', 'médio', 0],
    [85, 'UNESP 2024', 'No título "A rede que nos une e nos prende", a palavra "rede" adquire sentidos diferentes. Trata-se de um recurso de:', 'Metáfora baseada na homonímia.', 'Polissemia explorada para gerar efeito de sentido.', 'Ambiguidade viciosa.', 'Pleonasmo intencional.', 'Paradoxo estrutural.', 'b', 'A palavra "rede" tem seus vários significados acionados no contexto (rede de internet/conexão e rede de aprisionar/capturar), sendo um caso de polissemia.', 'médio', 0],
    [85, 'ENEM 2022', 'Qual das alternativas apresenta uma ambiguidade semântica (lexical) e não estrutural?', 'O pai viu a filha com seu namorado.', 'Maria encontrou João correndo.', 'A cadela da sua mãe sumiu.', 'Ele pediu um prato de pedreiro.', 'O menino cortou a manga.', 'e', '"Manga" é uma palavra polissêmica/homônima (pode ser a fruta ou a parte da camisa), gerando ambiguidade lexical independente da estrutura da frase.', 'difícil', 1],

    // [86] Classes Gramaticais de Palavras
    [86, 'ENEM 2023', 'Na frase "Os rápidos corredores venceram a prova", a palavra "rápidos" funciona como:', 'Substantivo', 'Adjetivo', 'Advérbio', 'Pronome', 'Verbo', 'b', '"Rápidos" está caracterizando o substantivo "corredores", portanto, exerce a função de adjetivo.', 'fácil', 0],
    [86, 'UNICAMP 2024', 'No trecho "Eles correm rápido", a palavra "rápido" pertence à classe dos:', 'Substantivos', 'Adjetivos', 'Advérbios', 'Preposições', 'Conjunções', 'c', 'Neste contexto, "rápido" não modifica um substantivo, mas o verbo "correm", indicando o modo como correm, logo, é um advérbio.', 'médio', 0],
    [86, 'USP (FUVEST) 2023', 'Assinale a alternativa onde a palavra "meio" atua como advérbio:', 'Bebi meio copo de água.', 'O relógio bateu meio-dia e meia.', 'Encontrei o meio de resolver o problema.', 'Ela estava meio triste ontem.', 'Comprou meia dúzia de ovos.', 'd', 'Como advérbio de intensidade (um pouco), a palavra "meio" modifica o adjetivo "triste" e é invariável.', 'médio', 0],
    [86, 'UNESP 2024', 'Na frase "O olhar dela era cativante", a palavra "olhar", que originalmente é um verbo, sofreu um processo de derivação imprópria. Nesse caso, tornou-se:', 'Adjetivo', 'Substantivo', 'Advérbio', 'Pronome', 'Preposição', 'b', 'A presença do artigo "O" substantivou o verbo "olhar", tornando-o o núcleo do sujeito.', 'fácil', 0],
    [86, 'ENEM 2022', 'Em "O QUE importa é que você venha", os dois "ques" classficam-se, correta e respectivamente, como:', 'Pronome relativo e conjunção integrante.', 'Conjunção integrante e pronome relativo.', 'Pronome interrogativo e conjunção coordenativa.', 'Partícula expletiva e pronome relativo.', 'Pronome relativo e preposição.', 'a', 'O primeiro "que" retoma o pronome demonstrativo "O" (Aquilo que importa), sendo pronome relativo. O segundo introduz uma oração subordinada substantiva (é que você venha), sendo conjunção integrante.', 'difícil', 1],

    // [87] Sintaxe: Sujeito, Predicado e Complementos
    [87, 'ENEM 2023', 'Em "Choveu muito ontem à noite", o sujeito da oração é:', 'Simples', 'Composto', 'Oculto (elíptico)', 'Indeterminado', 'Inexistente (Oração sem sujeito)', 'e', 'Verbos que indicam fenômenos da natureza (como chover), quando usados em sentido denotativo, formam orações sem sujeito.', 'fácil', 0],
    [87, 'UNICAMP 2024', 'Na oração "O professor entregou as provas aos alunos", o termo "aos alunos" exerce a função sintática de:', 'Objeto direto', 'Objeto indireto', 'Complemento nominal', 'Adjunto adverbial', 'Predicativo do sujeito', 'b', 'O verbo "entregar" é transitivo direto e indireto. "As provas" é o que foi entregue (objeto direto) e "aos alunos" indica a quem, acompanhado de preposição (objeto indireto).', 'fácil', 0],
    [87, 'USP (FUVEST) 2023', 'Identifique o predicativo do sujeito na frase: "Os alunos chegaram exaustos ao colégio".', 'Os alunos', 'chegaram', 'exaustos', 'ao colégio', 'chegaram exaustos', 'c', '"Exaustos" atribui uma característica, um estado ao sujeito "Os alunos" no momento da ação, funcionando como predicativo do sujeito (predicado verbo-nominal).', 'médio', 0],
    [87, 'UNESP 2024', 'Na frase "A obediência às leis é fundamental", o termo "às leis" funciona como:', 'Objeto indireto', 'Complemento nominal', 'Adjunto adnominal', 'Agente da passiva', 'Aposto', 'b', '"Às leis" completa o sentido de um substantivo abstrato ("obediência"), sendo paciente da ação de obedecer, o que caracteriza o complemento nominal.', 'difícil', 1],
    [87, 'ENEM 2022', 'Qual a classificação do sujeito em "Precisa-se de novos funcionários"?', 'Sujeito simples', 'Sujeito oculto', 'Sujeito indeterminado', 'Oração sem sujeito', 'Sujeito paciente', 'c', 'O verbo transitivo indireto (precisa) acompanhado do índice de indeterminação do sujeito "se" e de preposição "de" configura sujeito indeterminado.', 'médio', 0],

    // [88] Crase e Regência Verbal/Nominal
    [88, 'ENEM 2023', 'Assinale a alternativa em que o uso da crase está CORRETO:', 'Fui à cidade comprar frutas.', 'Fui a pé até à escola.', 'Ele se referiu à você.', 'Entreguei o livro à ela.', 'Vou à São Paulo.', 'a', 'Ocorre crase na contração da preposição "a" (quem vai, vai A algum lugar) com o artigo feminino "a" (A cidade). "A pé" é masculino, "você/ela" são pronomes que não admitem artigo, "São Paulo" não admite artigo feminino.', 'fácil', 0],
    [88, 'UNICAMP 2024', 'O verbo "assistir" no sentido de "ver, presenciar" exige qual regência?', 'Transitivo direto (sem preposição).', 'Transitivo indireto (com preposição "a").', 'Transitivo indireto (com preposição "com").', 'Intransitivo.', 'Transitivo direto e indireto.', 'b', 'No sentido de ver, "assistir" exige preposição A: "Assistimos ao filme".', 'médio', 0],
    [88, 'USP (FUVEST) 2023', 'Em relação à regência do verbo "implicar" no sentido de "acarretar, ter como consequência", assinale a opção correta:', 'A decisão implicará em demissões.', 'A decisão implicará a demissões.', 'A decisão implicará demissões.', 'A decisão implicará com demissões.', 'A decisão implicará para demissões.', 'c', 'No sentido de acarretar, o verbo "implicar" é transitivo direto, não exigindo preposição.', 'médio', 0],
    [88, 'UNESP 2024', 'Indique a frase em que a crase é facultativa:', 'Fomos à praia no domingo.', 'Chegamos à uma hora da tarde.', 'Entregou o documento à própria diretora.', 'Dei o presente à minha mãe.', 'Referiu-se àquele menino.', 'd', 'Antes de pronomes possessivos femininos no singular (como "minha"), o uso do artigo é opcional, tornando a crase facultativa.', 'difícil', 1],
    [88, 'ENEM 2022', 'Qual verbo apresenta regência correta na norma-padrão?', 'Eu prefiro mais doce do que salgado.', 'Eu prefiro doce que salgado.', 'Eu prefiro doce a salgado.', 'Eu prefiro mil vezes doce a salgado.', 'Eu prefiro mais doce a salgado.', 'c', 'O verbo "preferir" é transitivo direto e indireto na norma-padrão. Não admite intensificadores ("mais", "mil vezes") e exige a preposição "a" (preferir algo A outra coisa).', 'fácil', 0],

    // [89] Concordância Verbal e Nominal
    [89, 'ENEM 2023', 'Complete corretamente: "_____ fazer cinco anos que não o vejo".', 'Vai', 'Vão', 'Vão fazer', 'Faz', 'Fazem', 'a', 'O verbo "fazer" indicando tempo decorrido é impessoal (fica no singular). Em locuções verbais, transmite a impessoalidade ao auxiliar. Logo: "Vai fazer".', 'médio', 0],
    [89, 'UNICAMP 2024', 'Assinale a alternativa com ERRO de concordância nominal:', 'Ela mesma preparou o jantar.', 'Seguem anexos os documentos solicitados.', 'É proibida entrada de pessoas estranhas.', 'Muito obrigada, disse a moça.', 'A porta estava meio aberta.', 'c', 'O correto seria "É proibido entrada" (pois "entrada" está sem artigo) ou "É proibida a entrada" (com artigo feminino).', 'médio', 0],
    [89, 'USP (FUVEST) 2023', 'A concordância verbal está correta em:', 'Houveram muitos problemas na reunião.', 'Faz dez anos que nos formamos.', 'Devem haver soluções melhores.', 'Alugam-se apartamento na praia.', 'Faltou apenas dois dias para o fim do prazo.', 'b', 'O verbo "fazer" indicando tempo é impessoal e fica no singular. "Haver" no sentido de existir também (Houve). "Alugar" com pronome apassivador concorda com o sujeito paciente (Alugam-se apartamentos).', 'fácil', 0],
    [89, 'UNESP 2024', 'Qual a concordância correta para a frase: "A maior parte dos alunos _____ na prova"?', 'reprovou', 'reprovaram', 'reprovou ou reprovaram (ambas estão corretas)', 'reprovasse', 'reprovassem', 'c', 'Com expressões partitivas (a maior parte de, a maioria de) seguidas de substantivo no plural, o verbo pode ficar no singular (concordando com o núcleo "parte") ou no plural (concordando com o especificador "alunos").', 'difícil', 1],
    [89, 'ENEM 2022', 'Na oração "Eu e tu _____ a tarefa", o verbo deve ir para:', 'farei', 'fará', 'faremos', 'fareis', 'farão', 'c', 'O sujeito composto "Eu e tu" equivale a "Nós", pois a primeira pessoa ("Eu") prevalece sobre as demais. Logo, o verbo concorda na 1ª pessoa do plural: faremos.', 'fácil', 0],

    // [90] Pontuação e Emprego da Vírgula
    [90, 'ENEM 2023', 'A vírgula está empregada INCORRETAMENTE na frase:', 'Maria, a aluna mais aplicada, tirou dez.', 'Compramos pão, queijo, leite e café.', 'Os alunos, estudaram muito para a prova.', 'Quando cheguei, a festa já tinha começado.', 'São Paulo, 15 de maio de 2023.', 'c', 'Não se pode separar o sujeito (Os alunos) do seu respectivo verbo/predicado (estudaram) com vírgula.', 'fácil', 0],
    [90, 'UNICAMP 2024', 'Em "O cachorro, que estava doente, foi levado ao veterinário", o uso das vírgulas indica que:', 'Existem vários cachorros e apenas o que estava doente foi levado (oração restritiva).', 'Apenas um cachorro existe na situação, e a informação de que ele estava doente é adicional (oração explicativa).', 'A oração está na ordem indireta.', 'Há um vocativo na frase.', 'A vírgula substitui um verbo omitido.', 'b', 'As orações subordinadas adjetivas isoladas por vírgulas são EXPLICATIVAS. Se referem a um ser único no contexto, adicionando um detalhe.', 'médio', 0],
    [90, 'USP (FUVEST) 2023', 'A supressão da vírgula altera o sentido da frase em:', 'De repente, a luz apagou.', 'Os manifestantes que eram pacíficos foram liberados.', 'Durante a aula, não houve interrupções.', 'Ele, porém, não concordou.', 'Felizmente, todos chegaram bem.', 'b', 'Se a frase fosse "Os manifestantes, que eram pacíficos, foram liberados" (com vírgulas), significaria que TODOS eram pacíficos. Sem vírgulas (restritiva), significa que APENAS OS QUE ERAM pacíficos foram liberados.', 'difícil', 1],
    [90, 'UNESP 2024', 'Qual frase apresenta o uso correto do ponto e vírgula (;)?', 'Comprei maçãs; peras e uvas.', 'Ele estudou bastante; no entanto, não passou.', 'Eu gosto de bolo de; chocolate.', 'Amanhã irei ao parque; andar de bicicleta.', 'Quando ele chegou; todos saíram.', 'b', 'O ponto e vírgula é usado corretamente antes de conjunções adversativas (no entanto, porém, contudo) que separam orações coordenadas extensas ou para dar uma pausa maior.', 'médio', 0],
    [90, 'ENEM 2022', 'Em "João, traga-me o livro", a vírgula é utilizada para isolar:', 'Um aposto', 'Um adjunto adverbial', 'Um predicativo', 'Um vocativo', 'O sujeito', 'd', '"João" é o chamamento, o termo a quem a mensagem é dirigida, classificando-se como vocativo, que sempre deve ser isolado por vírgula.', 'fácil', 0],

    // [91] Figuras de Linguagem (Metáfora, Metonímia, Ironia)
    [91, 'ENEM 2023', 'Na frase "Aquele rapaz é um leão nos estudos", a figura de linguagem presente é:', 'Metáfora', 'Metonímia', 'Hipérbole', 'Eufemismo', 'Pleonasmo', 'a', 'A metáfora é uma comparação implícita (sem uso do conectivo "como"). O rapaz recebe as qualidades do leão.', 'fácil', 0],
    [91, 'UNICAMP 2024', 'Ler Machado de Assis é essencial para entender a literatura brasileira. A expressão "Ler Machado de Assis" é um exemplo de:', 'Ironia', 'Paradoxo', 'Metonímia', 'Metáfora', 'Prosopopeia', 'c', 'Ocorre metonímia (o autor pela obra). Ninguém lê a pessoa Machado de Assis, mas sim os livros escritos por ele.', 'médio', 0],
    [91, 'USP (FUVEST) 2023', 'Em "Que belo comportamento o seu! Gritando no meio do teatro!", a figura de linguagem destacada pelo contexto é:', 'Antítese', 'Ironia', 'Hipérbole', 'Eufemismo', 'Catacrese', 'b', 'A ironia consiste em afirmar o contrário do que se quer dizer (chamar de "belo" um comportamento inadequado).', 'fácil', 0],
    [91, 'UNESP 2024', 'Ao dizer "Estou morrendo de sede", utiliza-se um recurso de exagero intencional conhecido como:', 'Eufemismo', 'Ironia', 'Hipérbole', 'Gradação', 'Onomatopeia', 'c', 'A hipérbole é a figura do exagero, usada para enfatizar a intensidade da sede.', 'fácil', 0],
    [91, 'ENEM 2022', 'No verso "O vento beijava meus cabelos", a atribuição de ação humana a um ser inanimado chama-se:', 'Pleonasmo', 'Sinestesia', 'Paradoxo', 'Prosopopeia (Personificação)', 'Antítese', 'd', 'Atribuir a ação de "beijar" ao vento (ser inanimado) é uma personificação ou prosopopeia.', 'difícil', 1],

    // [92] Funções da Linguagem (Referencial, Emotiva, Poética)
    [92, 'ENEM 2023', 'Em uma notícia de jornal que relata dados sobre a economia sem expressar opiniões, predomina a função:', 'Emotiva', 'Conativa (Apelativa)', 'Fática', 'Referencial', 'Metalinguística', 'd', 'A função referencial ou denotativa foca no contexto e na informação objetiva, sendo típica de textos jornalísticos e científicos.', 'fácil', 0],
    [92, 'UNICAMP 2024', 'Num anúncio publicitário "Compre nosso produto e seja feliz!", a função da linguagem predominante é:', 'Emotiva', 'Referencial', 'Poética', 'Conativa (Apelativa)', 'Fática', 'd', 'A função conativa foca no receptor (uso de verbos no imperativo), visando convencê-lo a realizar uma ação (comprar).', 'médio', 0],
    [92, 'USP (FUVEST) 2023', 'Em um poema cujas palavras são cuidadosamente escolhidas e dispostas para gerar ritmo, rima e sonoridade especial, predomina a função:', 'Referencial', 'Poética', 'Emotiva', 'Fática', 'Metalinguística', 'b', 'A função poética tem como foco a própria mensagem e a forma como ela é estruturada, usando recursos estéticos e sonoros.', 'fácil', 0],
    [92, 'UNESP 2024', 'Quando um poeta escreve um poema sobre o ato de escrever poesia, está fazendo uso da função:', 'Emotiva', 'Referencial', 'Metalinguística', 'Conativa', 'Fática', 'c', 'A função metalinguística ocorre quando o código é utilizado para explicar ou falar do próprio código (poema sobre poema, dicionário).', 'difícil', 1],
    [92, 'ENEM 2022', '"Alô? Está me ouvindo?". As expressões usadas para testar o canal de comunicação marcam a função:', 'Fática', 'Emotiva', 'Referencial', 'Poética', 'Metalinguística', 'a', 'A função fática foca no canal de comunicação, visando estabelecer, prolongar ou testar o contato com o receptor.', 'fácil', 0],

    // [93] Denotação e Conotação
    [93, 'ENEM 2023', 'Qual das frases abaixo apresenta a palavra "cobra" em seu sentido denotativo?', 'Aquele vendedor é uma cobra, tome cuidado.', 'Minha sogra é uma cobra peçonhenta.', 'A cobra picou o pé do fazendeiro.', 'Fiquei uma cobra de raiva com o atraso.', 'No trânsito, ele age feito uma cobra.', 'c', 'O sentido denotativo é o sentido literal, do dicionário. Na alternativa C, "cobra" refere-se ao animal réptil. Nas demais, é conotação (falsidade, raiva).', 'fácil', 0],
    [93, 'UNICAMP 2024', 'A linguagem conotativa é aquela que:', 'Utiliza as palavras em seu sentido literal e objetivo.', 'É exclusiva de textos jornalísticos.', 'Atribui novos significados às palavras, dependendo do contexto figurado.', 'Não permite múltiplas interpretações.', 'É sinônimo de linguagem referencial.', 'c', 'A conotação explora o sentido figurado, poético ou simbólico das palavras, indo além do sentido do dicionário.', 'médio', 0],
    [93, 'USP (FUVEST) 2023', 'Na manchete "Preço do tomate vai às nuvens", a expressão "vai às nuvens" está empregada no sentido:', 'Denotativo, indicando a altura física dos tomates.', 'Denotativo, indicando clima chuvoso.', 'Conotativo, significando que o preço está muito alto.', 'Conotativo, referindo-se a tomates transportados por avião.', 'Literal, apontando inflação atmosférica.', 'c', '"Ir às nuvens" é uma expressão conotativa que significa que algo encareceu excessivamente.', 'fácil', 0],
    [93, 'UNESP 2024', 'Marque a opção que apresenta apenas sentido denotativo.', 'O coração de Pedro é de gelo.', 'Os olhos dela eram oceanos de tristeza.', 'A água ferve a cem graus Celsius.', 'A vida é um palco iluminado.', 'Ele quebrou o galho para mim no trabalho.', 'c', 'A alternativa C apresenta um fato científico, utilizando as palavras no seu sentido estritamente literal e objetivo.', 'fácil', 0],
    [93, 'ENEM 2022', 'Em um texto literário, o uso da conotação tem como principal objetivo:', 'Transmitir dados estatísticos com precisão.', 'Evitar ambiguidades na interpretação.', 'Garantir a objetividade da narração.', 'Ampliar as possibilidades de sentido e criar imagens poéticas.', 'Facilitar a leitura para o público infantil.', 'd', 'Na literatura, a conotação enriquece o texto ao permitir múltiplas interpretações, figuras de linguagem e apelo estético.', 'difícil', 1],

    // [94] Intertextualidade e Paródia
    [94, 'ENEM 2023', 'O poema "Canção do Exílio" de Gonçalves Dias ("Minha terra tem palmeiras...") frequentemente serve de base para novos poemas. Esse diálogo entre textos chama-se:', 'Coesão', 'Paródia', 'Intertextualidade', 'Plágio', 'Epígrafe', 'c', 'A intertextualidade é o fenômeno em que um texto faz referência explícita ou implícita a outro texto preexistente.', 'fácil', 0],
    [94, 'UNICAMP 2024', 'Quando um programa humorístico recria uma cena famosa de filme mudando o final para provocar risos, utiliza a:', 'Citação', 'Paródia', 'Tradução', 'Paráfrase', 'Epígrafe', 'b', 'A paródia é uma forma de intertextualidade que subverte o sentido do texto original, geralmente com fins humorísticos ou críticos.', 'fácil', 0],
    [94, 'USP (FUVEST) 2023', 'A paráfrase difere da paródia porque a paráfrase:', 'Faz críticas severas ao texto original.', 'É uma cópia literal não autorizada.', 'Mantém o sentido e a intenção do texto original, reescrevendo-o com outras palavras.', 'Subverte o sentido para causar humor.', 'Só pode ocorrer na linguagem não-verbal.', 'c', 'A paráfrase reafirma a ideia do texto fonte usando uma nova estrutura vocabular, sem tom de deboche ou ironia.', 'médio', 0],
    [94, 'UNESP 2024', 'Um anúncio publicitário que usa o quadro "Monalisa", mas coloca um hambúrguer em sua mão, está utilizando a:', 'Paráfrase visual.', 'Intertextualidade por paródia.', 'Citação direta.', 'Plágio descarado.', 'Tradução semiótica simples.', 'b', 'Trata-se de uma intertextualidade que modifica a obra original (Monalisa) de forma cômica/inusitada para fins publicitários, caracterizando a paródia.', 'médio', 0],
    [94, 'ENEM 2022', 'O uso de epígrafes (frases de outros autores no início de um capítulo) em romances é um recurso de:', 'Metalinguagem', 'Plágio intelectual', 'Coesão referencial', 'Intertextualidade', 'Ambiguidade', 'd', 'A epígrafe é uma citação explícita que estabelece um diálogo (intertextualidade) entre a obra lida e a ideia do autor citado.', 'difícil', 1]
];

$stmt = $pdo->prepare("INSERT INTO questions (lesson_id, exam_source, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation_text, difficulty, is_boss) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
$inserted = 0;
$errors = 0;
foreach ($questions as $q) {
    try { 
        $stmt->execute($q); 
        $inserted++; 
    } 
    catch (Exception $e) { 
        $errors++; 
        echo "ERRO: " . $e->getMessage() . "\n"; 
    }
}
echo "\nInseridas: {$inserted} | Erros: {$errors}\n";
