<?php
require_once __DIR__ . '/../config/db.php';
echo "=== Inserindo questões de Português / Literatura / Redação ===\n\n";

$questions = [
    // [95] Redação: Estrutura Dissertativo-Argumentativa
    [95, 'ENEM 2023', 'Em uma redação no modelo ENEM, a proposta de intervenção social é uma exigência que avalia a capacidade do candidato de propor soluções para o problema discutido. Qual dos elementos abaixo NÃO é obrigatório nessa proposta?', 'Agente', 'Ação', 'Citação filosófica', 'Modo/Meio', 'Detalhamento', 'c', 'Na proposta de intervenção do ENEM, os elementos obrigatórios são: agente, ação, modo/meio, efeito e detalhamento. Citações podem enriquecer o texto, mas não são obrigatórias na intervenção.', 'fácil', 0],
    [95, 'UNICAMP 2024', 'Na estrutura de uma dissertação-argumentativa, a tese é o elemento central do texto. Onde ela deve ser obrigatoriamente apresentada de forma clara?', 'No primeiro parágrafo (introdução)', 'Apenas na conclusão', 'Exclusivamente no desenvolvimento', 'Apenas no título do texto', 'Em qualquer parte, desde que no fim de um parágrafo', 'a', 'A tese, que é o posicionamento do autor sobre o tema, deve ser apresentada na introdução para guiar os argumentos subsequentes no desenvolvimento.', 'fácil', 0],
    [95, 'USP (FUVEST) 2023', 'Um argumento de autoridade em uma dissertação-argumentativa consiste em:', 'Citar um dado estatístico inventado para convencer o leitor', 'Apresentar a opinião de um especialista ou instituição reconhecida sobre o assunto', 'Usar perguntas retóricas sem resposta', 'Relatar uma experiência pessoal detalhada', 'Copiar trechos dos textos motivadores', 'b', 'O argumento de autoridade utiliza o prestígio de um especialista, pensador ou instituição para validar a tese defendida.', 'médio', 0],
    [95, 'UNESP 2024', 'Na conclusão de um texto dissertativo-argumentativo tradicional, além de propor uma solução (quando exigido), é fundamental que o autor:', 'Apresente um argumento totalmente novo', 'Retome a tese e sintetize as ideias principais', 'Faça uma crítica aos textos de apoio', 'Termine o texto com uma pergunta reflexiva sem fechamento', 'Escreva uma poesia que resuma o tema', 'b', 'A conclusão serve para fechar o raciocínio, devendo sempre retomar a tese apresentada na introdução e sintetizar os argumentos.', 'médio', 0],
    [95, 'ENEM 2022', 'Qual dos conectivos a seguir é o mais adequado para iniciar o parágrafo de conclusão em uma redação, indicando o fechamento das ideias?', 'Contudo', 'Nesse ínterim', 'Portanto', 'A priori', 'Ademais', 'c', 'O conectivo "portanto" é conclusivo, sendo ideal para iniciar o parágrafo final, indicando que as ideias ali presentes são o resultado do que foi argumentado antes.', 'difícil', 1],

    // [96] Trovadorismo, Humanismo e Quinhentismo
    [96, 'ENEM 2023', 'A Carta de Pero Vaz de Caminha, escrita durante o descobrimento do Brasil, é considerada o principal documento de qual movimento literário?', 'Trovadorismo', 'Barroco', 'Quinhentismo (Literatura de Informação)', 'Humanismo', 'Arcadismo', 'c', 'A Carta de Caminha marca o início do Quinhentismo no Brasil, caracterizada como literatura de informação (ou dos viajantes).', 'fácil', 0],
    [96, 'USP (FUVEST) 2023', 'No Trovadorismo, as cantigas de amigo caracterizam-se por:', 'Eu lírico masculino, declarando amor a uma dama inacessível', 'Eu lírico feminino, lamentando a ausência do amado', 'Crítica social direta, com citação de nomes', 'Temática exclusivamente religiosa e moralizante', 'Narrativas épicas sobre batalhas contra os mouros', 'b', 'Nas cantigas de amigo, embora escritas por homens, o eu lírico é feminino, frequentemente dialogando com a natureza e lamentando a saudade do amigo (amante).', 'médio', 0],
    [96, 'UNICAMP 2024', 'Gil Vicente, principal autor do teatro humanista português, destacou-se por escrever autos e farsas. Qual é a principal característica de sua obra "Auto da Barca do Inferno"?', 'A exaltação irrestrita da nobreza e do clero', 'A crítica moralizante aos diferentes estamentos da sociedade', 'O uso exclusivo de versos decassílabos', 'A defesa da Reforma Protestante', 'O foco na mitologia greco-romana', 'b', 'O Auto da Barca do Inferno faz uma sátira e crítica moralizante de várias classes sociais (padre, fidalgo, sapateiro, etc.) através do julgamento após a morte.', 'médio', 0],
    [96, 'UNESP 2024', 'No contexto do Quinhentismo no Brasil, os jesuítas, como Padre José de Anchieta, produziram uma literatura com o objetivo principal de:', 'Informar a coroa portuguesa sobre as riquezas minerais', 'Entreter os colonos europeus', 'Catequizar os indígenas e consolidar a fé católica', 'Registrar a fauna e flora local com rigor científico', 'Criticar a escravidão indígena', 'c', 'A literatura jesuítica (ou de catequese) tinha função pedagógica e religiosa, visando a conversão dos nativos.', 'fácil', 0],
    [96, 'USP (FUVEST) 2022', 'Nas cantigas de escárnio e de maldizer do Trovadorismo ibérico, a principal diferença entre elas reside no fato de que:', 'A cantiga de escárnio usa linguagem direta e palavras de baixo calão', 'A cantiga de maldizer faz uma crítica indireta e irônica, sem citar o nome da pessoa', 'A cantiga de escárnio apresenta crítica velada e irônica, enquanto a de maldizer é direta e frequentemente ofensiva', 'A cantiga de maldizer trata apenas de temas religiosos', 'A cantiga de escárnio foca apenas nos reis e nobres', 'c', 'Escárnio utiliza ironia e duplo sentido, não citando o alvo diretamente. Maldizer é direta, agressiva, cita nomes e usa linguagem chula.', 'difícil', 1],

    // [97] Barroco e Arcadismo no Brasil
    [97, 'ENEM 2023', 'O Barroco brasileiro teve como principal representante na poesia lírica e satírica:', 'Tomás Antônio Gonzaga', 'Gregório de Matos Guerra', 'Cláudio Manuel da Costa', 'Basílio da Gama', 'Padre Antônio Vieira', 'b', 'Gregório de Matos, o "Boca do Inferno", é o grande nome da poesia barroca no Brasil, destacando-se na lírica e na sátira.', 'fácil', 0],
    [97, 'USP (FUVEST) 2023', 'O Arcadismo, ou Neoclassicismo, opôs-se aos excessos do Barroco. Um dos seus princípios literários latinos é o "Fugere urbem", que significa:', 'A busca pela riqueza material', 'A fuga das cidades em busca de uma vida simples no campo', 'A exaltação da vida na corte', 'O uso de linguagem complexa e rebuscada', 'O conflito entre a fé e a razão', 'b', '"Fugere urbem" (fugir da cidade) representa o ideal árcade de abandonar a corrupção dos centros urbanos pela pureza e simplicidade do ambiente bucólico.', 'fácil', 0],
    [97, 'UNICAMP 2024', 'Em seus sermões, Padre Antônio Vieira utilizava uma linguagem extremamente argumentativa, baseada no raciocínio lógico e na persuasão. Esse estilo barroco é conhecido como:', 'Cultismo', 'Gongorismo', 'Conceptismo', 'Bucolismo', 'Parnasianismo', 'c', 'O Conceptismo caracteriza-se pelo jogo de ideias e raciocínio lógico, sendo a marca registrada dos sermões de Vieira, em oposição ao Cultismo (jogo de palavras).', 'médio', 0],
    [97, 'UNESP 2024', 'A obra "Marília de Dirceu", de Tomás Antônio Gonzaga, é um dos marcos do Arcadismo brasileiro. Qual característica desse movimento está mais presente na obra?', 'Angústia religiosa e medo do inferno', 'Linguagem hiperbólica e paradoxal', 'Pastoralismo e idealização amorosa', 'Nacionalismo exaltado e indianismo', 'Crítica social agressiva e direta', 'c', 'A obra apresenta Dirceu (pastor) idealizando sua amada Marília em um ambiente campestre, traço típico do pastoralismo árcade.', 'médio', 0],
    [97, 'ENEM 2022', 'O poema épico "O Uraguai", de Basílio da Gama, destoa de algumas convenções clássicas seguidas no Arcadismo, principalmente por:', 'Não apresentar heróis ou batalhas', 'Não utilizar estrofes e rimas regulares, optando por versos brancos', 'Ser escrito inteiramente em prosa', 'Focar exclusivamente na mitologia grega', 'Exaltar a figura dos jesuítas no sul do Brasil', 'b', '"O Uraguai" inovou ao não utilizar divisão em estrofes, nem rimas (versos brancos), rompendo com a rigidez formal de obras como "Os Lusíadas". Além disso, critica duramente os jesuítas.', 'difícil', 1],

    // [98] Romantismo e Realismo no Brasil
    [98, 'ENEM 2023', 'A primeira geração do Romantismo no Brasil, caracterizada pelo projeto de construção de uma identidade nacional, teve como figura central o índio. Esse aspecto é chamado de:', 'Bucolismo', 'Condoreirismo', 'Indianismo', 'Mal-do-século', 'Naturalismo', 'c', 'O Indianismo foi a expressão do nacionalismo romântico brasileiro, elegendo o indígena como o herói nacional, equivalente ao cavaleiro medieval europeu.', 'fácil', 0],
    [98, 'USP (FUVEST) 2023', 'A obra "Memórias Póstumas de Brás Cubas" (1881), de Machado de Assis, inaugurou o Realismo no Brasil. Qual característica abaixo é marcante nesse romance?', 'Idealização da mulher e do amor', 'Uso da ironia e pessimismo na análise do comportamento humano', 'Enredo focado na exaltação da natureza brasileira', 'Narrativa linear e previsível, com final feliz', 'Exagero na manifestação de sentimentos', 'b', 'Machado de Assis rompe com o Romantismo usando ironia, pessimismo, análise psicológica e o inusitado narrador defunto, criticando a hipocrisia social.', 'médio', 0],
    [98, 'UNICAMP 2024', 'No romance "O Cortiço", de Aluísio Azevedo, o comportamento dos personagens é frequentemente explicado pelo meio ambiente, pela raça e pelo momento histórico. Essa perspectiva é típica do:', 'Romantismo', 'Realismo psicológico', 'Naturalismo', 'Parnasianismo', 'Simbolismo', 'c', 'O Naturalismo aplica o determinismo científico, em que o homem é influenciado pelo meio, raça e momento histórico, sendo visto frequentemente de forma zoomorfizada.', 'médio', 0],
    [98, 'UNESP 2024', 'Castro Alves é o principal expoente da terceira geração romântica, conhecida como condoreira. O tema principal de sua poesia social foi:', 'O escapismo através do sonho', 'A idealização do índio como bom selvagem', 'A defesa da abolição da escravatura e ideais republicanos', 'O amor platônico e inatingível', 'O saudosismo da infância e da pátria', 'c', 'A geração condoreira, liderada por Castro Alves, engajou-se em causas sociais, especialmente a abolição da escravidão (ex: "O Navio Negreiro").', 'fácil', 0],
    [98, 'ENEM 2022', 'Em "Dom Casmurro", Machado de Assis utiliza um narrador em primeira pessoa (Bento Santiago) para relatar a história. O efeito principal dessa escolha narrativa é:', 'Garantir a veracidade absoluta dos fatos narrados', 'Criar uma perspectiva parcial e ambígua sobre a possível traição de Capitu', 'Mostrar o ponto de vista de Capitu sobre o casamento', 'Defender o Romantismo perante a crítica realista', 'Facilitar a leitura com uma linguagem puramente descritiva', 'b', 'A narrativa em primeira pessoa de Bentinho cria ambiguidade, pois o leitor só tem acesso à versão do narrador, tornando impossível ter certeza absoluta sobre a traição.', 'difícil', 1],

    // [99] Simbolismo e Parnasianismo
    [99, 'ENEM 2023', 'O Parnasianismo brasileiro caracterizou-se pela busca da perfeição formal. Qual elemento abaixo é considerado essencial para os poetas parnasianos?', 'Olavo Bilac e a defesa do verso livre', 'O engajamento em causas político-sociais', 'O uso de rimas ricas e raras e a precisão métrica', 'A expressão de sentimentos descontrolados', 'A valorização das culturas indígenas e africanas', 'c', 'Os parnasianos adotaram o lema "arte pela arte", buscando extrema rigidez formal, métrica perfeita, vocabulário rebuscado e rimas ricas.', 'fácil', 0],
    [99, 'USP (FUVEST) 2023', 'O Simbolismo, marcado pelo pessimismo e pela fuga da realidade concreta, utilizou largamente quais recursos estilísticos em sua poesia?', 'Objetividade e descrições minuciosas de objetos', 'Musicalidade, sinestesias e aliterações', 'Linguagem coloquial e versos livres', 'Ironia e sarcasmo contra a burguesia', 'Retomada de temas da mitologia grega', 'b', 'Os simbolistas (como Cruz e Sousa) buscavam sugerir os elementos em vez de nomeá-los, abusando de figuras sonoras (aliteração, assonância) e de sentido (sinestesia) para criar musicalidade.', 'médio', 0],
    [99, 'UNICAMP 2024', '"Profissão de Fé", de Olavo Bilac, é frequentemente considerado um manifesto do Parnasianismo. Nele, o trabalho do poeta é comparado ao de um:', 'Sacerdote que prega aos fiéis', 'Pescador lançando redes ao mar', 'Ourives que trabalha minuciosamente uma joia', 'Guerreiro no campo de batalha', 'Agricultor cultivando a terra', 'c', 'Bilac compara o esforço poético ao ofício do ourives, destacando o trabalho lento e minucioso de lapidar a palavra, em busca da perfeição da forma.', 'médio', 0],
    [99, 'UNESP 2024', 'João da Cruz e Sousa, o maior representante do Simbolismo no Brasil, aborda frequentemente em sua obra:', 'A exaltação do progresso científico', 'Temas como o mistério, a morte, a espiritualidade e a cor branca', 'O cotidiano urbano e a vida boêmia', 'A descrição fiel de vasos e estátuas clássicas', 'A vida dos retirantes nordestinos', 'b', 'Cruz e Sousa, o "Cisne Negro", marcou a poesia simbolista com a obsessão pela cor branca, além da exploração do sofrimento, transcendência espiritual e mistério.', 'fácil', 0],
    [99, 'ENEM 2022', 'Embora ambos os movimentos tenham ocorrido simultaneamente no final do século XIX, Parnasianismo e Simbolismo diferem radicalmente em suas bases filosóficas. A oposição principal entre eles pode ser definida como:', 'O Parnasianismo é subjetivo e o Simbolismo é objetivo', 'O Parnasianismo é materialista e descritivo; o Simbolismo é espiritualista e sugestivo', 'O Parnasianismo rejeita a forma e o Simbolismo a cultua', 'Ambos são românticos, mas o Parnasianismo foca na prosa', 'O Parnasianismo foca na musicalidade enquanto o Simbolismo foca na rima', 'b', 'O Parnasianismo lida com o mundo material, buscando descrevê-lo com precisão estatuária. O Simbolismo busca a essência transcendente, a alma das coisas, focando no impreciso e no espiritual.', 'difícil', 1],

    // [100] Modernismo Brasileiro e Vanguardas
    [100, 'ENEM 2023', 'O poema "No meio do caminho tinha uma pedra / tinha uma pedra no meio do caminho", de Carlos Drummond de Andrade, é representativo de qual fase do Modernismo brasileiro?', 'Pré-Modernismo', 'Primeira geração modernista (1922-1930)', 'Segunda geração modernista (1930-1945)', 'Terceira geração modernista (1945-1960)', 'Parnasianismo', 'c', 'Drummond é o maior expoente da segunda geração modernista, marcada pelo amadurecimento, reflexão existencial, filosófica e social.', 'fácil', 0],
    [100, 'USP (FUVEST) 2023', 'A Semana de Arte Moderna de 1922 marcou o início do Modernismo no Brasil. Qual era o principal objetivo dos artistas participantes, como Mário e Oswald de Andrade?', 'Retomar as regras clássicas da literatura e da pintura', 'Romper com o academicismo e criar uma arte com identidade genuinamente brasileira', 'Copiar integralmente os modelos artísticos dos Estados Unidos', 'Reforçar o estilo parnasiano na poesia nacional', 'Promover a literatura de cordel como único modelo literário', 'b', 'O principal objetivo da Semana de 22 foi a destruição do passado acadêmico e a busca por uma identidade artística brasileira moderna e livre.', 'médio', 0],
    [100, 'UNICAMP 2024', 'O "Manifesto Antropófago" (1928), escrito por Oswald de Andrade, propunha:', 'A rejeição total e absoluta de qualquer influência estrangeira', 'A devoração crítica da cultura estrangeira para recriá-la com base na realidade brasileira', 'O isolamento cultural do Brasil em relação à Europa', 'A imitação fiel da literatura portuguesa', 'O retorno às práticas canibais das tribos indígenas', 'b', 'A metáfora da antropofagia propunha "engolir" as técnicas e influências estrangeiras (europeias) e transformá-las em algo novo, misturado com a cultura nacional.', 'médio', 0],
    [100, 'UNESP 2024', 'O Romance de 30 (segunda fase modernista) destacou-se pela prosa regionalista. Qual obra abaixo e seu autor representam fortemente a crítica à miséria no Nordeste?', '"Macunaíma", de Mário de Andrade', '"O Cortiço", de Aluísio Azevedo', '"Vidas Secas", de Graciliano Ramos', '"Dom Casmurro", de Machado de Assis', '"A Moreninha", de Joaquim Manuel de Macedo', 'c', '"Vidas Secas" é o marco do romance regionalista de 30, expondo de forma crua e concisa a seca e a desigualdade social no sertão nordestino.', 'fácil', 0],
    [100, 'ENEM 2022', 'João Cabral de Melo Neto, pertencente à Geração de 45, ficou conhecido como o "poeta engenheiro". Isso se deve:', 'Ao seu trabalho exclusivo com temas urbanísticos e construções', 'À sua rejeição ao lirismo sentimental e à busca por uma poesia objetiva, construída palavra por palavra', 'Ao uso constante de versos livres, sem preocupação métrica', 'Ao seu apego às tradições parnasianas de exaltação da natureza', 'À sua crença na inspiração divina imediata para a escrita', 'b', 'João Cabral rejeitava o derramamento sentimental e acreditava na poesia como fruto do suor e do trabalho intelectual ("engenharia" da palavra), muito presente em obras como "Morte e Vida Severina".', 'difícil', 1],

    // [151] Classes Gramaticais de Palavras
    [151, 'ENEM 2023', 'Na frase "Os dois alunos estudiosos passaram na difícil prova", a palavra "estudiosos" pertence a qual classe gramatical?', 'Substantivo', 'Adjetivo', 'Advérbio', 'Pronome', 'Artigo', 'b', 'A palavra "estudiosos" qualifica o substantivo "alunos", atribuindo-lhe uma característica, configurando-se, portanto, como um adjetivo.', 'fácil', 0],
    [151, 'USP (FUVEST) 2023', 'No período "Ele fala muito, porém estuda pouco", as palavras "muito", "porém" e "pouco" classificam-se, respectivamente, como:', 'Adjetivo, conjunção, adjetivo', 'Advérbio, conjunção, advérbio', 'Pronome, preposição, advérbio', 'Advérbio, preposição, pronome', 'Substantivo, conjunção, advérbio', 'b', '"Muito" e "pouco" indicam intensidade ligada aos verbos (advérbios); "porém" liga orações indicando oposição (conjunção adversativa).', 'médio', 0],
    [151, 'UNICAMP 2024', 'Em "Certas pessoas não têm nenhuma educação", a palavra "Certas" funciona morfologicamente como:', 'Pronome indefinido', 'Adjetivo', 'Substantivo', 'Advérbio de afirmação', 'Numeral', 'a', 'Anteposto ao substantivo ("pessoas"), "certas" tem sentido vago, indefinido, classificando-se como pronome indefinido. Se estivesse posposto ("pessoas certas"), seria adjetivo (corretas).', 'médio', 0],
    [151, 'UNESP 2024', 'Assinale a alternativa em que a palavra "que" funciona como pronome relativo:', 'Espero que você venha logo.', 'Temos que estudar mais.', 'O livro que eu li é excelente.', 'Que belo dia!', 'Ele disse que não sabia de nada.', 'c', 'Em "O livro que eu li", o "que" retoma o substantivo antecedente "livro", podendo ser substituído por "o qual", caracterizando-se como pronome relativo.', 'fácil', 0],
    [151, 'ENEM 2022', 'Leia: "O jantar foi servido às pressas. O comer, no entanto, foi demorado." O processo que transforma o verbo "comer" em um substantivo na frase é chamado de:', 'Derivação sufixal', 'Derivação parassintética', 'Derivação imprópria', 'Composição por aglutinação', 'Derivação regressiva', 'c', 'A derivação imprópria ocorre quando uma palavra muda de classe gramatical sem alteração na sua forma. O artigo "O" substantivou o verbo "comer".', 'difícil', 1],

    // [152] Sintaxe: Sujeito, Predicado e Complementos
    [152, 'ENEM 2023', 'Na oração "Houve muitos protestos na capital do país", o sujeito é:', 'Muitos protestos', 'Na capital do país', 'Ele (oculto)', 'Inexistente', 'Indeterminado', 'd', 'O verbo "haver" no sentido de existir ou ocorrer é impessoal. Portanto, a oração não possui sujeito (sujeito inexistente). "Muitos protestos" é objeto direto.', 'fácil', 0],
    [152, 'USP (FUVEST) 2023', 'No trecho "A mãe considerava o filho um gênio", a expressão "um gênio" exerce a função sintática de:', 'Predicativo do sujeito', 'Objeto direto', 'Adjunto adnominal', 'Complemento nominal', 'Predicativo do objeto', 'e', '"Um gênio" atribui uma qualidade ou estado ao objeto direto "o filho", sendo classificado como predicativo do objeto.', 'médio', 0],
    [152, 'UNICAMP 2024', 'Analise a frase: "Precisa-se de novos funcionários experientes". O sujeito desta oração é classificado como:', 'Simples ("novos funcionários")', 'Oculto ("nós")', 'Indeterminado', 'Composto ("funcionários experientes")', 'Inexistente', 'c', 'Quando o verbo transitivo indireto ("precisar") vem acompanhado da partícula "se" (índice de indeterminação do sujeito), o sujeito é indeterminado.', 'médio', 0],
    [152, 'UNESP 2024', 'Na oração "Aos alunos, entregou o professor as provas", qual é a função sintática de "Aos alunos"?', 'Sujeito', 'Objeto direto', 'Objeto indireto', 'Agente da passiva', 'Adjunto adverbial', 'c', 'O verbo "entregar" é transitivo direto e indireto. Quem entrega, entrega algo ("as provas" - OD) a alguém ("aos alunos" - OI, introduzido pela preposição "a").', 'fácil', 0],
    [152, 'ENEM 2022', 'Na frase "A leitura do livro foi feita pelos estudantes", as expressões "do livro" e "pelos estudantes" exercem, respectivamente, as funções de:', 'Adjunto adnominal e sujeito', 'Complemento nominal e agente da passiva', 'Objeto indireto e agente da passiva', 'Complemento nominal e adjunto adverbial', 'Adjunto adnominal e objeto indireto', 'b', '"Do livro" completa o sentido do substantivo abstrato "leitura", sofrendo a ação de ser lido (complemento nominal). "Pelos estudantes" é quem pratica a ação na voz passiva (agente da passiva).', 'difícil', 1],

    // [153] Crase e Regência Verbal/Nominal
    [153, 'ENEM 2023', 'A frase que apresenta erro quanto ao uso ou ausência da crase é:', 'Vou a Roma no próximo mês.', 'Ele se referiu à aluna nova.', 'Entreguei o prêmio a ele.', 'O restaurante funciona de segunda à sexta.', 'Fomos à Bahia nas férias.', 'd', 'Na expressão "de... a...", se há apenas preposição "de", não há artigo no "a". O correto é "de segunda a sexta" ou "da segunda à sexta".', 'fácil', 0],
    [153, 'USP (FUVEST) 2023', 'Assinale a alternativa que completa corretamente a lacuna, de acordo com a norma-padrão de regência verbal: "Os adolescentes preferem jogar videogame _____ estudar matemática."', 'do que', 'a', 'que', 'mais que', 'em vez de', 'b', 'O verbo "preferir", na norma-padrão culta, exige a preposição "a" e não admite reforços de intensidade (preferir algo a outra coisa).', 'médio', 0],
    [153, 'UNICAMP 2024', 'Sobre o uso da crase, indique a frase em que ela é facultativa:', 'Fui à escola ontem.', 'Refiro-me àquilo que combinamos.', 'Entregue o documento à sua secretária.', 'Andamos à pé até o centro.', 'À noite, gosto de ler.', 'c', 'A crase é facultativa antes de pronomes possessivos femininos singulares, como "sua", pois o uso do artigo feminino antes deles é opcional.', 'médio', 0],
    [153, 'UNESP 2024', 'Quanto à regência do verbo "assistir", a frase correta, no sentido de presenciar/ver, é:', 'A enfermeira assistiu o paciente com dedicação.', 'Os alunos assistiram o filme em silêncio.', 'Os alunos assistiram ao filme em silêncio.', 'Esse direito não lhe assiste.', 'Eu assisto em São Paulo desde criança.', 'c', 'No sentido de ver/presenciar, o verbo "assistir" é transitivo indireto e exige a preposição "a" (assistir ao filme).', 'fácil', 0],
    [153, 'ENEM 2022', 'Há uma regra específica de regência e crase envolvendo nomes de lugares. Assinale a alternativa gramaticalmente CORRETA:', 'Fui à Paris dos meus sonhos.', 'Cheguei à Portugal ontem.', 'Vou à Londres no inverno.', 'Retornei a Brasília e depois irei à Curitiba.', 'Irei a Argentina amanhã.', 'a', 'A regra diz: "Vou a, volto da, crase há. Vou a, volto de, crase pra quê?". Porém, se o nome da cidade estiver especificado (Paris DOS MEUS SONHOS), o artigo é admitido e a crase é obrigatória.', 'difícil', 1],

    // [154] Figuras de Linguagem
    [154, 'ENEM 2023', 'O uso da expressão "O rei do futebol" para se referir a Pelé é um exemplo de qual figura de linguagem?', 'Metáfora', 'Metonímia', 'Perífrase (ou antonomásia)', 'Pleonasmo', 'Antítese', 'c', 'A perífrase (ou antonomásia) consiste na substituição do nome de uma pessoa ou lugar por uma característica ou título pelo qual é amplamente conhecido.', 'fácil', 0],
    [154, 'USP (FUVEST) 2023', 'No verso de Camões: "Amor é fogo que arde sem se ver", a aproximação dos termos "fogo" e "amor" constitui uma:', 'Metáfora', 'Comparação', 'Catacrese', 'Prosopopeia', 'Sinestesia', 'a', 'A metáfora é uma comparação implícita, sem conectivo comparativo (como "como", "tal qual"). Camões afirma diretamente que amor é fogo.', 'fácil', 0],
    [154, 'UNICAMP 2024', 'Na frase "Li Machado de Assis durante as férias inteiras", ocorre uma figura de linguagem baseada na relação de contiguidade (o autor pela obra). Trata-se da:', 'Metáfora', 'Metonímia', 'Hipérbole', 'Ironia', 'Elipse', 'b', 'A metonímia é a substituição de um termo por outro com o qual tem forte relação (autor pela obra, parte pelo todo, continente pelo conteúdo).', 'médio', 0],
    [154, 'UNESP 2024', 'Ao dizer "Aquele rapaz é desprovido de beleza" em vez de dizer que ele é feio, utiliza-se a figura de linguagem chamada:', 'Hipérbole', 'Eufemismo', 'Ironia', 'Paradoxo', 'Paradoxo', 'b', 'O eufemismo consiste na suavização de uma ideia desagradável ou chocante.', 'médio', 0],
    [154, 'ENEM 2022', 'Leia: "O doce som do violino misturava-se ao azul daquele entardecer frio". A figura de linguagem que mistura diferentes percepções sensoriais (audição, visão, tato) é a:', 'Prosopopeia', 'Sinestesia', 'Onomatopeia', 'Metáfora', 'Gradação', 'b', 'A sinestesia ocorre pela mescla de sensações advindas de diferentes órgãos dos sentidos (som/audição, doce/paladar, azul/visão, frio/tato).', 'difícil', 1],

    // [155] Funções da Linguagem
    [155, 'ENEM 2023', 'Um manual de instruções de um aparelho celular foca em transmitir informações claras e objetivas sobre o produto. A função da linguagem predominante nesse tipo de texto é:', 'Emotiva', 'Fática', 'Referencial (ou denotativa)', 'Metalinguística', 'Poética', 'c', 'A função referencial foca no referente (contexto, assunto), utilizando linguagem clara e objetiva para informar.', 'fácil', 0],
    [155, 'USP (FUVEST) 2023', 'Ao iniciar uma ligação telefônica dizendo "Alô? Está me ouvindo?", o emissor tem como objetivo testar e manter o canal de comunicação. Isso caracteriza a função:', 'Emotiva', 'Conativa (ou apelativa)', 'Fática', 'Metalinguística', 'Referencial', 'c', 'A função fática está centrada no canal de comunicação, buscando iniciar, manter ou encerrar o contato com o receptor.', 'fácil', 0],
    [155, 'UNICAMP 2024', 'Uma campanha publicitária que utiliza verbos no imperativo ("Compre!", "Participe!") para convencer o leitor a adquirir um produto foca em qual função da linguagem?', 'Conativa (ou apelativa)', 'Emotiva', 'Poética', 'Fática', 'Referencial', 'a', 'A função conativa foca no receptor (leitor/ouvinte), com o objetivo de persuadi-lo ou convencê-lo, sendo comum em propagandas.', 'médio', 0],
    [155, 'UNESP 2024', 'Quando um poema tem como tema o próprio ato de escrever poesia (ex: um poema que explica como se faz um poema), temos a predominância da função:', 'Referencial', 'Metalinguística', 'Fática', 'Conativa', 'Emotiva', 'b', 'A metalinguagem ocorre quando o código é usado para explicar o próprio código (um poema sobre poesia, um filme sobre cinema, o dicionário).', 'médio', 0],
    [155, 'ENEM 2022', 'Em obras literárias ricas em figuras de linguagem, onde a preocupação maior está na seleção e arranjo das palavras, na sonoridade e no ritmo da mensagem, predomina a função:', 'Poética', 'Referencial', 'Fática', 'Conativa', 'Emotiva', 'a', 'A função poética foca na própria mensagem, na forma como ela é elaborada, sendo muito comum na literatura e na música.', 'difícil', 1],

    // [156] Romantismo e Realismo no Brasil
    [156, 'ENEM 2023', 'A obra "Senhora", de José de Alencar, pertence à fase de romances urbanos do Romantismo. Qual o tema central dessa narrativa?', 'A exaltação das paisagens sertanejas', 'O casamento por interesse e a crítica aos valores burgueses', 'A vida dos escravizados nas fazendas', 'O heroísmo do indígena brasileiro', 'A loucura e o adultério comprovado', 'b', '"Senhora" foca na relação entre Aurélia Camargo e Fernando Seixas, abordando o casamento como transação comercial e criticando a hipocrisia da sociedade burguesa.', 'fácil', 0],
    [156, 'USP (FUVEST) 2023', 'No Realismo, autores como Machado de Assis opuseram-se fortemente aos ideais românticos. Qual destas é uma diferença clássica entre o Romantismo e o Realismo?', 'O Romantismo usava versos brancos, o Realismo preferia rimas ricas', 'O Romantismo idealizava a mulher; o Realismo a retratava com seus defeitos e contradições', 'O Romantismo focava na ciência; o Realismo na religião', 'O Romantismo era focado na prosa urbana; o Realismo apenas na poesia', 'Não havia diferença, o Realismo era apenas uma continuação estética do Romantismo', 'b', 'Enquanto o Romantismo criou mulheres idealizadas ("anjos"), o Realismo trouxe perfis psicológicos profundos e realistas de mulheres, com defeitos e impulsos carnais.', 'médio', 0],
    [156, 'UNICAMP 2024', 'A segunda geração romântica na poesia, conhecida como Ultrarromantismo ou Mal-do-século, teve como seu maior expoente no Brasil:', 'Castro Alves', 'Álvares de Azevedo', 'Gonçalves Dias', 'Machado de Assis', 'Olavo Bilac', 'b', 'Álvares de Azevedo, autor de "Lira dos Vinte Anos", é o maior nome da geração caracterizada pela morbidez, tédio, pessimismo e fuga na morte.', 'médio', 0],
    [156, 'UNESP 2024', 'Raul Pompeia é autor de "O Ateneu", romance classificado no período realista-naturalista, mas que também apresenta traços de qual outra corrente estética?', 'Simbolismo e Impressionismo', 'Parnasianismo', 'Arcadismo', 'Trovadorismo', 'Romantismo', 'a', '"O Ateneu" possui características naturalistas, mas destaca-se pela prosa altamente subjetiva, memorialista e descrições sensoriais, flertando com o Impressionismo.', 'fácil', 0],
    [156, 'ENEM 2022', 'Na transição do Romantismo para o Realismo no Brasil, Machado de Assis passou por uma fase romântica antes de publicar sua obra-prima realista. Qual dos romances abaixo pertence à fase romântica de Machado?', 'Quincas Borba', 'A Mão e a Luva', 'Esaú e Jacó', 'Dom Casmurro', 'Memorial de Aires', 'b', 'Os primeiros romances de Machado ("Ressurreição", "A Mão e a Luva", "Helena", "Iaiá Garcia") ainda possuem fortes traços românticos, embora já apontem para sua análise psicológica.', 'difícil', 1],

    // [157] Modernismo Brasileiro e Vanguardas
    [157, 'ENEM 2023', 'A pintora Anita Malfatti foi alvo de duras críticas de um famoso escritor pré-modernista após sua exposição em 1917, episódio que impulsionou o movimento modernista. Quem foi esse escritor?', 'Monteiro Lobato', 'Lima Barreto', 'Euclides da Cunha', 'Graça Aranha', 'Augusto dos Anjos', 'a', 'Monteiro Lobato escreveu o artigo "Paranoia ou Mistificação?", criticando ferozmente a arte moderna de Malfatti, o que uniu os jovens artistas para realizar a Semana de 22.', 'fácil', 0],
    [157, 'USP (FUVEST) 2023', 'Manuel Bandeira, no poema "Os Sapos", faz uma crítica irônica e direta a qual movimento literário do passado?', 'Romantismo', 'Arcadismo', 'Simbolismo', 'Parnasianismo', 'Barroco', 'd', '"Os Sapos" é uma sátira à rigidez formal e à falta de conteúdo profundo do Parnasianismo, declamado na Semana de Arte Moderna.', 'médio', 0],
    [157, 'UNICAMP 2024', 'Qual das vanguardas europeias, liderada por F.T. Marinetti, influenciou profundamente os modernistas brasileiros exaltando a velocidade, as máquinas e o progresso industrial?', 'Cubismo', 'Dadaísmo', 'Futurismo', 'Surrealismo', 'Expressionismo', 'c', 'O Futurismo idolatrava a vida moderna, a tecnologia e a velocidade, elementos muito presentes nos primeiros textos da 1ª geração modernista paulista.', 'médio', 0],
    [157, 'UNESP 2024', 'A terceira geração modernista (Geração de 45) é conhecida por um retorno a formas mais clássicas, com uma literatura mais reflexiva e de sondagem psicológica. O grande nome dessa prosa introspectiva no Brasil é:', 'José Lins do Rego', 'Jorge Amado', 'Clarice Lispector', 'Oswald de Andrade', 'Érico Veríssimo', 'c', 'Clarice Lispector é a maior representante da prosa introspectiva, fluxo de consciência e epifanias na 3ª geração modernista.', 'fácil', 0],
    [157, 'ENEM 2022', 'Guimarães Rosa, um dos maiores nomes da Geração de 45, revolucionou a literatura brasileira em obras como "Grande Sertão: Veredas" principalmente devido:', 'À adoção do verso livre na prosa nordestina', 'Ao uso de uma linguagem experimental, repleta de neologismos, sintaxe invertida e arcaísmos', 'Ao enfoque estritamente urbano de seus romances', 'À recusa em tratar de temas universais como amor, ódio e morte', 'À imitação direta dos romances de cavalaria portugueses', 'b', 'A revolução roseana deu-se na linguagem: recriou o falar sertanejo elevando-o a um nível poético universal com neologismos, arcaísmos e subversão sintática.', 'difícil', 1],
];

$stmt = $pdo->prepare("INSERT INTO questions (lesson_id, exam_source, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation_text, difficulty, is_boss) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
$inserted = 0;
$errors = 0;
foreach ($questions as $q) {
    try {
        $stmt->execute($q);
        $inserted++;
    } catch (Exception $e) {
        $errors++;
        echo "ERRO ao inserir lição {$q[0]}: " . $e->getMessage() . "\n";
    }
}
echo "\nInseridas: {$inserted} | Erros: {$errors}\n";
?>
