<?php
require_once __DIR__ . '/../config/db.php';
echo "=== Inserindo questões de História e Geografia 2 ===\n\n";

$questions = [
    // [115] Agropecuária e Uso da Terra no Brasil
    [115, 'ENEM 2022', 'A expansão da fronteira agrícola no Brasil a partir da década de 1970 ocorreu principalmente em direção à qual região e bioma, impulsionada pelo cultivo da soja e modernização do campo?', 'Centro-Oeste e Cerrado', 'Norte e Floresta Amazônica', 'Nordeste e Caatinga', 'Sul e Pampas', 'Sudeste e Mata Atlântica', 'a', 'A modernização agrícola nos anos 1970 avançou fortemente sobre o Cerrado do Centro-Oeste, com apoio estatal e adaptação da soja a solos ácidos.', 'médio', 0],
    [115, 'UNICAMP 2023', 'A estrutura fundiária brasileira é historicamente marcada por elevada concentração. O índice de Gini, quando aplicado à distribuição de terras no Brasil, apresenta valores próximos a:', '0,1, indicando distribuição igualitária', '0,4, indicando moderada concentração', '0,5, indicando equidade de acesso', '0,8, indicando extrema concentração', '1,0, indicando que todas as terras são estatais', 'd', 'O índice de Gini fundiário no Brasil é um dos mais altos do mundo, girando em torno de 0,8, refletindo a enorme concentração de terras (latifúndios).', 'médio', 0],
    [115, 'USP (FUVEST) 2021', 'A Lei de Terras de 1850 no Brasil determinou que as terras públicas só poderiam ser adquiridas por meio de:', 'doação pelo Império', 'usucapião', 'compra e venda', 'herança hereditária inalienável', 'concessão para cultivo de subsistência', 'c', 'A Lei de Terras (1850) extinguiu as doações e estipulou que terras públicas só poderiam ser obtidas por compra, dificultando o acesso de pobres e ex-escravizados à terra.', 'difícil', 1],
    [115, 'UNESP 2020', 'O sistema agrícola conhecido como "plantation", amplamente utilizado no período colonial e ainda presente com variações, caracteriza-se por:', 'minifúndio, policultura, mercado interno e trabalho familiar', 'latifúndio, monocultura, mercado externo e trabalho escravo/barato', 'pequena propriedade, rotação de culturas, exportação e trabalho cooperativo', 'cooperativas, policultura, subsistência e trabalho assalariado', 'latifúndio, agricultura orgânica, mercado local e maquinário pesado', 'b', 'A plantation clássica é definida pelo tripé: latifúndio, monocultura, voltada para exportação (mercado externo) e uso de mão de obra escrava ou barata.', 'fácil', 0],
    [115, 'ENEM 2019', 'O que caracteriza a agricultura familiar no Brasil, de acordo com a legislação e os dados do Censo Agropecuário?', 'Produz a maior parte das commodities para exportação em grandes latifúndios.', 'Emprega a minoria da mão de obra no campo, mas domina a área total.', 'Baseia-se no trabalho assalariado e mecanização intensiva de precisão.', 'É a principal responsável pelo abastecimento do mercado interno de alimentos e absorve a maior parte da mão de obra rural.', 'Caracteriza-se pela produção exclusiva de cana-de-açúcar e soja no Centro-Oeste.', 'd', 'A agricultura familiar emprega mais de 70% da mão de obra no campo e produz a maior parte dos alimentos consumidos diariamente pelos brasileiros (feijão, mandioca, etc).', 'fácil', 0],

    // [116] Geopolítica e Globalização Contemporânea
    [116, 'USP (FUVEST) 2022', 'A Nova Ordem Mundial, estabelecida após o fim da Guerra Fria e a desintegração da União Soviética em 1991, é frequentemente caracterizada como:', 'Bipolar, com ascensão imediata de China e EUA', 'Multipolar, devido à divisão exclusiva do mundo em blocos socialistas e capitalistas', 'Unipolar, no aspecto militar (EUA), e Multipolar, no aspecto econômico (EUA, UE, Japão, etc)', 'Apolar, sem nenhum país exercendo influência global', 'Unipolar econômica e militarmente pela União Europeia', 'c', 'No cenário pós-Guerra Fria, os EUA tornaram-se a única superpotência militar (unipolar), mas a economia mundial tornou-se multipolar com a força da UE, Japão e, mais tarde, China (ordem unimultipolar).', 'médio', 0],
    [116, 'ENEM 2021', 'A globalização financeira tem como uma de suas características mais marcantes:', 'O controle rigoroso do Estado sobre o fluxo de capitais e investimentos.', 'A desconcentração da riqueza mundial, igualando países ricos e pobres.', 'A velocidade e volatilidade do fluxo de capitais especulativos pelo mundo.', 'A proibição de empresas transnacionais de operarem fora de seus países sede.', 'O fim do uso do dólar como moeda de referência nas transações internacionais.', 'c', 'O avanço das telecomunicações e a desregulamentação permitiram o fluxo instantâneo de imensas somas de capital especulativo (hot money), gerando instabilidades financeiras.', 'médio', 0],
    [116, 'UNICAMP 2020', 'O conceito de "Aldeia Global", cunhado pelo sociólogo Marshall McLuhan na década de 1960, refere-se principalmente:', 'À volta das sociedades modernas aos padrões de vida das aldeias tribais antigas.', 'À interconexão global promovida pelos meios de comunicação de massa e pela tecnologia da informação.', 'Ao isolamento cultural provocado pela expansão da internet.', 'À padronização da produção agrícola em pequenas aldeias europeias.', 'À resistência política contra a globalização e o imperialismo cultural.', 'b', 'McLuhan previu que as novas tecnologias de comunicação conectariam o mundo de forma tão intensa que o transformaria numa "aldeia global", onde a informação circula instantaneamente.', 'fácil', 0],
    [116, 'UNESP 2022', 'Qual país asiático passou por profundas reformas econômicas a partir de 1978, lideradas por Deng Xiaoping, adotando o modelo de "Economia Socialista de Mercado"?', 'Japão', 'Coreia do Sul', 'Vietnã', 'Índia', 'China', 'e', 'As reformas de 1978 (Quatro Modernizações) abriram a economia da China ao capital estrangeiro, criando as Zonas Econômicas Especiais (ZEEs), resultando em rápido crescimento.', 'fácil', 0],
    [116, 'USP (FUVEST) 2023', 'A Guerra da Síria, iniciada em 2011 no contexto da Primavera Árabe, envolveu um complexo jogo geopolítico. Quais potências estrangeiras intervieram diretamente em apoio, respectivamente, ao governo de Bashar al-Assad e a grupos rebeldes?', 'Estados Unidos e Rússia', 'Rússia e Estados Unidos', 'China e França', 'Irã e Israel', 'Turquia e Rússia', 'b', 'A Rússia interveio militarmente em 2015 para sustentar o regime de Bashar al-Assad, enquanto os Estados Unidos forneceram apoio a certos grupos rebeldes e curdos.', 'difícil', 1],

    // [117] Blocos Econômicos Globais
    [117, 'ENEM 2020', 'O Mercosul, fundado em 1991 pelo Tratado de Assunção, teve como membros fundadores:', 'Brasil, Argentina, Paraguai e Uruguai', 'Brasil, Argentina, Chile e Bolívia', 'Brasil, Argentina, Colômbia e Peru', 'Brasil, México, Argentina e Chile', 'Brasil, Argentina, Venezuela e Paraguai', 'a', 'O Tratado de Assunção em 1991 foi assinado pelos quatro membros originais: Brasil, Argentina, Paraguai e Uruguai.', 'fácil', 0],
    [117, 'UNICAMP 2021', 'A União Europeia (UE) é considerada o bloco econômico mais avançado do mundo. Qual é o seu nível de integração atual?', 'Área de Livre Comércio', 'União Aduaneira', 'Mercado Comum e União Econômica e Monetária', 'Zona de Preferência Tarifária', 'Confederação Política Independente', 'c', 'A UE possui livre circulação de mercadorias, serviços, capitais e pessoas (Mercado Comum) e adota uma moeda única, o Euro, em grande parte de seus membros (União Econômica e Monetária).', 'médio', 0],
    [117, 'USP (FUVEST) 2019', 'O USMCA (Acordo Estados Unidos-México-Canadá), que entrou em vigor em 2020, substituiu qual antigo tratado comercial da América do Norte?', 'ALCA', 'Pacto Andino', 'NAFTA', 'Tratado Transpacífico (TPP)', 'Aliança do Pacífico', 'c', 'O USMCA substituiu o NAFTA (Acordo de Livre Comércio da América do Norte), criado em 1994, trazendo novas regras, especialmente para o setor automobilístico e direitos trabalhistas.', 'fácil', 0],
    [117, 'UNESP 2023', 'O bloco econômico ASEAN (Associação de Nações do Sudeste Asiático) tem como objetivo principal promover o desenvolvimento econômico e a estabilidade política na região. Qual dos seguintes países NÃO faz parte da ASEAN?', 'Indonésia', 'Japão', 'Tailândia', 'Vietnã', 'Filipinas', 'b', 'O Japão não faz parte da ASEAN. O bloco é formado por países do Sudeste Asiático (Indonésia, Tailândia, Vietnã, Filipinas, Malásia, Singapura, Myanmar, Camboja, Laos, Brunei).', 'médio', 0],
    [117, 'ENEM 2022', 'Qual a principal dificuldade enfrentada pelo Mercosul para consolidar sua União Aduaneira plena e avançar para um Mercado Comum?', 'A adoção do Euro como moeda única no bloco.', 'O excesso de infraestrutura física integrada, como rodovias e ferrovias.', 'As assimetrias econômicas entre os membros e as frequentes exceções à Tarifa Externa Comum (TEC).', 'O alto nível de livre circulação de trabalhadores, que satura os mercados.', 'A retirada da Argentina do bloco em 2019.', 'c', 'A Tarifa Externa Comum (TEC) possui muitas listas de exceções por conta das diferenças econômicas, e a instabilidade macroeconômica dos países trava a integração mais profunda.', 'difícil', 1],

    // [118] Fontes de Energia e Matriz Energética
    [118, 'ENEM 2021', 'A principal fonte de energia elétrica no Brasil é:', 'hidrelétrica', 'termelétrica a gás', 'eólica', 'nuclear', 'solar', 'a', 'Apesar do crescimento das energias eólica e solar, a energia hidrelétrica ainda responde por mais de 60% da matriz elétrica brasileira.', 'fácil', 0],
    [118, 'UNICAMP 2022', 'A matriz energética mundial difere consideravelmente da matriz brasileira, sendo a mundial predominantemente dependente de fontes não renováveis, liderada por:', 'Carvão mineral e energia nuclear', 'Petróleo e carvão mineral', 'Gás natural e energia hidrelétrica', 'Petróleo e biomassa', 'Gás natural e energia eólica', 'b', 'No mundo, as fontes fósseis (petróleo, carvão mineral e gás natural) dominam amplamente a matriz energética, sendo petróleo e carvão os mais utilizados.', 'médio', 0],
    [118, 'USP (FUVEST) 2020', 'O Proálcool, criado no Brasil em 1975, teve como principal motivação:', 'A preocupação com o aquecimento global e as mudanças climáticas.', 'A descoberta do pré-sal na bacia de Santos.', 'A crise do petróleo de 1973, visando reduzir a dependência de combustíveis fósseis importados.', 'O excesso de produção de açúcar que precisava ser escoado no mercado interno.', 'A exigência de blocos econômicos por matrizes de energia limpa.', 'c', 'O choque nos preços do petróleo em 1973 levou o Brasil a buscar alternativas, criando o Proálcool para estimular a produção de etanol da cana-de-açúcar.', 'médio', 0],
    [118, 'UNESP 2021', 'Sobre a energia nuclear no Brasil (Angra 1 e 2), é correto afirmar que:', 'Representa mais de 30% da matriz elétrica, situando-se no Nordeste.', 'É considerada uma energia limpa (não emite GEE), mas gera lixo radioativo e riscos de acidentes, localizando-se no estado do RJ.', 'Foi desativada após o acidente de Fukushima, no Japão.', 'Baseia-se no processo de fusão nuclear controlada.', 'É a principal fonte de energia da região Sul do país.', 'b', 'As usinas de Angra dos Reis (RJ) geram energia sem emitir gases do efeito estufa, mas o grande problema ambiental é a geração e armazenamento de rejeitos radioativos.', 'difícil', 1],
    [118, 'ENEM 2019', 'A energia eólica tem apresentado grande expansão no Brasil, especialmente em qual região, devido à constância dos ventos alísios?', 'Região Norte', 'Região Centro-Oeste', 'Região Sul', 'Região Nordeste', 'Região Sudeste', 'd', 'O litoral do Nordeste possui condições ideais de ventos fortes e constantes (ventos alísios), tornando a região a maior produtora de energia eólica do Brasil.', 'fácil', 0],

    // [119] Questão Ambiental e Desenvolvimento Sustentável
    [119, 'ENEM 2022', 'O conceito de Desenvolvimento Sustentável foi consagrado no Relatório Brundtland (Nosso Futuro Comum) em 1987 e define-se como o desenvolvimento que:', 'Prioriza o crescimento econômico imediato com uso intensivo de recursos naturais.', 'Elimina completamente qualquer atividade industrial para salvar os ecossistemas.', 'Atende às necessidades do presente sem comprometer a capacidade de as gerações futuras atenderem às suas próprias necessidades.', 'Substitui todas as fontes de energia fóssil por energia nuclear.', 'Transfere as indústrias poluidoras dos países desenvolvidos para os países em desenvolvimento.', 'c', 'Essa é a definição clássica: suprir as necessidades da geração atual sem esgotar os recursos para as gerações futuras.', 'fácil', 0],
    [119, 'UNICAMP 2021', 'O fenômeno das Ilhas de Calor é um problema ambiental tipicamente urbano que se caracteriza por:', 'Aumento das precipitações nas periferias em relação ao centro.', 'Resfriamento acentuado das áreas centrais devido aos prédios que bloqueiam o sol.', 'Temperaturas mais elevadas nas áreas centrais das cidades em comparação com as áreas rurais ou periféricas circundantes.', 'Inversão térmica que impede a dispersão de poluentes no inverno.', 'Destruição da camada de ozônio sobre os centros urbanos.', 'c', 'A alta concentração de concreto, asfalto, prédios e a falta de vegetação no centro das cidades retêm calor, elevando as temperaturas locais.', 'médio', 0],
    [119, 'USP (FUVEST) 2020', 'O Protocolo de Kyoto (1997) e o Acordo de Paris (2015) são importantes tratados internacionais focados em:', 'Proteção da biodiversidade da Amazônia.', 'Redução da emissão de gases de efeito estufa para mitigar as mudanças climáticas.', 'Proibição da pesca predatória em águas internacionais.', 'Erradicação do uso de agrotóxicos na agricultura.', 'Eliminação total de ogivas nucleares.', 'b', 'Ambos são os principais marcos da diplomacia ambiental voltada à redução das emissões de gases estufa e combate ao aquecimento global.', 'fácil', 0],
    [119, 'UNESP 2019', 'A chuva ácida ocorre principalmente devido à emissão na atmosfera de quais gases, provenientes da queima de combustíveis fósseis?', 'Clorofluorcarbonos (CFCs)', 'Dióxido de carbono e metano', 'Dióxido de enxofre (SO2) e óxidos de nitrogênio (NOx)', 'Monóxido de carbono e ozônio', 'Hélio e hidrogênio', 'c', 'Os óxidos de enxofre e nitrogênio reagem com a água na atmosfera, formando ácido sulfúrico e nítrico, que precipitam como chuva ácida.', 'médio', 0],
    [119, 'ENEM 2023', 'A eutrofização é um processo de degradação de corpos hídricos causado frequentemente pelo despejo de esgoto doméstico sem tratamento ou fertilizantes agrícolas. Qual o principal impacto imediato desse processo no lago ou rio?', 'Aumento da oxigenação da água, beneficiando os peixes.', 'Proliferação excessiva de algas, bloqueio da luz solar e posterior redução drástica do oxigênio dissolvido, causando mortandade de peixes.', 'Acidificação imediata do corpo hídrico.', 'Transformação do rio em um curso de água subterrâneo.', 'Salinização severa da água doce.', 'b', 'O excesso de nutrientes (nitrogênio e fósforo) gera superpopulação de algas. Quando morrem, as bactérias aeróbicas as decompõem, consumindo o oxigênio da água.', 'difícil', 1],

    // [120] Cartografia, Fusos Horários e Projeções
    [120, 'UNICAMP 2022', 'Se em Londres (fuso 0, Meridiano de Greenwich) são 15h de uma terça-feira, que horas e dia são na cidade de Brasília, que se encontra no fuso -3 (GMT-3)?', '18h de terça-feira', '12h de terça-feira', '15h de quarta-feira', '12h de segunda-feira', '9h de terça-feira', 'b', 'Brasília está a oeste de Greenwich (-3h). Portanto, subtrai-se 3 horas do horário de Londres. 15 - 3 = 12h do mesmo dia.', 'fácil', 0],
    [120, 'USP (FUVEST) 2021', 'A projeção cartográfica de Mercator e a de Peters são as duas projeções cilíndricas mais conhecidas. Uma diferença fundamental entre elas é que:', 'Mercator é equivalente e deforma as formas, Peters é conforme e deforma as áreas.', 'Mercator é conforme (preserva as formas) e amplia áreas de alta latitude, enquanto Peters é equivalente (preserva as áreas) e alonga os continentes no sentido norte-sul.', 'Mercator coloca o sul no topo, e Peters coloca a Ásia no centro.', 'Ambas são equivalentes, mas Mercator foca apenas no hemisfério norte.', 'Peters foi criada no século XVI para navegações, e Mercator no século XX focando no Terceiro Mundo.', 'b', 'Mercator, do séc XVI, mantém formas (conforme) mas distorce o tamanho, inflando o norte. Peters (1973) prioriza áreas reais (equivalente), deformando as formas.', 'médio', 0],
    [120, 'ENEM 2020', 'Em um mapa com escala de 1:500.000, duas cidades estão separadas por 4 cm. Qual a distância real em linha reta entre elas?', '2 km', '20 km', '200 km', '50 km', '500 km', 'b', '1 cm no mapa = 500.000 cm = 5.000 m = 5 km reais. Então 4 cm * 5 km/cm = 20 km.', 'médio', 0],
    [120, 'UNESP 2023', 'Uma aeronave decola de Tóquio (fuso +9) às 10h da manhã do dia 10 de maio em direção a Los Angeles (fuso -8). O tempo de voo é de 10 horas. Que horas locais e dia marcarão a chegada do voo em Los Angeles?', '13h do dia 10 de maio', '03h do dia 10 de maio', '03h do dia 11 de maio', '17h do dia 9 de maio', '13h do dia 9 de maio', 'b', 'Decolagem de Tóquio: 10h de 10/05. Fuso de LA = -8, de Tóquio = +9. Diferença = 17 horas a menos. Hora em LA na decolagem = 10h - 17h = 17h do dia 09/05. Chegada (após 10h de voo): 17h + 10h = 27h = 03h da manhã do dia 10/05.', 'difícil', 1],
    [120, 'ENEM 2019', 'As curvas de nível, muito utilizadas em mapas topográficos, são linhas que unem pontos com a mesma:', 'Latitude', 'Longitude', 'Temperatura', 'Altitude', 'Pressão atmosférica', 'd', 'Curvas de nível, ou isoípsas, são linhas que ligam pontos do terreno de mesma cota altimétrica (altitude).', 'fácil', 0],

    // [158] Ditadura Militar no Brasil
    [158, 'ENEM 2020', 'O Ato Institucional nº 5 (AI-5), decretado no Brasil durante a ditadura militar e considerado o golpe dentro do golpe por sua extrema dureza, ocorreu sob o governo de qual presidente e em que ano?', 'Castello Branco, 1964', 'Emílio Garrastazu Médici, 1970', 'João Figueiredo, 1979', 'Ernesto Geisel, 1974', 'Artur da Costa e Silva, 1968', 'e', 'O AI-5 foi decretado em 13 de dezembro de 1968, durante o governo de Costa e Silva, suspendendo garantias constitucionais e o habeas corpus para crimes políticos.', 'fácil', 0],
    [158, 'USP (FUVEST) 2021', 'O período conhecido como "Milagre Econômico" (1968-1973), durante o governo Médici, caracterizou-se por taxas de crescimento do PIB superiores a 10% ao ano. Esse crescimento foi alavancado por:', 'Amplo endividamento externo, obras faraônicas e arrocho salarial.', 'Autossuficiência em petróleo, distribuição de renda e reforma agrária.', 'Privatização de empresas estatais e abertura irrestrita a importações.', 'Fim da inflação, estabilização cambial e fortalecimento dos sindicatos.', 'Exportação exclusiva de produtos de alta tecnologia.', 'a', 'O "milagre" se sustentou com forte tomada de empréstimos internacionais, investimento em obras de infraestrutura e política de achatamento dos salários, o que aumentou a desigualdade.', 'médio', 0],
    [158, 'UNICAMP 2019', 'A campanha das "Diretas Já", ocorrida entre 1983 e 1984, mobilizou milhões de brasileiros que exigiam o retorno das eleições diretas para Presidente da República. A emenda constitucional que propunha essa mudança, porém derrotada no Congresso, era de autoria do deputado:', 'Ulysses Guimarães', 'Dante de Oliveira', 'Tancredo Neves', 'Leonel Brizola', 'Teotônio Vilela', 'b', 'A Emenda Dante de Oliveira (1983) propunha restabelecer a eleição direta, mas não obteve os 2/3 de votos necessários no Congresso em 1984.', 'médio', 0],
    [158, 'UNESP 2022', 'A Lei da Anistia, sancionada em agosto de 1979 pelo presidente João Figueiredo, permitiu o retorno de exilados políticos ao Brasil. No entanto, ela foi criticada por setores da oposição e de direitos humanos por ser considerada "ampla, geral e irrestrita", o que, na prática, resultou na:', 'Garantia de indenização financeira apenas a militares da reserva.', 'Punição imediata dos agentes de Estado envolvidos em tortura.', 'Anistia bilateral, perdoando também os crimes de violação de direitos humanos cometidos por agentes da repressão.', 'Expulsão do Brasil de militantes da luta armada.', 'Exclusão do perdão aos líderes partidários de esquerda.', 'c', 'O formato da Lei perdoou tanto os crimes políticos dos opositores quanto os crimes comuns e conexos cometidos por policiais e militares (tortura, assassinatos), impedindo julgamentos.', 'difícil', 1],
    [158, 'ENEM 2018', 'Qual foi o estopim imediato utilizado pelos militares para justificar a deposição do presidente João Goulart em 1964?', 'O Comício da Central do Brasil, onde Jango anunciou as Reformas de Base.', 'A renúncia inesperada de Jânio Quadros.', 'O assassinato do jornalista Vladimir Herzog.', 'A publicação do Plano Cohen por integralistas.', 'A assinatura da Lei de Remessa de Lucros por Getúlio Vargas.', 'a', 'O comício de 13 de março de 1964, anunciando as Reformas de Base (incluindo agrária), alarmou as classes conservadoras, resultando na Marcha da Família com Deus e no subsequente golpe em 31 de março.', 'fácil', 0],

    // [159] Antiguidade Clássica: Grécia e Roma
    [159, 'USP (FUVEST) 2022', 'A democracia em Atenas, consolidada no século V a.C., difere da democracia representativa moderna, pois era do tipo:', 'Direta, participando todos os habitantes da cidade, inclusive mulheres.', 'Indireta, com representantes eleitos a cada 10 anos pelos patrícios.', 'Direta, mas restrita aos cidadãos (homens adultos, livres e filhos de pai e mãe atenienses).', 'Censitária, onde apenas os mais ricos podiam votar e ser votados.', 'Representativa, com o Senado tomando todas as decisões de Estado.', 'c', 'A democracia ateniense era direta (os cidadãos votavam as leis na Ágora), porém excludente: mulheres, escravos e metecos (estrangeiros) não tinham direitos políticos.', 'fácil', 0],
    [159, 'ENEM 2021', 'A sociedade romana no período da República era marcadamente dividida em estamentos. A longa luta política pelo acesso a direitos e leis escritas, que resultou, por exemplo, na Lei das Doze Tábuas, foi liderada pelos:', 'Patrícios, contra os ditadores.', 'Plebeus, que reivindicavam igualdade de direitos e fim da escravidão por dívidas.', 'Escravos, inspirados na revolta de Espártaco.', 'Cavaleiros, para dominar o comércio no Mediterrâneo.', 'Metecos, que queriam cidadania romana.', 'b', 'As Lutas da Plebe (séc V ao III a.C) garantiram aos plebeus conquistas como a Lei das XII Tábuas, o fim da escravidão por dívida e a eleição dos Tribunos da Plebe.', 'médio', 0],
    [159, 'UNICAMP 2020', 'O período conhecido como Helenismo, originado após as conquistas de Alexandre, o Grande, caracterizou-se culturalmente pela:', 'Difusão da religião monoteísta judaica por todo o Império.', 'Fusão da cultura grega clássica com as culturas orientais (persa, egípcia).', 'Imposição do latim como língua oficial na Ásia e na África.', 'Total destruição das bibliotecas, rejeitando o conhecimento científico.', 'Exclusividade do pensamento espartano focado no militarismo em todo o império.', 'b', 'A expansão macedônica mesclou os valores, a língua (koiné) e a arte grega (helenismo) com elementos das tradições orientais dominadas.', 'médio', 0],
    [159, 'UNESP 2023', 'A transição da República para o Império Romano, consolidada por Otávio Augusto (27 a.C.), foi motivada por uma profunda crise. Entre os fatores dessa crise republicana, destaca-se:', 'As invasões germânicas bárbaras que destruíram o senado.', 'O fracasso nas Guerras Púnicas e a perda do Mar Mediterrâneo para Cartago.', 'As tensões sociais causadas pelo acúmulo de terras e escravos nas mãos dos patrícios e a ruína da pequena propriedade camponesa.', 'A adoção do Cristianismo como religião oficial, fragmentando o poder.', 'O movimento separatista do Egito comandado por Cleópatra.', 'c', 'A expansão romana gerou imenso influxo de riqueza e escravos, arruinando os camponeses plebeus (levando ao êxodo rural) e concentrando poder em generais, resultando em guerras civis.', 'difícil', 1],
    [159, 'ENEM 2019', 'O modelo espartano de pólis grega diferenciava-se fortemente do ateniense por priorizar:', 'A liberdade de expressão e filosofia nas praças públicas.', 'O forte comércio marítimo e o artesanato refinado.', 'A democracia plena e a educação artística.', 'A agricultura escravista estruturada no militarismo estatal e oligarquia (diarquia).', 'A igualdade social entre hilotas e esparciatas.', 'd', 'Esparta, localizada na planície da Lacônia, tinha economia agropecuária, sociedade estamental e um rígido treinamento militar (agogê) para os cidadãos.', 'fácil', 0],

    // [160] Revoluções Industriais e Transformações
    [160, 'ENEM 2022', 'A Primeira Revolução Industrial, ocorrida na Inglaterra no final do século XVIII, baseou-se na mecanização da indústria têxtil e teve como principal fonte de energia motriz:', 'O carvão mineral alimentando as máquinas a vapor.', 'A eletricidade gerada por usinas hidrelétricas.', 'O petróleo utilizado nos motores de combustão interna.', 'A energia eólica aplicada em moinhos.', 'A energia nuclear gerada em pequenos reatores.', 'a', 'A invenção da máquina a vapor (James Watt), movida a carvão mineral, substituiu a força humana e revolucionou os transportes (ferrovias) e a manufatura têxtil.', 'fácil', 0],
    [160, 'USP (FUVEST) 2021', 'A Segunda Revolução Industrial (a partir da segunda metade do século XIX) trouxe inovações cruciais e a expansão para novos países (EUA, Alemanha, Japão). Quais foram as indústrias de base e fontes de energia típicas dessa fase?', 'Setor têxtil e carvão vegetal.', 'Indústria automobilística, petroquímica e siderúrgica pesada; energia elétrica e derivados de petróleo.', 'Indústria microeletrônica, informática e energia eólica.', 'Biotecnologia, robótica e energia solar.', 'Ferrovias primárias, metalurgia do ferro e carvão mineral.', 'b', 'A Segunda Revolução é a era do aço, do petróleo (motor a combustão) e da eletricidade, permitindo a invenção do automóvel, telefone e química moderna.', 'médio', 0],
    [160, 'UNICAMP 2023', 'O modelo de organização da produção industrial denominado Fordismo, consolidado no início do século XX, baseava-se em:', 'Produção flexível e just-in-time, atendendo a nichos de consumo.', 'Trabalho artesanal valorizado e alta customização de produtos.', 'Linha de montagem móvel, padronização de peças e produção em massa de produtos iguais.', 'Desconcentração espacial das fábricas e terceirização global.', 'Foco absoluto no bem-estar psíquico do operário e cogestão da fábrica.', 'c', 'O Fordismo instituiu a esteira rolante (linha de montagem), ritmando o trabalho, gerando alta produtividade, barateando custos e ofertando produtos padronizados em massa (ex: Ford T).', 'fácil', 0],
    [160, 'UNESP 2020', 'O Toyotismo, desenvolvido no Japão pós-Guerra e característico da Terceira Revolução Industrial, difere do Fordismo por priorizar:', 'Grandes estoques de produtos prontos nas fábricas.', 'O método just-in-time e o trabalhador polivalente, flexível às demandas.', 'A rígida separação entre concepção e execução do trabalho manual.', 'A superespecialização do operário em uma única função repetitiva.', 'O uso exclusivo de mão de obra imigrante desqualificada.', 'b', 'O Toyotismo produz conforme a demanda ("just in time"), reduzindo estoques. O trabalhador não é especializado em uma só tarefa, mas qualificado para operar várias máquinas e processos.', 'médio', 0],
    [160, 'ENEM 2018', 'Qual impacto social negativo imediato ocorreu nos centros urbanos ingleses durante o ápice da Primeira Revolução Industrial?', 'Superlotação, péssimas condições de moradia e proliferação de doenças devido à falta de saneamento para a classe operária.', 'Envelhecimento da população causado pelo controle estatal de natalidade.', 'Criação de bairros sustentáveis para o operariado pelos industriais filantropos.', 'Acesso universal à educação primária gratuita e fim do trabalho infantil.', 'Retorno da maioria da população para as áreas rurais face à falta de empregos nas fábricas.', 'a', 'O rápido êxodo rural inchou cidades como Londres e Manchester, resultando em cortiços insalubres, ausência de esgoto e epidemias (cólera) atingindo a classe trabalhadora.', 'difícil', 1],

    // [161] Primeira e Segunda Guerra Mundial
    [161, 'ENEM 2021', 'O estopim que desencadeou o início da Primeira Guerra Mundial (1914-1918) foi:', 'O ataque alemão de submarinos aos navios mercantes americanos (Lusitânia).', 'A invasão da Polônia pelas tropas de Adolf Hitler.', 'O assassinato do arquiduque Francisco Ferdinando, herdeiro do trono Austro-Húngaro, em Sarajevo.', 'A assinatura do Tratado de Versalhes, humilhando a Alemanha.', 'A Revolução Russa e a saída da Rússia da guerra.', 'c', 'O assassinato ocorrido em junho de 1914 ativou as alianças militares (Tríplice Entente x Tríplice Aliança), dando início ao conflito de grandes proporções.', 'fácil', 0],
    [161, 'USP (FUVEST) 2019', 'Uma das consequências mais graves da Primeira Guerra Mundial foi a imposição do Tratado de Versalhes em 1919. A principal diretriz desse tratado foi:', 'A criação da União Europeia para garantir a paz duradoura.', 'A responsabilização exclusiva da Alemanha pela guerra, impondo-lhe pesadas indenizações e perda de territórios.', 'O plano de recuperação econômica de toda a Europa, financiado pelos EUA (Plano Marshall).', 'A divisão da Alemanha em duas Alemanhas (Ocidental e Oriental).', 'A anexação da Áustria e devolução da Alsácia-Lorena para o Império Alemão.', 'b', 'Versalhes impôs condições punitivas e humilhantes à Alemanha (indenizações, redução do exército, perda da Alsácia-Lorena), alimentando o revanchismo que culminou no Nazismo.', 'médio', 0],
    [161, 'UNICAMP 2022', 'O ataque aéreo e naval a Pearl Harbor, em 7 de dezembro de 1941, provocou uma virada significativa na Segunda Guerra Mundial, pois:', 'Resultou na rendição imediata das potências do Eixo.', 'Marcou a entrada oficial e direta dos Estados Unidos no conflito ao lado dos Aliados.', 'Forçou a União Soviética a assinar o pacto de não agressão Molotov-Ribbentrop com o Japão.', 'Iniciou o lançamento das bombas atômicas sobre o Japão no mesmo ano.', 'Provocou a saída da Inglaterra do conflito.', 'b', 'O ataque surpresa japonês à base militar no Havaí rompeu o isolacionismo americano, levando os EUA a declarar guerra ao Japão e, consequentemente, Alemanha e Itália.', 'fácil', 0],
    [161, 'UNESP 2020', 'A Batalha de Stalingrado (1942-1943) é amplamente considerada o principal ponto de virada da Segunda Guerra Mundial na Europa, pois resultou na:', 'Vitória definitiva das tropas de Hitler e tomada do petróleo soviético.', 'Primeira grande e catastrófica derrota do exército alemão em terra, iniciando o recuo nazista frente ao Exército Vermelho.', 'Evacuação heroica das tropas britânicas pelo Canal da Mancha (Dunquerque).', 'Abertura da frente ocidental com o desembarque na Normandia (Dia D).', 'Queda de Mussolini e rendição da Itália aos Aliados.', 'b', 'Stalingrado marcou o fracasso do Eixo no front oriental. A aniquilação do 6º Exército alemão quebrou o mito da invencibilidade nazista e iniciou a marcha soviética para Berlim.', 'médio', 0],
    [161, 'ENEM 2023', 'A criação do Tribunal de Nuremberg, logo após o término da Segunda Guerra Mundial, estabeleceu um precedente histórico fundamental no direito internacional moderno. Qual era o seu objetivo central?', 'Julgar e punir civil e criminalmente altas lideranças nazistas pelos crimes de guerra e crimes contra a humanidade.', 'Organizar a divisão territorial e as zonas de ocupação aliadas no Leste Europeu.', 'Estabelecer os limites para o uso pacífico de energia nuclear pelas potências vencedoras.', 'Condenar e banir os prisioneiros de guerra soviéticos para gulags na Sibéria.', 'Restaurar as monarquias depostas pelas potências do Eixo durante o conflito.', 'a', 'Nuremberg foi um tribunal militar internacional focado em responsabilizar líderes nazistas, introduzindo e aplicando penalmente a categoria jurídica de "crimes contra a humanidade".', 'difícil', 1],

    // [162] Geomorfologia e Climas do Brasil
    [162, 'UNICAMP 2020', 'O relevo brasileiro é caracterizado por formações antigas e rebaixadas por intenso processo erosivo. Qual a classificação de relevo predominante, onde se observam chapadas e escarpas, como a Serra do Mar?', 'Planícies de inundação', 'Cordilheiras de desdobramentos modernos', 'Planalto', 'Depressão absoluta', 'Dobramentos terciários', 'c', 'Os planaltos (que incluem serras e chapadas) são superfícies irregulares em que os processos de erosão superam os de deposição, e ocupam grande parte do Brasil.', 'fácil', 0],
    [162, 'USP (FUVEST) 2019', 'O clima Equatorial, predominante na Região Norte do Brasil, caracteriza-se por:', 'Altas temperaturas o ano todo e chuvas abundantes e bem distribuídas, sem estação seca.', 'Verões quentes e chuvosos, e invernos frios e muito secos.', 'Temperaturas amenas, chuvas concentradas no inverno e formação de geadas.', 'Baixa pluviosidade anual, ocorrendo secas severas.', 'Amplas amplitudes térmicas diárias, chegando a graus negativos à noite.', 'a', 'O clima equatorial da Amazônia tem baixa amplitude térmica anual, calor constante e chuvas praticamente diárias (índices pluviométricos acima de 2.000 mm/ano).', 'fácil', 0],
    [162, 'ENEM 2021', 'As depressões, na classificação do relevo de Jurandyr Ross, correspondem a áreas mais baixas que o entorno e formadas por processos erosivos. No Brasil, todas as depressões são:', 'Absolutas (abaixo do nível do mar).', 'Relativas (acima do nível do mar, mas abaixo dos planaltos vizinhos).', 'Formadas por vulcanismo recente do Quaternário.', 'Resultantes do choque direto de placas tectônicas (fossas).', 'Inexistentes, pois o Brasil só possui planaltos e planícies.', 'b', 'O Brasil não possui depressões absolutas (como o Mar Morto ou os Países Baixos). Nossas depressões são relativas, rebaixadas pela erosão entre bacias ou planaltos.', 'médio', 0],
    [162, 'UNESP 2022', 'A massa de ar responsável por levar o ar frio e seco do Polo Sul, causando queda brusca de temperaturas no Sul e Sudeste, além da "friagem" na região Norte durante o inverno, é a:', 'Massa Tropical Atlântica (mTa)', 'Massa Equatorial Continental (mEc)', 'Massa Polar Atlântica (mPa)', 'Massa Tropical Continental (mTc)', 'Massa Equatorial Atlântica (mEa)', 'c', 'A Massa Polar Atlântica (mPa) avança no inverno pelo corredor formado pelos Andes e Planalto Central, levando frio para o sul, sudeste e chegando ao Acre (friagem).', 'médio', 0],
    [162, 'USP (FUVEST) 2023', 'A formação dos "mares de morros", paisagem muito comum na porção litorânea do Sudeste (Mata Atlântica), deve-se principalmente ao processo de:', 'Ação intensa do intemperismo químico e erosão em rochas cristalinas num clima tropical úmido.', 'Erosão eólica esculpindo dunas de areia sobre bacias sedimentares.', 'Dobramentos modernos provocados pela placa de Nazca empurrando a placa Sul-Americana.', 'Acumulação de sedimentos glaciais do último período do Pleistoceno.', 'Inundação e deposição fluvial em grandes planícies amazônicas.', 'a', 'Os mares de morros (mamelonares/meias-laranjas) resultam do desgaste profundo (intemperismo químico) das antigas rochas cristalinas sob ação do calor e intensa umidade.', 'difícil', 1],

    // [163] Urbanização, Demografia e Migrações
    [163, 'ENEM 2021', 'O processo de urbanização brasileira foi rápido e concentrado, ocorrendo principalmente a partir da segunda metade do século XX. O principal fator impulsionador desse processo foi:', 'A reforma agrária radical promovida na década de 1950.', 'A industrialização por substituição de importações, que gerou empregos nas cidades e provocou êxodo rural.', 'A imigração maciça de europeus após a Segunda Guerra Mundial para o interior do país.', 'A descoberta de ouro em Minas Gerais.', 'O declínio da taxa de fecundidade e estagnação do crescimento populacional nas capitais.', 'b', 'A instalação de fábricas nas cidades (sobretudo no Sudeste) atraiu milhões de trabalhadores do campo, alavancando uma urbanização rápida e frequentemente desordenada.', 'fácil', 0],
    [163, 'UNICAMP 2020', 'O fenômeno de conurbação, muito comum em regiões metropolitanas como a de São Paulo e Rio de Janeiro, refere-se:', 'Ao despovoamento gradual dos centros históricos das grandes cidades.', 'À migração diária de trabalhadores entre cidade-dormitório e cidade central (movimento pendular).', 'À junção física das malhas urbanas de duas ou mais cidades vizinhas, que crescem até se encontrarem.', 'Ao surgimento de favelas verticais no topo de morros em áreas de risco.', 'Ao processo de revitalização urbana (gentrificação) que expulsa pobres da área central.', 'c', 'Conurbação é o processo espacial onde o crescimento contíguo das áreas urbanas de municípios fronteiriços faz com que eles se unam fisicamente, formando uma única mancha urbana.', 'médio', 0],
    [163, 'USP (FUVEST) 2018', 'Atualmente, o Brasil vivencia a transição demográfica. Uma das principais características dessa fase, observada na pirâmide etária brasileira recente, é:', 'A base extremamente larga, mostrando explosão de natalidade.', 'O estreitamento da base e o alargamento do topo, indicando queda da fecundidade e envelhecimento da população.', 'Uma drástica redução na proporção de adultos em relação às crianças (fim do bônus demográfico).', 'A predominância do sexo masculino na terceira idade devido à alta expectativa de vida masculina.', 'A diminuição progressiva da expectativa de vida provocada pelas doenças crônicas.', 'b', 'A redução da taxa de fecundidade estreita a base da pirâmide (menos crianças), enquanto o aumento da expectativa de vida alarga o topo e o corpo (mais adultos e idosos).', 'médio', 0],
    [163, 'UNESP 2021', 'Historicamente, qual foi a principal corrente migratória interna no Brasil entre as décadas de 1950 e 1980?', 'Sul -> Norte, para trabalhar no Ciclo da Borracha.', 'Nordeste -> Sudeste, atraídos pelas vagas na indústria e construção civil.', 'Sudeste -> Centro-Oeste, motivados pela mineração no século XIX.', 'Centro-Oeste -> Sul, em busca de terras para o agronegócio familiar.', 'Norte -> Nordeste, fugindo do desmatamento na Amazônia.', 'b', 'As secas no sertão e a miséria impulsionaram os nordestinos para o Sudeste (SP e RJ), onde a indústria e obras civis necessitavam de muita mão de obra.', 'fácil', 0],
    [163, 'ENEM 2022', 'O processo de "gentrificação" ocorre em grandes cidades e impacta fortemente a geografia social do espaço urbano, sendo definido como:', 'A construção de habitações populares financiadas pelo Estado em áreas centrais de alto valor.', 'A ocupação de terrenos vazios nas periferias distantes por sem-tetos e autoconstrução de moradias.', 'A valorização imobiliária e revitalização de bairros degradados que resulta na expulsão da população de baixa renda para áreas mais baratas.', 'A proibição municipal de construção de prédios altos em bairros de classe média.', 'O êxodo de moradores ricos do centro histórico em direção a condomínios fechados horizontais na periferia.', 'c', 'Gentrificação é o enobrecimento de áreas (geralmente centrais ou antigas), que atrai comércio gourmet e aumenta aluguéis, forçando os antigos moradores pobres a se mudarem.', 'difícil', 1],

    // [164] Geopolítica e Globalização Contemporânea (Part 2 - focusing on different aspects like BRICS, crises, tech)
    [164, 'ENEM 2019', 'O BRICS (grupo formado por Brasil, Rússia, Índia, China e África do Sul) tem se destacado no cenário internacional contemporâneo como:', 'Uma aliança militar nos moldes da OTAN para defesa mútua no Hemisfério Sul.', 'Uma zona de livre comércio onde não há tarifas alfandegárias entre os membros.', 'Um fórum diplomático e econômico de países emergentes, visando maior influência política global e financiamento de infraestrutura.', 'Um bloco estritamente ideológico de oposição ao sistema capitalista mundial.', 'A substituição da ONU em resoluções de conflitos geopolíticos.', 'c', 'O BRICS não é um bloco econômico clássico, mas um agrupamento político-estratégico de nações emergentes de grande porte para ampliar influência e cooperar (ex: Novo Banco de Desenvolvimento).', 'médio', 0],
    [164, 'USP (FUVEST) 2020', 'No contexto da globalização, o fenômeno da deslocalização industrial (offshoring) praticado por corporações transnacionais visa essencialmente:', 'Evitar o transporte marítimo global e aproximar as fábricas das matérias-primas raras.', 'Transferir unidades produtivas de países centrais para países em desenvolvimento, buscando mão de obra mais barata e menores leis trabalhistas e ambientais.', 'Concentrar a produção no país de origem para garantir o emprego nacional de sua matriz.', 'Inibir o desenvolvimento econômico de países periféricos retirando investimentos locais.', 'Estigmatizar e substituir robôs e máquinas por trabalho escravo nos EUA e Europa.', 'b', 'As transnacionais buscam reduzir custos transferindo indústrias (maquiladoras, confecções, montadoras) para a Ásia ou América Latina, onde salários e impostos são baixos.', 'médio', 0],
    [164, 'UNICAMP 2021', 'Uma das consequências do avanço da globalização neoliberal no século XXI é o acirramento das tensões comerciais. A chamada "Guerra Comercial", iniciada intensamente a partir de 2018, envolveu diretamente quais duas superpotências impondo tarifas mútuas?', 'Estados Unidos e União Europeia', 'Rússia e China', 'Estados Unidos e China', 'Reino Unido e Alemanha', 'Japão e Coreia do Sul', 'c', 'Durante o governo de Donald Trump, os EUA iniciaram uma guerra tarifária contra a China, acusando-a de práticas desleais, roubo de propriedade intelectual e déficit comercial, sendo retrucado por Pequim.', 'fácil', 0],
    [164, 'UNESP 2019', 'A Organização Mundial do Comércio (OMC) é a principal instituição reguladora das trocas globais. Qual o seu princípio básico perante os acordos internacionais?', 'A proibição de todo subsídio agrícola por países em desenvolvimento.', 'A condenação de todas as barreiras sanitárias e ambientais.', 'A padronização obrigatória da moeda em todas as negociações.', 'O livre comércio, combatendo o protecionismo e mediando disputas por meio da cláusula da "nação mais favorecida".', 'A garantia de superávit na balança comercial para países do Sul global.', 'd', 'A OMC atua para diminuir tarifas alfandegárias, combater o protecionismo e evitar práticas desleais de mercado (como dumping), tentando estimular o livre comércio.', 'fácil', 0],
    [164, 'ENEM 2021', 'A "Nova Rota da Seda" (Belt and Road Initiative), anunciada em 2013, é o maior e mais ambicioso projeto geopolítico de infraestrutura da atualidade, liderado por qual país e com qual principal objetivo estratégico?', 'Rússia; reviver o poder soviético e reconquistar as repúblicas da Europa Oriental.', 'Estados Unidos; construir dutos interoceânicos unindo as Américas à África para frear a Ásia.', 'Índia; dominar a tecnologia de fibra óptica do Oceano Índico conectando África do Sul e Austrália.', 'China; integrar comercialmente e expandir sua influência geopolítica pela Ásia, África e Europa através de portos, ferrovias e estradas financiados por Pequim.', 'União Europeia; interligar os países dos Bálcãs para facilitar a migração de trabalhadores.', 'd', 'Pequim está investindo trilhões em infraestrutura global para facilitar suas exportações, garantir matérias-primas e consolidar-se como a principal superpotência do século XXI.', 'difícil', 1],
];

$stmt = $pdo->prepare("INSERT INTO questions (lesson_id, exam_source, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation_text, difficulty, is_boss) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
$inserted = 0;
$errors = 0;
foreach ($questions as $q) {
    try { 
        $stmt->execute($q); 
        $inserted++; 
    } 
    catch (Exception $e) { 
        $errors++; 
        echo "ERRO ao inserir: " . $e->getMessage() . "\n"; 
    }
}
echo "\nInseridas: {$inserted} | Erros: {$errors}\n";
?>
