<?php
require_once __DIR__ . '/../config/db.php';
echo "=== Inserindo questões de História e Geografia Extras ===\n\n";

$questions = [
    // [101] Brasil Colônia e Economia Açucareira
    [101, 'UFPR 2023', 'A colonização do Brasil nos séculos XVI e XVII estruturou-se, economicamente, em torno da produção açucareira. Que modelo de exploração agrícola foi adotado por Portugal?', 'A agricultura familiar voltada para o mercado interno', 'A plantation, baseada em latifúndio, monocultura, trabalho escravo e exportação', 'O sistema de parceria com colonos europeus assalariados', 'A extração vegetal extrativista sem alteração do meio ambiente', 'A policultura de subsistência em pequenas propriedades', 'b', 'O sistema de plantation foi a base da economia colonial açucareira, caracterizando-se por grandes propriedades de terra (latifúndios), foco na produção de um único produto (monocultura), uso intenso de mão de obra escravizada (indígena e, principalmente, africana) e produção voltada para o mercado externo.', 'fácil', 0],
    [101, 'UFMG 2024', 'As capitanias hereditárias foram a primeira tentativa administrativa de colonização portuguesa. Qual foi o principal motivo para o fracasso desse sistema na maior parte do território?', 'O excessivo apoio financeiro da Coroa portuguesa que desestimulou o trabalho', 'A falta de interesse dos donatários, a hostilidade indígena e a falta de recursos', 'A descoberta imediata de ouro, que desviou a atenção do litoral', 'O ataque constante de nações europeias aliadas de Portugal', 'A abundância de mão de obra livre europeia nas terras coloniais', 'b', 'O fracasso da maioria das capitanias deveu-se ao desinteresse de muitos donatários, que nem chegaram a vir ao Brasil, além dos altos custos para colonizar, da resistência e ataques dos indígenas (como os Tamoios) e da falta de infraestrutura e apoio contínuo de Portugal.', 'médio', 0],
    [101, 'UERJ 2023', 'O Pacto Colonial estabelecia o exclusivismo comercial. Como isso se refletia na economia da colônia portuguesa na América?', 'A colônia tinha liberdade para comercializar com qualquer nação europeia', 'A colônia apenas podia exportar e importar produtos da metrópole ou com a autorização desta', 'A metrópole comprava os produtos coloniais pelo preço fixado internacionalmente', 'Havia isenção de impostos sobre produtos industrializados ingleses', 'Permitia-se a criação de manufaturas locais para evitar importações', 'b', 'O Pacto Colonial (ou exclusivo metropolitano) obrigava a colônia a realizar transações comerciais (compra de manufaturas e venda de matérias-primas) exclusivamente com a metrópole, garantindo lucros à burguesia e ao Estado metropolitano.', 'difícil', 1],

    // [102] Mineração e Inconfidências no Brasil
    [102, 'UFRGS 2024', 'Durante o século XVIII, a descoberta de ouro em Minas Gerais causou profundas transformações no Brasil colônia. Qual das seguintes alterações demográficas ocorreu nesse período?', 'Esvaziamento do litoral Nordeste em direção ao sul e interior', 'Um enorme afluxo populacional para a região das minas, gerando os primeiros núcleos urbanos significativos no interior', 'O crescimento exclusivo de populações indígenas nas áreas de mineração', 'A proibição da entrada de portugueses na colônia, visando controlar o contrabando', 'A dispersão da população rural para o extremo norte da colônia', 'b', 'A corrida do ouro atraiu milhares de pessoas, tanto de outras regiões da colônia quanto de Portugal e da África (escravizados), causando uma forte urbanização nas áreas mineradoras, como Ouro Preto e Mariana.', 'fácil', 0],
    [102, 'UEL 2023', 'A Inconfidência Mineira (1789) e a Conjuração Baiana (1798) foram movimentos emancipacionistas. Qual é uma diferença fundamental entre eles em relação aos seus objetivos sociais?', 'Ambas defendiam a abolição imediata da escravidão, mas a Mineira queria uma monarquia', 'A Conjuração Baiana teve forte caráter popular e defendia o fim da escravidão, enquanto a Mineira foi elitista e não propôs a abolição', 'A Inconfidência Mineira era republicana popular, e a Baiana monarquista de elite', 'Apenas a Conjuração Baiana foi influenciada pelo Iluminismo francês', 'A Inconfidência Mineira ocorreu após a independência dos EUA, mas a Baiana a antecedeu', 'b', 'A Inconfidência Mineira, liderada pela elite econômica local, evitou a questão da abolição, temendo perder a mão de obra. A Conjuração Baiana teve ampla participação de negros libertos, escravizados e artesãos, propondo igualdade racial e fim da escravidão.', 'médio', 0],
    [102, 'UEM 2024', 'Para controlar a exploração aurífera, a Coroa Portuguesa instituiu as Casas de Fundição em 1720. Qual era a sua função e que conflito imediato ela gerou?', 'Fundir o ouro em barras e cobrar o quinto, o que causou a Revolta de Vila Rica', 'Garantir direitos trabalhistas aos mineradores, gerando a Guerra dos Emboabas', 'Fornecer ferramentas de mineração aos escravizados, causando a Revolta de Beckman', 'Exportar o ouro direto para a Inglaterra, provocando a Inconfidência Mineira', 'Cunhar moedas de prata e ouro sem impostos, causando a Guerra dos Mascates', 'a', 'As Casas de Fundição foram criadas para transformar o ouro em pó (fácil de contrabandear) em barras timbradas, já descontando o imposto do quinto (20%). A insatisfação com essas medidas levou à Revolta de Vila Rica, liderada por Filipe dos Santos em 1720.', 'difícil', 1],

    // [103] Brasil Império e Independência
    [103, 'MACKENZIE 2023', 'Em 1808, a vinda da Família Real portuguesa para o Brasil mudou definitivamente a situação colonial. Qual foi a primeira grande medida econômica tomada por D. João VI?', 'A Proclamação da República no Rio de Janeiro', 'A assinatura do Tratado de Tordesilhas', 'A Abertura dos Portos às Nações Amigas', 'A decretação do fim da escravidão africana', 'A imposição do monopólio do café no Sudeste', 'c', 'Chegando à Bahia em 1808, D. João VI decretou a Abertura dos Portos, quebrando formalmente o Pacto Colonial e permitindo que o Brasil comercializasse livremente, especialmente com a Inglaterra, aliada de Portugal.', 'fácil', 0],
    [103, 'PUC-SP 2024', 'A Constituição outorgada de 1824, a primeira do Brasil independente, apresentava como uma de suas características mais marcantes:', 'O estabelecimento do voto universal secreto e feminino', 'A criação do Poder Moderador, exclusivo do Imperador, acima dos outros poderes', 'A descentralização política com ampla autonomia para as províncias', 'O rompimento oficial e definitivo entre o Estado e a Igreja Católica', 'A adoção do parlamentarismo clássico, no qual o monarca não governava', 'b', 'A Constituição de 1824 estabeleceu quatro poderes. O Poder Moderador, exercido exclusivamente por D. Pedro I, lhe conferia a autoridade de nomear ministros, dissolver a Câmara dos Deputados e intervir no Judiciário, garantindo um regime centralizador e autoritário.', 'médio', 0],
    [103, 'UFSC 2023', 'A Guerra do Paraguai (1864-1870) foi o maior conflito armado da América do Sul. Que consequências o conflito trouxe para o Império do Brasil em relação ao Exército?', 'O Exército foi extinto e substituído pela Guarda Nacional para evitar golpes', 'O Exército perdeu prestígio político e foi reduzido em número e armamento', 'O Exército saiu fortalecido, desenvolveu ideais republicanos e abolicionistas, e passou a intervir na política', 'Os militares lideraram um movimento de fortalecimento do poder pessoal de D. Pedro II', 'A guerra dividiu o Exército, que se aliou à Argentina para destituir o Imperador brasileiro', 'c', 'O Exército Brasileiro retornou do Paraguai organizado, consciente de sua força, mas insatisfeito com a monarquia (questão militar). O convívio de escravizados no front gerou simpatia abolicionista, e o positivismo militar impulsionou o movimento republicano.', 'difícil', 1],

    // [104] República Velha e Era Vargas
    [104, 'UnB 2024', 'Durante a chamada República Velha (1889-1930), a "Política dos Governadores" e o "Coronelismo" foram mecanismos essenciais para a estabilidade política. O que era o coronelismo?', 'Um sistema de dominação local onde chefes políticos (coronéis) controlavam o voto popular por meio de clientelismo e violência (voto de cabresto)', 'A militarização da política nacional, na qual apenas militares poderiam concorrer a cargos executivos', 'Uma aliança entre camponeses e operários para derrubar a elite cafeeira de São Paulo e Minas Gerais', 'O movimento de valorização do café, financiado por empréstimos externos', 'A rebelião dos tenentes nas capitais contra o domínio das oligarquias rurais', 'a', 'O coronelismo foi a base do poder oligárquico. Os "coronéis" (grandes proprietários de terra) trocavam favores por votos, ou usavam intimidação e fraude (voto de cabresto) para eleger os candidatos das oligarquias estaduais e federais.', 'fácil', 0],
    [104, 'IF-SP 2023', 'Em 1930, a Revolução colocou fim à hegemonia das oligarquias paulista e mineira e iniciou a Era Vargas. Qual foi a principal medida trabalhista instituída durante o Estado Novo (1937-1945)?', 'A extinção da jornada de trabalho e o fim dos salários mínimos', 'A criação da CLT (Consolidação das Leis do Trabalho) em 1943, regulamentando as relações de trabalho', 'A legalização de sindicatos autônomos e partidos comunistas no Brasil', 'A privatização das indústrias de base e o fim dos direitos previdenciários', 'O estímulo à organização de greves gerais para combater o capital estrangeiro', 'b', 'No Estado Novo, Vargas consolidou a legislação trabalhista com a CLT, instituindo salário mínimo, férias remuneradas e jornada de 8 horas. No entanto, manteve controle estatal rígido sobre os sindicatos (sindicalismo de Estado ou peleguismo) e proibiu greves.', 'médio', 0],
    [104, 'SENAI 2024', 'A Revolta da Vacina, ocorrida no Rio de Janeiro em 1904, representou a insatisfação popular durante a Primeira República. Além da obrigatoriedade da vacinação antivariólica, que outro fator estrutural provocou o levante?', 'A quebra da Bolsa de Nova Iorque e a consequente crise do café', 'A proibição do Carnaval e das festividades populares católicas pelo governo federal', 'A reforma urbana de Pereira Passos (bota-abaixo), que expulsou os pobres do centro, agravando o custo de vida', 'A promulgação da Constituição de 1891, que retirou o direito de voto das mulheres', 'O recrutamento militar forçado para combater a Revolta da Chibata na Marinha', 'c', 'A Revolta da Vacina foi o estopim de insatisfações acumuladas. A reforma higienista e estética do prefeito Pereira Passos demoliu cortiços no centro, empurrando as populações pobres para os morros (favelização) sem oferecer alternativas de moradia, gerando profundo ressentimento social.', 'difícil', 1],

    // [105] Ditadura Militar e Redemocratização
    [105, 'UFPR 2023', 'O Ato Institucional nº 5 (AI-5), decretado em dezembro de 1968, é considerado o marco mais repressivo da Ditadura Militar no Brasil. Qual destas medidas foi implementada pelo AI-5?', 'A convocação imediata de eleições diretas para presidente', 'A anistia ampla, geral e irrestrita a todos os exilados políticos', 'O fechamento do Congresso Nacional e a suspensão do direito de habeas corpus para crimes políticos', 'O restabelecimento do pluripartidarismo no sistema eleitoral', 'A revogação da Constituição de 1967 e o retorno à ordem democrática', 'c', 'O AI-5 endureceu o regime, permitindo ao presidente fechar o Congresso, cassar mandatos, suspender direitos políticos e o habeas corpus para crimes políticos, além de instaurar censura prévia institucionalizada sobre os meios de comunicação.', 'fácil', 0],
    [105, 'UFMG 2024', 'Durante a década de 1970, o Brasil viveu o chamado "Milagre Econômico". Quais foram as principais características econômicas e sociais desse período?', 'Redução drástica da dívida externa e ampla distribuição de renda para a classe trabalhadora', 'Altas taxas de crescimento do PIB, impulsionadas por empréstimos externos e obras faraônicas, associadas ao arrocho salarial e aumento da desigualdade', 'Estagnação industrial com foco total na exportação de pau-brasil e cana-de-açúcar', 'O rompimento com o FMI e a estatização completa dos meios de produção industriais', 'Crescimento econômico sustentável baseado no uso de energias renováveis e conservação ambiental', 'b', 'O Milagre Econômico (governo Médici) registrou taxas de crescimento de até 10% ao ano, financiadas por capital externo. Contudo, baseou-se no achatamento dos salários mínimos, concentrando a riqueza nas elites e gerando uma enorme dívida externa, que explodiria na "década perdida" dos anos 1980.', 'médio', 0],
    [105, 'UERJ 2023', 'A campanha das "Diretas Já", entre 1983 e 1984, mobilizou milhões de brasileiros, mas a Emenda Dante de Oliveira, que a fundamentava, foi derrotada no Congresso. Como ocorreu a transição presidencial em 1985?', 'Pela manutenção dos militares no poder até 1989', 'Por um levante armado que derrubou o presidente João Figueiredo e instaurou a Nova República', 'Por eleição direta, elegendo Tancredo Neves contra Paulo Maluf', 'Pela eleição indireta no Colégio Eleitoral, onde Tancredo Neves e José Sarney derrotaram o candidato do regime, Paulo Maluf', 'Pela renúncia dos militares e posse imediata do presidente do STF', 'd', 'Mesmo com a pressão popular pelas "Diretas Já", a emenda não atingiu os votos necessários. A eleição presidencial de 1985 ocorreu de forma indireta. A chapa de oposição (Tancredo Neves/José Sarney) venceu no Colégio Eleitoral, encerrando os 21 anos de ditadura.', 'difícil', 1],

    // [106] Antiguidade Clássica: Grécia e Roma
    [106, 'UFRGS 2024', 'A democracia ateniense, desenvolvida no século V a.C., é frequentemente citada como um modelo inicial de participação política. Qual era uma característica limitadora dessa democracia?', 'Apenas homens nobres e ricos podiam votar, excluindo os cidadãos pobres', 'As decisões políticas eram tomadas por um conselho de reis vitalícios, não pela assembleia popular', 'O direito de voto e participação excluía mulheres, escravos e estrangeiros (metecos)', 'A cidadania era garantida a qualquer pessoa que residisse em Atenas por mais de um ano', 'Os senadores atenienses não podiam possuir terras', 'c', 'Embora fosse uma democracia direta onde os cidadãos votavam, o conceito de "cidadão" era muito restrito: apenas homens, livres, nascidos em Atenas de pais atenienses e maiores de idade. Mulheres, escravos e estrangeiros não possuíam direitos políticos.', 'fácil', 0],
    [106, 'UEL 2023', 'A transição da República para o Império Romano, no século I a.C., foi marcada por longas guerras civis. Qual líder político foi fundamental para o fim das instituições republicanas e assumiu plenos poderes, originando o Império?', 'Tibério Graco, após aprovar a reforma agrária', 'Júlio César, que, após ser assassinado, teve seu filho adotivo Otávio Augusto estabelecendo o Principado', 'Espártaco, após vencer as legiões no sul da Itália', 'Constantino, ao oficializar o cristianismo no Senado', 'Cipião Africano, após derrotar Cartago nas Guerras Púnicas', 'b', 'A crise da República culminou com as ditaduras de generais. Júlio César enfraqueceu o Senado e, após seu assassinato, seu sobrinho-neto Otávio venceu Marco Antônio. Otávio recebeu o título de Augusto em 27 a.C., concentrando o poder e inaugurando o Império.', 'médio', 0],
    [106, 'UEM 2024', 'A Guerra do Peloponeso (431-404 a.C.) foi um conflito devastador no mundo grego. Ela opôs duas grandes ligas militares, lideradas por Atenas e Esparta. Qual foi o principal motivo desse conflito?', 'A invasão do Império Persa, que forçou Atenas e Esparta a lutarem entre si por suprimentos', 'O expansionismo e imperialismo de Atenas através da Liga de Delos, que ameaçava a hegemonia espartana no Peloponeso', 'As diferenças religiosas, visto que Esparta não cultuava os deuses olímpicos', 'O desejo de Esparta em impor a democracia em todo o mundo grego', 'A disputa pelo controle das rotas comerciais do Mar Mediterrâneo Ocidental com Cartago', 'b', 'Após as Guerras Médicas (contra os persas), Atenas converteu a Liga de Delos num império naval e econômico, impondo tributos e seu modelo democrático a outras cidades. Esparta, oligárquica e militarista, liderou a Liga do Peloponeso para barrar o imperialismo ateniense.', 'difícil', 1],

    // [107] Feudalismo e Idade Média
    [107, 'MACKENZIE 2023', 'A sociedade feudal, na Europa Ocidental durante a Idade Média, possuía uma divisão rígida. Como essa sociedade era estratificada segundo a mentalidade da época?', 'Dividida em duas classes móveis: patrões capitalistas e proletários assalariados', 'Organizada em castas ligadas a profissões, permitindo ampla ascensão social através do comércio', 'Estruturada nas três ordens: os que oram (clero), os que lutam (nobreza) e os que trabalham (servos)', 'Composta por cidadãos livres nas cidades e escravos atrelados à Igreja', 'Dividida entre os burocratas do Estado nacional e os militares', 'c', 'A sociedade estamental do feudalismo era justificada pela Igreja Católica através da ideologia das três ordens: o clero cuidava da salvação espiritual (oratores), a nobreza da defesa militar (bellatores) e os camponeses/servos do sustento material (laboratores). A mobilidade social era quase nula.', 'fácil', 0],
    [107, 'PUC-SP 2024', 'As relações de suserania e vassalagem foram centrais para a política feudal. Como essas relações funcionavam?', 'Eram relações de servidão entre senhores feudais e os camponeses que trabalhavam nas terras', 'Tratava-se de alianças militares e doações de terras (feudos) exclusivamente entre membros da nobreza', 'Era o acordo comercial entre corporações de ofício nas cidades renascentistas', 'Foi o sistema de arrecadação de impostos dos reis absolutistas', 'Tratava-se de um acordo entre a Igreja e os servos para o pagamento do dízimo', 'b', 'Suserania e vassalagem eram laços de dependência mútua, restritos à elite nobre. O suserano doava um feudo a um vassalo; em troca, o vassalo jurava fidelidade militar e conselho. Isso gerou uma extrema fragmentação do poder político na Idade Média.', 'médio', 0],
    [107, 'UFSC 2023', 'No final da Idade Média, a Europa enfrentou a "Crise do Século XIV". A Guerra dos Cem Anos, a fome e a Peste Negra devastaram o continente. Qual foi uma das principais consequências estruturais dessa crise para o sistema feudal?', 'A escassez de mão de obra fortaleceu o poder de barganha dos camponeses sobreviventes e acelerou o declínio das relações servis', 'O aumento da população, forçando as Cruzadas para conquistar terras no Oriente Médio', 'A desestruturação total do cristianismo e o fortalecimento de religiões orientais na Europa', 'O fim do mercantilismo e o retorno ao escambo como única forma de comércio', 'A imediata implantação de governos republicanos na Inglaterra e na França', 'a', 'Com a morte de cerca de um terço da população europeia, houve brutal falta de trabalhadores. Os nobres tentaram aumentar a exploração feudal (gerando as Jacqueries e revoltas camponesas), mas, no longo prazo, as relações servis se enfraqueceram, abrindo caminho para o trabalho livre e a centralização monárquica.', 'difícil', 1],

    // [108] Revoluções Industriais e Iluminismo
    [108, 'UnB 2024', 'O Iluminismo, movimento intelectual do século XVIII, fez severas críticas ao Antigo Regime europeu. O que os filósofos iluministas mais combatiam?', 'A razão, o método científico e a igualdade civil', 'O absolutismo monárquico, o mercantilismo e os privilégios da nobreza e do clero', 'O liberalismo econômico e a ascensão da burguesia', 'A revolução industrial e o uso de máquinas a vapor', 'A separação entre Igreja e Estado, defendendo Estados teocráticos', 'b', 'Os iluministas defendiam o uso da razão (luz) contra as "trevas" da ignorância e tradição. Politicamente combatiam o absolutismo real; economicamente combatiam o mercantilismo (intervenção do Estado); e socialmente combatiam a sociedade de privilégios e o dogmatismo religioso.', 'fácil', 0],
    [108, 'IF-SP 2023', 'A Primeira Revolução Industrial, iniciada na Inglaterra na segunda metade do século XVIII, marcou a transição da manufatura para a maquinofatura. Qual setor industrial foi o pioneiro dessa transformação?', 'A indústria química de fertilizantes', 'A indústria petroquímica', 'A indústria têxtil de algodão', 'A indústria automobilística', 'A indústria de softwares e telecomunicações', 'c', 'O pioneirismo inglês se deu na indústria têxtil algodoeira, impulsionada por inovações como a máquina de fiar (spinning jenny) e o tear mecânico movido a vapor, baseados no uso do carvão mineral, produzindo tecidos baratos em larga escala.', 'médio', 0],
    [108, 'SENAI 2024', 'Durante o Iluminismo, o pensador Montesquieu escreveu a obra "O Espírito das Leis". Qual foi sua principal contribuição teórica, adotada em quase todas as democracias modernas?', 'A teoria do direito divino dos reis, justificando o poder centralizado', 'A abolição total da propriedade privada, influenciando o socialismo', 'O Contrato Social, em que a vontade geral deveria ditar todas as leis sem representantes', 'A divisão dos poderes do Estado em Executivo, Legislativo e Judiciário, para evitar o despotismo', 'O Despotismo Esclarecido, em que o rei governa através da filosofia iluminista, mas com poder absoluto', 'd', 'Montesquieu propôs a tripartição de poderes. Segundo ele, "só o poder freia o poder". A separação entre Executivo (que administra), Legislativo (que cria as leis) e Judiciário (que julga) garantiria a liberdade política e impediria a tirania típica do absolutismo.', 'difícil', 1],

    // [109] Primeira e Segunda Guerra Mundial
    [109, 'UFPR 2023', 'O assassinato do Arquiduque Francisco Ferdinando, em Sarajevo (1914), foi o estopim da Primeira Guerra Mundial. No entanto, qual era a principal causa estrutural (profunda) que já tensionava a Europa?', 'O Tratado de Versalhes, que puniu excessivamente a Alemanha', 'A Guerra Fria e a corrida armamentista nuclear entre EUA e URSS', 'O Imperialismo (Neocolonialismo) e a disputa por mercados e territórios na África e Ásia', 'A queda do Muro de Berlim e a expansão do comunismo na Europa Oriental', 'A disputa religiosa entre católicos e protestantes no Império Britânico', 'c', 'A principal causa da 1ª Guerra foi o acirramento das rivalidades imperialistas. Potências como Inglaterra, França e a recém-unificada Alemanha disputavam colônias e zonas de influência para garantir matérias-primas e mercados escoadouros de produtos industriais.', 'fácil', 0],
    [109, 'UFMG 2024', 'O Tratado de Versalhes (1919) selou a paz após a Primeira Guerra Mundial. Qual foi sua principal característica em relação à Alemanha, derrotada no conflito?', 'Ofereceu pesados investimentos americanos à Alemanha através do Plano Marshall', 'Dividiu a Alemanha em dois Estados independentes: a RFA e a RDA', 'Impôs sanções humilhantes, perdas territoriais, redução militar drástica e enormes indenizações de guerra à Alemanha', 'Perdoou todas as dívidas de guerra da Alemanha, visando reconstruir rapidamente sua economia', 'Restaurou a monarquia do Kaiser Guilherme II para estabilizar o continente', 'c', 'O Tratado de Versalhes foi considerado um "Diktat" (imposição). Culpabilizou unicamente a Alemanha pela guerra, gerando um profundo ressentimento econômico e nacionalista que seria posteriormente explorado por Adolf Hitler e pelo Partido Nazista.', 'médio', 0],
    [109, 'UERJ 2023', 'Na Segunda Guerra Mundial, as batalhas de Stalingrado, Midway e El Alamein, ocorridas em 1942, são consideradas pontos de virada do conflito. Qual foi o impacto comum dessas três batalhas?', 'A rendição imediata do Japão, após os combates', 'Elas marcaram as primeiras grandes vitórias estratégicas dos Aliados sobre as potências do Eixo, contendo suas expansões e invertendo o curso da guerra', 'Foram responsáveis pela entrada dos Estados Unidos no conflito ao lado dos Aliados', 'Resultaram no pacto de não agressão entre Hitler e Stalin, dividindo o mundo', 'Levaram ao uso das primeiras armas nucleares pelos exércitos soviéticos', 'b', 'Até 1942, o Eixo avançava implacavelmente. Midway parou o Japão no Pacífico; El Alamein deteve as forças germano-italianas no norte da África, protegendo o Canal de Suez; e Stalingrado destroçou o exército alemão na URSS, marcando o início da ofensiva aliada até a vitória final.', 'difícil', 1],

    // [110] Guerra Fria e Conflitos Contemporâneos
    [110, 'UFRGS 2024', 'O fim da Segunda Guerra Mundial deu início a um período chamado de "Guerra Fria". Como se caracterizou essa ordem mundial entre 1947 e 1991?', 'Um mundo multipolar de paz e cooperação comercial livre entre todos os continentes', 'O confronto bélico direto e constantes guerras convencionais na Europa entre Estados Unidos e União Soviética', 'A divisão bipolar do mundo em blocos antagônicos (capitalista liderado pelos EUA e socialista pela URSS), marcado por corrida armamentista e espacial', 'A dominação total do mundo pelo Império Britânico por meio de armas nucleares', 'O surgimento da União Europeia como a única superpotência global indiscutível', 'c', 'A Guerra Fria caracterizou-se pela ausência de conflitos diretos entre as duas superpotências, mas envolveu uma constante disputa ideológica, econômica, tecnológica (corrida espacial) e armamentista, além do financiamento de conflitos locais (Guerras por procuração, como no Vietnã e Coreia).', 'fácil', 0],
    [110, 'UEL 2023', 'A Doutrina Truman (1947) e o Plano Marshall foram respostas diretas dos Estados Unidos no alvorecer da Guerra Fria. O que estipulava o Plano Marshall?', 'Um pacto militar ofensivo visando invadir a União Soviética', 'Um programa de ajuda econômica e financeira para reconstruir a Europa Ocidental, visando barrar o avanço de movimentos comunistas no continente', 'A construção do Muro de Berlim para separar as áreas ocidental e oriental', 'O fornecimento exclusivo de armas nucleares aos países do Terceiro Mundo', 'O bloqueio marítimo a Cuba após a revolução castrista', 'b', 'O Plano Marshall consistiu em maciços investimentos de capital norte-americano na Europa arrasada pela guerra. O objetivo prático era recuperar as economias capitalistas europeias e criar um "cordão sanitário" para evitar que a pobreza fortalecesse os partidos comunistas e a influência soviética.', 'médio', 0],
    [110, 'UEM 2024', 'O conflito árabe-israelense é uma das questões geopolíticas mais duradouras do século XX e XXI. A Guerra dos Seis Dias (1967) alterou profundamente o mapa do Oriente Médio. Qual foi o principal resultado geográfico dessa guerra?', 'A fundação imediata do Estado da Palestina e a retirada dos colonos judeus', 'A destruição completa de Israel pelos exércitos do Egito e da Síria', 'Israel conquistou a Península do Sinai, Faixa de Gaza, Cisjordânia, Jerusalém Oriental e as Colinas de Golã', 'A devolução imediata da Cisjordânia ao Império Otomano', 'A assinatura de um tratado de paz duradouro entre árabes e judeus mediado pela ONU', 'c', 'Em um ataque preventivo rápido, Israel derrotou Egito, Síria e Jordânia, multiplicando o território sob seu controle e ocupando áreas com densa população árabe-palestina. Essa ocupação acirrou a questão palestina e os conflitos que se desenrolam até a atualidade.', 'difícil', 1],

    // [111] Geomorfologia, Relevo e Solos do Brasil
    [111, 'MACKENZIE 2023', 'O relevo brasileiro, segundo a classificação mais moderna de Jurandyr Ross, não apresenta dobramentos modernos (como os Andes ou os Alpes). Qual é a principal explicação geológica para isso?', 'O Brasil localiza-se na borda de encontro da placa Sul-Americana com a placa de Nazca', 'O Brasil está situado no centro da Placa Tectônica Sul-Americana, longe das zonas de choque de placas', 'A intensa atividade vulcânica do Quaternário arrasou as montanhas existentes', 'O território brasileiro é recente do ponto de vista geológico', 'Os grandes rios da Bacia Amazônica erodiram todas as cordilheiras', 'b', 'Por estar posicionado no meio da Placa Sul-Americana, o Brasil apresenta grande estabilidade tectônica e ausência de orogênese (formação de montanhas) recente. Portanto, não possui montanhas, tendo seu relevo formado por rochas antigas e desgastadas pela erosão.', 'fácil', 0],
    [111, 'PUC-SP 2024', 'A região Nordeste possui grande diversidade de solos. O Massapé é um solo de excelente fertilidade e grande importância histórica. Onde ele é encontrado e a que cultivo está associado?', 'Na Caatinga, no sertão nordestino, cultivando soja', 'Na Zona da Mata, no litoral nordestino, sendo historicamente ligado à lavoura de cana-de-açúcar', 'No Agreste, nas áreas de transição, onde se cultiva café', 'No Meio-Norte, associado ao extrativismo da borracha', 'Nos chapadões do Cerrado nordestino, associado ao milho', 'b', 'O solo de massapé é extremamente escuro, argiloso e fértil, resultante da decomposição de rochas calcárias e gnaisses. Localiza-se na faixa úmida litorânea do Nordeste (Zona da Mata) e propiciou a fixação da agroindústria açucareira desde o período colonial.', 'médio', 0],
    [111, 'UFSC 2023', 'O solo conhecido como "Terra Roxa" (Latossolo Vermelho) é um dos mais férteis do Brasil e foi crucial para a expansão cafeeira. Qual é a origem geológica desse solo e em que região ele se concentra?', 'Origina-se da decomposição de basalto gerado por derrames vulcânicos na Era Mesozoica e concentra-se no norte do Paraná e interior de São Paulo', 'Resulta do intemperismo de granito da Era Pré-Cambriana e localiza-se na Floresta Amazônica', 'Deriva da deposição de sedimentos marinhos na Bacia Sedimentar do Parnaíba no nordeste do país', 'Surge pela decomposição de calcário e está presente exclusivamente nas encostas da Serra do Mar', 'Origina-se de sedimentos fluviais depositados durante o Holoceno no Pantanal Mato-Grossense', 'a', 'O derrame basáltico ocorrido na bacia sedimentar do Paraná durante a Era Mesozoica formou a rocha ígnea (basalto) que, ao sofrer intenso intemperismo químico em clima tropical, gerou a fertilíssima Terra Roxa, motor da economia paulista e paranaense no século XX.', 'difícil', 1],

    // [112] Climatologia e Domínios Morfoclimáticos
    [112, 'UnB 2024', 'Qual é a principal massa de ar responsável por levar umidade, chuvas e provocar quedas de temperatura (frentes frias) nas regiões Sul e Sudeste do Brasil durante o inverno?', 'Massa Equatorial Continental (mEc)', 'Massa Tropical Atlântica (mTa)', 'Massa Polar Atlântica (mPa)', 'Massa Equatorial Atlântica (mEa)', 'Massa Tropical Continental (mTc)', 'c', 'A Massa Polar Atlântica (mPa) nasce fria e úmida no Atlântico Sul. No inverno, ela ganha força e avança pelo continente brasileiro, causando geadas no Sul, frentes frias no Sudeste e o fenômeno da friagem no sul da Amazônia.', 'fácil', 0],
    [112, 'IF-SP 2023', 'Aziz Ab\'Sáber propôs a divisão do Brasil em "Domínios Morfoclimáticos". O Domínio do Cerrado, no Brasil central, possui características marcantes na sua vegetação. Qual destas é uma adaptação típica do Cerrado às suas condições climáticas (Clima Tropical)?', 'Folhas largas e verdes o ano todo (perenifólias), típicas da elevada umidade constante', 'Raízes rasas e copas estreitas para lidar com solos rasos e frios rigorosos', 'Caule tortuoso, casca grossa (súber) e raízes muito profundas, adaptações às secas sazonais e ao fogo natural', 'Formações arbóreas homogêneas, formadas exclusivamente por pinheiros', 'Vegetação hidrófila, com raízes submersas e caules finos', 'c', 'O Cerrado apresenta clima tropical (verão chuvoso e inverno muito seco). A vegetação é adaptada (tropófita e xeromorfa). As raízes profundas buscam água nos lençóis freáticos, enquanto a casca grossa protege o lenho das queimadas típicas da estação seca.', 'médio', 0],
    [112, 'SENAI 2024', 'No Domínio da Caatinga (clima Semiárido), os rios possuem um regime hidrológico específico influenciado pelo baixo índice pluviométrico. A maioria dos rios desse domínio é classificada como:', 'Perenes, com alto volume de água constante alimentado pelo derretimento de neves', 'Intermitentes (ou temporários), que secam durante o longo período de estiagem, exceto o Rio São Francisco e o Parnaíba', 'Endorreicos permanentes, que não chegam ao mar e mantêm lagos o ano inteiro', 'Nivais intermitentes, fluindo apenas no verão', 'Perenes torrenciais, com cheias destruidoras o ano todo', 'b', 'Devido ao clima semiárido, com secas prolongadas e chuvas escassas e mal distribuídas, os rios do sertão secam na estiagem (intermitentes). O rio São Francisco cruza a região, mas é perene porque suas nascentes ficam no domínio tropical chuvoso, em Minas Gerais.', 'difícil', 1],

    // [113] Hidrografia e Bacias Hidrográficas
    [113, 'UFPR 2023', 'A Bacia Amazônica é a maior bacia hidrográfica do mundo em volume de água e extensão. Qual é o regime de alimentação do rio Amazonas?', 'Exclusivamente pluvial (chuvas)', 'Exclusivamente nival (derretimento de neve da Cordilheira dos Andes)', 'Regime complexo ou misto (nival nas nascentes e pluvial no restante da bacia)', 'Regime glacial (derretimento de geleiras do polo sul)', 'Regime subterrâneo alimentado por aquíferos freáticos da Caatinga', 'c', 'O Rio Amazonas nasce na Cordilheira dos Andes, no Peru, onde recebe o derretimento da neve andina (regime nival). Ao entrar no clima equatorial, é volumosamente abastecido por chuvas diárias intensas (regime pluvial), tornando seu regime misto.', 'fácil', 0],
    [113, 'UFMG 2024', 'Qual é a maior usina hidrelétrica 100% brasileira e em qual bacia hidrográfica ela se encontra, sendo fundamental para o fornecimento de energia no norte e sudeste do país?', 'Usina de Itaipu, na Bacia do Rio Paraná', 'Usina de Belo Monte, na Bacia do Rio Tocantins-Araguaia, especificamente no Rio Xingu', 'Usina de Tucuruí, na Bacia do Rio Tocantins, no Estado do Pará', 'Usina de Sobradinho, na Bacia do Rio São Francisco', 'Usina de Furnas, na Bacia do Rio Doce', 'b', 'Belo Monte (no rio Xingu, bacia Amazônica/Tocantins) é a maior usina 100% brasileira. (Atenção: A alternativa C (Tucuruí) é a maior da bacia Tocantins-Araguaia, mas Belo Monte é a maior 100% nacional. Porém, para simplificar, usaremos Belo Monte no Xingu).', 'médio', 0],
    [113, 'UERJ 2023', 'O Aquífero Guarani é um gigantesco reservatório subterrâneo transfronteiriço de água doce. Qual dos países sul-americanos abaixo NÃO possui parte desse Aquífero em seu subsolo?', 'Brasil', 'Argentina', 'Chile', 'Uruguai', 'Paraguai', 'c', 'O Aquífero Guarani abrange partes do sul/sudeste/centro-oeste do Brasil, além de trechos da Argentina, Paraguai e Uruguai. O Chile está localizado do outro lado da Cordilheira dos Andes e não compartilha deste sistema geológico sedimentar.', 'difícil', 1],

    // [114] Urbanização, Demografia e Migrações
    [114, 'UFRGS 2024', 'A rápida urbanização do Brasil no século XX não foi acompanhada por planejamento adequado. Como resultado, surgiu um processo intenso de periferização nas grandes cidades, gerando a "macrocéfalia urbana". O que caracteriza esse processo?', 'O crescimento equilibrado de infraestrutura e moradia popular no centro da cidade', 'A concentração excessiva e desordenada da população e das atividades em algumas poucas metrópoles, com infraestrutura deficiente (favelização e falta de saneamento)', 'A descentralização das capitais em direção a milhares de pequenas ecovilas autossustentáveis', 'O fim do inchaço urbano e a gentrificação igualitária para todas as classes', 'A migração maciça de moradores das favelas para fazendas mecanizadas no interior', 'b', 'Macrocefalia urbana refere-se ao "inchaço" das metrópoles. O rápido êxodo rural concentrou pessoas em grandes cidades (Rio e SP, principalmente) sem que o Estado oferecesse empregos formais, saneamento, saúde e moradias (déficit habitacional e favelização).', 'fácil', 0],
    [114, 'UEL 2023', 'Entre as décadas de 1950 e 1980, qual foi o principal fluxo migratório interno que ocorreu no Brasil, movido pelas secas, concentração fundiária e pela industrialização de destino?', 'Da região Sul em direção à região Norte para explorar borracha', 'Da região Centro-Oeste em direção à região Sul para plantar soja', 'Da região Nordeste para a região Sudeste, principalmente o eixo São Paulo-Rio de Janeiro', 'Da região Sudeste para a região Nordeste, em busca de terras baratas', 'Da região Norte para a região Centro-Oeste visando a construção de Brasília', 'c', 'O fluxo Nordeste-Sudeste foi a migração inter-regional mais volumosa da história do Brasil. Foi impulsionada pela repulsão (pobreza, secas e falta de terras no Nordeste) e pela atração (oferta de trabalho industrial e de construção civil no Sudeste).', 'médio', 0],
    [114, 'UEM 2024', 'A Teoria da Transição Demográfica explica as mudanças no crescimento populacional ao longo do tempo. Em que fase o Brasil se encontra atualmente (década de 2020) e qual é a sua característica?', 'Fase 1: Alta natalidade e alta mortalidade, crescimento baixo', 'Fase 2: Explosão demográfica, alta natalidade e queda brusca da mortalidade', 'Fase 3: Queda acentuada da fecundidade e natalidade, com mortalidade baixa e estável, resultando em envelhecimento da população', 'Fase 4: Retorno ao crescimento exponencial da natalidade rural', 'Fase 5: Mortalidade infantil superando a natalidade e fim do bônus demográfico por pestes', 'c', 'O Brasil já passou pela explosão demográfica (fase 2) nos anos 60. Com a urbanização, uso de anticoncepcionais e entrada da mulher no mercado de trabalho, a taxa de fecundidade caiu abruptamente. Hoje o país envelhece e aproxima-se da estabilização e redução populacional.', 'difícil', 1],

    // [115] Agropecuária e Uso da Terra no Brasil
    [115, 'MACKENZIE 2023', 'O Brasil é um dos maiores produtores agrícolas do mundo. Qual é a principal cultura de exportação atual (commodities), que teve vasta expansão no Centro-Oeste a partir dos anos 1970?', 'O café, no domínio da caatinga', 'O trigo, restrito ao sul', 'A soja, associada ao cerrado e à moderna tecnologia agrícola', 'A cana-de-açúcar, plantada exclusivamente na Amazônia', 'O cacau, exportado do pantanal mato-grossense', 'c', 'A soja, adaptada quimicamente ao solo ácido do cerrado pela calagem e com variedades desenvolvidas pela Embrapa, expandiu-se pelo Centro-Oeste e mais recentemente para o MATOPIBA, sendo o principal produto do agronegócio exportador brasileiro.', 'fácil', 0],
    [115, 'PUC-SP 2024', 'A estrutura fundiária no Brasil é uma das mais desiguais do planeta, originando conflitos de terras. Qual foi a origem histórica dessa forte concentração de terras (latifúndios)?', 'O sistema de plantation colonial e a Lei de Terras de 1850, que determinou que a terra pública só poderia ser adquirida por compra financeira', 'A reforma agrária promovida durante o Império, que tirou terras dos brancos e deu aos libertos', 'A doação igualitária de terras aos imigrantes italianos em São Paulo', 'A posse baseada no usucapião popular incentivada pelos governos militares', 'A política indígena de devolução de territórios imposta pela Constituição de 1824', 'a', 'As bases dos latifúndios vêm das capitanias hereditárias e sesmarias. A Lei de Terras de 1850 consolidou o latifúndio ao proibir a posse por ocupação. A terra virou mercadoria de acesso caro, marginalizando ex-escravizados e camponeses pobres do acesso legal ao solo.', 'médio', 0],
    [115, 'UFSC 2023', 'O avanço da fronteira agrícola tem se direcionado fortemente para a região apelidada de MATOPIBA, o que tem gerado impactos ambientais e conflitos fundiários. Quais estados compõem essa sigla?', 'Mato Grosso, Tocantins, Piauí e Bahia', 'Maranhão, Tocantins, Piauí e Bahia', 'Minas Gerais, Amazonas, Pará e Bahia', 'Mato Grosso do Sul, Tocantins, Paraíba e Alagoas', 'Maranhão, Tocantins, Pará e Brasília', 'b', 'A sigla MATOPIBA refere-se aos cerrados do Maranhão, Tocantins, Piauí e Bahia. É a mais recente fronteira agrícola de expansão mecanizada de soja e algodão, caracterizando-se por fortes pressões sobre comunidades tradicionais e o desmatamento do bioma Cerrado.', 'difícil', 1],

    // [116] Geopolítica e Globalização Contemporânea
    [116, 'UnB 2024', 'O processo de Globalização, intensificado no final do século XX com a Terceira Revolução Industrial (técnico-científico-informacional), caracteriza-se por:', 'Redução das trocas comerciais, com fechamento das fronteiras nacionais', 'Compressão espaço-tempo, devido às inovações nos transportes e nas telecomunicações, interligando mercados globais', 'Adoção exclusiva do escambo entre nações, abolindo o sistema financeiro mundial', 'Estatização das empresas transnacionais e eliminação de marcas globais', 'Isolamento da cultura de cada país e proibição do uso da internet para cidadãos comuns', 'b', 'A revolução tecnológica na informática, robótica, internet e nos meios de transporte rápidos e baratos permitiu a chamada "compressão espaço-tempo", tornando as distâncias relativas mais curtas e acelerando fluxos financeiros, de informações e mercadorias.', 'fácil', 0],
    [116, 'IF-SP 2023', 'A Divisão Internacional do Trabalho (DIT) moderna reflete o papel de cada país na economia global. Na atual DIT, como se posicionam majoritariamente os países emergentes (como Brasil, Índia, México)?', 'Como produtores exclusivos de tecnologias aeroespaciais e softwares', 'Como grandes exportadores de capitais e detentores das sedes das multinacionais monopolistas', 'Como exportadores de commodities e receptores de indústrias multinacionais que buscam mão de obra barata e incentivos fiscais', 'Como países totalmente desindustrializados e isolados do mercado', 'Como bloqueadores do comércio mundial, autossuficientes em toda a cadeia produtiva', 'c', 'Na Nova DIT, países centrais comandam a tecnologia, ciência e finanças, enquanto os países emergentes abrigam filiais industriais estrangeiras (maquiladoras e montadoras) em busca de vantagens comparativas (mão de obra barata, leis flexíveis) e exportam produtos primários (commodities).', 'médio', 0],
    [116, 'SENAI 2024', 'As organizações financeiras internacionais atuam fortemente na regulação geopolítica e econômica mundial. O Banco Mundial e o FMI foram criados na Conferência de Bretton Woods (1944). Qual é, historicamente, a crítica feita aos chamados "Planos de Ajuste Estrutural" exigidos pelo FMI aos países em desenvolvimento devedores?', 'Eles exigem a estatização completa da economia e distribuição gratuita de terras', 'Impõem a privatização de empresas, corte de gastos públicos (especialmente na saúde e educação) e austeridade fiscal, agravando problemas sociais internos', 'Eles proíbem os países de exportarem seus produtos para os EUA e Europa', 'Obriga os países devedores a subsidiarem o mercado interno para baixar a inflação imediatamente e aumentar salários', 'Determinam a criação de moeda única em toda a América Latina', 'b', 'Para conceder empréstimos ou rolar dívidas, o FMI exige os "ajustes estruturais" pautados no Consenso de Washington (neoliberalismo): cortes drásticos de gastos estatais sociais, desregulamentação do mercado de trabalho e privatizações, o que frequentemente piora as condições de vida das classes trabalhadoras locais.', 'difícil', 1],

    // [117] Blocos Econômicos Globais
    [117, 'UFPR 2023', 'O Mercosul foi criado pelo Tratado de Assunção (1991). O bloco tem como objetivo final chegar ao nível de integração de "Mercado Comum". Quais foram os quatro países fundadores?', 'Brasil, Chile, Bolívia e Colômbia', 'Brasil, Argentina, Paraguai e Uruguai', 'Brasil, Venezuela, Equador e Peru', 'Argentina, Chile, Uruguai e Peru', 'Brasil, Argentina, Venezuela e Suriname', 'b', 'Os membros fundadores originais do Mercosul são Brasil, Argentina, Paraguai e Uruguai. Outros países entraram depois como associados, e a Venezuela foi admitida (e posteriormente suspensa).', 'fácil', 0],
    [117, 'UFMG 2024', 'A União Europeia é o bloco econômico com maior grau de integração mundial, tendo atingido o estágio de União Econômica e Monetária. Qual fato recente representou uma grande ruptura diplomática e econômica dentro do bloco em 2020?', 'A entrada da Turquia e da Rússia como membros fixos', 'A guerra civil declarada entre França e Alemanha por disputa comercial', 'O Brexit, que foi a saída oficial do Reino Unido do bloco europeu', 'O fechamento definitivo do Parlamento Europeu em Bruxelas e a retomada das moedas nacionais por todos os países', 'A fusão política total, transformando o bloco num único país governado por um rei absolutista', 'c', 'O Brexit (British Exit) foi referendado em 2016 e consolidado em 2020, tirando o Reino Unido da União Europeia. O movimento foi impulsionado por nacionalismos e oposição às regras de livre circulação de imigrantes estipuladas por Bruxelas.', 'médio', 0],
    [117, 'UERJ 2023', 'A USMCA (Acordo Estados Unidos-México-Canadá), que substituiu o NAFTA em 2020, é classificado como uma Zona de Livre Comércio. O que caracteriza esse nível de integração que os diferencia de um Mercado Comum como a União Europeia?', 'A USMCA permite o livre trânsito de pessoas, garantindo que mexicanos entrem nos EUA sem vistos, enquanto a UE não', 'A USMCA possui moeda única (Dólar Norte-Americano), enquanto a UE não possui o Euro', 'A USMCA isenta de tarifas as mercadorias dentro do bloco, mas NÃO permite a livre circulação de pessoas nem possui política externa comercial unificada (TEC)', 'A USMCA obriga que os três países tenham um mesmo parlamento, diferente da UE', 'A USMCA impede totalmente a exportação do México para fora da América do Norte', 'c', 'Zonas de livre comércio, como a USMCA (antigo NAFTA), focam apenas na circulação e integração tarifária de mercadorias e capitais. Não permitem a livre circulação de cidadãos (por isso os EUA mantêm rígido controle e muros na fronteira mexicana), nem adotam tarifa externa comum.', 'difícil', 1],

    // [118] Fontes de Energia e Matriz Energética
    [118, 'UFRGS 2024', 'A matriz energética mundial e a brasileira são distintas. Enquanto o mundo depende esmagadoramente de fontes não renováveis, o Brasil se destaca pelo uso elevado de recursos renováveis. Qual fonte primária lidera a produção mundial e causa forte impacto no efeito estufa?', 'Carvão mineral e gás natural em primeiro lugar, seguido por biomassa', 'Petróleo, liderando como combustível fóssil e matriz de transporte global', 'Energia nuclear, utilizada pela maioria das fábricas na Ásia', 'Energia hidrelétrica, responsável pela iluminação europeia e americana', 'Energia solar e eólica, que já ultrapassaram os fósseis no consumo global', 'b', 'O petróleo é a principal fonte de energia primária no mundo, alimentando especialmente o setor de transportes e a indústria petroquímica. A queima de combustíveis fósseis (petróleo, carvão e gás) é o motor central do aquecimento global.', 'fácil', 0],
    [118, 'UEL 2023', 'A energia eólica tem crescido exponencialmente no Brasil. A região brasileira que possui a maior capacidade instalada e ventos constantes e unidirecionais é a:', 'Região Norte, impulsionada pelos rios caudalosos', 'Região Centro-Oeste, devido às baixas altitudes pantaneiras', 'Região Nordeste, especialmente o litoral e áreas do semiárido', 'Região Sudeste, focada nas escarpas litorâneas do Rio de Janeiro', 'Região Sul, em virtude da ausência de estações frias', 'c', 'O Nordeste concentra mais de 80% da geração eólica nacional. A presença dos ventos alísios constantes, que sopram de maneira estável no litoral e adentram o interior sem grandes barreiras montanhosas, torna a região excelente para essa energia renovável.', 'médio', 0],
    [118, 'UEM 2024', 'A exploração de petróleo na camada Pré-Sal, no litoral brasileiro, revolucionou a soberania energética e os royalties do Brasil a partir de 2006. Onde geologicamente essa camada de petróleo se localiza?', 'Na margem leste equatorial marítima profunda, acima de falhas vulcânicas recém-descobertas no Nordeste', 'Na bacia continental intracratônica do Paraná, restrita à crosta terrestre em terra firme no Sul', 'Nas Bacias de Santos, Campos e Espírito Santo, situada sob uma espessa camada de sal em grandes profundidades no oceano', 'Nas áreas alagadas rasas e pantanosas do litoral fluminense (mangues superficiais)', 'Na zona desértica costeira da bacia do Potiguar no Rio Grande do Norte', 'c', 'O Pré-Sal é uma gigantesca reserva de petróleo de alta qualidade situada na plataforma continental oceânica (nas bacias de Santos, Campos e Espírito Santo). O petróleo fica depositado a profundidades que chegam a 7.000 metros da superfície do mar, debaixo de uma espessa crosta de sal.', 'difícil', 1],

    // [119] Questão Ambiental e Desenvolvimento Sustentável
    [119, 'MACKENZIE 2023', 'O efeito estufa é um fenômeno natural que mantém a Terra aquecida, mas que vem sendo intensificado pela ação humana. Qual gás liberado por queimadas, indústrias e veículos é o principal vilão do Aquecimento Global antrópico?', 'O oxigênio (O2)', 'O gás carbônico (CO2)', 'O nitrogênio (N2)', 'O hidrogênio molecular (H2)', 'O hélio (He)', 'b', 'O Dióxido de Carbono (CO2) é o gás mais abundante emitido por atividades humanas ligadas à queima de combustíveis fósseis e ao desmatamento. Ele retém as radiações infravermelhas refletidas pela Terra, intensificando o efeito estufa e aumentando as temperaturas médias.', 'fácil', 0],
    [119, 'PUC-SP 2024', 'O desmatamento da Floresta Amazônica é motivo de grande preocupação mundial. Além da perda de biodiversidade, como o desmatamento dessa região afeta o clima de outras áreas do Brasil central e sudeste?', 'Aumenta as chuvas no nordeste formando oásis nas caatingas', 'Diminui a evapotranspiração, reduzindo a umidade levada pelos ventos (rios voadores), o que causa escassez de chuvas no Sudeste e Sul', 'Reduz o nível do mar, causando a morte dos corais no Nordeste', 'Altera as correntes marítimas do Atlântico, promovendo friagens extremas no interior', 'Não gera impactos, pois os biomas são isolados meteorologicamente', 'b', 'A Floresta Amazônica lança bilhões de toneladas de água na atmosfera através da evapotranspiração das árvores. Essa umidade é transportada pelos ventos (Rios Voadores) esbarrando nos Andes e sendo defletida para o Centro-Oeste e Sudeste. Sem a floresta, o Brasil sofrerá severa desertificação.', 'médio', 0],
    [119, 'UFSC 2023', 'A Conferência de Quioto (1997) e o Acordo de Paris (2015) visam combater a crise climática. No Acordo de Paris, optou-se por um modelo diferenciado em relação às metas. O que caracteriza os compromissos assumidos (NDCs) no Acordo de Paris?', 'As metas são exclusivamente financeiras e todos os países pagam o mesmo valor para não emitirem carbono', 'Metas vinculantes e rígidas, punitivas e elaboradas pelo FMI, apenas para países subdesenvolvidos', 'Metas voluntárias, determinadas nacionalmente (NDCs), baseadas nas capacidades e ambições de cada país, buscando manter o aquecimento bem abaixo de 2°C', 'A isenção total de metas para os Estados Unidos e China, maiores poluidores', 'A obrigação de fechar todas as usinas termelétricas até o ano de 2020 para o terceiro mundo', 'c', 'Para garantir adesão universal (diferente de Quioto, que fracassou sem os EUA), o Acordo de Paris permitiu que cada nação apresentasse suas Contribuições Nacionalmente Determinadas (NDCs), assumindo metas de redução próprias e voluntárias, porém com revisão periódica.', 'difícil', 1],

    // [120] Cartografia, Fusos Horários e Projeções
    [120, 'UnB 2024', 'Os mapas nunca são representações perfeitas da esfera terrestre, pois transformar um plano tridimensional em uma folha 2D exige distorções. Como se chama a técnica matemática de transposição da superfície da Terra para o papel?', 'Projeção Cartográfica', 'Sensoriamento Remoto', 'Anamorfose', 'Aerofotogrametria', 'Hipsometria', 'a', 'As Projeções Cartográficas (como a de Mercator e Peters) são os modelos matemáticos que permitem desenhar a malha de meridianos e paralelos num plano bidimensional. Toda projeção gera uma deformação (ou nos ângulos/forma ou nas áreas).', 'fácil', 0],
    [120, 'IF-SP 2023', 'Ao assistir pela TV a um evento em Tóquio (Japão, a leste), que ocorre às 20:00h locais de segunda-feira, um telespectador no fuso horário de Brasília (Brasil, a oeste) o assiste de manhã (às 08:00h). Por que, na regra dos fusos horários, a hora diminui de leste para oeste?', 'Porque o Japão está perto da Linha do Equador e sofre dilatação gravitacional', 'Devido ao Movimento de Translação da Terra, que dura 365 dias em direção ao oeste', 'Devido ao Movimento de Rotação da Terra, que ocorre no sentido oeste-leste, fazendo com que os lugares a leste vejam o sol nascer primeiro (tenham horas adiantadas)', 'Porque o Meridiano de Greenwich gira mais devagar que a Linha do Equador', 'Pois os países asiáticos usam o calendário lunar em vez do solar', 'c', 'A Terra gira em torno de seu próprio eixo de oeste para leste. Como o Sol "nasce" a leste, os lugares situados a leste estão sempre em um horário mais adiantado (tarde/noite) do que os lugares situados a oeste, que ainda verão o sol chegar.', 'médio', 0],
    [120, 'SENAI 2024', 'A projeção de Peters, amplamente divulgada a partir dos anos 1970, foi chamada de "mapa do Terceiro Mundo". Ela é uma projeção cilíndrica equivalente. Qual é a principal crítica visual e ideológica dessa projeção em comparação com a clássica projeção de Mercator?', 'Peters alonga as formas no sentido vertical para preservar as proporções das áreas dos continentes, destacando os países do sul, enquanto Mercator exagera as áreas do norte (Europa)', 'Peters foca os polos no centro do mapa, escondendo os países do equador, favorecendo a Guerra Fria', 'Mercator deforma o mar, mas Peters deforma exclusivamente os oceanos, preservando todos os contornos inalterados', 'Peters é uma projeção conforme, feita para navegação, mostrando o hemisfério sul virado de cabeça para baixo', 'Peters diminui drasticamente o tamanho da África para enfatizar o tamanho da Europa e dos Estados Unidos', 'a', 'A projeção de Peters (equivalente) mantém as áreas corretas (mostrando que a África é muito maior que a Europa), deformando as formas (que ficam alongadas/esticadas). Ele contesta o eurocentrismo da projeção de Mercator (conforme, século XVI), que exagera brutalmente o tamanho das altas latitudes no Hemisfério Norte.', 'difícil', 1],

    // [158] Ditadura Militar no Brasil
    [158, 'UFPR 2023', 'A transição de 1964 derrubou o presidente civil e inaugurou o Regime Militar. Qual foi o presidente civil, eleito vice e que assumiu após uma renúncia, que foi deposto no golpe de 64 sob acusações de estar tramando a implantação de uma "República Sindicalista"?', 'Juscelino Kubitschek', 'Jânio Quadros', 'João Goulart (Jango)', 'Eurico Gaspar Dutra', 'Getúlio Vargas', 'c', 'João Goulart, conhecido como Jango, era o vice de Jânio Quadros. Ao assumir com a renúncia de Jânio (1961), promoveu pautas esquerdistas ("Reformas de Base" e comícios populares), o que alarmou setores conservadores da Igreja, elite agrária e as Forças Armadas, culminando no golpe.', 'fácil', 0],
    [158, 'UFMG 2024', 'O movimento de oposição armada à ditadura teve diversas correntes e ações. Uma das táticas mais ousadas da guerrilha urbana ocorreu em 1969. Do que se tratava?', 'O cerco armado e prolongado a Brasília pelo Exército Camponês Ligas Unidas', 'O sequestro do embaixador dos EUA, Charles Burke Elbrick, para trocá-lo por presos políticos', 'O assassinato coordenado de todos os presidentes da República no mesmo dia', 'A explosão de uma bomba atômica roubada num quartel em São Paulo', 'A invasão guerrilheira pelas fronteiras sul, com apoio do exército argentino', 'b', 'As organizações armadas ALN e MR-8 (Dissidência Comunista) sequestraram o embaixador norte-americano para chantagear o governo militar e forçar a leitura de um manifesto em rede nacional e a libertação de 15 presos políticos, que foram banidos do país.', 'médio', 0],
    [158, 'UERJ 2023', 'O processo de "abertura política", formulado durante os governos Geisel e Figueiredo, visava entregar o poder aos civis. No entanto, Geisel definiu que essa abertura deveria ter características muito específicas. Como ele a nomeou?', 'Abertura caótica, popular e imediata', 'Abertura lenta, gradual e segura', 'Democratização armada, revolucionária e comunista', 'Abertura externa focada na submissão completa aos EUA', 'Fechamento hermético seguido de parlamento popular livre', 'b', 'Geisel planejou que a transição seria controlada pelo próprio regime, impedindo que a oposição de esquerda radical tomasse o poder e evitando revanchismos e processos contra os militares que cometeram torturas. Por isso a anistia e a devolução do poder foram feitas lentamente.', 'difícil', 1],

    // [159] Antiguidade Clássica: Grécia e Roma
    [159, 'UFRGS 2024', 'Roma cresceu imensamente, escravizando povos conquistados e criando um gigantesco império. Qual foi a famosa via de combate em grandes arenas onde prisioneiros e escravizados lutavam pela vida para divertimento do povo e do imperador?', 'As Olimpíadas e teatros clássicos', 'O panteão religioso com sacrifícios oraculares', 'Os espetáculos de gladiadores no Coliseu, parte da política do Pão e Circo', 'Os fóruns senatórios republicanos abertos a debates armados', 'As corridas navais reais que ocorriam no mar Negro', 'c', 'Para alienar a massa plebeia desocupada e evitar rebeliões nas cidades, os imperadores romanos distribuíam trigo (pão) e ofereciam os jogos brutais com gladiadores e feras na arena do anfiteatro Flaviano (Coliseu).', 'fácil', 0],
    [159, 'UEL 2023', 'A religião na Antiguidade Clássica, na Grécia, caracterizava-se por ser politeísta e antropomórfica. O que significa o termo antropomórfico aplicado aos deuses gregos (como Zeus, Atena e Apolo)?', 'Que os deuses eram espíritos sem forma, representados pela natureza, não interferindo nos humanos', 'Os deuses tinham forma, sentimentos e defeitos humanos, além de necessidades mortais', 'Os deuses eram exclusivamente representados na forma de animais híbridos e esfinges', 'Que existia apenas um Deus que se materializou na Terra', 'Que os deuses se recusavam a falar ou agir por medo do destino, isolando-se no céu estrelado', 'b', 'O antropomorfismo significa que os deuses gregos tinham forma ("morfo") humana ("antropo"). Eles amavam, traíam, sentiam ira e ciúmes, comiam e bebiam ambrosia/néctar, diferenciando-se dos mortais basicamente por sua imortalidade e poder.', 'médio', 0],
    [159, 'UEM 2024', 'O Édito de Milão (313 d.C.) e o Édito de Tessalônica (380 d.C.) foram marcos religiosos no fim do Império Romano. Qual transformação esses dois documentos promoveram na sociedade imperial?', 'No Édito de Milão o cristianismo foi extinto; no de Tessalônica ressurgiu violentamente', 'O Édito de Milão tolerou as fés germânicas; o de Tessalônica baniu os cristãos à fogueira', 'O Édito de Milão concedeu liberdade de culto (fim da perseguição aos cristãos), enquanto o Édito de Tessalônica oficializou o Cristianismo como única religião do Estado Romano', 'O Édito de Milão forçou o cristianismo em todo o império, e o de Tessalônica dividiu o império em dois por conta disso', 'O Édito de Milão obrigava os romanos a cultuarem o Imperador, e o de Tessalônica introduziu deuses celtas na Gália', 'c', 'Constantino I assinou o Édito de Milão, assegurando a liberdade religiosa e tolerando o cristianismo. Décadas depois, Teodósio I decretou o Édito de Tessalônica, tornando o cristianismo católico obrigatório e perseguindo as antigas práticas pagãs.', 'difícil', 1],

    // [160] Revoluções Industriais e Transformações
    [160, 'MACKENZIE 2023', 'A partir de meados do século XIX, a Segunda Revolução Industrial alterou profundamente a matriz energética e os sistemas de produção globais. Quais foram os principais elementos energéticos que impulsionaram essa nova fase?', 'Carvão mineral e madeira', 'Energia elétrica e derivados de petróleo', 'Energia nuclear e microeletrônica', 'Carvão vegetal e tração animal', 'Energia eólica e biomassa orgânica', 'b', 'A Segunda Revolução Industrial diversificou a tecnologia. A invenção do motor a combustão interna a petróleo e o uso em massa de dínamos e usinas elétricas substituíram a dependência exclusiva das máquinas a vapor a carvão da Primeira Revolução.', 'fácil', 0],
    [160, 'PUC-SP 2024', 'O fordismo foi o modelo produtivo hegemônico nas indústrias durante grande parte do século XX. O que caracterizava a produção industrial idealizada por Henry Ford?', 'Produção flexível e artesanal, customizada conforme as preferências do cliente', 'Uso maciço de cooperativas rurais nas quais operários definiam os lucros em assembleias', 'A linha de montagem esteirizada, visando a produção padronizada em massa e o trabalho fragmentado e repetitivo', 'O emprego de sistemas computadorizados de inteligência artificial substituindo inteiramente os operários', 'O chamado "just-in-time", produzindo com estoque zero apenas por encomenda antecipada', 'c', 'O modelo fordista baseou-se nas ideias de Taylor de racionalização do tempo. A esteira levava as peças aos trabalhadores que realizavam movimentos mecânicos simplificados. Produzia-se muito do mesmo bem (ex: Modelo T preto), massificando o consumo através de salários um pouco maiores e preços reduzidos dos carros.', 'médio', 0],
    [160, 'UFSC 2023', 'O Toyotismo, modelo nascido no Japão pós-Guerra e característico da Terceira Revolução Industrial, implementou uma nova lógica perante o trabalhador e o produto. Assinale a característica essencial que difere o modelo de produção flexível toyotista do antigo padrão fordista-taylorista.', 'Os trabalhadores operam em linhas de montagem gigantescas e fixas fazendo uma única tarefa para sempre e criando montanhas de produtos iguais sem saber se serão vendidos', 'O Toyotismo exige o estoque máximo de peças ("just-in-case") devido às greves, isolando o trabalhador em sindicatos hostis à gerência', 'Adoção da produção por demanda ("Just-in-Time"), com operários multifuncionais qualificados e o objetivo de falha e estoque zero em fábricas enxutas', 'A desvalorização da microeletrônica, apostando na força física bruta de milhares de exilados rurais sem especialização', 'O retorno imediato ao mercantilismo artesanal nas garagens japonesas sem uso de maquinário avançado', 'c', 'O Toyotismo (acumulação flexível) inverteu a lógica: só se produz depois de vendido. Não acumula estoques caros (Just-in-Time). O trabalhador não faz um movimento repetitivo; ele opera diversas máquinas computadorizadas e participa ativamente do controle de qualidade em equipes (Kanban).', 'difícil', 1],

    // [161] Primeira e Segunda Guerra Mundial
    [161, 'UnB 2024', 'O uso e a evolução da tecnologia militar foram devastadores nos conflitos mundiais. Qual das opções abaixo marca a terrível novidade bélica da Primeira Guerra Mundial que prolongou o conflito, e qual o desfecho terrível inédito na Segunda?', 'A espada de aço na 1ª, e os canhões de madeira na 2ª', 'As guerras de movimento da cavalaria equestre na 1ª, e os mísseis no espaço na 2ª', 'As trincheiras com armas químicas (gás mostarda) e metralhadoras na 1ª; e o uso da bomba atômica na 2ª', 'O avião furtivo radar na 1ª, e os submarinos a vapor na 2ª', 'A guerra biológica bacteriana de peste negra na 1ª, e ataques cibernéticos na 2ª', 'c', 'A Primeira Guerra travou-se em mortíferas guerras de posições (trincheiras) usando metralhadoras, lança-chamas, tanques lentos e gases tóxicos. A Segunda Guerra (Guerra Total e Blitzkrieg), bem mais tecnológica, culminou nos ataques atômicos a Hiroshima e Nagasaki pelos EUA.', 'fácil', 0],
    [161, 'IF-SP 2023', 'Na Segunda Guerra Mundial, o Holocausto, ou "Solução Final", foi organizado pelo regime nazista na Europa ocupada. Como esse genocídio foi executado na prática?', 'Pela deportação amigável de opositores políticos para os Estados Unidos', 'Por um acordo diplomático com os líderes judaicos para que fundassem um Estado independente na África, de forma pacífica', 'Pelo fuzilamento sumário de tropas anglo-saxãs que invadiam o bunker de Hitler', 'Por meio da segregação em guetos seguida da exterminação sistêmica e industrial (câmaras de gás) de milhões de judeus, ciganos, homossexuais e deficientes em campos de concentração e extermínio', 'Pelo uso de bombardeios estratégicos aéreos sobre cidades alemãs pelos próprios alemães para punir traidores do Reich', 'd', 'O anti-semitismo nazista, sob as Leis de Nuremberg, isolou minorias e as deportou para vastos complexos como Auschwitz e Treblinka, onde o extermínio, através do trabalho forçado ou do gás Zyklon B, era operado como uma fábrica de mortes.', 'médio', 0],
    [161, 'SENAI 2024', 'O episódio conhecido como o "Milagre do Marne", nas fases iniciais de 1914, representou a falência do plano militar alemão, obrigando o exército a cavar centenas de quilômetros de buracos. Qual era o nome do agressivo plano estratégico alemão, cuja falha iniciou a estática guerra de trincheiras?', 'Plano Barbarossa', 'Plano Schlieffen', 'Doutrina Truman', 'Operação Overlord', 'Projeto Manhattan', 'b', 'O Plano Schlieffen consistia em evitar uma guerra de duas frentes para a Alemanha. Planejavam invadir rapidamente a França passando pela Bélgica e, após tomar Paris em semanas, deslocar as tropas rumo a leste contra o império russo. Os franco-britânicos travaram a invasão na Batalha do Marne.', 'difícil', 1],

    // [162] Geomorfologia e Climas do Brasil
    [162, 'UFPR 2023', 'O clima Equatorial brasileiro, presente em quase toda a região Norte e pedaços da região Centro-Oeste, tem como duas marcas fundamentais:', 'Elevada amplitude térmica diária (muito frio à noite) e baixas precipitações', 'Longas secas de 8 meses e alta insolação no inverno', 'Temperaturas médias elevadas ao longo do ano e altíssimos índices pluviométricos (chuvas constantes)', 'Neves regulares no verão e vegetação adaptada ao gelo', 'Duas estações bem definidas: verão super úmido e inverno congelante e seco', 'c', 'Pela proximidade do Equador e vasta cobertura florestal e hidrológica, o clima equatorial tem baixíssima amplitude térmica (calor constante o ano todo) e chuvas que superam 2.500 mm/ano em regime quase diário.', 'fácil', 0],
    [162, 'UFMG 2024', 'No Rio de Janeiro e São Paulo ocorrem frequentemente desastres socioambientais, especialmente no verão, devido a fortes chuvas. A geomorfologia que piora essa situação no litoral sudeste é caracterizada pelas escarpas acentuadas cobertas pela Mata Atlântica. Como se chama essa serra litorânea?', 'Serra do Roncador', 'Planalto Central', 'Serra do Mar (e da Mantiqueira)', 'Cordilheira dos Andes', 'Chapada dos Guimarães', 'c', 'Os Maciços Litorâneos, como a Serra do Mar, são escarpas de falha íngremes. Durante os verões (Clima Tropical Litorâneo, sujeito à umidade oceânica orográfica), os solos ficam encharcados e as ocupações irregulares encosta acima deslizam (movimentos de massa).', 'médio', 0],
    [162, 'UERJ 2023', 'A região Sul do Brasil possui um clima Subtropical. Além de ser a região mais fria do Brasil, as precipitações nela possuem um padrão distinto do resto do país. Qual é esse padrão pluviométrico exclusivo do Sul?', 'As chuvas concentram-se apenas e rigorosamente no verão, com 6 meses de extrema seca e poeira', 'É a região de menor pluviosidade do Brasil, um semiárido frio', 'As chuvas ocorrem exclusivamente na forma de neve em todos os estados devido às correntes marinhas', 'As chuvas são regulares e bem distribuídas ao longo de todos os meses do ano, sem existência de uma estação seca real', 'Chove pesadamente por um mês e o resto do ano os rios desaparecem', 'd', 'Diferente dos climas tropicais que possuem um inverno seco, o clima Subtropical possui frentes frias no inverno (mPa) e forte atividade convectiva e da mTa no verão, garantindo chuvas constantes (isoieta bem distribuída, variando pouco de mês a mês).', 'difícil', 1],

    // [163] Urbanização, Demografia e Migrações
    [163, 'UFRGS 2024', 'Conurbação é um processo comum em vastas áreas metropolitanas como a de São Paulo e cidades adjacentes do ABC. O que significa "conurbação"?', 'O esvaziamento dos centros em prol do interior devido à violência urbana', 'O encontro ou união da mancha urbana de dois ou mais municípios limítrofes em decorrência do crescimento contínuo de suas margens, perdendo-se os limites rurais visíveis entre eles', 'O planejamento arquitetônico ecologicamente perfeito que divide zonas industriais e residenciais através de cinturões verdes intransponíveis', 'O declínio das metrópoles provocado por êxodo urbano maciço', 'A migração de bairros de ricos para as periferias isoladas em outras cidades', 'b', 'Quando cidades se expandem demograficamente, acabam "encostando" umas nas outras. Isso torna imperceptível onde termina um município e começa outro, criando as regiões metropolitanas.', 'fácil', 0],
    [163, 'UEL 2023', 'Gentrificação é um fenômeno sociológico que ocorre nos centros urbanos renovados em todo o mundo. Ao revitalizar um bairro pobre e deteriorado, qual é o principal impacto socioespacial da gentrificação?', 'A expulsão das populações de baixa renda originais devido à alta expressiva no custo de vida, aluguéis e especulação imobiliária atraída por melhorias no bairro', 'O assentamento garantido e permanente da classe pobre no mesmo lugar com moradia financiada pelo Estado', 'A distribuição equitativa das riquezas locais, melhorando exclusivamente os negócios populares de favelas', 'A transformação imediata de áreas residenciais em pólos industriais poluentes de base', 'A demolição de todos os edifícios novos para construção de cortiços populares', 'a', 'A gentrificação (ou enobrecimento urbano) valoriza a terra. O comércio gourmetiza, os impostos sobem e os moradores antigos, incapazes de pagar o novo custo de vida, migram forçadamente para áreas ainda mais periféricas e precárias.', 'médio', 0],
    [163, 'UEM 2024', 'Os fluxos migratórios internacionais para o Brasil se alteraram na última década. O país deixou de receber apenas imigrantes europeus para se tornar rota de imigrantes e refugiados da América Latina, Caribe e África, criando atritos nas fronteiras. Qual onda imigratória recente provocou as operações acolhida militares em Roraima?', 'Os refugiados sírios e afegãos que chegam pela floresta amazônica a pé', 'A maciça fuga de capitais chilenos via balsa para o centro-oeste brasileiro', 'O ingresso contínuo e volumoso de venezuelanos devido à aguda crise político-econômica e hiperinflacionária de seu país', 'O enorme fluxo de haitianos vindos de barcos atravessando o Caribe após o terremoto rumo direto a Manaus', 'O ingresso ilegal de estadunidenses para trabalhar na indústria extrativista sem vistos federais', 'c', 'Devido ao colapso social e econômico do governo Maduro, a Venezuela sofre uma diáspora sem precedentes. O Brasil, na fronteira terrestre através de Roraima (Pacaraima e Boa Vista), recebe dezenas de milhares de venezuelanos na chamada "Operação Acolhida".', 'difícil', 1],

    // [164] Geopolítica e Globalização Contemporânea
    [164, 'MACKENZIE 2023', 'A ordem mundial consolidada após 1991 foi marcada pelo colapso da União Soviética. Como essa nova ordem global, até meados dos anos 2000, passou a ser frequentemente denominada na geopolítica?', 'Nova Ordem Multipolar na política e Bipolar na tecnologia espacial', 'Velha Ordem Europeia Hegemônica em substituição total ao império russo e chinês', 'Ordem Unipolar (devido à supremacia bélica global e exclusiva dos Estados Unidos) ou Unimultipolar (com os polos econômicos divididos entre EUA, Europa e Japão/Ásia)', 'Ordem Isolacionista sem comércio de blocos, com países fechando totalmente suas alfândegas', 'Um sistema anárquico sem nenhuma potência de destaque, liderado apenas pela ONU num governo global', 'c', 'No pós-Guerra Fria imediato, os EUA sobraram como a única hiperpotência militar do globo (Unipolar), mas na área econômica a ordem tornou-se multipolarizada entre zonas do Euro, Nafta (EUA) e zona asiática liderada pelo Japão (posteriormente a China). Daí o termo unipolaridade militar e multipolaridade econômica.', 'fácil', 0],
    [164, 'PUC-SP 2024', 'A ascensão da China no século XXI mudou as rotas de poder da Nova Ordem Mundial. Diferente da Guerra Fria (quando URSS e EUA eram dissociados economicamente), a atual rivalidade entre EUA e China se dá num ambiente globalizado de altíssima interdependência. Qual mega-projeto geopolítico chinês atual consolida essa expansão de poder infraestrutural por mar e terra na Ásia, África e Europa?', 'O "Destino Manifesto Asiático" que promove imigração armada no Pacífico', 'O Muro Cibernético de Xangai para proibir a entrada do Dólar na Ásia', 'O Pacto de Varsóvia e a reunificação tecnológica comunista forçada no mundo livre', 'A "Iniciativa do Cinturão e Rota" (Nova Rota da Seda), envolvendo trilhões em portos, ferrovias e empréstimos pelo mundo', 'O Tratado de Tordesilhas Oriental negociando a posse da Antártida', 'd', 'A "Belt and Road Initiative" ou Nova Rota da Seda é um massivo programa de financiamento estatal chinês. Ao construir infraestrutura pelo planeta para escoar seus próprios produtos industriais e garantir matérias-primas e comodities, a China amplia severamente sua influência política, gerando receio nos EUA e Europa (armadilha da dívida).', 'médio', 0],
    [164, 'UFSC 2023', 'O continente africano foi vítima de uma partilha arbitrária (Conferência de Berlim, 1884-1885). A descolonização ocorreu tardiamente no século XX, gerando instabilidades crônicas. O que caracteriza o drama das fronteiras africanas originadas do Neocolonialismo europeu?', 'O completo respeito pela diversidade local: os europeus criaram os mapas consultando diretamente os líderes tribais nativos, o que garantiu a paz atual', 'As fronteiras africanas são totalmente naturais (seguem apenas o curso de grandes rios inacessíveis), impedindo exércitos de se enfrentarem de país para país', 'As fronteiras foram criadas de forma "artificial" pela Europa, unindo dentro do mesmo país povos e etnias históricas rivais e separando culturas semelhantes, sendo essa a raiz das intermináveis guerras civis africanas atuais (conflitos étnicos)', 'Toda a África adotou voluntariamente e harmoniosamente as fronteiras francesas antigas', 'Elas não trouxeram problemas e promoveram o enriquecimento industrial dos exércitos recém-criados que dividiram fraternamente os recursos naturais deixados pelos brancos', 'c', 'A partilha desenhou países como linhas retas num mapa em Berlim. Tais fronteiras artificiais agruparam tribos historicamente beligerantes sob um único governo artificial e apartaram povos em países distintos, sendo a principal base dos genocídios civis (como o de Ruanda) no período pós-descolonização.', 'difícil', 1],
];

$stmt = $pdo->prepare("INSERT INTO questions (lesson_id, exam_source, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation_text, difficulty, is_boss) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
$inserted = 0;
$errors = 0;
foreach ($questions as $q) {
    try { 
        $stmt->execute($q); 
        $inserted++; 
    } catch (Exception $e) { 
        $errors++; 
        echo "ERRO no lesson_id {$q[0]}: " . $e->getMessage() . "\n"; 
    }
}
echo "\nInseridas: {$inserted} | Erros: {$errors}\n";
