<?php
require_once __DIR__ . '/../config/db.php';
echo "=== Inserindo questões de Química ===\n\n";

$questions = [
    // [55] Eletroquímica: Pilhas e Eletrólise
    [55, 'ENEM 2022', 'Na pilha de Daniell, zinco e cobre são utilizados com seus respectivos sulfatos. Considerando os potenciais padrão de redução E°(Zn²⁺/Zn) = -0,76V e E°(Cu²⁺/Cu) = +0,34V, qual é a diferença de potencial (ddp) gerada pela pilha?', '1,10 V', '0,42 V', '0,76 V', '1,52 V', '0,34 V', 'a', 'A ddp é calculada por ΔE° = E°(maior) - E°(menor) = +0,34 - (-0,76) = 1,10 V.', 'fácil', 0],
    [55, 'FUVEST 2021', 'Em uma eletrólise ígnea do cloreto de sódio (NaCl), os produtos formados no cátodo e no ânodo são, respectivamente:', 'Gás cloro e sódio metálico', 'Sódio metálico e gás cloro', 'Gás oxigênio e sódio metálico', 'Gás hidrogênio e gás cloro', 'Sódio metálico e gás oxigênio', 'b', 'Na eletrólise ígnea, o cátodo atrai os cátions (Na⁺ sofre redução formando Na metálico) e o ânodo atrai os ânions (Cl⁻ sofre oxidação formando gás Cl₂).', 'médio', 0],
    [55, 'UNESP 2020', 'Para proteger tubulações de ferro contra corrosão, utiliza-se frequentemente um metal de sacrifício. Sabendo que os potenciais padrão de redução são: Fe²⁺/Fe = -0,44 V, Mg²⁺/Mg = -2,37 V, Cu²⁺/Cu = +0,34 V, Ni²⁺/Ni = -0,25 V e Ag⁺/Ag = +0,80 V, o melhor metal para atuar como ânodo de sacrifício é o:', 'Cobre', 'Níquel', 'Prata', 'Magnésio', 'Ferro', 'd', 'O metal de sacrifício deve ter potencial de oxidação maior que o ferro, ou seja, potencial de redução menor. O Mg tem E° = -2,37 V, oxidando-se mais facilmente.', 'médio', 0],
    [55, 'UNICAMP 2019', 'Uma corrente de 9,65 A atravessa uma solução aquosa de AgNO₃ durante 1000 segundos. Considerando a constante de Faraday (1 F = 96500 C/mol) e a massa molar da prata (108 g/mol), qual a massa aproximada de prata depositada no cátodo?', '1,08 g', '10,8 g', '5,40 g', '21,6 g', '108 g', 'b', 'Q = i.t = 9,65 * 1000 = 9650 C. Como 96500 C depositam 1 mol (108 g) de Ag, 9650 C depositarão 10,8 g.', 'médio', 0],
    [55, 'ENEM 2021', 'Considere uma célula eletrolítica contendo solução aquosa de Na₂SO₄. Durante a eletrólise, observa-se a liberação de gases nos eletrodos. Quais são esses gases e a semirreação que ocorre no ânodo, respectivamente?', 'H₂ e O₂; oxidação da água gerando O₂ e H⁺', 'O₂ e H₂; redução da água gerando H₂ e OH⁻', 'Na e SO₂; oxidação do sulfato', 'H₂ e SO₂; redução do sódio', 'O₂ e SO₂; oxidação da água gerando H⁺ e SO₂', 'a', 'Na eletrólise aquosa do Na₂SO₄, ocorre a eletrólise da água. No ânodo há oxidação da água (2H₂O -> O₂ + 4H⁺ + 4e⁻) e no cátodo redução (2H₂O + 2e⁻ -> H₂ + 2OH⁻). Boss question.', 'difícil', 1],

    // [56] Química Orgânica: Cadeias Carbônicas
    [56, 'ENEM 2023', 'O composto CH₃-CH₂-CH₂-CH₃ é classificado quanto à sua cadeia carbônica como:', 'aberta, normal, saturada e homogênea', 'aberta, ramificada, saturada e homogênea', 'fechada, normal, insaturada e heterogênea', 'aberta, normal, insaturada e homogênea', 'fechada, ramificada, saturada e heterogênea', 'a', 'O butano possui cadeia aberta (acíclica), sem ramificações (normal), com apenas ligações simples entre carbonos (saturada) e sem heteroátomos (homogênea).', 'fácil', 0],
    [56, 'UNESP 2022', 'O isopropeno, ou 2-metil-1,3-butadieno, é o monômero da borracha natural. A classificação da sua cadeia carbônica é:', 'aberta, normal, insaturada e homogênea', 'aberta, ramificada, saturada e homogênea', 'aberta, ramificada, insaturada e homogênea', 'fechada, ramificada, insaturada e heterogênea', 'aberta, ramificada, insaturada e heterogênea', 'c', 'É aberta, apresenta ramificação (metil), tem duplas ligações (insaturada) e apenas carbonos na cadeia principal (homogênea).', 'médio', 0],
    [56, 'UNICAMP 2021', 'A cafeína é um estimulante do sistema nervoso central e possui anéis heterocíclicos na sua estrutura. Uma cadeia carbônica heterogênea se caracteriza por:', 'Possuir átomos de halogênio ligados ao carbono', 'Ter insaturações entre carbonos', 'Apresentar um átomo diferente de carbono e hidrogênio ligado às extremidades', 'Apresentar um heteroátomo (como O, N ou S) intercalado entre átomos de carbono', 'Ser constituída apenas de ligações pi conjugadas', 'd', 'Cadeias heterogêneas possuem pelo menos um heteroátomo (átomo diferente de C e H) interrompendo a sequência de carbonos na cadeia.', 'fácil', 0],
    [56, 'FUVEST 2020', 'Analisando a estrutura do colesterol, nota-se que ele é classificado como um esteroide de cadeia mista. Uma cadeia carbônica alicíclica e insaturada possui, respectivamente:', 'Anel aromático e apenas ligações simples', 'Ciclo não aromático e pelo menos uma ligação dupla ou tripla', 'Cadeia aberta e grupo hidroxila', 'Apenas átomos de carbono primário e ligações sigma', 'Cadeia fechada sem heteroátomos e ressonância de elétrons pi', 'b', 'Alicíclica indica cadeia fechada não aromática. Insaturada indica a presença de ligações duplas ou triplas entre carbonos.', 'médio', 0],
    [56, 'ENEM 2019', 'O composto H₂C=CH-O-CH(CH₃)-CH₃ possui uma cadeia classificada como:', 'Aberta, ramificada, saturada e homogênea', 'Aberta, ramificada, insaturada e heterogênea', 'Aberta, normal, insaturada e heterogênea', 'Fechada, ramificada, insaturada e homogênea', 'Aberta, ramificada, insaturada e homogênea', 'b', 'A cadeia é aberta. Possui dupla ligação (insaturada), o oxigênio está entre carbonos (heterogênea) e há ramificação (isopropil).', 'difícil', 1],

    // [57] Funções Orgânicas Oxigenadas
    [57, 'ENEM 2022', 'O etanol (CH₃CH₂OH) e o metoximetano (CH₃OCH₃) possuem a mesma fórmula molecular C₂H₆O, porém diferem na função orgânica. Essas funções são, respectivamente:', 'Álcool e éster', 'Álcool e éter', 'Ácido carboxílico e cetona', 'Aldeído e éter', 'Fenol e éter', 'b', 'O etanol possui o grupo -OH ligado a carbono saturado (álcool). O metoximetano possui o oxigênio entre dois carbonos (éter).', 'fácil', 0],
    [57, 'UNICAMP 2023', 'A oxidação de um álcool primário, como o propan-1-ol, usando um forte agente oxidante (como KMnO₄ em meio ácido) com aquecimento contínuo, produz principalmente:', 'Propanona', 'Propanal', 'Ácido propanoico', 'Propanoato de propila', 'Propeno', 'c', 'A oxidação enérgica de álcoois primários leva inicialmente a aldeído e, em seguida, a ácido carboxílico. Como o agente é forte e há aquecimento, o produto final é o ácido propanoico.', 'médio', 0],
    [57, 'FUVEST 2022', 'Na reação de esterificação de Fischer, um ácido carboxílico reage com um álcool em meio ácido para formar um éster e água. Se reagirmos o ácido etanoico com o propan-1-ol, o éster formado será o:', 'Propanoato de etila', 'Etanoato de etila', 'Etanoato de propila', 'Metanoato de etila', 'Etanoato de metila', 'c', 'O ácido etanoico fornece a parte "etanoato" e o álcool propan-1-ol fornece a parte "propila". Logo, etanoato de propila.', 'médio', 0],
    [57, 'UNESP 2021', 'As cetonas diferem dos aldeídos porque:', 'Possuem a carbonila ligada a pelo menos um átomo de hidrogênio', 'Apresentam o grupo carboxila na extremidade da cadeia', 'Têm o grupo carbonila (C=O) localizado em um carbono secundário', 'São mais ácidas devido à presença do grupo hidroxila', 'Apresentam ligações de hidrogênio intermoleculares intensas', 'c', 'Nas cetonas, o grupo carbonila está entre dois átomos de carbono, ou seja, em carbono secundário. Nos aldeídos, está na extremidade (carbono primário).', 'fácil', 0],
    [57, 'ENEM 2020', 'Um composto de fórmula molecular C₄H₈O reage positivamente com o reativo de Tollens, formando um espelho de prata. Qual é o possível isômero e sua função orgânica correspondente?', 'Butan-2-ona, uma cetona', 'Metoxipropano, um éter', 'Butanal, um aldeído', 'Ácido butanoico, um ácido carboxílico', 'Butan-1-ol, um álcool', 'c', 'O reativo de Tollens oxida aldeídos a ácidos carboxílicos e sofre redução formando prata metálica. Apenas aldeídos dão teste positivo. Portanto, é o butanal.', 'difícil', 1],

    // [58] Funções Orgânicas Nitrogenadas
    [58, 'ENEM 2021', 'A ureia é um importante fertilizante agrícola e apresenta a fórmula química CO(NH₂)₂. A função orgânica presente na ureia é classificada como:', 'Amina primária', 'Amida', 'Nitrila', 'Nitrocomposto', 'Aminoácido', 'b', 'O grupo carbonila (C=O) ligado a átomo(s) de nitrogênio caracteriza a função amida. Na ureia, a carbonila está ligada a dois grupos amino, sendo uma diamida.', 'fácil', 0],
    [58, 'FUVEST 2020', 'Dentre os compostos abaixo, qual apresenta a função amina terciária?', 'Trimetilamina', 'Metilamina', 'Etilamina', 'Acetamida', 'Propanamida', 'a', 'Uma amina terciária possui três grupos substituintes ligados ao nitrogênio. A trimetilamina possui o N ligado a três grupos metil.', 'fácil', 0],
    [58, 'UNICAMP 2022', 'As aminas alifáticas são bases orgânicas derivadas da amônia. A ordem crescente de basicidade em fase aquosa para metilamina, dimetilamina e trimetilamina, em geral, é diferente da fase gasosa devido à solvatação. Em solução aquosa, a ordem de basicidade é:', 'trimetilamina < metilamina < dimetilamina', 'metilamina < dimetilamina < trimetilamina', 'trimetilamina < dimetilamina < metilamina', 'dimetilamina < metilamina < trimetilamina', 'metilamina < trimetilamina < dimetilamina', 'a', 'Em solução aquosa, o impedimento estérico e a menor capacidade de hidratação do íon trimetilamônio reduzem a basicidade da amina terciária. Logo, a ordem é terciária < primária < secundária.', 'difícil', 1],
    [58, 'UNESP 2019', 'A reação de uma amina primária com um ácido carboxílico, sob aquecimento, produz água e um composto pertencente à função:', 'Amina secundária', 'Éster', 'Amida', 'Nitrila', 'Cetonitrila', 'c', 'A reação entre ácido carboxílico e amina, com desidratação, forma uma ligação amídica, gerando uma amida e água.', 'médio', 0],
    [58, 'ENEM 2018', 'Os aminoácidos são compostos fundamentais para a vida, pois compõem as proteínas. A estrutura genérica de um alfa-aminoácido possui quais funções orgânicas presas ao mesmo átomo de carbono?', 'Amina e álcool', 'Amida e aldeído', 'Amina e ácido carboxílico', 'Nitro e cetona', 'Amina e éster', 'c', 'Os alfa-aminoácidos possuem um grupo amino (-NH₂) e um grupo ácido carboxílico (-COOH) ligados ao mesmo carbono alfa.', 'médio', 0],

    // [59] Isomeria Plana e Espacial
    [59, 'FUVEST 2023', 'Quantos isômeros ópticos ativos apresenta uma molécula que possui dois carbonos quirais diferentes, como no caso do ácido 2-amino-3-hidroxibutanoico (treonina)?', '2', '3', '4', '6', '8', 'c', 'O número de isômeros opticamente ativos é 2^n, onde n é o número de carbonos quirais diferentes. 2^2 = 4 isômeros ativos.', 'médio', 0],
    [59, 'ENEM 2020', 'O but-2-eno é um hidrocarboneto que apresenta isomeria espacial. A respeito dos seus isômeros cis e trans, é correto afirmar que:', 'O isômero trans é mais polar que o cis', 'O isômero cis tem maior ponto de ebulição devido ao momento dipolar resultante', 'Não há diferença nas propriedades físicas entre eles', 'O isômero trans sofre combustão formando mais CO₂ que o cis', 'Ambos possuem atividade óptica', 'b', 'O isômero cis é polar (momento dipolar diferente de zero), apresentando interações intermoleculares mais fortes e, logo, maior ponto de ebulição que o isômero trans (apolar).', 'médio', 0],
    [59, 'UNESP 2021', 'Os compostos propanona e propen-2-ol apresentam a mesma fórmula molecular C₃H₆O e coexistem em um equilíbrio dinâmico. Esse caso específico de isomeria de função é conhecido como:', 'Isomeria de compensação (metameria)', 'Tautomeria', 'Isomeria geométrica', 'Isomeria de posição', 'Isomeria de cadeia', 'b', 'O equilíbrio entre uma cetona e um enol é um caso clássico de tautomeria (ceto-enólica).', 'fácil', 0],
    [59, 'UNICAMP 2022', 'Qual das moléculas a seguir NÃO apresenta isomeria óptica?', 'Ácido 2-cloropropanoico', '2-butanol', '1-cloropropano', 'Ácido lático', 'Alanina', 'c', 'O 1-cloropropano não possui carbono quiral (carbono ligado a quatro grupos diferentes), não apresentando atividade óptica.', 'fácil', 0],
    [59, 'ENEM 2019', 'Uma mistura equimolar dos enantiômeros (R) e (S) de uma substância apresenta rotação óptica nula. Essa mistura é chamada de racêmica. Se um ácido tem 3 centros estereogênicos, sendo dois deles idênticos (pseudoassimétricos), quantos isômeros opticamente inativos por compensação interna (meso) existirão?', 'Zero', 'Um', 'Dois', 'Quatro', 'Oito', 'c', 'Moléculas com centros estereogênicos que apresentam plano de simetria podem formar compostos meso. Num sistema com 3 centros, o do meio pode ser pseudoassimétrico gerando estruturas meso diferentes.', 'difícil', 1],

    // [60] Reações Orgânicas e Polímeros
    [60, 'ENEM 2021', 'A reação de hidratação do propeno, em meio ácido, segue a regra de Markovnikov. O principal produto orgânico formado nessa reação é o:', 'Propan-1-ol', 'Propan-2-ol', 'Propanona', 'Propano', 'Ácido propanoico', 'b', 'A regra de Markovnikov diz que o H se liga ao carbono mais hidrogenado da dupla. Assim, o OH se liga ao carbono central, formando propan-2-ol.', 'fácil', 0],
    [60, 'FUVEST 2022', 'O poli(cloreto de vinila), conhecido como PVC, é obtido através de uma reação de polimerização por:', 'Condensação de cloreto de etanila', 'Adição sucessiva de monômeros de cloreto de vinila (cloroeteno)', 'Substituição de átomos de cloro no etano', 'Eliminação de água a partir do cloretanol', 'Oxidação do eteno com gás cloro', 'b', 'O PVC é um polímero de adição formado a partir da quebra da dupla ligação do monômero cloreto de vinila (cloroeteno).', 'fácil', 0],
    [60, 'UNESP 2020', 'Na reação de substituição nucleofílica unimolecular (SN1) do cloreto de terc-butila com água, qual intermediário reacional é formado?', 'Radical livre terc-butila', 'Carbânion metila', 'Carbocátion terc-butila', 'Complexo ativado pentacoordenado', 'Íon cloreto positivo', 'c', 'Em reações SN1, o grupo de saída abandona a molécula formando um intermediário carbocátion estabilizado, neste caso, o carbocátion terc-butila.', 'médio', 0],
    [60, 'UNICAMP 2023', 'A formação do poliéster PET envolve a reação entre o ácido tereftálico e o etilenoglicol. Essa reação de polimerização é classificada como de:', 'Adição, com quebra de ligação pi', 'Eliminação, gerando ligações triplas', 'Condensação, com liberação de moléculas de água', 'Substituição radicalar', 'Isomerização, rearranjando monômeros', 'c', 'PET é um polímero de condensação. A reação entre um diácido carboxílico e um diálcool forma ligações éster, liberando água como subproduto.', 'médio', 0],
    [60, 'ENEM 2018', 'A ozonólise de um alceno X produziu equimolarmente propanona e etanal. Qual é o nome oficial IUPAC do alceno X?', '2-metilbut-2-eno', '3-metilbut-1-eno', 'Pent-2-eno', '2-metilpent-2-eno', 'Hex-3-eno', 'a', 'Na ozonólise com água e zinco, a dupla ligação é clivada. Se formou propanona (acetona) e etanal, juntando os fragmentos (C=O da propanona e O=C do etanal), a dupla estava entre os carbonos 2 e 3 do 2-metilbut-2-eno.', 'difícil', 1],

    // [135] Tabela Periódica e Propriedades
    [135, 'ENEM 2022', 'Ao descer no grupo 1 da Tabela Periódica, dos metais alcalinos, observa-se que o raio atômico aumenta. Esse aumento está diretamente relacionado a:', 'Maior carga nuclear', 'Maior quantidade de nêutrons no núcleo', 'Aumento do número de níveis de energia (camadas)', 'Diminuição da blindagem eletrônica', 'Aumento do potencial de ionização', 'c', 'Ao descer no grupo, um novo nível de energia é ocupado pelos elétrons de valência, tornando o átomo sucessivamente maior.', 'fácil', 0],
    [135, 'FUVEST 2021', 'Considerando os elementos Flúor (F), Oxigênio (O) e Cloro (Cl), a ordem decrescente de eletronegatividade entre eles é:', 'F > Cl > O', 'F > O > Cl', 'O > F > Cl', 'Cl > O > F', 'O > Cl > F', 'b', 'O flúor é o elemento mais eletronegativo, seguido pelo oxigênio. O cloro está abaixo do flúor e, portanto, tem menor eletronegatividade que o oxigênio.', 'médio', 0],
    [135, 'UNESP 2019', 'A energia de ionização é a energia necessária para remover um elétron de um átomo isolado no estado gasoso. Considerando os elementos Li, Be e B do segundo período, a primeira energia de ionização cresce na ordem:', 'Li < Be < B', 'Li < B < Be', 'B < Be < Li', 'Be < B < Li', 'B < Li < Be', 'b', 'Apesar da tendência geral de aumento da EI ao longo do período, o Be possui subnível 2s² completo, conferindo maior estabilidade, logo a EI do Be é maior que a do B (que tem elétron em 2p¹).', 'difícil', 1],
    [135, 'UNICAMP 2020', 'O íon isoeletrônico com o gás nobre Argônio (Ar, Z=18) e que possui menor raio iônico é:', 'S²⁻', 'Cl⁻', 'K⁺', 'Ca²⁺', 'P³⁻', 'd', 'Para espécies isoeletrônicas (mesmo número de elétrons), o raio diminui conforme aumenta o número de prótons. Ca²⁺ possui 20 prótons, puxando os 18 elétrons com maior força.', 'médio', 0],
    [135, 'ENEM 2023', 'A afinidade eletrônica é a energia liberada quando um elétron é adicionado a um átomo no estado gasoso. Qual grupo da Tabela Periódica possui, em geral, os maiores valores de afinidade eletrônica (em módulo)?', 'Gases nobres', 'Metais alcalinos', 'Halogênios', 'Calcogênios', 'Metais alcalinoterrosos', 'c', 'Os halogênios, por precisarem de apenas um elétron para atingir configuração de gás nobre, liberam maior quantidade de energia ao ganhar esse elétron.', 'fácil', 0],

    // [136] Geometria Molecular e Polaridade
    [136, 'ENEM 2021', 'A molécula de amônia (NH₃) possui o nitrogênio como átomo central ligado a três hidrogênios, sobrando um par de elétrons livres. A geometria e a polaridade dessa molécula são:', 'Trigonal plana e apolar', 'Piramidal trigonal e polar', 'Tetraédrica e polar', 'Linear e apolar', 'Angular e polar', 'b', 'Com 3 pares ligantes e 1 não ligante, a repulsão gera a geometria piramidal. A assimetria vetorial resulta num momento dipolar resultante diferente de zero, sendo polar.', 'fácil', 0],
    [136, 'UNICAMP 2023', 'A molécula de trifluoreto de boro (BF₃) reage frequentemente com moléculas que possuem pares de elétrons livres, pois o boro não atinge o octeto. A geometria do BF₃ e sua hibridização são:', 'Piramidal e sp³', 'Trigonal plana e sp²', 'Angular e sp', 'Linear e sp', 'Tetraédrica e sp³', 'b', 'O boro central possui 3 nuvens eletrônicas, todas ligantes. Isso caracteriza hibridização sp² e geometria trigonal plana.', 'médio', 0],
    [136, 'UNESP 2020', 'O dióxido de carbono (CO₂) e o dióxido de enxofre (SO₂) são ambos óxidos triatômicos, porém possuem propriedades físicas diferentes. A respeito da geometria molecular de ambas, é correto afirmar que:', 'Ambas são lineares e apolares', 'CO₂ é linear e polar; SO₂ é angular e apolar', 'CO₂ é angular e apolar; SO₂ é linear e polar', 'CO₂ é linear e apolar; SO₂ é angular e polar', 'Ambas são angulares e polares', 'd', 'O C não possui pares não ligantes no CO₂ (geometria linear, vetores anulam-se). O S possui par de elétrons livres no SO₂ (geometria angular, momento polar resultante diferente de zero).', 'médio', 0],
    [136, 'FUVEST 2019', 'O pentafluoreto de fósforo (PF₅) é uma molécula em que o fósforo central sofre expansão de octeto. Qual é a geometria molecular adotada por esta espécie?', 'Tetraédrica', 'Bipiramidal trigonal', 'Octaédrica', 'Quadrada plana', 'Gangorra (Seesaw)', 'b', 'Com 5 pares de elétrons ligantes ao redor do fósforo e nenhum par não ligante, a melhor disposição espacial para minimizar a repulsão é a bipirâmide de base trigonal.', 'fácil', 0],
    [136, 'ENEM 2018', 'Considerando as forças intermoleculares, analise a temperatura de ebulição da água (H₂O) e do sulfeto de hidrogênio (H₂S). A água ferve a 100 °C e o H₂S ferve a -60 °C. Essa grande diferença deve-se principalmente a:', 'Maior massa molar da água', 'Hibridização diferente entre O e S', 'Formação de ligações de hidrogênio intensas na água e não no H₂S', 'Geometria linear do H₂S em oposição à angular da H₂O', 'Interações de London muito mais fracas no H₂S do que na água', 'c', 'Devido à alta eletronegatividade do Oxigênio, a água forma ligações de hidrogênio (pontes de hidrogênio) fortes, exigindo mais energia para vaporizar. H₂S faz apenas dipolo-dipolo.', 'difícil', 1],

    // [137] Concentração de Soluções e Molaridade
    [137, 'FUVEST 2022', 'Qual é a concentração em mol/L de uma solução preparada dissolvendo-se 20 g de hidróxido de sódio (NaOH, massa molar = 40 g/mol) em água suficiente para completar 500 mL de solução?', '0,5 mol/L', '1,0 mol/L', '2,0 mol/L', '4,0 mol/L', '0,25 mol/L', 'b', 'n = m/M = 20 / 40 = 0,5 mol. Molaridade = n / V = 0,5 mol / 0,5 L = 1,0 mol/L.', 'fácil', 0],
    [137, 'ENEM 2020', 'Para preparar 250 mL de uma solução 0,1 mol/L de ácido sulfúrico (H₂SO₄) a partir de uma solução estoque 2,0 mol/L, o volume necessário da solução estoque é de:', '12,5 mL', '25,0 mL', '50,0 mL', '5,0 mL', '1,25 mL', 'a', 'Pela equação de diluição C1.V1 = C2.V2, temos 2,0 * V1 = 0,1 * 250. Logo, 2,0 * V1 = 25 -> V1 = 12,5 mL.', 'médio', 0],
    [137, 'UNICAMP 2019', 'Uma solução de ácido nítrico concentrado tem densidade 1,4 g/mL e título em massa de 63%. Sabendo que a massa molar do HNO₃ é 63 g/mol, a concentração dessa solução em mol/L é:', '1,4 mol/L', '6,3 mol/L', '14,0 mol/L', '20,0 mol/L', '9,8 mol/L', 'c', 'A massa de 1 L de solução é 1400 g. Como 63% é ácido, a massa de HNO3 é 0,63 * 1400 = 882 g. Molaridade = 882 / 63 = 14 mol/L.', 'difícil', 1],
    [137, 'UNESP 2021', 'Misturam-se 200 mL de solução 0,5 mol/L de NaCl com 300 mL de solução 0,2 mol/L do mesmo sal. Qual a concentração final aproximada de cloreto de sódio em mol/L?', '0,35 mol/L', '0,32 mol/L', '0,25 mol/L', '0,40 mol/L', '0,15 mol/L', 'b', 'n1 = 0,5 * 0,2 = 0,1 mol. n2 = 0,2 * 0,3 = 0,06 mol. n total = 0,16 mol. V total = 0,5 L. C final = 0,16 / 0,5 = 0,32 mol/L.', 'médio', 0],
    [137, 'ENEM 2023', 'O soro fisiológico é uma solução aquosa a 0,9% m/v de cloreto de sódio (NaCl). Essa porcentagem significa que há:', '0,9 g de NaCl em 100 mL de água', '0,9 g de NaCl em 1000 mL de solução', '9 g de NaCl em 100 mL de solução', '0,9 g de NaCl em 100 mL de solução', '0,9 mols de NaCl em 1 L de solução', 'd', 'A notação % m/v indica a massa de soluto (em gramas) dissolvida em 100 mL de solução. Logo, são 0,9 g em 100 mL.', 'fácil', 0],

    // [138] Cálculo Estequiométrico
    [138, 'UNICAMP 2022', 'A combustão completa de 1 mol de etanol (C₂H₆O) gera dióxido de carbono e água. Qual a massa de CO₂ formada na queima completa de 46 g de etanol? (Dados: H=1, C=12, O=16)', '44 g', '22 g', '88 g', '132 g', '176 g', 'c', 'Equação: C₂H₆O + 3O₂ -> 2CO₂ + 3H₂O. 46 g de etanol correspondem a 1 mol. Portanto, produz-se 2 mols de CO₂, o que equivale a 2 * 44 = 88 g.', 'fácil', 0],
    [138, 'ENEM 2021', 'Na reação de síntese da amônia, N₂ + 3H₂ -> 2NH₃, reagem-se 14 g de gás nitrogênio com 6 g de gás hidrogênio. Qual é a massa de amônia (NH₃) produzida, considerando rendimento de 100%? (Massas molares: N=14, H=1)', '20 g', '17 g', '34 g', '8,5 g', '51 g', 'b', '14 g de N2 = 0,5 mol. 6 g de H2 = 3 mols. A estequiometria pede 1:3. Para 0,5 mol de N2 precisamos de 1,5 mol de H2. O H2 está em excesso. O limitante é o N2. A massa de amônia será 2 * 0,5 = 1 mol, ou seja, 17 g.', 'médio', 0],
    [138, 'FUVEST 2020', 'O carbonato de cálcio (CaCO₃) decompõe-se termicamente em óxido de cálcio (CaO) e dióxido de carbono (CO₂). Se aquecermos 200 g de calcário com 80% de pureza em CaCO₃, qual a massa de CaO obtida? (Massas molares: CaCO₃=100 g/mol, CaO=56 g/mol)', '56 g', '112 g', '89,6 g', '140 g', '44,8 g', 'c', 'Massa pura de CaCO3 = 0,8 * 200 = 160 g. N mols = 160 / 100 = 1,6 mol. Mol de CaO gerado = 1,6 mol. Massa de CaO = 1,6 * 56 = 89,6 g.', 'médio', 0],
    [138, 'UNESP 2023', 'Numa reação siderúrgica, Fe₂O₃ reage com CO para formar Fe metálico e CO₂. Fe₂O₃ + 3 CO -> 2 Fe + 3 CO₂. Se desejamos obter 11,2 toneladas de ferro com um processo que tem 80% de rendimento, qual a massa de Fe₂O₃ pura que deve ser colocada para reagir? (Dados: Fe=56, O=16)', '16 toneladas', '20 toneladas', '32 toneladas', '25 toneladas', '12,8 toneladas', 'b', '11,2 ton Fe seria gerada por 16 ton de Fe2O3 se o rendimento fosse 100%. Como é 80%, massa necessária = 16 / 0,8 = 20 toneladas.', 'difícil', 1],
    [138, 'ENEM 2019', 'Uma amostra de 2 mols de um gás ideal sob temperatura e pressão padrão (CNTP) ocupa um volume de aproximadamente:', '22,4 L', '11,2 L', '44,8 L', '67,2 L', '100 L', 'c', 'Nas CNTP (0°C, 1 atm), o volume molar de um gás ideal é aproximadamente 22,4 L/mol. Para 2 mols, o volume é 2 * 22,4 = 44,8 L.', 'fácil', 0],

    // [139] Termoquímica e Entalpia
    [139, 'ENEM 2021', 'A queima de 1 mol de gás metano (CH₄) em condições padrão libera cerca de 890 kJ de calor. O valor da variação de entalpia (ΔH) e a classificação dessa reação são, respectivamente:', '+890 kJ; Endotérmica', '-890 kJ; Endotérmica', '+890 kJ; Exotérmica', '-890 kJ; Exotérmica', 'Zero; Isotérmica', 'd', 'Como o calor é liberado para o ambiente, trata-se de uma reação exotérmica, e por convenção, o ΔH é negativo.', 'fácil', 0],
    [139, 'FUVEST 2022', 'Conhecendo as entalpias de formação: ΔH°f(CO₂) = -394 kJ/mol, ΔH°f(H₂O) = -286 kJ/mol e ΔH°f(CH₄) = -75 kJ/mol. Qual é a entalpia de combustão completa do metano? (CH₄ + 2O₂ -> CO₂ + 2H₂O)', '-891 kJ/mol', '-605 kJ/mol', '-966 kJ/mol', '+891 kJ/mol', '+966 kJ/mol', 'a', 'ΔH = ΣHprodutos - ΣHreagentes = [-394 + 2(-286)] - [-75 + 0] = -394 - 572 + 75 = -891 kJ/mol.', 'médio', 0],
    [139, 'UNICAMP 2020', 'Pela Lei de Hess, se invertermos a equação de formação da água líquida (H₂ + 1/2 O₂ -> H₂O, ΔH = -286 kJ), o valor do ΔH da nova reação (H₂O -> H₂ + 1/2 O₂) será:', '-286 kJ', '+286 kJ', '0 kJ', '-143 kJ', '+143 kJ', 'b', 'De acordo com as consequências da Lei de Hess, ao inverter a equação química o sinal da variação de entalpia deve ser invertido.', 'fácil', 0],
    [139, 'UNESP 2019', 'A energia de ligação é a energia requerida para quebrar um mol de ligações gasosas. Dados: H-H (436 kJ/mol), Cl-Cl (242 kJ/mol), H-Cl (431 kJ/mol). Qual a entalpia da reação de síntese de 2 mols de HCl (H₂ + Cl₂ -> 2HCl)?', '-184 kJ/mol', '+184 kJ/mol', '-92 kJ/mol', '+92 kJ/mol', '-247 kJ/mol', 'a', 'ΔH = (Energias quebradas) - (Energias formadas). Reagentes: 436 + 242 = 678 kJ (absorvidos). Produtos: 2 * 431 = 862 kJ (liberados). ΔH = 678 - 862 = -184 kJ.', 'médio', 0],
    [139, 'ENEM 2023', 'A capacidade calorífica de uma substância afeta diretamente como ela responde a trocas de calor. Se aplicarmos 500 J de calor a um bloco de metal e sua temperatura variar de forma idêntica à de uma amostra de água com a qual recebe apenas 50 J, conclui-se que:', 'A capacidade calorífica da água é 10 vezes menor que a do metal', 'O calor específico do metal é maior, tornando o ΔH da substância menor', 'A massa da água deve ser muito maior que a do metal para igualar o aumento', 'A capacidade calorífica do metal é 10 vezes maior que a da amostra de água', 'O processo de queima ocorreu sob entalpia de vaporização idêntica', 'd', 'Como C = Q/ΔT, se o metal precisou de 10 vezes mais calor (500 J contra 50 J) para apresentar a mesma variação de temperatura, sua capacidade calorífica C é 10 vezes maior.', 'difícil', 1],

    // [140] Eletroquímica: Pilhas e Eletrólise (Same lesson name, new questions)
    [140, 'FUVEST 2018', 'Para obtermos alumínio metálico industrialmente, utiliza-se a eletrólise ígnea da alumina (Al₂O₃) no processo Hall-Héroult. Por que a eletrólise aquosa de um sal de alumínio não serviria para esse fim?', 'O alumínio reagiria espontaneamente com os ânions sulfato da solução', 'Os íons H⁺ da água se reduziriam no lugar do Al³⁺, formando H₂', 'O oxigênio da água se oxidaria no lugar do alumínio', 'A resistência elétrica da água pura é muito elevada para a eletrólise', 'Ocorreriam explosões pela formação espontânea de peróxidos', 'b', 'O alumínio tem potencial de redução menor que a água (-1,66 V contra -0,83 V do pH neutro), então a água sofre redução preferencialmente formando gás hidrogênio no cátodo.', 'médio', 0],
    [140, 'ENEM 2019', 'O fenômeno de recarga de uma bateria de chumbo-ácido (bateria de carro) consiste em aplicar uma corrente externa na bateria descarregada. Esse procedimento converte a pilha em uma:', 'Célula galvânica primária', 'Ponte salina de alta tensão', 'Célula eletrolítica não espontânea', 'Fonte de f.e.m. termodinamicamente irreversível', 'Bateria alcalina de longa duração', 'c', 'Durante a recarga, uma fonte de tensão externa reverte a reação global (que é espontânea na descarga), caracterizando o funcionamento não espontâneo de uma eletrólise (célula eletrolítica).', 'fácil', 0],
    [140, 'UNICAMP 2021', 'A força eletromotriz de uma pilha é alterada pela concentração dos reagentes, de acordo com a equação de Nernst. Se em uma pilha de cobre e zinco aumentarmos a concentração do íon Cu²⁺, mantendo Zn²⁺ constante, a diferença de potencial gerada (ddp):', 'Vai aumentar', 'Vai diminuir', 'Permanecerá inalterada', 'Ficará negativa, invertendo os polos', 'Zera instantaneamente, bloqueando a pilha', 'a', 'Cu²⁺ atua como reagente na equação global de oxirredução (Zn + Cu²⁺ -> Zn²⁺ + Cu). Ao aumentar um reagente, o equilíbrio desloca para a direita, aumentando o potencial (ddp) da pilha.', 'médio', 0],
    [140, 'UNESP 2022', 'Qual a principal função da ponte salina (ou membrana porosa) em uma célula galvânica?', 'Facilitar o fluxo exclusivo de elétrons entre os eletrodos', 'Impedir qualquer troca iônica, forçando a reação pelo fio externo', 'Catalisar a oxidação do anodo', 'Manter o equilíbrio elétrico (eletro neutralidade) em ambos os compartimentos de solução', 'Aumentar a concentração dos íons dos metais nos béqueres', 'd', 'A ponte salina permite a migração de íons compensando o desequilíbrio de carga nas meias-células à medida que os íons se formam e são consumidos, fechando o circuito elétrico internamente.', 'fácil', 0],
    [140, 'ENEM 2020', 'Na eletrólise de uma solução aquosa concentrada de NaCl (salmoura) utilizando eletrodos inertes, o ânodo e o cátodo produzem, respectivamente, e a solução adquire caráter:', 'Cl₂ e H₂, ficando básica (pH > 7)', 'H₂ e Cl₂, ficando ácida (pH < 7)', 'O₂ e Na, neutra (pH = 7)', 'Cl₂ e Na, básica (pH > 7)', 'O₂ e H₂, básica (pH > 7)', 'a', 'No ânodo, o Cl⁻ (concentrado) oxida a Cl₂. No cátodo, a água reduz a H₂ liberando OH⁻. A sobra de Na⁺ e OH⁻ forma uma solução de NaOH (caráter básico).', 'difícil', 1],

    // [141] Química Orgânica: Cadeias Carbônicas (More questions)
    [141, 'UNESP 2023', 'A fórmula estrutural do benzeno é classicamente representada por um anel hexagonal com três ligações duplas alternadas. Na verdade, suas ligações carbono-carbono possuem tamanho idêntico. Isso se explica pelo fenômeno da:', 'Ressonância ou deslocalização dos elétrons pi', 'Hibridização sp³ de todos os átomos', 'Tautomeria anelar intra-molecular', 'Isomeria cis-trans restrita do anel', 'Radiação ultravioleta que quebra e refaz as ligações muito rápido', 'a', 'O benzeno possui uma nuvem eletrônica pi deslocalizada ao longo do anel (ressonância), o que torna todas as ligações carbono-carbono equivalentes e intermediárias entre simples e dupla.', 'fácil', 0],
    [141, 'ENEM 2021', 'Quantos carbonos primários, secundários, terciários e quaternários, respectivamente, possui o hidrocarboneto 2,2,4-trimetilpentano?', '5, 1, 1, 1', '4, 2, 1, 1', '5, 1, 0, 2', '4, 1, 2, 1', '3, 3, 1, 1', 'a', 'A cadeia principal possui 5 carbonos. Há um grupo terc-butil e um isobutil. O composto tem 5 carbonos primários, 1 secundário, 1 terciário (carbono 4) e 1 quaternário (carbono 2).', 'médio', 0],
    [141, 'FUVEST 2020', 'As parafinas são ceras compostas majoritariamente por alcanos de cadeia longa. Devido a serem saturadas e apolares, interagem molecularmente por meio de:', 'Ligações de hidrogênio', 'Interações dipolo permanente', 'Interações dipolo induzido - dipolo induzido (Forças de London)', 'Ligações iônicas intramoleculares', 'Forças íon-dipolo', 'c', 'Moléculas apolares, como os alcanos (hidrocarbonetos saturados), sofrem apenas atração por forças de dispersão de London, ou dipolo induzido-dipolo induzido.', 'fácil', 0],
    [141, 'UNICAMP 2019', 'Uma substância apresenta a fórmula geral CnH2n. Pode-se concluir, com certeza, que esta molécula pertence à classe dos:', 'Alcanos', 'Alcinos', 'Alcadienos', 'Alcenos ou Cicloalcanos', 'Aromáticos', 'd', 'A fórmula molecular geral CnH2n é válida para os alcenos (que possuem uma dupla ligação) e cicloalcanos (compostos fechados saturados).', 'médio', 0],
    [141, 'ENEM 2018', 'Um composto cíclico com 6 átomos de carbono apresenta a fórmula C₆H₁₀. Sabendo que este não possui ramificações, ele deve conter:', 'Três duplas ligações conjugadas (aromático)', 'Apenas ligações simples', 'Duas ligações duplas (ciclohexadieno)', 'Uma ligação dupla (ciclohexeno)', 'Uma ligação tripla (ciclohexino)', 'd', 'Um cicloalcano de 6 carbonos tem fórmula C6H12. Com C6H10 (menos dois hidrogênios), ocorreu a formação de uma insaturação (uma ligação pi), logo é o ciclohexeno.', 'difícil', 1],

    // [142] Funções Orgânicas e Isomeria
    [142, 'FUVEST 2021', 'A aspirina (ácido acetilsalicílico) possui as funções ácido carboxílico e éster em sua estrutura. O composto que é isômero de função de um ácido carboxílico que não apresenta cadeia ramificada, geralmente é um:', 'Éster', 'Álcool', 'Éter', 'Aldeído', 'Fenol', 'a', 'Os ácidos carboxílicos e os ésteres mono-oxigenados correspondentes possuem a mesma fórmula geral CnH2nO2, sendo os clássicos isômeros de função.', 'fácil', 0],
    [142, 'ENEM 2022', 'Qual dos compostos aromáticos abaixo possui comportamento mais ácido, sendo capaz de reagir de forma neutralizante com uma base forte como NaOH?', 'Benzeno', 'Tolueno', 'Anilina', 'Fenol', 'Clorobenzeno', 'd', 'O fenol apresenta hidroxila diretamente ligada ao anel aromático, o qual estabiliza o íon fenóxido formado por ressonância, conferindo um caráter fracamente ácido.', 'fácil', 0],
    [142, 'UNICAMP 2020', 'Para que uma substância orgânica com dupla ligação apresente isomeria geométrica (cis-trans), qual condição é indispensável em relação aos ligantes dos carbonos insaturados?', 'Ambos os carbonos devem possuir obrigatoriamente um átomo de hidrogênio', 'O composto deve ser assimétrico com pelo menos um carbono quiral', 'A dupla ligação deve estar em uma cadeia cíclica restrita', 'Cada carbono da dupla ligação deve estar ligado a dois grupos ou átomos diferentes entre si', 'Os carbonos insaturados devem estar ligados a pelo menos um heteroátomo', 'd', 'A condição essencial para ocorrer isomeria geométrica cis-trans em alcenos é que no carbono 1 da dupla os ligantes sejam diferentes, o mesmo valendo para os ligantes no carbono 2 da dupla.', 'médio', 0],
    [142, 'UNESP 2021', 'A vanilina, responsável pelo aroma de baunilha, contém as funções aldeído, éter e fenol em sua molécula. Se ela sofrer completa redução catalítica (com excesso de H2), a principal alteração nas funções orgânicas será a transformação do aldeído em:', 'Ácido carboxílico', 'Álcool secundário', 'Álcool primário', 'Éster metílico', 'Uma nova cetona', 'c', 'O grupo aldeído (carbonila terminal) quando sofre redução, converte-se sempre em um álcool primário (-CH2OH).', 'médio', 0],
    [142, 'ENEM 2019', 'Considere o ácido tartárico. Ele apresenta carbonos quirais e isômeros opticamente ativos, além de uma forma meso, inativa. Essa inatividade óptica do composto meso ocorre porque:', 'Ele tem apenas um carbono assimétrico de configuração absoluta R', 'Há compensação externa, por ser uma mistura racêmica na proporção de 1:1', 'A molécula não possui carbonos assimétricos (quirais)', 'O arranjo geométrico é cis-trans, neutralizando as interações polares', 'A molécula possui um plano de simetria interno que anula as rotações geradas pelos centros quirais', 'e', 'Compostos meso possuem dois ou mais centros quirais, mas contêm um plano ou centro de simetria que faz com que a rotação provocada por uma metade da molécula cancele a da outra (compensação interna).', 'difícil', 1],
];

$stmt = $pdo->prepare("INSERT INTO questions (lesson_id, exam_source, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation_text, difficulty, is_boss) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
$inserted = 0;
$errors = 0;
foreach ($questions as $q) {
    try { 
        $stmt->execute($q); 
        $inserted++; 
    } catch (Exception $e) { 
        $errors++; 
        echo "ERRO: " . $e->getMessage() . "\n"; 
    }
}
echo "\nInseridas: {$inserted} | Erros: {$errors}\n";
