<?php
require_once __DIR__ . '/../config/db.php';
echo "=== Inserindo questões de Química ===\n\n";

$questions = [
// [41] Modelos Atômicos e Distribuição Eletrônica
[41, 'UFPR 2023', 'O íon Fe³⁺ (Z=26) possui qual configuração eletrônica em subníveis de energia?', '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d³', '1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁵', '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁶', '1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁶', '1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹ 3d⁵', 'b', 'O Fe neutro tem Z=26: 1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁶. O íon Fe³⁺ perde 3 elétrons, inicialmente do subnível mais externo (4s) e depois do 3d. Assim, perde os 2 do 4s e 1 do 3d, ficando 3d⁵.', 'médio', 0],
[41, 'UFMG 2024', 'O modelo atômico de Bohr propôs que os elétrons giram em órbitas circulares ao redor do núcleo. Qual fenômeno esse modelo conseguiu explicar com sucesso?', 'Efeito fotoelétrico.', 'Espectro de emissão do átomo de hidrogênio.', 'Princípio da incerteza de Heisenberg.', 'Isotopia dos elementos químicos.', 'Radioatividade natural.', 'b', 'Bohr utilizou os níveis de energia quantizados para explicar o espectro de linhas de emissão do hidrogênio, mostrando que a transição de um elétron para uma órbita mais interna libera um fóton com energia específica.', 'fácil', 0],
[41, 'UERJ 2023', 'De acordo com o princípio da exclusão de Pauli, um orbital pode conter no máximo:', '8 elétrons com spins paralelos.', '2 elétrons com spins opostos.', '18 elétrons com qualquer spin.', '2 elétrons com spins paralelos.', '6 elétrons com spins opostos.', 'b', 'O princípio de Pauli estabelece que dois elétrons no mesmo átomo não podem ter os quatro números quânticos iguais. Logo, um orbital abriga no máximo 2 elétrons com spins opostos.', 'fácil', 1],

// [42] Tabela Periódica e Propriedades Periódicas
[42, 'UFRGS 2024', 'Dentre os elementos a seguir, qual apresenta o maior raio atômico?', 'Sódio (Na)', 'Cloro (Cl)', 'Potássio (K)', 'Cálcio (Ca)', 'Magnésio (Mg)', 'c', 'O raio atômico cresce da direita para a esquerda e de cima para baixo na tabela. O Potássio (K) está no 4º período, grupo 1, possuindo maior raio entre as opções.', 'médio', 0],
[42, 'UEL 2023', 'A energia de ionização é a energia necessária para remover um elétron de um átomo no estado gasoso. Qual dos elementos possui a primeira energia de ionização mais elevada?', 'Lítio (Li)', 'Berílio (Be)', 'Flúor (F)', 'Neônio (Ne)', 'Oxigênio (O)', 'd', 'O Neônio é um gás nobre, com a camada de valência completa. Tem a maior energia de ionização do seu período, pois remover um elétron é muito difícil.', 'fácil', 0],
[42, 'UEM 2024', 'Analisando os elementos X (Z=11) e Y (Z=17), podemos afirmar que, em relação à eletronegatividade e raio atômico:', 'X é mais eletronegativo e tem menor raio que Y.', 'X é menos eletronegativo e tem maior raio que Y.', 'Ambos possuem a mesma eletronegatividade.', 'Y é menos eletronegativo e tem maior raio que X.', 'Y é mais eletronegativo e tem maior raio que X.', 'b', 'X é o Sódio (Na, Z=11) e Y é o Cloro (Cl, Z=17). O Cloro está mais à direita no mesmo período, logo tem maior eletronegatividade e menor raio atômico que o Sódio.', 'médio', 1],

// [43] Ligações Iônicas e Covalentes
[43, 'MACKENZIE 2023', 'A substância cloreto de magnésio (MgCl₂) possui qual tipo principal de ligação química e que estado físico em temperatura ambiente?', 'Ligação iônica e sólido.', 'Ligação covalente e líquido.', 'Ligação iônica e gás.', 'Ligação metálica e sólido.', 'Ligação covalente e sólido.', 'a', 'Mg (metal do grupo 2) doa 2 elétrons, e cada Cl (ametal do grupo 17) recebe 1. Forma-se um composto iônico, que à temperatura ambiente é sólido e possui alto ponto de fusão.', 'fácil', 0],
[43, 'PUC-MG 2024', 'Quantas ligações sigma (σ) e pi (π) existem na molécula de etino (C₂H₂)?', '3 ligações σ e 2 ligações π', '2 ligações σ e 2 ligações π', '3 ligações σ e 1 ligação π', '4 ligações σ e 1 ligação π', '1 ligação σ e 2 ligações π', 'a', 'A molécula H-C≡C-H possui uma ligação simples C-H (1 σ), outra simples C-H (1 σ) e uma tripla C≡C (1 σ e 2 π). Total: 3 σ e 2 π.', 'médio', 0],
[43, 'ITA 2023', 'Qual das seguintes moléculas não obedece à regra do octeto?', 'CO₂', 'H₂O', 'NH₃', 'PCl₅', 'CH₄', 'd', 'O fósforo no PCl₅ faz 5 ligações, ficando com 10 elétrons na camada de valência (expansão do octeto), pois pertence ao 3º período e possui orbitais d disponíveis.', 'difícil', 1],

// [44] Ligações Metálicas e Forças Intermoleculares
[44, 'FATEC 2024', 'Qual das substâncias abaixo apresenta ponte de hidrogênio (ligação de hidrogênio) como principal força intermolecular?', 'CH₄', 'H₂S', 'NH₃', 'HCl', 'CO₂', 'c', 'Ligações de hidrogênio ocorrem quando o H está ligado diretamente a F, O ou N. O NH₃ é a única opção que atende a esse critério.', 'fácil', 0],
[44, 'SENAI 2023', 'Os metais são bons condutores de eletricidade e calor. Essa propriedade deve-se:', 'Ao arranjo cristalino iônico rígido.', 'À mobilidade dos elétrons livres (mar de elétrons) na estrutura metálica.', 'Às forças de dispersão de London intensas.', 'À formação de ligações covalentes dativas.', 'Ao elevado peso atômico dos metais.', 'b', 'A teoria do mar de elétrons descreve cátions metálicos imersos em uma nuvem de elétrons deslocalizados, que têm alta mobilidade e conduzem eletricidade.', 'fácil', 0],
[44, 'IF-SP 2024', 'Compare a temperatura de ebulição da água (H₂O) e do sulfeto de hidrogênio (H₂S). Por que a da água é muito maior?', 'Porque a massa molar da água é maior.', 'Porque a água é apolar.', 'Porque a água forma ligações de hidrogênio, que são mais fortes que as interações dipolo-dipolo do H₂S.', 'Porque a água possui geometria linear.', 'Porque a molécula de H₂S é iônica.', 'c', 'O oxigênio é muito mais eletronegativo, permitindo que a água forme ligações de hidrogênio fortes, elevando o ponto de ebulição. O H₂S forma apenas interações dipolo-dipolo, que são mais fracas.', 'médio', 1],

// [45] Radioatividade e Decaimento
[45, 'UFPR 2023', 'Um isótopo radioativo X emite uma partícula alfa e se transforma no isótopo Y. Em relação a X, o elemento Y possui:', 'O mesmo número atômico e número de massa 4 unidades menor.', 'Número atômico 2 unidades menor e número de massa 4 unidades menor.', 'Número atômico 1 unidade maior e mesmo número de massa.', 'O mesmo número atômico e mesmo número de massa.', 'Número atômico 2 unidades maior e número de massa 2 unidades menor.', 'b', 'A partícula alfa é análoga ao núcleo de hélio (₂⁴α). Sua emissão reduz o número atômico (Z) em 2 e o número de massa (A) em 4.', 'fácil', 0],
[45, 'UFMG 2024', 'A meia-vida do Césio-137 é de 30 anos. Se tivermos uma amostra inicial de 80 g, qual será a massa restante após 90 anos?', '10 g', '20 g', '40 g', '30 g', '5 g', 'a', '90 anos equivalem a 3 meias-vidas (90/30). A massa decai pela metade a cada meia-vida: 80g → 40g → 20g → 10g.', 'médio', 0],
[45, 'UERJ 2023', 'A emissão de uma partícula beta negativa (β⁻) por um núcleo radioativo resulta em:', 'Aumento do número atômico em uma unidade.', 'Diminuição do número de massa em uma unidade.', 'Diminuição do número atômico em uma unidade.', 'Emissão de dois prótons e dois nêutrons.', 'Nenhuma alteração no núcleo.', 'a', 'A partícula beta é um elétron originado da conversão de um nêutron em um próton (que fica no núcleo). Assim, Z aumenta em 1 e A permanece constante.', 'médio', 1],

// [46] Geometria Molecular e Polaridade
[46, 'UFRGS 2024', 'Qual é a geometria molecular da molécula de dióxido de carbono (CO₂)?', 'Angular', 'Trigonal plana', 'Linear', 'Piramidal', 'Tetraédrica', 'c', 'O carbono no CO₂ (O=C=O) não possui pares de elétrons livres, formando um ângulo de 180° entre as ligações duplas, caracterizando uma geometria linear.', 'fácil', 0],
[46, 'UEL 2023', 'Considerando a molécula de trifluoreto de boro (BF₃), sua geometria molecular e polaridade são, respectivamente:', 'Piramidal e polar', 'Trigonal plana e apolar', 'Trigonal plana e polar', 'Tetraédrica e apolar', 'Angular e polar', 'b', 'O boro faz 3 ligações com flúor e não tem pares livres. Geometria trigonal plana. Os momentos de dipolo se anulam mutuamente, tornando a molécula apolar.', 'médio', 0],
[46, 'UEM 2024', 'O dióxido de enxofre (SO₂) e o trióxido de enxofre (SO₃) possuem, respectivamente, quais geometrias moleculares?', 'Linear e Trigonal plana.', 'Angular e Trigonal plana.', 'Linear e Piramidal.', 'Angular e Piramidal.', 'Trigonal plana e Tetraédrica.', 'b', 'No SO₂, o S possui um par de elétrons livre, repelindo as ligações, resultando em geometria angular. No SO₃, o S faz três ligações e não tem pares livres, logo é trigonal plana.', 'difícil', 1],

// [47] Concentração de Soluções e Molaridade
[47, 'MACKENZIE 2023', 'Uma solução foi preparada dissolvendo-se 20 g de NaOH em água suficiente para produzir 500 mL de solução. Qual a concentração em mol/L? (Massa Molar NaOH = 40 g/mol)', '0,5 mol/L', '1,0 mol/L', '2,0 mol/L', '0,2 mol/L', '4,0 mol/L', 'b', 'Mols de NaOH = m/MM = 20g / 40g/mol = 0,5 mol. O volume é 0,5 L. A molaridade (M) = n/V = 0,5 mol / 0,5 L = 1,0 mol/L.', 'fácil', 0],
[47, 'PUC-MG 2024', 'Um volume de 250 mL de solução aquosa contém 14,9 g de cloreto de potássio (KCl). A concentração dessa solução em g/L é:', '29,8 g/L', '59,6 g/L', '74,5 g/L', '14,9 g/L', '100 g/L', 'b', 'C = m/V(L). C = 14,9 g / 0,250 L = 14,9 / (1/4) = 14,9 * 4 = 59,6 g/L.', 'fácil', 0],
[47, 'ITA 2023', 'Qual a fração molar do soluto em uma solução preparada com 18 g de glicose (C₆H₁₂O₆, M=180 g/mol) e 90 g de água (H₂O, M=18 g/mol)?', '0,0196', '0,02', '0,166', '0,2', '0,05', 'a', 'Mols de glicose (n1) = 18/180 = 0,1 mol. Mols de água (n2) = 90/18 = 5 mol. Fração molar do soluto (X1) = n1 / (n1+n2) = 0,1 / 5,1 ≈ 0,0196.', 'difícil', 1],

// [48] Titulação e Diluição de Soluções
[48, 'FATEC 2024', 'Ao adicionar 300 mL de água a 200 mL de uma solução 0,5 mol/L de HCl, a concentração final da solução será:', '0,1 mol/L', '0,2 mol/L', '0,3 mol/L', '0,15 mol/L', '0,25 mol/L', 'b', 'C1V1 = C2V2. 0,5 * 200 = C2 * (200+300). 100 = C2 * 500. C2 = 100/500 = 0,2 mol/L.', 'médio', 0],
[48, 'SENAI 2023', 'Para neutralizar 25 mL de solução de NaOH de concentração desconhecida, foram necessários 20 mL de solução de H₂SO₄ 0,1 mol/L. Qual a concentração em mol/L da base? A reação é: 2 NaOH + H₂SO₄ → Na₂SO₄ + 2 H₂O', '0,16 mol/L', '0,08 mol/L', '0,20 mol/L', '0,32 mol/L', '0,10 mol/L', 'a', 'n(H2SO4) = M*V = 0,1 * 0,020 = 0,002 mol. Pela estequiometria, n(NaOH) = 2 * n(H2SO4) = 0,004 mol. M(NaOH) = 0,004 / 0,025 = 0,16 mol/L.', 'médio', 0],
[48, 'IF-SP 2024', 'Deseja-se preparar 500 mL de solução de H₂SO₄ 0,1 mol/L a partir de uma solução estoque 2,0 mol/L. O volume de solução estoque necessário é:', '25 mL', '50 mL', '100 mL', '12,5 mL', '20 mL', 'a', 'C1V1 = C2V2. 2,0 * V1 = 0,1 * 500. 2,0 * V1 = 50. V1 = 25 mL.', 'fácil', 1],

// [49] Cálculo Estequiométrico e Rendimento
[49, 'UFPR 2023', 'Na combustão de 16 g de metano (CH₄, M=16 g/mol), qual a massa de água formada, sabendo que o rendimento é 100%? (H₂O: M=18 g/mol). Reação: CH₄ + 2 O₂ → CO₂ + 2 H₂O', '18 g', '36 g', '72 g', '54 g', '9 g', 'b', '16 g de CH4 = 1 mol. A equação indica que 1 mol de CH4 produz 2 mols de H2O. Massa de 2 mols de H2O = 2 * 18g/mol = 36 g.', 'fácil', 0],
[49, 'UFMG 2024', 'Quantos litros de gás carbônico (nas CNTP) são gerados pela decomposição térmica de 100 g de CaCO₃ (M=100 g/mol)? Volume molar = 22,4 L/mol. CaCO₃ → CaO + CO₂', '22,4 L', '44,8 L', '11,2 L', '5,6 L', '2,24 L', 'a', '100 g de CaCO3 corresponde a 1 mol. A reação produz 1 mol de CO2. Como 1 mol ocupa 22,4 L nas CNTP, o volume é 22,4 L.', 'fácil', 0],
[49, 'UERJ 2023', 'Seja a reação N₂ + 3 H₂ → 2 NH₃. Reagindo-se 14 g de N₂ (M=28 g/mol) e 6 g de H₂ (M=2 g/mol), qual a massa de amônia (M=17 g/mol) produzida, sabendo que o rendimento é 80%?', '17,0 g', '13,6 g', '34,0 g', '27,2 g', '20,4 g', 'b', 'N2 (14g) = 0,5 mol. H2 (6g) = 3 mol. O N2 é o limitante (1 mol N2 precisa de 3 mol H2, logo 0,5 mol N2 precisa de 1,5 mol H2). Produção teórica de NH3 = 2 * 0,5 = 1 mol = 17 g. Com 80% de rendimento: 0,8 * 17 = 13,6 g.', 'difícil', 1],

// [50] Gases Ideais e Equação de Clapeyron
[50, 'UFRGS 2024', 'Qual é o volume ocupado por 2 mols de um gás ideal a uma pressão de 1 atm e temperatura de 300 K? (Dado: R = 0,082 atm·L/mol·K)', '24,6 L', '49,2 L', '12,3 L', '36,9 L', '61,5 L', 'b', 'P.V = n.R.T. 1 * V = 2 * 0,082 * 300. V = 2 * 24,6 = 49,2 L.', 'fácil', 0],
[50, 'UEL 2023', 'Um pneu contém ar a 2,0 atm e 27 °C. Após rodar muito, a temperatura sobe para 87 °C. Considerando o volume constante, a nova pressão é:', '2,4 atm', '6,4 atm', '4,0 atm', '3,0 atm', '2,8 atm', 'a', 'T1 = 300K, T2 = 360K. P1/T1 = P2/T2 (transformação isovolumétrica). 2,0 / 300 = P2 / 360. P2 = (2 * 360) / 300 = 720 / 300 = 2,4 atm.', 'médio', 0],
[50, 'UEM 2024', 'A densidade de um gás é 1,25 g/L a 0 °C e 1 atm (CNTP). Qual a massa molar desse gás? (Dado Vm = 22,4 L/mol)', '14 g/mol', '16 g/mol', '28 g/mol', '32 g/mol', '44 g/mol', 'c', 'A massa molar M = d * Vm. M = 1,25 g/L * 22,4 L/mol = 28 g/mol. O gás pode ser, por exemplo, N2 ou CO.', 'médio', 1],

// [51] Termoquímica e Entalpia
[51, 'MACKENZIE 2023', 'Se a combustão completa do etanol (C₂H₆O) tem ΔH = -1368 kJ/mol, a queima de 2 mols de etanol irá:', 'Absorver 1368 kJ.', 'Liberar 1368 kJ.', 'Absorver 2736 kJ.', 'Liberar 2736 kJ.', 'Liberar 684 kJ.', 'd', 'Como ΔH é negativo, a reação libera energia (exotérmica). Para 2 mols, a energia liberada será o dobro: 2 * 1368 = 2736 kJ.', 'fácil', 0],
[51, 'PUC-MG 2024', 'Dadas as entalpias de formação: CO₂(g) = -394 kJ/mol; H₂O(l) = -286 kJ/mol; CH₄(g) = -75 kJ/mol. Qual o ΔH da combustão completa do metano? CH₄ + 2 O₂ → CO₂ + 2 H₂O', '-891 kJ/mol', '-605 kJ/mol', '-966 kJ/mol', '-816 kJ/mol', '-740 kJ/mol', 'a', 'ΔH = ΣHprodutos - ΣHreagentes. ΔH = [1*(-394) + 2*(-286)] - [1*(-75) + 0] = [-394 - 572] + 75 = -966 + 75 = -891 kJ/mol.', 'médio', 0],
[51, 'ITA 2023', 'A lei de Hess afirma que a variação de entalpia de uma reação química:', 'Depende apenas das energias de ligação dos reagentes.', 'Depende das etapas intermediárias pelas quais a reação passa.', 'Depende apenas dos estados inicial e final, independentemente do caminho.', 'É sempre negativa para reações espontâneas.', 'Aumenta com o aumento da temperatura do sistema.', 'c', 'A lei de Hess é uma aplicação do princípio da conservação da energia (função de estado). O ΔH de uma reação só depende do estado inicial (reagentes) e final (produtos).', 'fácil', 1],

// [52] Cinética Química e Velocidade de Reação
[52, 'FATEC 2024', 'O uso de catalisadores em reações químicas tem a finalidade de:', 'Aumentar a energia de ativação e o rendimento.', 'Diminuir o ΔH da reação.', 'Aumentar a velocidade da reação, diminuindo a energia de ativação.', 'Aumentar a quantidade de produtos formados.', 'Tornar exotérmica uma reação endotérmica.', 'c', 'O catalisador atua criando um caminho alternativo de menor energia de ativação, o que aumenta a velocidade da reação sem ser consumido ou alterar o ΔH e o equilíbrio.', 'fácil', 0],
[52, 'SENAI 2023', 'Para a reação elementar A + 2 B → C, a lei de velocidade é dada por:', 'v = k[A][B]', 'v = k[A][B]²', 'v = k[A]²[B]', 'v = k[C]', 'v = k[A][C]', 'b', 'Por ser uma reação elementar (ocorre em uma única etapa), as ordens parciais coincidem com os coeficientes estequiométricos da equação balanceada. Logo, v = k[A]^1[B]^2.', 'médio', 0],
[52, 'IF-SP 2024', 'A velocidade de uma reação aumenta com a elevação da temperatura porque:', 'Diminui a energia de ativação.', 'Aumenta o choque das moléculas contra as paredes do recipiente.', 'Aumenta a energia cinética média das moléculas e o número de colisões efetivas.', 'Diminui a concentração dos reagentes.', 'O catalisador fica mais ativo.', 'c', 'O aumento da temperatura eleva a energia cinética média das partículas, aumentando a frequência de colisões e, principalmente, a fração de moléculas que possuem energia superior à energia de ativação (colisões efetivas).', 'médio', 1],

// [53] Equilíbrio Químico e Le Chatelier
[53, 'UFPR 2023', 'Dado o equilíbrio: N₂(g) + 3 H₂(g) ⇌ 2 NH₃(g) (ΔH < 0). Para aumentar o rendimento na produção de amônia, deve-se:', 'Aumentar a temperatura e diminuir a pressão.', 'Aumentar a temperatura e aumentar a pressão.', 'Diminuir a temperatura e diminuir a pressão.', 'Diminuir a temperatura e aumentar a pressão.', 'Adicionar um catalisador.', 'd', 'Como a reação direta é exotérmica (ΔH < 0), diminuir a temperatura desloca para os produtos. A reação contrai volume (4 mols gasosos para 2 mols), então o aumento de pressão desloca para os produtos.', 'médio', 0],
[53, 'UFMG 2024', 'Em um recipiente de 1 L em equilíbrio, temos 2 mols de SO₂, 1 mol de O₂ e 4 mols de SO₃. A reação é 2 SO₂(g) + O₂(g) ⇌ 2 SO₃(g). O valor da constante Kc é:', '1', '2', '4', '8', '16', 'c', 'Kc = [SO3]² / ([SO2]² * [O2]). Como o volume é 1 L, a concentração = mols. Kc = (4)² / ((2)² * 1) = 16 / (4 * 1) = 4.', 'médio', 0],
[53, 'UERJ 2023', 'O Princípio de Le Chatelier prevê que a adição de um gás inerte a um sistema em equilíbrio, mantendo-se o volume constante:', 'Desloca o equilíbrio para o lado com mais mols.', 'Desloca o equilíbrio para o lado com menos mols.', 'Não altera a posição de equilíbrio.', 'Altera a constante de equilíbrio Kc.', 'Aumenta a energia de ativação.', 'c', 'Como o volume é constante, a adição de um gás inerte não altera as pressões parciais nem as concentrações dos gases reagentes/produtos, portanto o equilíbrio não é deslocado.', 'difícil', 1],

// [54] pH, pOH e Hidrólise Salina
[54, 'UFRGS 2024', 'Qual é o pH de uma solução aquosa de HCl 0,001 mol/L? (Considere α = 100%)', '1', '2', '3', '4', '11', 'c', 'HCl é ácido forte, se ioniza totalmente. [H+] = 0,001 mol/L = 10⁻³ mol/L. pH = -log[H+] = -log(10⁻³) = 3.', 'fácil', 0],
[54, 'UEL 2023', 'Um suco de limão possui [H+] = 10⁻² mol/L. Qual o valor do pOH desse suco a 25°C?', '2', '12', '7', '10', '14', 'b', 'O pH = -log(10⁻²) = 2. A 25°C, pH + pOH = 14. Logo, pOH = 14 - 2 = 12.', 'fácil', 0],
[54, 'UEM 2024', 'A dissolução do acetato de sódio (CH₃COONa) em água gera uma solução:', 'Ácida, devido à hidrólise do íon sódio.', 'Básica, devido à hidrólise do íon acetato.', 'Neutra, pois não ocorre hidrólise.', 'Ácida, devido à ionização completa do sal.', 'Básica, pela hidrólise de ambos os íons.', 'b', 'CH3COONa deriva de base forte (NaOH) e ácido fraco (CH3COOH). O íon Na+ não sofre hidrólise, mas o acetato sofre: CH3COO- + H2O ⇌ CH3COOH + OH-. A produção de OH- deixa a solução básica.', 'médio', 1],

// [55] Eletroquímica: Pilhas e Eletrólise
[55, 'MACKENZIE 2023', 'Na pilha de Daniell, os elétrons fluem do ânodo para o cátodo pelo circuito externo. O ânodo é o polo onde ocorre a:', 'Redução e é o polo positivo.', 'Oxidação e é o polo negativo.', 'Redução e é o polo negativo.', 'Oxidação e é o polo positivo.', 'Hidrólise e é o polo neutro.', 'b', 'Na pilha, o ânodo (zinco, por exemplo) sofre oxidação (perde elétrons), tornando-se a fonte de elétrons, logo, o polo negativo.', 'fácil', 0],
[55, 'PUC-MG 2024', 'Dado: Cu²⁺ + 2e⁻ ⇌ Cu (E° = +0,34V); Zn²⁺ + 2e⁻ ⇌ Zn (E° = -0,76V). Qual a ddp (potencial padrão) dessa pilha?', '+1,10 V', '-1,10 V', '+0,42 V', '-0,42 V', '+2,20 V', 'a', 'O maior E° é o cátodo (Cu) que reduz; o menor é o ânodo (Zn) que oxida. ddp = E°(cátodo) - E°(ânodo) = 0,34 - (-0,76) = 0,34 + 0,76 = +1,10 V.', 'médio', 0],
[55, 'ITA 2023', 'Na eletrólise ígnea do cloreto de sódio (NaCl), quais são os produtos formados no cátodo e no ânodo, respectivamente?', 'Na metálico e gás cloro.', 'Gás hidrogênio e gás cloro.', 'Gás hidrogênio e oxigênio.', 'Na metálico e gás oxigênio.', 'Íons sódio e íons cloreto.', 'a', 'Na eletrólise ígnea (sem água), os únicos íons são Na+ e Cl-. O cátodo (-) atrai os cátions Na+, onde são reduzidos a Na metálico. O ânodo (+) atrai ânions Cl-, que oxidam a gás Cl2.', 'difícil', 1],

// [56] Química Orgânica: Cadeias Carbônicas
[56, 'FATEC 2024', 'O composto hex-2-eno é um hidrocarboneto que apresenta qual tipo de cadeia carbônica?', 'Aberta, ramificada e saturada.', 'Fechada, normal e insaturada.', 'Aberta, normal e insaturada.', 'Aberta, ramificada e insaturada.', 'Fechada, aromática e insaturada.', 'c', 'Cadeia com 6 carbonos (hex), sem ramificações (normal), com uma ligação dupla (eno, logo insaturada) e extremidades livres (aberta ou acíclica).', 'fácil', 0],
[56, 'SENAI 2023', 'Quantos carbonos primários existem na molécula de isobutano (metilpropano)?', '1', '2', '3', '4', '0', 'c', 'O metilpropano tem a cadeia principal propano (3 carbonos) com um grupo metil no carbono central. O carbono central é terciário e os três CH3 periféricos são primários.', 'médio', 0],
[56, 'IF-SP 2024', 'O naftaleno, substância presente na naftalina, é classificado como um composto aromático:', 'Mononuclear.', 'Polinuclear de núcleos isolados.', 'Polinuclear de núcleos condensados.', 'Acíclico saturado.', 'Alicíclico insaturado.', 'c', 'O naftaleno (C10H8) é formado por dois anéis benzênicos fundidos, o que caracteriza núcleos condensados em compostos aromáticos polinucleares.', 'fácil', 1],

// [57] Funções Orgânicas Oxigenadas
[57, 'UFPR 2023', 'Qual é a função orgânica caracterizada pelo grupo funcional -OH ligado diretamente a um anel aromático?', 'Álcool', 'Fenol', 'Enol', 'Éter', 'Aldeído', 'b', 'Quando a hidroxila (-OH) está ligada diretamente a um carbono do anel aromático (benzeno, por exemplo), a função é o fenol.', 'fácil', 0],
[57, 'UFMG 2024', 'O composto propanona (acetona) pertence a qual função orgânica e possui quantos átomos de carbono?', 'Aldeído, 3 carbonos.', 'Cetona, 3 carbonos.', 'Álcool, 4 carbonos.', 'Éster, 3 carbonos.', 'Cetona, 4 carbonos.', 'b', 'A terminação -ona indica uma cetona (C=O entre carbonos). O prefixo prop- indica 3 átomos de carbono na cadeia principal.', 'fácil', 0],
[57, 'UERJ 2023', 'O vinagre contém um composto orgânico responsável pelo seu sabor azedo, que é o ácido etanoico (ácido acético). A qual função ele pertence e qual a sua fórmula estrutural?', 'Aldeído, CH3CHO', 'Ácido carboxílico, HCOOH', 'Ácido carboxílico, CH3COOH', 'Cetona, CH3COCH3', 'Éster, CH3COOCH3', 'c', 'O ácido etanoico possui a função ácido carboxílico, caracterizada pela carboxila (-COOH). O prefixo et- indica 2 carbonos, sendo um do grupo funcional: CH3COOH.', 'médio', 1],

// [58] Funções Orgânicas Nitrogenadas
[58, 'UFRGS 2024', 'As proteínas são polímeros naturais formados pela união de aminoácidos através de ligações peptídicas. Uma ligação peptídica é, do ponto de vista funcional, uma:', 'Amina primária.', 'Amina secundária.', 'Amida.', 'Nitrila.', 'Imina.', 'c', 'A ligação peptídica resulta da reação entre o grupo carboxila de um aminoácido e o grupo amina de outro, formando um grupo funcional amida (C=O ligado a NH).', 'fácil', 0],
[58, 'UEL 2023', 'Qual a classificação da amina dimetilamina (CH₃-NH-CH₃)?', 'Amina primária.', 'Amina secundária.', 'Amina terciária.', 'Amina quaternária.', 'Amina aromática.', 'b', 'O nitrogênio está ligado a dois átomos de carbono (dois grupos metil), portanto, trata-se de uma amina secundária.', 'fácil', 0],
[58, 'UEM 2024', 'Os compostos com o grupo funcional -C≡N são classificados como:', 'Isonitrilas.', 'Amidas.', 'Nitrilas.', 'Aminas.', 'Nitrocompostos.', 'c', 'A presença do grupo ciano (-C≡N) ligado a uma cadeia carbônica caracteriza a função nitrila.', 'médio', 1],

// [59] Isomeria Plana e Espacial
[59, 'MACKENZIE 2023', 'O etanol (álcool etílico) e o metoximetano (éter dimetílico) possuem a mesma fórmula molecular (C₂H₆O). Eles são isômeros de:', 'Cadeia', 'Posição', 'Função', 'Compensação (Metameria)', 'Tautomeria', 'c', 'O etanol é um álcool e o metoximetano é um éter. Como possuem grupos funcionais diferentes para a mesma fórmula molecular, são isômeros de função.', 'fácil', 0],
[59, 'PUC-MG 2024', 'Qual das moléculas a seguir pode apresentar isomeria geométrica (cis-trans)?', 'Propeno', 'But-1-eno', 'But-2-eno', 'Eteno', '2-metilpropeno', 'c', 'Para ter isomeria cis-trans, os carbonos da dupla devem estar ligados a grupos diferentes entre si. No but-2-eno (CH3-CH=CH-CH3), ambos os carbonos da dupla estão ligados a um H e a um CH3, permitindo os isômeros cis e trans.', 'médio', 0],
[59, 'ITA 2023', 'Um composto orgânico possui 2 carbonos assimétricos (quirais) diferentes em sua estrutura. Quantos isômeros ópticos ativos esse composto apresentará?', '2', '3', '4', '8', '16', 'c', 'O número de estereoisômeros opticamente ativos (isômeros espaciais) é dado pela regra 2^n, onde n é o número de carbonos quirais. 2^2 = 4 isômeros ativos.', 'difícil', 1],

// [60] Reações Orgânicas e Polímeros
[60, 'FATEC 2024', 'A reação entre um ácido carboxílico e um álcool, em meio ácido e sob aquecimento, produzindo éster e água, é chamada de:', 'Saponificação', 'Esterificação', 'Hidrólise', 'Oxidação', 'Hidrogenação', 'b', 'A reação clássica de Fischer, na qual ácido carboxílico e álcool formam éster e água, é denominada reação de esterificação.', 'fácil', 0],
[60, 'SENAI 2023', 'O polietileno, muito utilizado em sacolas plásticas, é formado pela união de milhares de moléculas de eteno (etileno). Qual é o tipo de reação de polimerização envolvida?', 'Polimerização por condensação.', 'Polimerização por adição.', 'Copolimerização.', 'Vulcanização.', 'Transesterificação.', 'b', 'O eteno tem dupla ligação que se quebra para formar ligações simples com outros monômeros de eteno. Isso caracteriza uma polimerização por adição.', 'médio', 0],
[60, 'IF-SP 2024', 'A hidrogenação catalítica do propeno (CH₂=CH-CH₃) produz qual substância?', 'Propino', 'Ciclopropano', 'Propano', 'Metil-propano', 'Propan-2-ol', 'c', 'A hidrogenação (adição de H2) quebra a ligação pi do propeno. Cada carbono da insaturação recebe um hidrogênio, formando o propano, um alcano saturado.', 'médio', 1],

// [135] Tabela Periódica e Propriedades
[135, 'UFPR 2023', 'Qual dos elementos a seguir é classificado como halogênio?', 'Oxigênio (O)', 'Enxofre (S)', 'Bromo (Br)', 'Criptônio (Kr)', 'Cálcio (Ca)', 'c', 'Os halogênios pertencem ao grupo 17 (VIIA) da tabela periódica, que inclui F, Cl, Br, I e At.', 'fácil', 0],
[135, 'UFMG 2024', 'A afinidade eletrônica é a energia liberada quando um átomo neutro e isolado ganha um elétron. Em um mesmo período, ela geralmente:', 'Aumenta da esquerda para a direita.', 'Diminui da esquerda para a direita.', 'Permanece constante.', 'Aumenta de cima para baixo.', 'Diminui de baixo para cima.', 'a', 'No mesmo período, da esquerda para a direita, o raio atômico diminui e a carga nuclear efetiva aumenta. Isso faz com que a atração pelo elétron recebido seja maior, aumentando a afinidade eletrônica.', 'médio', 0],
[135, 'UERJ 2023', 'O íon O²⁻ e o íon Mg²⁺ são isoeletrônicos. Qual deles apresenta o menor raio iônico?', 'O²⁻, pois tem mais prótons.', 'Mg²⁺, pois tem maior número atômico (Z).', 'O²⁻, pois ganhou elétrons.', 'Mg²⁺, pois pertence ao grupo 2.', 'Eles possuem o mesmo raio.', 'b', 'Ambos têm 10 elétrons. O Mg²⁺ tem 12 prótons atraindo esses elétrons, enquanto o O²⁻ tem 8 prótons. Maior atração nuclear encolhe mais a nuvem, logo Mg²⁺ tem menor raio.', 'difícil', 1],

// [136] Geometria Molecular e Polaridade
[136, 'UFRGS 2024', 'A molécula de amônia (NH₃) tem geometria piramidal. Isso ocorre porque o nitrogênio:', 'Possui dois pares de elétrons livres.', 'Não possui par de elétrons livres.', 'Possui um par de elétrons livres que repulsa as ligações.', 'Faz 4 ligações covalentes simples.', 'Tem hibridização sp.', 'c', 'O N tem 5 elétrons na valência, usa 3 para ligar com os H e sobra 1 par livre. A repulsão (Teoria VSEPR) desse par empurra as ligações para baixo, formando a pirâmide.', 'fácil', 0],
[136, 'UEL 2023', 'A molécula CCl₄ (tetracloreto de carbono) apresenta:', 'Geometria tetraédrica e é polar.', 'Geometria quadrada plana e é apolar.', 'Geometria tetraédrica e é apolar.', 'Geometria piramidal e é apolar.', 'Geometria tetraédrica e alta solubilidade em água.', 'c', 'O carbono forma 4 ligações idênticas em geometria tetraédrica regular. Os quatro momentos de dipolo individuais (C-Cl) se anulam, tornando a molécula globalmente apolar.', 'médio', 0],
[136, 'UEM 2024', 'Considerando as moléculas H₂O, BeH₂ e BCl₃, as geometrias são, respectivamente:', 'Angular, linear, trigonal plana.', 'Angular, angular, piramidal.', 'Linear, linear, trigonal plana.', 'Linear, angular, piramidal.', 'Angular, linear, piramidal.', 'a', 'H2O tem 2 pares livres no oxigênio (angular). BeH2 não tem pares livres no Be central (linear). BCl3 não tem pares livres no B (trigonal plana).', 'difícil', 1],

// [137] Concentração de Soluções e Molaridade
[137, 'MACKENZIE 2023', 'Uma solução foi preparada dissolvendo-se 5,85 g de NaCl em água suficiente para 200 mL de solução. Qual a concentração em mol/L? (Massa molar NaCl = 58,5 g/mol)', '0,1 mol/L', '0,5 mol/L', '1,0 mol/L', '2,0 mol/L', '0,2 mol/L', 'b', 'n = 5,85 / 58,5 = 0,1 mol. V = 200 mL = 0,2 L. M = n/V = 0,1 / 0,2 = 0,5 mol/L.', 'fácil', 0],
[137, 'PUC-MG 2024', 'Qual o título em massa (ou porcentagem em massa) de uma solução preparada com 20 g de soluto e 80 g de solvente?', '25%', '20%', '80%', '10%', '30%', 'b', 'A massa total da solução é 20 + 80 = 100 g. O título é a massa do soluto sobre a total: 20/100 = 0,2, o que equivale a 20%.', 'fácil', 0],
[137, 'ITA 2023', 'Uma solução aquosa de ácido nítrico (HNO₃) tem densidade de 1,2 g/mL e concentração em massa (título) de 31,5%. Qual a molaridade da solução? (Massa molar HNO₃ = 63 g/mol)', '12,0 mol/L', '3,15 mol/L', '6,0 mol/L', '4,5 mol/L', '9,0 mol/L', 'c', '1 L = 1000 mL. Massa de 1 L de solução = 1000 * 1,2 = 1200 g. Massa de soluto em 1 L = 0,315 * 1200 = 378 g. Molaridade = m / (M * V) = 378 / (63 * 1) = 6,0 mol/L.', 'difícil', 1],

// [138] Cálculo Estequiométrico
[138, 'FATEC 2024', 'Quantos gramas de oxigênio (O₂, M=32 g/mol) são consumidos para queimar completamente 24 g de carbono puro (C, M=12 g/mol)? (Reação: C + O₂ → CO₂)', '32 g', '64 g', '16 g', '48 g', '96 g', 'b', '24 g de C = 2 mols. A proporção é 1:1, logo precisamos de 2 mols de O2. Massa = 2 * 32g/mol = 64 g.', 'fácil', 0],
[138, 'SENAI 2023', 'Seja a reação: 2 H₂ + O₂ → 2 H₂O. Ao reagir 4 g de hidrogênio (M=2 g/mol) com 16 g de oxigênio (M=32 g/mol), a massa de água (M=18 g/mol) formada será de:', '36 g', '18 g', '54 g', '20 g', '24 g', 'b', 'H2 (4g) = 2 mol. O2 (16g) = 0,5 mol. A proporção requer 2 mols de H2 para 1 mol de O2. Como só temos 0,5 mol de O2, o O2 é o limitante. Produção de H2O = 2 * 0,5 = 1 mol = 18 g.', 'médio', 0],
[138, 'IF-SP 2024', 'Um minério contém 80% de pureza em Fe₂O₃ (M=160 g/mol). Na reação de redução (Fe₂O₃ + 3 CO → 2 Fe + 3 CO₂), que massa de ferro (M=56 g/mol) será obtida a partir de 200 g do minério?', '112 g', '140 g', '89,6 g', '56 g', '224 g', 'a', 'Massa de Fe2O3 puro = 0,8 * 200 = 160 g = 1 mol. 1 mol de Fe2O3 produz 2 mols de Fe. Massa de Fe = 2 * 56 = 112 g.', 'difícil', 1],

// [139] Termoquímica e Entalpia
[139, 'UFPR 2023', 'Quando a água líquida evapora, ela sofre uma transformação de estado físico. O processo de vaporização da água é:', 'Exotérmico e ΔH < 0.', 'Endotérmico e ΔH > 0.', 'Isotérmico e ΔH = 0.', 'Exotérmico e ΔH > 0.', 'Endotérmico e ΔH < 0.', 'b', 'Para passar do estado líquido para o gasoso, a água precisa absorver calor (energia) do ambiente. Portanto, o processo é endotérmico (ΔH positivo).', 'fácil', 0],
[139, 'UFMG 2024', 'Considerando os calores de formação do CO(g) (-110,5 kJ/mol) e do CO₂(g) (-393,5 kJ/mol), o calor de combustão de 1 mol de CO (CO + 1/2 O₂ → CO₂) é:', '-283,0 kJ', '+283,0 kJ', '-504,0 kJ', '+504,0 kJ', '-110,5 kJ', 'a', 'ΔH = H(produtos) - H(reagentes). ΔH = -393,5 - (-110,5 + 0) = -393,5 + 110,5 = -283,0 kJ.', 'médio', 0],
[139, 'UERJ 2023', 'As reações de neutralização entre ácidos e bases fortes liberam aproximadamente 57,7 kJ por mol de água formada. Isso indica que a reação é:', 'Endotérmica e a temperatura do sistema cai.', 'Exotérmica e a temperatura do sistema cai.', 'Exotérmica e a temperatura do sistema aumenta.', 'Atermica.', 'Endotérmica e a temperatura do sistema aumenta.', 'c', 'Reações que liberam energia térmica (calor) para o ambiente são exotérmicas (ΔH < 0), o que ocasiona o aquecimento do sistema em que ocorrem.', 'fácil', 1],

// [140] Eletroquímica: Pilhas e Eletrólise
[140, 'UFRGS 2024', 'Uma bateria de chumbo-ácido descarrega fornecendo energia elétrica. Durante esse processo de descarga, ela atua como:', 'Uma célula eletrolítica.', 'Uma célula galvânica.', 'Um capacitor.', 'Um resistor puro.', 'Um diodo.', 'b', 'Durante a descarga, a bateria converte energia química de uma reação espontânea em energia elétrica, atuando como uma pilha ou célula galvânica (volumétrica).', 'fácil', 0],
[140, 'UEL 2023', 'Ao mergulhar uma lâmina de zinco numa solução de sulfato de cobre(II), observa-se a deposição de cobre metálico na lâmina. Isso ocorre porque:', 'O zinco se reduz e o cobre se oxida.', 'O zinco é um agente oxidante mais forte que o Cu²⁺.', 'O cobre tem maior potencial de redução que o zinco.', 'Não há reação química, apenas mistura física.', 'O íon sulfato reage com o zinco.', 'c', 'O cobre tem um potencial de redução (+0,34 V) superior ao do zinco (-0,76 V). O íon Cu²⁺ em solução rouba elétrons da lâmina de Zn, ocorrendo uma reação espontânea de óxido-redução.', 'médio', 0],
[140, 'UEM 2024', 'Na eletrólise aquosa do sulfato de sódio (Na₂SO₄), os gases liberados nos eletrodos são:', 'O₂ no cátodo e H₂ no ânodo.', 'H₂ no cátodo e O₂ no ânodo.', 'Na no cátodo e SO₂ no ânodo.', 'H₂ no cátodo e SO₃ no ânodo.', 'O₂ no cátodo e SO₂ no ânodo.', 'b', 'O Na+ e o SO4(2-) perdem na disputa de descarga na água. Quem reduz no cátodo é o H2O (ou H+), gerando gás H2. Quem oxida no ânodo é a água (ou OH-), gerando gás O2.', 'difícil', 1],

// [141] Química Orgânica: Cadeias Carbônicas
[141, 'MACKENZIE 2023', 'Qual é a fórmula molecular do ciclohexano, um hidrocarboneto cíclico saturado de 6 carbonos?', 'C₆H₁₀', 'C₆H₁₂', 'C₆H₁₄', 'C₆H₆', 'C₆H₈', 'b', 'Hidrocarbonetos cíclicos saturados (ciclanos) têm fórmula geral CnH2n. Para n=6, C6H12. Todos os carbonos formam duas ligações C-C no anel e duas ligações com hidrogênio.', 'fácil', 0],
[141, 'PUC-MG 2024', 'Sobre o composto metilbenzeno (tolueno), pode-se afirmar que ele possui uma cadeia carbônica:', 'Acíclica e heterogênea.', 'Cíclica aromática e ramificada.', 'Alicíclica insaturada e normal.', 'Aromática e saturada.', 'Aberta, ramificada e insaturada.', 'b', 'O anel benzênico torna a cadeia cíclica aromática. O grupo metil (CH3) ligado a ele atua como ramificação, logo, a cadeia é aromática e ramificada.', 'médio', 0],
[141, 'ITA 2023', 'A molécula de cubano (C₈H₈) é altamente tensionada e apresenta átomos de carbono que sofrem forte tensão angular. Qual é a hibridização esperada dos carbonos (desconsiderando a tensão angular que deforma as ligações) num sistema de quatro ligações simples?', 'sp', 'sp²', 'sp³', 'sp³d', 'sp³d²', 'c', 'Cada carbono no cubano faz quatro ligações sigma (3 com carbonos e 1 com hidrogênio). A hibridização que abriga quatro pares eletrônicos direcionados em arranjo com 4 ligações simples é a sp³.', 'difícil', 1],

// [142] Funções Orgânicas e Isomeria
[142, 'FATEC 2024', 'O composto metanoato de etila possui sabor artificial de morango e framboesa. A qual função orgânica ele pertence?', 'Éter', 'Aldeído', 'Éster', 'Ácido carboxílico', 'Cetona', 'c', 'A nomenclatura derivada da união de duas partes, com o sufixo -oato seguido do nome do radical ligado ao oxigênio (-ila), é típica dos ésteres.', 'fácil', 0],
[142, 'SENAI 2023', 'Ao oxidar um álcool primário brandamente com KMnO₄ em meio ácido, o primeiro produto formado é:', 'Um ácido carboxílico.', 'Uma cetona.', 'Um aldeído.', 'Um éter.', 'Um alceno.', 'c', 'A oxidação de álcoois primários (R-CH2-OH) produz inicialmente um aldeído (R-CHO). (Se a oxidação for energética, ele prossegue até ácido carboxílico).', 'médio', 0],
[142, 'IF-SP 2024', 'Qual o tipo de isomeria que ocorre entre a propanona (CH₃-CO-CH₃) e o propen-2-ol (CH₂=C(OH)-CH₃)?', 'Isomeria de posição.', 'Metameria.', 'Isomeria de cadeia.', 'Tautomeria.', 'Isomeria geométrica.', 'd', 'Cetona e enol em equilíbrio dinâmico caracterizam a isomeria dinâmica ou tautomeria.', 'difícil', 1],
];

$stmt = $pdo->prepare("INSERT INTO questions (lesson_id, exam_source, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation_text, difficulty, is_boss) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
$inserted = 0;
$errors = 0;
foreach ($questions as $q) {
    try { $stmt->execute($q); $inserted++; } 
    catch (Exception $e) { $errors++; echo "ERRO: " . $e->getMessage() . "\n"; }
}
echo "\nInseridas: {$inserted} | Erros: {$errors}\n";
