<?php
require_once __DIR__ . '/../config/db.php';
echo "=== Inserindo questões de Biologia ===\n\n";

$questions = [
    // Lição 61: Citologia: Organelas e Funções
    [61, 'ENEM 2023', 'A organela celular responsável pela síntese de proteínas e que pode estar associada ao retículo endoplasmático é:', 'ribossomo', 'lisossomo', 'complexo golgiense', 'mitocôndria', 'peroxissomo', 'a', 'Os ribossomos são as organelas responsáveis pela síntese proteica (tradução do mRNA). Quando associados ao RER, formam o retículo endoplasmático rugoso.', 'fácil', 0],
    [61, 'UNICAMP 2024', 'A doença de Tay-Sachs é caracterizada pela disfunção de uma organela rica em enzimas hidrolíticas, que perde a capacidade de digerir lipídios celulares. Qual é a organela afetada?', 'Retículo endoplasmático liso', 'Complexo golgiense', 'Lisossomo', 'Mitocôndria', 'Peroxissomo', 'c', 'Os lisossomos são vesículas repletas de enzimas hidrolíticas que atuam na digestão intracelular. A deficiência de certas enzimas lisossômicas leva ao acúmulo de substratos.', 'médio', 0],
    [61, 'USP (FUVEST) 2023', 'Células produtoras de hormônios esteroides, como os testículos e ovários, possuem uma abundância de qual organela citoplasmática responsável pela síntese de lipídios?', 'Retículo endoplasmático rugoso', 'Retículo endoplasmático liso', 'Complexo golgiense', 'Peroxissomos', 'Lisossomos', 'b', 'O retículo endoplasmático liso (agranular) é responsável pela síntese de lipídios, incluindo os hormônios esteroides (derivados do colesterol), além da desintoxicação celular.', 'médio', 0],
    [61, 'UNESP 2024', 'O uso de drogas que inibem o funcionamento dos microtúbulos afeta diretamente qual estrutura celular essencial para a locomoção de espermatozoides?', 'Cílios', 'Flagelos', 'Pseudópodes', 'Microvilosidades', 'Desmossomos', 'b', 'Os flagelos são estruturas longas formadas por microtúbulos (proteína tubulina) organizados em um padrão 9+2, essenciais para a locomoção de espermatozoides.', 'fácil', 0],
    [61, 'UNICAMP 2023', 'As mitocôndrias e os cloroplastos são organelas que possuem DNA próprio, ribossomos e capacidade de autoduplicação. Essa constatação fundamenta qual teoria biológica?', 'Teoria Celular', 'Teoria da Geração Espontânea', 'Teoria Endossimbiótica', 'Teoria da Evolução Química', 'Teoria Criacionista', 'c', 'A Teoria Endossimbiótica, proposta por Lynn Margulis, sugere que mitocôndrias e cloroplastos surgiram de procariontes ancestrais englobados por células eucarióticas primitivas.', 'difícil', 1],

    // Lição 62: Membrana Plasmática e Transporte Celular
    [62, 'ENEM 2023', 'A membrana plasmática é descrita pelo modelo do mosaico fluido. Neste modelo, o que compõe o "mosaico" e o que confere a "fluidez", respectivamente?', 'Proteínas inseridas na bicamada de fosfolipídios em constante movimento lateral.', 'Carboidratos na superfície e proteínas estáticas.', 'Fosfolipídios estáticos e proteínas em constante movimento.', 'Colesterol e ácido nucleico.', 'Água e celulose.', 'a', 'O modelo do mosaico fluido propõe que proteínas (mosaico) estão dispersas e inseridas em uma bicamada de fosfolipídios que possui fluidez (movimentação lateral contínua).', 'fácil', 0],
    [62, 'USP (FUVEST) 2023', 'Células vegetais murchas foram colocadas em uma solução e, após algum tempo, recuperaram a sua turgidez. A solução em que as células foram imersas era, em relação ao citoplasma celular:', 'Isotônica', 'Hipertônica', 'Hipotônica', 'Saturada', 'Plasmolítica', 'c', 'Para recuperar a turgidez, a célula precisa ganhar água por osmose. A água move-se do meio menos concentrado (hipotônico) para o mais concentrado (interior da célula).', 'médio', 0],
    [62, 'UNESP 2024', 'A bomba de sódio e potássio é fundamental para a manutenção do potencial de repouso dos neurônios. Esse tipo de transporte celular caracteriza-se por ser:', 'A favor do gradiente de concentração, sem gasto de ATP.', 'Contra o gradiente de concentração, com gasto de ATP.', 'Por difusão facilitada utilizando proteínas canais.', 'Uma forma de endocitose para macromoléculas.', 'Um transporte passivo dependente apenas da concentração iônica.', 'b', 'A bomba de sódio e potássio é um transporte ativo que move Na+ para fora e K+ para dentro, contra os respectivos gradientes de concentração, o que exige a hidrólise de ATP.', 'médio', 0],
    [62, 'UNICAMP 2024', 'Quando um leucócito engloba uma bactéria patogênica para destruí-la, ele utiliza um processo de transporte em bloco denominado:', 'Pinocitose', 'Exocitose', 'Osmose', 'Fagocitose', 'Difusão simples', 'd', 'Fagocitose é o englobamento de partículas sólidas e grandes (como bactérias) por meio da emissão de pseudópodes, formando o fagossomo para digestão intracelular.', 'fácil', 0],
    [62, 'ENEM 2022', 'O oxigênio molecular (O2) e o dióxido de carbono (CO2) atravessam a membrana plasmática das células dos alvéolos pulmonares e dos capilares sanguíneos através do processo de:', 'Difusão simples', 'Difusão facilitada', 'Transporte ativo', 'Fagocitose', 'Osmose', 'a', 'Gases pequenos, apolares e sem carga (O2 e CO2) atravessam diretamente a bicamada lipídica a favor do gradiente de concentração por difusão simples.', 'difícil', 1],

    // Lição 63: Respiração Celular e Fermentação
    [63, 'ENEM 2023', 'Durante a produção de pão, o fermento biológico realiza um processo anaeróbio que libera um gás responsável por fazer a massa crescer. Esse processo é a:', 'Fermentação láctica', 'Fermentação alcoólica', 'Fermentação acética', 'Respiração aeróbia', 'Quimiossíntese', 'b', 'A levedura Saccharomyces cerevisiae realiza fermentação alcoólica, convertendo açúcares em etanol e gás carbônico (CO2). O CO2 liberado faz a massa do pão crescer.', 'fácil', 0],
    [63, 'USP (FUVEST) 2023', 'Na respiração aeróbia de uma célula eucariótica, a etapa que gera a maior quantidade de moléculas de ATP ocorre:', 'No citosol, durante a glicólise.', 'Na matriz mitocondrial, durante o Ciclo de Krebs.', 'Nas cristas mitocondriais, durante a cadeia respiratória.', 'No núcleo, durante a transcrição.', 'No citosol, durante a fermentação.', 'c', 'A fosforilação oxidativa (cadeia respiratória) ocorre nas cristas mitocondriais e produz a maior parte do ATP ao oxidar o NADH e o FADH2, utilizando O2 como aceptor final de elétrons.', 'médio', 0],
    [63, 'UNESP 2024', 'Após exercícios intensos, um atleta sente dor e fadiga muscular devido ao acúmulo de uma substância no tecido muscular. Essa substância é produto da:', 'Fermentação alcoólica', 'Fermentação láctica', 'Glicólise seguida de Ciclo de Krebs', 'Fotossíntese', 'Fosforilação oxidativa', 'b', 'Em condição de hipóxia (falta de oxigênio) durante o exercício intenso, as células musculares realizam fermentação láctica, produzindo ácido láctico, que contribui para a fadiga.', 'fácil', 0],
    [63, 'UNICAMP 2024', 'O ciclo de Krebs, também conhecido como ciclo do ácido cítrico, é uma via metabólica crucial da respiração celular. Onde esse ciclo ocorre nas células eucarióticas?', 'No citoplasma', 'Na matriz mitocondrial', 'Na membrana plasmática', 'No estroma do cloroplasto', 'Nas cristas mitocondriais', 'b', 'O ciclo de Krebs ocorre na matriz mitocondrial. Nessa etapa, o acetil-CoA é oxidado, produzindo CO2, ATP, NADH e FADH2.', 'médio', 0],
    [63, 'ENEM 2022', 'Qual é a função do oxigênio na respiração celular aeróbia?', 'Atuar como doador de elétrons na glicólise.', 'Combinar-se com o carbono para formar glicose.', 'Atuar como aceptor final de elétrons na cadeia respiratória, formando água.', 'Fornecer energia para o ciclo de Krebs.', 'Romper a molécula de glicose durante a glicólise.', 'c', 'O O2 atrai fortemente elétrons e atua no fim da cadeia respiratória nas cristas mitocondriais, recolhendo elétrons e prótons (H+) para formar água (H2O).', 'difícil', 1],

    // Lição 64: Fotossíntese e Quimiossíntese
    [64, 'ENEM 2023', 'Durante a etapa fotoquímica (fase clara) da fotossíntese, ocorre a quebra da molécula de água na presença de luz, liberando um gás essencial para a maioria dos seres vivos. Esse processo é conhecido como:', 'Ciclo de Calvin', 'Fotólise da água', 'Fosforilação cíclica', 'Fermentação', 'Quimiossíntese', 'b', 'A fotólise da água (quebra pela luz) ocorre nos tilacoides e resulta na produção de O2, prótons (H+) e elétrons que repõem os perdidos pela clorofila.', 'fácil', 0],
    [64, 'UNICAMP 2024', 'A fase química (fase escura) da fotossíntese é responsável pela fixação do carbono e síntese de carboidratos. Essa etapa utiliza a energia proveniente de ATP e o poder redutor de NADPH produzidos na fase clara, ocorrendo no:', 'Citosol', 'Matriz mitocondrial', 'Lúmen do tilacoide', 'Estroma do cloroplasto', 'Complexo golgiense', 'd', 'A fixação do CO2 (Ciclo de Calvin-Benson) acontece no estroma do cloroplasto, aproveitando o ATP e NADPH gerados na fase fotoquímica.', 'médio', 0],
    [64, 'USP (FUVEST) 2023', 'Determinadas bactérias no fundo do oceano, onde não há luz, produzem matéria orgânica a partir da oxidação de compostos inorgânicos (como sulfeto de hidrogênio). Esse processo autotrófico é denominado:', 'Fotossíntese', 'Respiração celular', 'Fermentação', 'Quimiossíntese', 'Decomposição', 'd', 'A quimiossíntese é a produção de matéria orgânica utilizando a energia química liberada pela oxidação de compostos inorgânicos, sem a dependência da luz solar.', 'médio', 0],
    [64, 'UNESP 2024', 'Qual é a molécula que atua como o principal aceptor de gás carbônico (CO2) durante o ciclo de Calvin na fotossíntese?', 'Glicose', 'RuBP (Ribulose 1,5-bisfosfato)', 'PGA (Ácido fosfoglicérico)', 'ATP', 'NADP+', 'b', 'A enzima Rubisco catalisa a fixação do CO2 ligando-o à RuBP (ribulose bisfosfato), um açúcar de 5 carbonos, iniciando a fase química.', 'difícil', 1],
    [64, 'ENEM 2022', 'Qual é o papel da clorofila na fotossíntese?', 'Capturar CO2 da atmosfera.', 'Reduzir a molécula de água.', 'Absorver a energia luminosa e excitar elétrons.', 'Sintetizar diretamente moléculas de glicose.', 'Atuar como coenzima no ciclo de Calvin.', 'c', 'A clorofila e outros pigmentos nos fotossistemas absorvem a luz, elevando os elétrons a níveis mais altos de energia, iniciando a cadeia de transporte de elétrons.', 'fácil', 0],

    // Lição 65: Divisão Celular: Mitose e Meiose
    [65, 'ENEM 2023', 'O processo de divisão celular que ocorre em células somáticas, resultando em duas células-filhas geneticamente idênticas à célula-mãe, é fundamental para o crescimento e renovação tecidual. Trata-se da:', 'Meiose I', 'Meiose II', 'Mitose', 'Fecundação', 'Conjugação', 'c', 'A mitose é a divisão equacional das células somáticas onde o número de cromossomos é mantido (2n → 2n + 2n), garantindo regeneração e crescimento.', 'fácil', 0],
    [65, 'USP (FUVEST) 2023', 'Durante a meiose, o emparelhamento dos cromossomos homólogos e a troca de fragmentos de cromátides não irmãs (crossing-over) ocorrem em qual fase?', 'Prófase I', 'Metáfase II', 'Anáfase I', 'Telófase II', 'Prófase da mitose', 'a', 'O crossing-over ou permutação ocorre durante o paquíteno da Prófase I da meiose, sendo crucial para a variabilidade genética.', 'médio', 0],
    [65, 'UNESP 2024', 'A não disjunção dos cromossomos homólogos durante a anáfase I da meiose na formação de gametas humanos pode resultar em condições como a:', 'Anemia falciforme', 'Fenilcetonúria', 'Síndrome de Down', 'Hemofilia', 'Daltonismo', 'c', 'Erros na separação (não disjunção) geram gametas aneuploides. Se um gameta com 24 cromossomos (com 2 cromossomos 21) fecundar um normal (23), surge a trissomia 21 (Síndrome de Down).', 'médio', 0],
    [65, 'UNICAMP 2024', 'A etapa do ciclo celular caracterizada pela intensa síntese de DNA e duplicação dos cromossomos, preparando a célula para a divisão, é a:', 'Fase G1', 'Fase S (Síntese)', 'Fase G2', 'Prófase', 'Citocinese', 'b', 'Na fase S (Síntese) da Interfase ocorre a replicação semiconservativa do DNA, de modo que cada cromossomo passa a ter duas cromátides-irmãs.', 'fácil', 0],
    [65, 'ENEM 2022', 'Qual é a principal diferença observada entre a anáfase I da meiose e a anáfase da mitose?', 'Na anáfase I há separação de cromátides-irmãs; na mitose há separação de homólogos.', 'Na anáfase I há separação de cromossomos homólogos; na mitose há separação de cromátides-irmãs.', 'Ambas apresentam separação de cromátides-irmãs, porém a meiose ocorre duas vezes.', 'Na anáfase I o fuso acromático se desfaz, na mitose ele permanece.', 'Na anáfase I não há migração de material genético para os polos.', 'b', 'A anáfase I da meiose é reducional, separando os pares de cromossomos homólogos. Já a anáfase da mitose é equacional, separando as cromátides-irmãs.', 'difícil', 1],

    // Lição 66: Ecologia: Cadeias e Teias Alimentares
    [66, 'ENEM 2023', 'Em uma cadeia alimentar, os decompositores (fungos e bactérias) desempenham um papel vital, atuando:', 'degradando a matéria orgânica morta e reciclando nutrientes para o ambiente', 'produzindo alimento por fotossíntese para os consumidores', 'como consumidores primários exclusivos de folhas', 'apenas sobre vegetais mortos para liberar oxigênio', 'como predadores de topo para controlar populações', 'a', 'Fungos e bactérias decompõem matéria orgânica de organismos mortos de todos os níveis tróficos, devolvendo compostos inorgânicos ao solo, fechando o ciclo da matéria.', 'fácil', 0],
    [66, 'USP (FUVEST) 2023', 'Considere a cadeia: Capim -> Gafanhoto -> Sapo -> Cobra -> Gavião. O fluxo de energia ao longo dessa cadeia:', 'É cíclico, retornando aos produtores através dos decompositores.', 'Aumenta a cada nível trófico devido ao acúmulo biológico.', 'É unidirecional e decrescente, pois parte da energia é dissipada como calor.', 'Permanece constante, garantindo que o gavião receba o mesmo que o gafanhoto.', 'É bidirecional, fluindo tanto dos produtores aos consumidores quanto o inverso.', 'c', 'A energia nos ecossistemas tem fluxo unidirecional e decrescente, pois em cada nível trófico grande parte da energia é gasta no metabolismo ou dissipada como calor (Regra dos 10%).', 'médio', 0],
    [66, 'UNESP 2024', 'O acúmulo de metais pesados (como o mercúrio) ao longo das teias alimentares, atingindo maiores concentrações nos predadores de topo, é um fenômeno conhecido como:', 'Eutrofização', 'Magnificação trófica (biomagnificação)', 'Sucessão ecológica', 'Bioindicação', 'Biorremediação', 'b', 'Substâncias não biodegradáveis tendem a se acumular nos tecidos. Como os predadores de topo comem muitos indivíduos do nível inferior, eles bioacumulam concentrações altíssimas (biomagnificação).', 'médio', 0],
    [66, 'UNICAMP 2024', 'Numa teia alimentar aquática, o fitoplâncton ocupa a posição de:', 'Consumidor primário', 'Consumidor secundário', 'Produtor', 'Decompositor', 'Consumidor terciário', 'c', 'O fitoplâncton (algas unicelulares e cianobactérias) é fotossintetizante e constitui a base produtora das cadeias alimentares aquáticas.', 'fácil', 0],
    [66, 'ENEM 2022', 'Qual pirâmide ecológica jamais poderá ser invertida e sempre terá a base mais larga que o topo?', 'Pirâmide de números', 'Pirâmide de biomassa', 'Pirâmide de energia', 'Pirâmide de indivíduos', 'Pirâmide de peso seco', 'c', 'Segundo as leis da termodinâmica, o fluxo de energia diminui de um nível trófico para o outro. Logo, a pirâmide de energia nunca pode ter um topo maior que a base (nunca se inverte).', 'difícil', 1],

    // Lição 67: Relações Ecológicas Harmoniosas e Desarmoniosas
    [67, 'ENEM 2023', 'Líquens são associações formadas por algas e fungos, onde a alga fornece alimento via fotossíntese e o fungo retém umidade e nutrientes minerais. Como ambos se beneficiam e a separação pode causar a morte, trata-se de:', 'Protocooperação', 'Mutualismo', 'Comensalismo', 'Amensalismo', 'Inquilinismo', 'b', 'O mutualismo (+/+) é uma relação simbiótica obrigatória em que as duas espécies associadas têm benefícios mútuos e frequentemente não sobrevivem se separadas na natureza.', 'fácil', 0],
    [67, 'USP (FUVEST) 2023', 'A rêmora possui uma ventosa no dorso e viaja presa ao tubarão, alimentando-se dos restos das presas dele sem prejudicá-lo ou ajudá-lo. Essa relação é um exemplo clássico de:', 'Comensalismo', 'Parasitismo', 'Predação', 'Mutualismo', 'Competição', 'a', 'O comensalismo é uma relação (+/0) onde uma espécie se beneficia obtendo alimento, enquanto a outra não sofre prejuízo nem recebe vantagem.', 'médio', 0],
    [67, 'UNESP 2024', 'As orquídeas e bromélias vivem sobre galhos de árvores altas para obterem mais luz solar, mas não retiram seiva da árvore hospedeira. Esse tipo de relação é classificado como:', 'Parasitismo', 'Epifitismo (Inquilinismo)', 'Amensalismo', 'Comensalismo', 'Mutualismo', 'b', 'O epifitismo é uma forma de inquilinismo (+/0) em plantas. As epífitas buscam suporte físico em árvores maiores, sem parasitar ou danificar a planta suporte.', 'fácil', 0],
    [67, 'UNICAMP 2024', 'A maré vermelha é causada pela proliferação excessiva de dinoflagelados, que liberam toxinas na água, causando a morte de peixes e outros organismos locais. A relação que os dinoflagelados estabelecem com os peixes mortos é chamada de:', 'Competição interespecífica', 'Amensalismo (Antibiose)', 'Predação', 'Comensalismo', 'Esclavagismo', 'b', 'No amensalismo (-/0), uma espécie inibe o crescimento ou sobrevivência de outra secretando substâncias tóxicas, sem obter um benefício direto (como se alimentar da outra).', 'difícil', 1],
    [67, 'ENEM 2022', 'Leões e hienas habitam a mesma savana africana e frequentemente disputam as carcaças de presas abatidas. Essa interação em que ambas as partes gastam energia na disputa por um recurso escasso é a:', 'Competição interespecífica', 'Competição intraespecífica', 'Protocooperação', 'Predação', 'Parasitismo', 'a', 'A disputa por recursos (alimento, território) entre indivíduos de espécies diferentes é a competição interespecífica (-/-), sendo prejudicial energeticamente para ambos.', 'médio', 0],

    // Lição 68: Ciclos Biogeoquímicos
    [68, 'ENEM 2023', 'A fixação biológica do nitrogênio atmosférico (N2), transformando-o em amônia (NH3), é realizada exclusivamente por:', 'Plantas leguminosas, através de suas raízes.', 'Animais herbívoros no processo digestivo.', 'Fungos saprófitos do solo.', 'Bactérias fixadoras, como as do gênero Rhizobium.', 'Cianobactérias presentes na transpiração.', 'd', 'O N2 só pode ser incorporado na biosfera por organismos procariontes fixadores (bactérias e cianobactérias), muitas vezes em simbiose com raízes de leguminosas.', 'médio', 0],
    [68, 'USP (FUVEST) 2023', 'Qual é o processo biológico principal que retira o dióxido de carbono (CO2) da atmosfera no ciclo do carbono?', 'Respiração celular', 'Decomposição orgânica', 'Fotossíntese', 'Queima de combustíveis fósseis', 'Fermentação alcoólica', 'c', 'A fotossíntese fixa o CO2 atmosférico, convertendo o carbono inorgânico em moléculas orgânicas (glicose), sendo a principal via de sequestro natural de carbono.', 'fácil', 0],
    [68, 'UNESP 2024', 'Durante o ciclo da água, as plantas devolvem grande quantidade de vapor d\'água para a atmosfera, um fenômeno fundamental para o microclima e regime de chuvas, conhecido como:', 'Condensação', 'Evapotranspiração', 'Precipitação', 'Infiltração', 'Lixiviação', 'b', 'A evapotranspiração engloba a evaporação direta da água do solo e a transpiração vegetal, onde as plantas perdem água na forma de vapor pelos estômatos.', 'fácil', 0],
    [68, 'UNICAMP 2024', 'Na etapa de nitrificação do ciclo do nitrogênio, as bactérias quimiossintetizantes nitrificantes oxidam a amônia (NH3) primeiro para nitrito (NO2-) e depois para nitrato (NO3-). Esse nitrato tem grande importância porque:', 'É a forma de nitrogênio mais prontamente absorvida pelas plantas.', 'É liberado imediatamente como gás (N2) para a atmosfera.', 'É a principal reserva de energia das raízes.', 'Atua como veneno para plantas invasoras.', 'Forma nódulos apenas nas raízes das orquídeas.', 'a', 'O nitrato (NO3-) é altamente solúvel em água e representa a forma predominante na qual as plantas assimilam o nitrogênio do solo para sintetizar proteínas.', 'médio', 0],
    [68, 'ENEM 2022', 'O uso excessivo de fertilizantes nitrogenados na agricultura pode levar à lixiviação do nitrato para os rios, provocando proliferação excessiva de algas, morte de peixes e anóxia hídrica. Esse desequilíbrio no ciclo recebe o nome de:', 'Eutrofização', 'Efeito estufa', 'Chuva ácida', 'Biomagnificação', 'Salinização', 'a', 'A eutrofização é o enriquecimento artificial dos corpos d\'água com nutrientes (N e P), gerando floração de algas que impede a entrada de luz e esgota o oxigênio por decomposição.', 'difícil', 1],

    // Lição 69: Biomas Brasileiros e Globais
    [69, 'ENEM 2023', 'Considerado a "caixa d\'água do Brasil", este bioma apresenta vegetação de savana, com árvores de troncos tortuosos e casca grossa, adaptadas ao fogo e a um clima com duas estações bem definidas. Trata-se do:', 'Cerrado', 'Caatinga', 'Pampa', 'Mata Atlântica', 'Pantanal', 'a', 'O Cerrado (savana brasileira) abriga as nascentes das principais bacias hidrográficas. Suas árvores possuem adaptações (escleromorfismo oligotrófico) ao fogo natural e solos ácidos.', 'fácil', 0],
    [69, 'USP (FUVEST) 2023', 'A Caatinga é um bioma exclusivamente brasileiro caracterizado por um clima semiárido. Qual adaptação morfológica é típica das plantas xerófitas nativas desse bioma?', 'Folhas largas e permanentemente verdes (perenifólias).', 'Raízes respiratórias (pneumatóforos).', 'Transformação de folhas em espinhos e caules suculentos (armazenam água).', 'Caule tipo estipe sem ramificações.', 'Grande presença de epífitas e lianas.', 'c', 'Para reduzir a perda de água por transpiração, as xerófitas da Caatinga transformam folhas em espinhos e utilizam caules suculentos (cladódios) que fazem fotossíntese e armazenam água.', 'médio', 0],
    [69, 'UNESP 2024', 'O maior bioma do Brasil possui enorme biodiversidade, clima equatorial úmido, pluviosidade altíssima e solos que, surpreendentemente, são pobres em nutrientes superficiais, sustentando-se pelo rápido ciclo da serrapilheira. É a:', 'Mata Atlântica', 'Floresta Amazônica', 'Pantanal', 'Mata de Araucárias', 'Zona dos Cocais', 'b', 'A Floresta Amazônica possui solo pobre (lixiviado), dependendo estritamente da ciclagem rápida da matéria orgânica depositada no chão (serrapilheira) pelos fungos e bactérias.', 'fácil', 0],
    [69, 'UNICAMP 2024', 'O bioma Mata Atlântica é um "hotspot" global de biodiversidade. Essa classificação (hotspot) significa que o bioma:', 'Está completamente preservado, sendo área intocada.', 'Possui alta taxa de endemismo e sofre grave ameaça de degradação.', 'Abriga espécies exóticas trazidas pelo homem.', 'Apresenta baixa biodiversidade, requerendo recuperação.', 'Tem seu clima modificado por vulcanismo ativo.', 'b', 'Um hotspot é uma região com altíssima biodiversidade e muitas espécies endêmicas (exclusivas) que já perdeu mais de 70% de sua cobertura vegetal original devido à ação humana.', 'médio', 0],
    [69, 'ENEM 2022', 'O Pantanal é um bioma de transição rico em biodiversidade. Sua principal característica abiótica, que rege toda a dinâmica da fauna e flora local, é:', 'A ocorrência de invernos rigorosos com geada constante.', 'A baixa umidade relativa do ar o ano inteiro.', 'O regime de enchentes anuais que alaga vastas planícies no verão.', 'A presença de solos formados por permafrost.', 'A existência exclusiva de manguezais costeiros.', 'c', 'O pulso de inundação anual define o Pantanal. As cheias periódicas na bacia do rio Paraguai criam zonas alagáveis sazonais que sustentam a dinâmica ecológica do bioma.', 'difícil', 1],

    // Lição 70: Impactos Ambientais e Poluição
    [70, 'ENEM 2023', 'O aumento excessivo da concentração de gases de efeito estufa (como CO2 e metano) retém radiação infravermelha, levando ao Aquecimento Global. Qual das atividades abaixo NÃO contribui primariamente para esse aumento?', 'Desmatamento de florestas tropicais.', 'Queima de combustíveis fósseis (carvão e petróleo).', 'Agropecuária com emissões de metano por ruminantes.', 'Uso de fontes de energia eólica e solar.', 'Queimadas e emissão de gases por indústrias.', 'd', 'A energia eólica e a solar são consideradas energias "limpas" e renováveis, pois não emitem gases de efeito estufa (GEE) durante a geração de eletricidade.', 'fácil', 0],
    [70, 'USP (FUVEST) 2023', 'Gases contendo dióxido de enxofre (SO2) e óxidos de nitrogênio (NOx), liberados na queima de carvão, reagem com o vapor d\'água na atmosfera. Esse fenômeno gera um impacto ambiental destrutivo para florestas e monumentos, conhecido como:', 'Destruição da camada de ozônio', 'Chuva ácida', 'Ilha de calor', 'Inversão térmica', 'Efeito estufa', 'b', 'Os óxidos reagem formando ácido sulfúrico e ácido nítrico, reduzindo o pH da chuva. A chuva ácida corrói calcário e prejudica solos e ecossistemas aquáticos.', 'médio', 0],
    [70, 'UNESP 2024', 'O descarte irregular de plásticos nos oceanos tem formado gigantescas "ilhas de lixo". Com a fotodegradação e ação das ondas, esses plásticos formam os microplásticos, cuja principal ameaça é:', 'Bloquear a luz solar, impedindo a quimiossíntese abissal.', 'Aquecer a superfície do oceano e derreter as calotas polares.', 'Entrar na cadeia alimentar ao ser ingerido por animais marinhos e absorver toxinas.', 'Aumentar o pH oceânico, causando acidificação das águas.', 'Eliminar o sal da água do mar.', 'c', 'Microplásticos são engolidos por plâncton, peixes e aves. Eles causam danos físicos no trato digestório, acumulam poluentes persistentes e chegam aos seres humanos pela dieta.', 'médio', 0],
    [70, 'UNICAMP 2024', 'No inverno, grandes centros urbanos sofrem com um fenômeno meteorológico em que uma camada de ar quente se sobrepõe a uma de ar frio próxima à superfície, impedindo a dispersão de poluentes. Trata-se da:', 'Ilha de calor', 'Chuva ácida', 'Inversão térmica', 'Magnificação trófica', 'Depressão atmosférica', 'c', 'A inversão térmica quebra o fluxo normal de convecção (onde o ar quente sobe e dissipa o ar sujo). Com o ar frio pesado preso embaixo, a fumaça fica retida perto do solo, causando doenças respiratórias.', 'fácil', 0],
    [70, 'ENEM 2022', 'O uso de gases CFCs (clorofluorocarbonetos) em aerossóis e refrigeração foi banido pelo Protocolo de Montreal. O principal motivo desse banimento foi que os CFCs:', 'Aumentam a eutrofização das águas continentais.', 'Causam mutações diretas no DNA por inalação.', 'Reagem na estratosfera, destruindo a camada de ozônio que filtra raios UV.', 'São os principais responsáveis pelo efeito estufa antrópico.', 'Geram chuva ácida com pH inferior a 3.', 'c', 'O átomo de cloro dos CFCs age como catalisador quebrando milhares de moléculas de ozônio (O3) em O2. O "buraco" na camada de ozônio permite maior incidência de radiação ultravioleta (UV) nociva.', 'difícil', 1],

    // Lição 71: Genética: Primeira e Segunda Lei de Mendel
    [71, 'ENEM 2023', 'Em ervilhas, a cor amarela da semente (V) é dominante sobre a verde (v). Do cruzamento entre dois indivíduos heterozigotos (Vv x Vv), qual a proporção fenotípica esperada na descendência (F1)?', '100% amarela', '3 amarelas para 1 verde', '1 amarela para 3 verdes', '2 amarelas para 2 verdes', '50% amarela e 50% verde', 'b', 'Ao cruzar Vv x Vv, o quadrado de Punnett gera: 1 VV (amarela), 2 Vv (amarelas) e 1 vv (verde). Portanto, a proporção fenotípica é 3 amarelas para 1 verde (75% a 25%).', 'fácil', 0],
    [71, 'USP (FUVEST) 2023', 'A Segunda Lei de Mendel (Segregação Independente) estuda a herança simultânea de duas ou mais características. Qual cruzamento clássico e sua proporção fenotípica representam essa lei num cruzamento duplo-heterozigoto (AaBb x AaBb)?', '1:2:1', '9:3:3:1', '3:1', '1:1:1:1', '9:7', 'b', 'No cruzamento de dois diíbridos (AaBb x AaBb), desde que os genes estejam em cromossomos diferentes, a proporção esperada de fenótipos é 9 (dominante p/ ambos) : 3 : 3 : 1 (recessivo p/ ambos).', 'médio', 0],
    [71, 'UNESP 2024', 'Cruzando-se maravilhas (Mirabilis jalapa) de flores vermelhas (VV) com flores brancas (BB), obtém-se 100% de flores cor-de-rosa (VB) na F1. Esse caso, onde o heterozigoto tem fenótipo intermediário, é um exemplo de:', 'Dominância completa', 'Codominância', 'Alelos múltiplos', 'Dominância incompleta (Herança intermediária)', 'Epistasia recessiva', 'd', 'Na dominância incompleta (ou semidominância), nenhum alelo domina o outro totalmente; o heterozigoto expressa um fenótipo intermediário (mistura das cores).', 'fácil', 0],
    [71, 'UNICAMP 2024', 'Um indivíduo tem o genótipo AabbCc. Considerando segregação independente, quantos tipos diferentes de gametas esse indivíduo pode formar?', '2', '4', '8', '16', '3', 'b', 'O número de gametas é 2^n, onde n é o número de pares heterozigotos. Temos Aa (1) e Cc (1), logo n=2. Os gametas possíveis são AbC, Abc, abC e abc (2^2 = 4 tipos).', 'médio', 0],
    [71, 'ENEM 2022', 'Em galinhas, o tipo de crista é determinado por dois pares de genes (E e R) com interação gênica não epistática. Ao cruzar indivíduos de crista noz (EeRr) entre si, qual das opções abaixo não representa um dos 4 fenótipos clássicos gerados?', 'Crista rosa', 'Crista ervilha', 'Crista andaluz', 'Crista simples', 'Crista noz', 'c', 'A interação dos genes E e R forma 4 fenótipos na proporção 9:3:3:1: Noz (E_R_), Rosa (eeR_), Ervilha (E_rr) e Simples (eerr). "Crista andaluz" não existe nessa interação.', 'difícil', 1],

    // Lição 72: Sistema ABO, Fator Rh e Alelos Múltiplos
    [72, 'ENEM 2023', 'O sistema sanguíneo ABO é um exemplo clássico de alelos múltiplos (polialelia). Uma pessoa de tipo sanguíneo O possui qual genótipo e que tipo de aglutinogênios nas hemácias?', 'Genótipo IAIB, antígenos A e B.', 'Genótipo ii, ausência de antígenos A e B.', 'Genótipo IAi, apenas antígeno A.', 'Genótipo IBi, apenas antígeno B.', 'Genótipo ii, antígenos O.', 'b', 'O tipo O é recessivo (ii) e caracteriza-se por não possuir glicoproteínas (aglutinogênios) A ou B na superfície das hemácias, sendo por isso o doador universal em emergências.', 'fácil', 0],
    [72, 'USP (FUVEST) 2023', 'A eritroblastose fetal (Doença Hemolítica do Recém-Nascido) ocorre devido à incompatibilidade do Fator Rh. Para que essa condição ocorra na segunda gestação, é necessário que:', 'Mãe seja Rh+ e o feto Rh-.', 'Mãe seja Rh+ e o pai Rh-.', 'Mãe seja Rh- e o primeiro filho tenha sido Rh+.', 'Mãe seja Rh- e o primeiro filho tenha sido Rh-.', 'Pai e mãe sejam Rh-.', 'c', 'A mãe (Rh-) ao gerar o primeiro filho (Rh+) entra em contato com o sangue dele no parto e produz anticorpos anti-Rh. Numa gestação futura de feto Rh+, esses anticorpos destroem as hemácias do feto.', 'médio', 0],
    [72, 'UNESP 2024', 'Se um homem de tipo sanguíneo AB e Fator Rh positivo heterozigoto (IAIB Rr) casar-se com uma mulher de tipo O negativo (ii rr), qual a probabilidade de terem uma criança de tipo A e Rh negativo?', '25%', '50%', '12,5%', '0%', '100%', 'a', 'Os gametas do pai para ABO são IA ou IB. Da mãe, i. Filhos podem ser IAi (A) ou IBi (B). 50% chance de A. Para o Rh: Rr x rr gera 50% Rr (Rh+) e 50% rr (Rh-). Multiplicando 1/2 x 1/2 = 1/4 (25%).', 'médio', 0],
    [72, 'UNICAMP 2024', 'Qual conceito genético explica o fato de os alelos IA e IB no sistema ABO se expressarem juntos num indivíduo heterozigoto (tipo AB), sem que um mascare o outro?', 'Dominância completa', 'Epistasia dominante', 'Codominância', 'Pleiotropia', 'Poligenia', 'c', 'Na codominância, os dois alelos dominantes se expressam simultaneamente e integralmente no fenótipo. As hemácias apresentam tanto o antígeno A quanto o B.', 'fácil', 0],
    [72, 'ENEM 2022', 'A cor da pelagem em coelhos é determinada por alelos múltiplos: C (aguti), c^ch (chinchila), c^h (himalaia) e c (albino), com a ordem de dominância C > c^ch > c^h > c. Qual o fenótipo do cruzamento de um chinchila (c^ch c) com um himalaia (c^h c)?', '50% chinchila, 50% himalaia', '25% chinchila, 50% himalaia, 25% albino', '50% chinchila, 25% himalaia, 25% albino', '75% chinchila, 25% himalaia', '100% aguti', 'c', 'Gametas 1: c^ch e c. Gametas 2: c^h e c. Cruzando: c^ch c^h (chinchila), c^ch c (chinchila), c^h c (himalaia), c c (albino). Proporção: 2 chinchilas (50%), 1 himalaia (25%), 1 albino (25%).', 'difícil', 1],

    // Lição 73: Heredogramas e Genética Ligada ao Sexo
    [73, 'ENEM 2023', 'No estudo de heredogramas, se pais fenotipicamente normais (sem a doença) têm uma filha afetada por uma anomalia genética, podemos concluir com certeza que a herança dessa doença é:', 'Autossômica dominante', 'Autossômica recessiva', 'Ligada ao cromossomo X recessiva', 'Ligada ao cromossomo Y', 'Mitocondrial', 'b', 'Para pais iguais terem um filho diferente, os pais são heterozigotos e a característica do filho é recessiva. Como é uma MENINA, não pode ser ligada ao X recessiva (pois o pai normal XDY teria dado XD para ela). Logo, é autossômica recessiva.', 'médio', 0],
    [73, 'USP (FUVEST) 2023', 'O daltonismo e a hemofilia são exemplos clássicos de herança ligada ao sexo. Em humanos, os genes para essas condições estão localizados no:', 'Cromossomo Y (porção não homóloga)', 'Cromossomo X (porção não homóloga)', 'Cromossomo X (porção homóloga)', 'Cromossomos autossômicos', 'DNA mitocondrial', 'b', 'Heranças ligadas ao sexo estão nos genes presentes no cromossomo X que não têm alelos correspondentes no cromossomo Y (porção não homóloga).', 'fácil', 0],
    [73, 'UNESP 2024', 'Um homem daltônico casa-se com uma mulher de visão normal, cujo pai era daltônico. Qual é a probabilidade de eles terem uma menina daltônica?', '0%', '25%', '50%', '75%', '100%', 'b', 'Homem: Xd Y. Mulher: XD Xd (herdada do pai XdY). Probabilidade geral: cruzamento XdY x XDXd gera meninas (XDXd, XdXd) e meninos (XDY, XdY). Uma menina daltônica (XdXd) corresponde a 1/4 (25%) dos filhos totais (ou 50% se já soubermos que é menina).', 'médio', 0],
    [73, 'UNICAMP 2024', 'Na genealogia, o quadrado hachurado (pintado) geralmente representa:', 'Uma mulher normal', 'Um homem normal', 'Uma mulher afetada pela característica estudada', 'Um homem afetado pela característica estudada', 'Gêmeos monozigóticos', 'd', 'Na padronização de heredogramas, quadrados representam sexo masculino, e os símbolos preenchidos (pintados/hachurados) indicam indivíduos afetados pelo fenótipo em estudo.', 'fácil', 0],
    [73, 'ENEM 2022', 'Algumas síndromes, como a calvície precoce, apresentam padrão de expressão diferente entre homens e mulheres dependendo dos níveis de testosterona. Esse tipo de herança, localizada em autossomos mas influenciada pelo sexo, é chamada de:', 'Herança ligada ao sexo', 'Herança restrita ao sexo (holândrica)', 'Herança influenciada pelo sexo', 'Herança mitocondrial', 'Epistasia dominante', 'c', 'Na herança influenciada pelo sexo, o gene é autossômico, mas se comporta como dominante num sexo (homens, na calvície) e recessivo noutro (mulheres), devido aos hormônios sexuais.', 'difícil', 1],

    // Lição 74: Biotecnologia, Engenharia Genética e DNA
    [74, 'ENEM 2023', 'A técnica de DNA recombinante permite introduzir um gene de interesse em um organismo receptor, criando um organismo geneticamente modificado. Para "cortar" o DNA em locais específicos, os cientistas utilizam:', 'DNA polimerase', 'Enzimas de restrição (endonucleases)', 'Plasmídeos', 'RNA mensageiro', 'Bacteriófagos', 'b', 'As enzimas de restrição, descobertas em bactérias, atuam como "tesouras moleculares", reconhecendo e cortando sequências específicas de pares de bases no DNA.', 'fácil', 0],
    [74, 'USP (FUVEST) 2023', 'A técnica de PCR (Reação em Cadeia da Polimerase) revolucionou a biologia forense e a medicina diagnóstica (como nos testes da COVID-19). Qual é o objetivo principal da PCR?', 'Traduzir RNA em proteínas', 'Amplificar (multiplicar) bilhões de cópias de uma sequência específica de DNA', 'Sequenciar genomas inteiros base por base', 'Extrair o DNA diretamente da célula', 'Inibir o crescimento de vírus na amostra', 'b', 'A PCR realiza ciclos de aquecimento e resfriamento com a enzima Taq Polimerase para multiplicar exponencialmente (amplificar) regiões específicas do DNA, permitindo análise a partir de amostras minúsculas.', 'médio', 0],
    [74, 'UNESP 2024', 'Na produção comercial de insulina humana, o gene humano da insulina é inserido em um pequeno anel de DNA bacteriano que funciona como um vetor de clonagem. Esse anel de DNA extracromossômico é chamado de:', 'Cromossomo circular', 'Nucleoide', 'Plasmídeo', 'Mesossomo', 'Píli', 'c', 'Plasmídeos são moléculas circulares de DNA extracromossômico bacteriano frequentemente usadas em biotecnologia como vetores para transferir genes estrangeiros para bactérias hospedeiras.', 'fácil', 0],
    [74, 'UNICAMP 2024', 'Organismos transgênicos, como a soja Roundup Ready, possuem um gene exógeno (de outra espécie). A transgenia baseia-se num princípio fundamental da genética, que afirma que o código genético é:', 'Degenerado', 'Ambigo', 'Universal', 'Mutável', 'Exclusivo', 'c', 'A universalidade do código genético significa que as mesmas trincas de bases (códons) codificam os mesmos aminoácidos em quase todos os seres vivos (de bactérias a humanos).', 'médio', 0],
    [74, 'ENEM 2022', 'A nova tecnologia CRISPR-Cas9 permite a edição precisa de genomas, onde o complexo utiliza uma molécula guia para encontrar a sequência alvo de DNA e inativar ou alterar genes. Essa molécula guia no complexo CRISPR é formada por:', 'Proteína (enzima Cas9 sozinha)', 'DNA complementar', 'RNA guia (gRNA)', 'Anticorpos monoclonais', 'Carboidrato de reconhecimento celular', 'c', 'O sistema CRISPR-Cas9 usa um pequeno pedaço de RNA sintetizado (o RNA guia ou gRNA) que é complementar à sequência de DNA alvo, orientando a enzima Cas9 exatamente para o local a ser editado.', 'difícil', 1]
];

$stmt = $pdo->prepare("INSERT INTO questions (lesson_id, exam_source, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation_text, difficulty, is_boss) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
$inserted = 0;
$errors = 0;
foreach ($questions as $q) {
    try { 
        $stmt->execute($q); 
        $inserted++; 
    } catch (Exception $e) { 
        $errors++; 
        echo "ERRO: " . $e->getMessage() . "\n"; 
    }
}
echo "Inseridas: {$inserted} | Erros: {$errors}\n";
