<?php
require_once __DIR__ . '/../config/db.php';
echo "=== Inserindo questões de Biologia ===\n\n";

$questions = [
    // [61] Citologia: Organelas e Funções
    [61, 'UFPR 2023', 'Em uma célula eucariótica, o processo de glicosilação de proteínas e empacotamento em vesículas secretoras ocorre predominantemente na seguinte organela:', 'Complexo golgiense', 'Retículo endoplasmático liso', 'Lisossomo', 'Peroxissomo', 'Mitocôndria', 'a', 'O complexo golgiense é responsável por modificar (como a glicosilação), empacotar e distribuir as proteínas sintetizadas no retículo endoplasmático rugoso para diferentes destinos na célula ou para secreção.', 'médio', 0],
    [61, 'UFMG 2024', 'Pesquisadores isolaram uma organela celular caracterizada por possuir dupla membrana, DNA próprio circular e capacidade de autoduplicação, atuando na geração de ATP. Essa organela é o:', 'Mitocôndria', 'Ribossomo', 'Centríolo', 'Lisossomo', 'Cloroplasto', 'a', 'As mitocôndrias possuem dupla membrana e DNA próprio (evidência da teoria endossimbiótica) e são o principal local de produção de ATP via respiração celular.', 'fácil', 0],
    [61, 'UERJ 2023', 'A adrenoleucodistrofia (ALD) é uma doença genética grave que afeta o metabolismo de ácidos graxos de cadeia muito longa, levando ao seu acúmulo. Esse acúmulo é causado por uma disfunção em qual organela citoplasmática responsável pela oxidação desses ácidos?', 'Peroxissomo', 'Lisossomo', 'Mitocôndria', 'Complexo golgiense', 'Retículo endoplasmático rugoso', 'a', 'Os peroxissomos contêm enzimas que quebram ácidos graxos de cadeia muito longa (beta-oxidação), além de atuarem na degradação de água oxigenada pela catalase.', 'difícil', 1],

    // [62] Membrana Plasmática e Transporte Celular
    [62, 'UFRGS 2024', 'Quando hemácias humanas são colocadas em uma solução de cloreto de sódio a 0,1% (hipotônica em relação ao meio intracelular), o que ocorre com o volume dessas células e que fenômeno explica isso?', 'Incham até sofrer hemólise, devido à osmose', 'Murcham e sofrem crenação, devido à osmose', 'Mantêm o volume, devido à bomba de sódio e potássio', 'Incham sem romper, devido ao transporte ativo', 'Murcham, devido à difusão facilitada', 'a', 'A água entra na célula (meio mais concentrado) por osmose. Como a hemácia não possui parede celular, o aumento excessivo de volume rompe a membrana plasmática (hemólise).', 'fácil', 0],
    [62, 'UEL 2023', 'O processo celular no qual partículas sólidas grandes, como bactérias, são englobadas por uma célula através da emissão de pseudópodes para formar um vacúolo digestivo é denominado:', 'Fagocitose', 'Pinocitose', 'Exocitose', 'Difusão simples', 'Osmose', 'a', 'A fagocitose é um tipo de endocitose em que a célula engloba partículas sólidas e grandes emitindo projeções da membrana chamadas pseudópodes, formando o fagossomo.', 'fácil', 0],
    [62, 'UEM 2024', 'A bomba de sódio e potássio é essencial para a manutenção do potencial de repouso das células nervosas. Sobre esse transporte, é correto afirmar que ocorre:', 'Contra o gradiente de concentração, com gasto de ATP, transportando 3 íons Na+ para fora e 2 íons K+ para dentro', 'A favor do gradiente de concentração, sem gasto de ATP, por difusão facilitada', 'Contra o gradiente de concentração, com gasto de ATP, transportando 2 íons Na+ para fora e 3 íons K+ para dentro', 'A favor do gradiente, transportando prótons por proteínas de canal', 'Contra o gradiente, via exocitose de ambos os íons simultaneamente', 'a', 'A bomba de Na+/K+ é um transporte ativo que gasta ATP para manter alta concentração de Na+ fora e K+ dentro da célula, movendo-os contra seus gradientes de concentração (3 Na+ saem, 2 K+ entram).', 'difícil', 1],

    // [63] Respiração Celular e Fermentação
    [63, 'MACKENZIE 2023', 'Durante a respiração celular aeróbica, a maior produção de ATP e a formação de água ocorrem na etapa denominada:', 'Cadeia respiratória', 'Glicólise', 'Ciclo de Krebs', 'Fermentação láctica', 'Fosforilação em nível de substrato', 'a', 'A cadeia respiratória (fosforilação oxidativa) na membrana mitocondrial interna gera a maior parte do ATP, sendo o oxigênio o aceptor final de elétrons que se une aos prótons para formar água.', 'médio', 0],
    [63, 'PUC-RS 2024', 'Um atleta fundista, após intenso esforço muscular, apresenta fadiga e dores nas pernas. O acúmulo de uma substância no tecido muscular é a causa principal. Que substância é essa e por qual processo é produzida?', 'Ácido láctico, por fermentação láctica', 'Ácido pirúvico, por glicólise anaeróbia', 'Etanol, por fermentação alcoólica', 'Ácido cítrico, pelo Ciclo de Krebs', 'Acetil-CoA, pela descarboxilação oxidativa', 'a', 'Na falta de oxigênio suficiente durante exercício intenso, as células musculares realizam fermentação láctica, acumulando ácido láctico (lactato), o que causa fadiga e dor.', 'fácil', 0],
    [63, 'UFSC 2023', 'No Ciclo de Krebs, que ocorre na matriz mitocondrial, uma molécula de acetil-CoA reage com o ácido oxaloacético para formar qual composto com 6 carbonos, que dá início ao ciclo?', 'Ácido cítrico', 'Ácido pirúvico', 'Ácido alfa-cetoglutárico', 'Ácido succínico', 'Ácido málico', 'a', 'A primeira reação do ciclo de Krebs envolve a combinação da acetil-CoA (2 carbonos) com o ácido oxaloacético (4 carbonos) para formar o ácido cítrico (citrato, 6 carbonos).', 'difícil', 1],

    // [64] Fotossíntese e Quimiossíntese
    [64, 'UnB 2024', 'Na fase fotoquímica da fotossíntese, a energia luminosa é utilizada para excitar elétrons da clorofila e realizar a quebra de uma molécula, liberando o gás oxigênio. Essa reação é conhecida como:', 'Fotólise da água', 'Ciclo de Calvin', 'Fosforilação cíclica', 'Carboxilação da RuBP', 'Redução do NADP+', 'a', 'A fotólise da água é a quebra da molécula de H2O pela luz, fornecendo elétrons para os fotossistemas, prótons para o lúmen e liberando O2 para a atmosfera.', 'médio', 0],
    [64, 'FATEC 2023', 'Organismos autotróficos quimiossintetizantes, como as bactérias nitrificantes, obtêm a energia necessária para a produção de compostos orgânicos a partir de:', 'Oxidação de substâncias inorgânicas', 'Absorção de energia luminosa', 'Decomposição de matéria orgânica morta', 'Fermentação de carboidratos', 'Respiração celular anaeróbica', 'a', 'A quimiossíntese utiliza a energia liberada pela oxidação de compostos inorgânicos (como amônia, nitrito, sulfeto de hidrogênio) para sintetizar matéria orgânica.', 'médio', 0],
    [64, 'IF-PR 2024', 'Durante a etapa química (ou fase escura) da fotossíntese, que ocorre no estroma dos cloroplastos, o dióxido de carbono é fixado na molécula de ribulose bisfosfato (RuBP) por intermédio de qual enzima crítica?', 'Rubisco', 'ATP sintase', 'Amilase', 'Hexoquinase', 'Desidrogenase lática', 'a', 'A Rubisco (Ribulose-1,5-bisfosfato carboxilase/oxigenase) é a enzima que catalisa a fixação inicial de CO2 na RuBP durante o Ciclo de Calvin.', 'difícil', 1],

    // [65] Divisão Celular: Mitose e Meiose
    [65, 'UFPR 2023', 'Em uma célula animal, a fase da mitose caracterizada pelo alinhamento dos cromossomos no plano equatorial da célula, formando a placa metafásica, é a:', 'Metáfase', 'Prófase', 'Anáfase', 'Telófase', 'Interfase', 'a', 'A metáfase é marcada pelo grau máximo de condensação cromossômica e pela organização dos cromossomos no equador da célula, presos às fibras do fuso.', 'fácil', 0],
    [65, 'UFMG 2024', 'O crossing-over (ou permutação) é um evento crucial para o aumento da variabilidade genética. Em qual fase específica da meiose I esse fenômeno ocorre?', 'Prófase I', 'Metáfase I', 'Anáfase I', 'Prófase II', 'Anáfase II', 'a', 'O crossing-over, que é a troca de segmentos entre cromátides não irmãs de cromossomos homólogos, ocorre na subfase paquíteno da Prófase I da meiose.', 'médio', 0],
    [65, 'UERJ 2023', 'A Síndrome de Down, na maioria dos casos, é causada pela presença de uma cópia extra do cromossomo 21. Esse erro cromossômico (aneuploidia) geralmente resulta de um fenômeno chamado de não disjunção, que ocorre mais frequentemente durante a:', 'Anáfase da meiose', 'Telófase da mitose', 'Prófase I da meiose', 'Fase S da interfase', 'Metáfase da mitose', 'a', 'A não disjunção ocorre quando cromossomos homólogos (na Anáfase I) ou cromátides irmãs (na Anáfase II) falham em se separar, resultando em gametas com cromossomos a mais ou a menos.', 'difícil', 1],

    // [66] Ecologia: Cadeias e Teias Alimentares
    [66, 'UFRGS 2024', 'Em uma cadeia alimentar composta por capim, gafanhotos, sapos, cobras e gaviões, qual nível trófico é ocupado pelos sapos?', 'Consumidor secundário', 'Produtor', 'Consumidor primário', 'Consumidor terciário', 'Decompositor', 'a', 'O capim é produtor, o gafanhoto é consumidor primário e o sapo, que se alimenta do gafanhoto, é o consumidor secundário.', 'fácil', 0],
    [66, 'UEL 2023', 'A energia que flui ao longo de uma cadeia alimentar diminui a cada nível trófico. Considerando a produtividade primária líquida (PPL), ela representa:', 'A energia total assimilada pelos produtores menos a energia gasta em sua respiração', 'A quantidade total de energia solar captada pelos produtores', 'A biomassa de consumidores secundários em um ecossistema', 'A taxa de fotossíntese de todos os seres fotossintetizantes sem descontar o consumo', 'A energia transferida para os decompositores no final da teia alimentar', 'a', 'A PPL é a quantidade de energia (matéria orgânica) que fica efetivamente disponível para o próximo nível trófico, ou seja, Produtividade Primária Bruta (PPB) menos a Respiração (R).', 'médio', 0],
    [66, 'UEM 2024', 'O processo de magnificação trófica (ou biomagnificação) ocorre quando compostos tóxicos não biodegradáveis, como os pesticidas organoclorados, se acumulam nos ecossistemas. Numa teia alimentar aquática, a maior concentração desses compostos será encontrada nos:', 'Consumidores de topo (ex: aves piscívoras)', 'Fitoplâncton', 'Zooplâncton', 'Peixes herbívoros', 'Decompositores microbianos', 'a', 'A biomagnificação faz com que substâncias tóxicas, que não são excretadas nem degradadas, tenham sua concentração multiplicada ao longo da cadeia, sendo máxima nos níveis tróficos mais altos.', 'difícil', 1],

    // [67] Relações Ecológicas Harmoniosas e Desarmoniosas
    [67, 'MACKENZIE 2023', 'As orquídeas vivem sobre os troncos das árvores para obter melhor iluminação para a fotossíntese, mas não retiram nutrientes nem prejudicam a árvore suporte. Essa relação ecológica interespecífica é denominada:', 'Epifitismo (Inquilinismo)', 'Parasitismo', 'Mutualismo', 'Amensalismo', 'Competição', 'a', 'O epifitismo é um tipo de inquilinismo onde uma planta usa a outra apenas como suporte (benefício para a epífita, indiferente para a hospedeira: +/0).', 'fácil', 0],
    [67, 'PUC-RS 2024', 'Líquens são associações ecológicas entre fungos e algas (ou cianobactérias). O fungo fornece um ambiente úmido e sais minerais, enquanto a alga fornece matéria orgânica produzida na fotossíntese. Esta associação obrigatória para a sobrevivência de ambos em certos ambientes é um exemplo de:', 'Mutualismo', 'Protocooperação', 'Comensalismo', 'Predação', 'Parasitismo', 'a', 'No mutualismo, ambas as espécies se beneficiam (+/+) e a relação é frequentemente tão íntima e dependente que não sobrevivem separados naqueles habitats.', 'médio', 0],
    [67, 'UFSC 2023', 'A erva-de-passarinho é uma planta que se fixa nos galhos de outras árvores, enviando raízes modificadas chamadas haustórios que penetram até o xilema da planta hospedeira, de onde extrai água e sais minerais. Trata-se de uma relação de:', 'Hemiparasitismo', 'Holoparasitismo', 'Epifitismo', 'Mutualismo', 'Amensalismo', 'a', 'Por retirar seiva bruta (xilema) e ainda realizar sua própria fotossíntese, a erva-de-passarinho é classificada como um parasita parcial, ou hemiparasita.', 'difícil', 1],

    // [68] Ciclos Biogeoquímicos (Água, Carbono, Nitrogênio)
    [68, 'UnB 2024', 'No ciclo do nitrogênio, a conversão do gás nitrogênio (N2) atmosférico em amônia (NH3), que será incorporada ao solo e utilizada pelos seres vivos, é realizada majoritariamente por:', 'Bactérias fixadoras de nitrogênio', 'Bactérias desnitrificantes', 'Fungos decompositores', 'Plantas leguminosas', 'Bactérias nitrificantes', 'a', 'A fixação do nitrogênio é realizada principalmente por bactérias (como as do gênero Rhizobium e cianobactérias) que possuem a enzima nitrogenase capaz de quebrar o N2.', 'médio', 0],
    [68, 'FATEC 2023', 'Qual processo biológico é o principal responsável pela retirada do dióxido de carbono (CO2) da atmosfera no ciclo global do carbono?', 'Fotossíntese', 'Respiração celular', 'Queima de combustíveis fósseis', 'Decomposição de matéria orgânica', 'Excreção de animais', 'a', 'A fotossíntese realizada por plantas, algas e cianobactérias fixa o CO2 atmosférico em compostos orgânicos, sendo o principal processo de sequestro de carbono biológico.', 'fácil', 0],
    [68, 'IF-PR 2024', 'Durante a nitrificação no solo, a amônia é convertida sequencialmente em nitrito e depois em nitrato. A conversão de nitrito (NO2-) em nitrato (NO3-) é realizada de forma quimiossintetizante pelas bactérias do gênero:', 'Nitrobacter', 'Nitrosomonas', 'Rhizobium', 'Pseudomonas', 'Azotobacter', 'a', 'A etapa de nitratação (oxidação de nitrito para nitrato) é realizada por bactérias quimioautotróficas do gênero Nitrobacter.', 'difícil', 1],

    // [69] Biomas Brasileiros e Globais
    [69, 'UFPR 2023', 'O bioma brasileiro caracterizado por um longo período de seca, vegetação com folhas pequenas e modificadas em espinhos, caules suculentos e raízes profundas, localizado predominantemente no Nordeste, é o(a):', 'Caatinga', 'Cerrado', 'Pampa', 'Pantanal', 'Mata Atlântica', 'a', 'A Caatinga é um bioma exclusivamente brasileiro de clima semiárido, com flora adaptada ao estresse hídrico (xerófitas).', 'fácil', 0],
    [69, 'UFMG 2024', 'O Cerrado brasileiro é conhecido como a "caixa d\'água do Brasil" e possui vegetação adaptada a solos ácidos e ricos em alumínio. Uma adaptação morfológica típica das árvores desse bioma é:', 'Troncos tortuosos e casca espessa', 'Folhas largas com ápice gotejador (latifoliadas)', 'Raízes respiratórias (pneumatóforos)', 'Ausência total de folhas no verão', 'Folhas com glândulas de sal', 'a', 'As árvores do Cerrado apresentam escleromorfismo oligotrófico: troncos retorcidos, casca espessa e raízes profundas, em parte como adaptação aos solos pobres e às queimadas naturais.', 'médio', 0],
    [69, 'UERJ 2023', 'O bioma global caracterizado por permafrost (solo permanentemente congelado), verões curtos, ausência de árvores de grande porte e dominância de musgos, líquens e arbustos rasteiros é denominado:', 'Tundra', 'Taiga (Floresta Boreal)', 'Floresta Temperada Decídua', 'Savana', 'Deserto Polar', 'a', 'A Tundra ocorre no extremo norte global; o permafrost impede o crescimento de raízes profundas, restringindo a vegetação a pequeno porte.', 'difícil', 1],

    // [70] Impactos Ambientais e Poluição
    [70, 'UFRGS 2024', 'A emissão de gases como dióxido de enxofre (SO2) e óxidos de nitrogênio (NOx) pelas indústrias e veículos reage com a umidade da atmosfera e precipita na forma de:', 'Chuva ácida', 'Efeito estufa', 'Inversão térmica', 'Destruição da camada de ozônio', 'Smog fotoquímico', 'a', 'O SO2 e NOx reagem com a água atmosférica formando ácidos sulfúrico e nítrico, que caem com as precipitações (chuva ácida), prejudicando solos, lagos e construções.', 'fácil', 0],
    [70, 'UEL 2023', 'O despejo excessivo de esgotos domésticos e fertilizantes agrícolas em lagos promove a proliferação exagerada de algas na superfície. Quando essas algas morrem, a sua decomposição por bactérias aeróbicas esgota o oxigênio da água, causando a morte de peixes. Esse processo é chamado de:', 'Eutrofização', 'Magnificação trófica', 'Lixiviação', 'Salinização', 'Maré vermelha', 'a', 'A eutrofização (ou eutrofização artificial) é o enriquecimento do corpo d\'água com nutrientes (nitratos e fosfatos), desencadeando um colapso no ecossistema aquático local.', 'médio', 0],
    [70, 'UEM 2024', 'Os clorofluorcarbonos (CFCs), gases antigamente usados em aerossóis e refrigeração, ao atingirem a estratosfera, sofrem fotólise pela radiação UV, liberando um elemento que catalisa a destruição da molécula de ozônio (O3). Que elemento altamente reativo é esse?', 'Radical livre de cloro', 'Radical livre de flúor', 'Dióxido de carbono', 'Gás metano', 'Dióxido de enxofre', 'a', 'O átomo de cloro liberado do CFC atua como catalisador na quebra do O3 em O2, sendo que um único cloro pode destruir milhares de moléculas de ozônio.', 'difícil', 1],

    // [71] Genética: Primeira e Segunda Lei de Mendel
    [71, 'MACKENZIE 2023', 'No cruzamento entre duas plantas de ervilha heterozigotas para a cor da semente (Vv), onde o alelo V (amarela) é dominante sobre v (verde), a proporção fenotípica esperada na descendência é de:', '3 amarelas para 1 verde', '1 amarela para 1 verde', '9 amarelas para 3 verdes', 'Todos amarelos', '1 amarela para 2 verdes e 1 branca', 'a', 'Pela 1ª Lei de Mendel (Vv x Vv), a descendência genotípica é 1 VV : 2 Vv : 1 vv. Como VV e Vv exibem fenótipo dominante, a proporção fenotípica é 3 amarelas : 1 verde.', 'fácil', 0],
    [71, 'PUC-RS 2024', 'Em ervilhas, a textura da semente lisa (R) domina a rugosa (r), e a cor amarela (V) domina a verde (v). Realizando-se o cruzamento de um duplo-heterozigoto (RrVv) com um duplo-recessivo (rrvv), qual a proporção genotípica esperada?', '1 RrVv : 1 Rrvv : 1 rrVv : 1 rrvv', '9 R_V_ : 3 R_vv : 3 rrV_ : 1 rrvv', '1 RRVV : 2 RrVv : 1 rrvv', '3 R_V_ : 1 rrvv', 'Todos RrVv', 'a', 'É um cruzamento-teste. O duplo heterozigoto forma gametas RV, Rv, rV, rv em iguais proporções (25% cada). O recessivo forma apenas rv. O resultado é 1:1:1:1 para os quatro genótipos possíveis.', 'médio', 0],
    [71, 'UFSC 2023', 'A segunda lei de Mendel (Segregação Independente) se aplica apenas sob qual condição em relação aos pares de alelos envolvidos no cruzamento?', 'Os pares de alelos devem estar localizados em pares de cromossomos homólogos diferentes', 'Os genes devem estar fortemente ligados no mesmo cromossomo (linkage)', 'Ocorrer sempre permuta (crossing-over) entre os genes no mesmo cromossomo', 'Haver dominância incompleta em ambos os loci', 'Estar no cromossomo sexual X (herança ligada ao sexo)', 'a', 'A 2ª Lei descreve a separação independente de genes que estão em cromossomos não homólogos distintos, o que permite o arranjo aleatório de gametas.', 'difícil', 1],

    // [72] Sistema ABO, Fator Rh e Alelos Múltiplos
    [72, 'UnB 2024', 'No sistema sanguíneo ABO, o tipo sanguíneo que é considerado o doador universal genérico em hemotransfusões de hemácias é o O negativo (O-). A explicação biológica para o tipo O poder doar para os demais é:', 'A ausência de aglutinogênios (antígenos) A e B na superfície de suas hemácias', 'A presença de aglutininas (anticorpos) anti-A e anti-B no plasma', 'A presença de aglutinogênios A e B na superfície de suas hemácias', 'A ausência de anticorpos no seu plasma', 'A presença de fator Rh em todas as células', 'a', 'Como as hemácias do tipo O não possuem os antígenos A nem B, elas não provocam reação de aglutinação (rejeição) pelo sistema imune de receptores tipo A, B ou AB.', 'fácil', 0],
    [72, 'FATEC 2023', 'A eritroblastose fetal (ou doença hemolítica do recém-nascido) pode ocorrer quando há incompatibilidade do fator Rh entre mãe e feto. Para que haja o risco dessa doença na segunda gestação, qual deve ser a combinação de Rh entre a mãe, o pai e o primeiro filho, respectivamente?', 'Mãe Rh negativo, Pai Rh positivo, 1º Filho Rh positivo', 'Mãe Rh positivo, Pai Rh negativo, 1º Filho Rh negativo', 'Mãe Rh positivo, Pai Rh positivo, 1º Filho Rh positivo', 'Mãe Rh negativo, Pai Rh negativo, 1º Filho Rh negativo', 'Mãe Rh positivo, Pai Rh negativo, 1º Filho Rh positivo', 'a', 'Se a mãe Rh- gestar um feto Rh+, ela se sensibiliza aos antígenos Rh (produzindo anticorpos anti-Rh). Em uma próxima gestação Rh+, os anticorpos maternos destroem as hemácias do feto.', 'médio', 0],
    [72, 'IF-PR 2024', 'A herança da cor da pelagem em coelhos é um caso de alelos múltiplos (polialelia), governada por 4 alelos (C > c^ch > c^h > c). O alelo C (aguti) é dominante sobre todos; c^ch (chinchila) domina himalaia e albino; c^h (himalaia) domina c (albino). Do cruzamento entre um chinchila (c^ch c^h) e um himalaia (c^h c), qual a probabilidade de nascer um filhote albino?', '0%', '25%', '50%', '75%', '12,5%', 'a', 'Os gametas do chinchila são (c^ch) e (c^h). Os do himalaia são (c^h) e (c). As combinações são: c^ch c^h (chinchila), c^ch c (chinchila), c^h c^h (himalaia) e c^h c (himalaia). Nenhuma combinação gera cc (albino).', 'difícil', 1],

    // [73] Heredogramas e Genética Ligada ao Sexo
    [73, 'UFPR 2023', 'O daltonismo (cegueira para cores verde e vermelho) possui herança recessiva ligada ao cromossomo X. Um homem daltônico casou-se com uma mulher de visão normal, que não possui o alelo para o daltonismo. A probabilidade de esse casal ter um filho do sexo masculino daltônico é:', '0%', '25%', '50%', '100%', '75%', 'a', 'O pai passa o cromossomo Y para seus filhos homens. Como a mãe é normal homozigota (X^D X^D), ela passará o cromossomo X normal para todos os filhos. Logo, nenhum filho homem será daltônico.', 'fácil', 0],
    [73, 'UFMG 2024', 'Em um heredograma, pais fenotipicamente normais têm um filho do sexo masculino e uma filha do sexo feminino afetados por uma doença genética grave. Este padrão sugere fortemente que a herança da doença é:', 'Autossômica recessiva', 'Autossômica dominante', 'Ligada ao X recessiva', 'Ligada ao X dominante', 'Restrita ao Y (holândrica)', 'a', 'Se pais normais têm filhos afetados, os pais são heterozigotos e o traço é recessivo. Por haver uma filha afetada de pai normal, não pode ser ligada ao X recessiva (se fosse, o pai teria que ser afetado). Logo, é autossômica recessiva.', 'médio', 0],
    [73, 'UERJ 2023', 'A hemofilia A é recessiva e ligada ao cromossomo X. Se uma mulher normal, cujo pai era hemofílico, tem filhos com um homem de coagulação normal, qual a chance de gerar uma filha hemofílica?', '0%', '25%', '50%', '75%', '100%', 'a', 'A mulher é portadora (X^H X^h) porque recebeu o X com hemofilia do pai. O marido é normal (X^H Y). As filhas receberão o X normal do pai obrigatoriamente, sendo portanto X^H X^H ou X^H X^h. Nenhuma filha será hemofílica (X^h X^h).', 'difícil', 1],

    // [74] Biotecnologia, Engenharia Genética e DNA
    [74, 'UFRGS 2024', 'As enzimas de restrição (ou endonucleases de restrição) são ferramentas biotecnológicas essenciais. A sua função natural nas bactérias, de onde são extraídas, e na engenharia genética é:', 'Cortar a molécula de DNA em sequências nucleotídicas específicas', 'Sintetizar RNA a partir de um molde de DNA', 'Unir (ligar) fragmentos de DNA isolados', 'Multiplicar o DNA bacteriano exponencialmente', 'Inserir genes humanos dentro de plasmídeos bacterianos', 'a', 'As enzimas de restrição reconhecem sequências palindrômicas e cortam o DNA. Na natureza, protegem a bactéria contra DNA de vírus invasores. Na biotecnologia, formam "fragmentos de DNA recombinante".', 'fácil', 0],
    [74, 'UEL 2023', 'A técnica de PCR (Reação em Cadeia da Polimerase) revolucionou a biologia molecular. Ela permite:', 'Amplificar in vitro bilhões de cópias de um segmento específico de DNA', 'Sequenciar completamente o genoma humano', 'Inserir o gene produtor de insulina em bactérias E. coli', 'Criar clones reprodutivos de mamíferos a partir de células adultas', 'Editar os genes embrionários para corrigir falhas cromossômicas', 'a', 'A PCR utiliza a enzima Taq polimerase para, através de ciclos de aquecimento e resfriamento, copiar exponencialmente regiões alvo do DNA em laboratório.', 'médio', 0],
    [74, 'UEM 2024', 'A tecnologia CRISPR-Cas9 baseia-se num sistema de defesa bacteriano. Para funcionar como ferramenta de edição genômica, o sistema requer o complexo proteico Cas9 associado a uma molécula de:', 'RNA guia (sgRNA)', 'DNA de transferência', 'MicroRNA (miRNA)', 'Enzima transcriptase reversa', 'Primase de DNA', 'a', 'A Cas9 é a nuclease que corta o DNA, mas ela precisa ser direcionada ao local exato do genoma por uma pequena molécula de RNA sintetizada sob medida (o RNA guia).', 'difícil', 1],

    // [75] Teorias Evolutivas e Neodarwinismo
    [75, 'MACKENZIE 2023', 'A teoria da evolução pela seleção natural foi proposta conjuntamente por Charles Darwin e outro importante naturalista britânico. Quem foi esse cientista?', 'Alfred Russel Wallace', 'Jean-Baptiste Lamarck', 'Gregor Mendel', 'Thomas Malthus', 'Charles Lyell', 'a', 'Wallace chegou de forma independente à mesma conclusão que Darwin sobre a seleção natural após observar a fauna do sudeste asiático e enviou um manuscrito a Darwin, motivando a publicação de "A Origem das Espécies".', 'fácil', 0],
    [75, 'PUC-RS 2024', 'Segundo a Teoria Sintética da Evolução (Neodarwinismo), quais são os dois principais fatores que geram a variabilidade genética dentro de uma população?', 'Mutação e recombinação gênica', 'Seleção natural e deriva genética', 'Uso e desuso e transmissão de caracteres adquiridos', 'Isolamento reprodutivo e especiação alopátrica', 'Migração e endemismo', 'a', 'O neodarwinismo agregou a genética de populações a Darwin: as mutações (criam novos alelos) e a recombinação gênica (embaralha os alelos via crossing-over e segregação na meiose) são as fontes de variação sobre as quais age a seleção.', 'médio', 0],
    [75, 'UFSC 2023', 'O mimetismo batesiano ocorre quando uma espécie não venenosa ou palatável evolui para se assemelhar a uma espécie tóxica. Este é um clássico resultado evolutivo gerado por qual força evolutiva?', 'Seleção natural', 'Deriva genética (Efeito fundador)', 'Mutação neutra direcionada', 'Isolamento reprodutivo pós-zigótico', 'Lei do uso e desuso', 'a', 'No mimetismo, indivíduos que, por mutação aleatória, apresentam semelhança com a espécie perigosa sofrem menor predação (seleção natural direcional), sobrevivendo mais e deixando mais descendentes com essa característica.', 'difícil', 1],

    // [76] Fisiologia Humana: Digestório e Circulatório
    [76, 'UnB 2024', 'No sistema digestório humano, o órgão onde ocorre a principal absorção de nutrientes e que possui as chamadas vilosidades e microvilosidades em sua mucosa é o:', 'Intestino delgado', 'Estômago', 'Intestino grosso', 'Fígado', 'Esôfago', 'a', 'O intestino delgado é o principal local de digestão química final e de absorção. Suas dobras, vilosidades e microvilosidades ampliam enormemente a área de contato com o quilo.', 'fácil', 0],
    [76, 'FATEC 2023', 'A bile é um fluido emulsificador de gorduras essencial na digestão. Ela é produzida pelo(a) [X] e armazenada no(a) [Y]. Os órgãos X e Y são, respectivamente:', 'Fígado e vesícula biliar', 'Pâncreas e duodeno', 'Estômago e vesícula biliar', 'Fígado e pâncreas', 'Vesícula biliar e intestino delgado', 'a', 'O fígado produz a bile (sem enzimas digestivas, mas rica em sais biliares), que segue para a vesícula biliar, onde é armazenada e concentrada antes de ser liberada no duodeno.', 'médio', 0],
    [76, 'IF-PR 2024', 'O coração humano possui quatro câmaras. O sangue rico em oxigênio (arterial), vindo dos pulmões, chega inicialmente ao coração por qual câmara e por meio de quais vasos?', 'Átrio esquerdo, através das veias pulmonares', 'Átrio direito, através das veias cavas', 'Ventrículo esquerdo, através da artéria aorta', 'Ventrículo direito, através da artéria pulmonar', 'Átrio esquerdo, através da artéria pulmonar', 'a', 'O sangue oxigenado nos pulmões retorna ao coração (átrio esquerdo) sendo transportado pelas 4 veias pulmonares (exceção, pois carregam sangue arterial).', 'difícil', 1],

    // [77] Fisiologia Humana: Nervoso e Endócrino
    [77, 'UFPR 2023', 'A fenda sináptica é o espaço entre dois neurônios por onde a comunicação química é realizada através de moléculas específicas chamadas de:', 'Neurotransmissores', 'Hormônios esteroides', 'Anticorpos', 'Enzimas hidrolíticas', 'Lipoproteínas', 'a', 'Os neurotransmissores (ex: acetilcolina, dopamina, serotonina) são liberados pelo terminal axônico na fenda e se ligam a receptores no neurônio pós-sináptico, propagando o sinal.', 'fácil', 0],
    [77, 'UFMG 2024', 'O hormônio responsável pela regulação da glicemia, diminuindo a concentração de glicose no sangue ao promover sua entrada nas células, é a [X], produzida pelas células beta do [Y].', 'Insulina, Pâncreas', 'Glucagon, Pâncreas', 'Adrenalina, Suprarrenal', 'Insulina, Fígado', 'Glicogênio, Fígado', 'a', 'A insulina é um hormônio proteico secretado pelas ilhotas de Langerhans no pâncreas que atua baixando a glicose no sangue e estimulando o armazenamento de glicogênio.', 'médio', 0],
    [77, 'UERJ 2023', 'O impulso nervoso percorre o axônio do neurônio devido a uma alteração transitória no potencial elétrico da membrana, causada pela abertura e fechamento de canais iônicos. A rápida entrada de íons Na+ na célula, invertendo a polaridade interna de negativa para positiva, corresponde à:', 'Despolarização', 'Repolarização', 'Hiperpolarização', 'Período refratário', 'Potencial de repouso', 'a', 'Quando o estímulo atinge o limiar, os canais de sódio voltagem-dependentes se abrem, o Na+ entra a favor do gradiente, despolarizando a membrana e gerando o potencial de ação.', 'difícil', 1],

    // [78] Imunologia, Vacinas e Soros
    [78, 'UFRGS 2024', 'As vacinas são agentes biológicos compostos por antígenos que estimulam o corpo a criar memória imunológica. Portanto, a vacinação promove uma imunização do tipo:', 'Ativa e artificial', 'Passiva e artificial', 'Ativa e natural', 'Passiva e natural', 'Inata e permanente', 'a', 'É ativa pois induz o próprio organismo a produzir anticorpos e células de memória, e é artificial por ser administrada profilaticamente pela medicina.', 'fácil', 0],
    [78, 'UEL 2023', 'Em casos de acidentes ofídicos (picadas de cobras venenosas), a pessoa deve receber a aplicação de soro antiofídico o mais rápido possível. Esse soro salva vidas porque contém:', 'Anticorpos específicos prontos contra a peçonha', 'Antígenos atenuados do veneno da cobra', 'Glóbulos brancos do cavalo imunizado', 'Células de memória de resposta imune rápida', 'Enzimas que digerem proteínas estruturais da cobra', 'a', 'O soro terapêutico confere imunização passiva, entregando uma grande carga de anticorpos pré-formados (geralmente em cavalos) para neutralizar o veneno circulante imediatamente.', 'médio', 0],
    [78, 'UEM 2024', 'Os linfócitos são peças fundamentais da imunidade adquirida. Os linfócitos T citotóxicos (CD8+) têm como principal função no organismo:', 'Destruir células infectadas por vírus e células tumorais através de apoptose induzida', 'Produzir e secretar anticorpos (imunoglobulinas) no plasma sanguíneo', 'Apresentar antígenos (APC) para os linfócitos B ativarem a fagocitose', 'Sintetizar citocinas que impedem a replicação do DNA viral na corrente sanguínea', 'Fagocitar bactérias extracelulares no local de uma inflamação aguda', 'a', 'Os linfócitos T CD8+ reconhecem antígenos estranhos apresentados no MHC classe I das próprias células do corpo e as destroem usando perfirinas e granzimas.', 'difícil', 1],

    // [79] Botânica: Grupos Vegetais
    [79, 'MACKENZIE 2023', 'As briófitas (como os musgos) são plantas de pequeno porte que habitam preferencialmente locais úmidos e sombreados. A restrição de tamanho nessas plantas ocorre principalmente devido à:', 'Ausência de tecidos condutores de seiva (xilema e floema)', 'Dependência da água para a reprodução', 'Falta de sementes e frutos', 'Fase gametofítica ser efêmera', 'Incapacidade de realizar fotossíntese eficientemente', 'a', 'Sem vasos condutores, a água é transportada lentamente célula a célula por difusão e osmose (avasculares), o que impede que atinjam grandes alturas.', 'fácil', 0],
    [79, 'PUC-RS 2024', 'As gimnospermas, como os pinheiros, foram o primeiro grupo vegetal na linha evolutiva a apresentar independência da água para a fecundação. A novidade evolutiva que permitiu essa independência foi o(a):', 'Tubo polínico originado a partir do grão de pólen', 'Surgimento da semente dura', 'Formação do estróbilo (cone)', 'Desenvolvimento de ovário e fruto', 'Raiz pivotante profunda', 'a', 'O grão de pólen (gametófito masculino parcialmente desenvolvido) é levado pelo vento até o óvulo. Lá, germina formando o tubo polínico, que conduz o gameta masculino diretamente à oosfera, sem necessidade de água.', 'médio', 0],
    [79, 'UFSC 2023', 'Nas angiospermas ocorre o fenômeno exclusivo da dupla fecundação. Nele, um dos núcleos espermáticos fecunda a oosfera (formando o zigoto 2n) e o segundo núcleo espermático funde-se a duas outras células do saco embrionário, gerando um tecido nutritivo. Que tecido é esse e qual a sua ploidia?', 'Endosperma secundário, triploide (3n)', 'Cotilédone, diploide (2n)', 'Endosperma primário, haploide (n)', 'Tegumento, diploide (2n)', 'Embrião, tetraploide (4n)', 'a', 'O segundo núcleo espermático (n) une-se aos dois núcleos polares (n + n) no saco embrionário, originando a célula-mãe do albúmen ou endosperma secundário, que é 3n.', 'difícil', 1],

    // [80] Zoologia: Invertebrados e Vertebrados
    [80, 'UnB 2024', 'A planária, um platelminto de vida livre, pertence a um grupo de animais cujo sistema digestório possui apenas uma abertura (a boca), funcionando tanto para a ingestão quanto para a eliminação. Classificamos esse sistema digestório como:', 'Incompleto', 'Completo', 'Ausente', 'Intracelular exclusivo', 'Extracelular radicular', 'a', 'Nos platelmintos e cnidários o sistema digestório é dito incompleto porque não há ânus; os resíduos não digeridos saem pela mesma abertura por onde entra o alimento (a boca).', 'fácil', 0],
    [80, 'FATEC 2023', 'Os artrópodes, que incluem insetos, aracnídeos e crustáceos, são o filo com maior diversidade animal do planeta. Duas características morfológicas fundamentais que definem este filo são:', 'Exoesqueleto de quitina e apêndices articulados', 'Simetria radial e presença de cnidócitos', 'Corpo mole e presença de manto', 'Endoesqueleto calcário e sistema ambulacrário', 'Corpo segmentado (metameria) e cerdas locomotoras de sílica', 'a', 'Artrópode significa "pés articulados". O sucesso evolutivo deve-se aos apêndices articulados adaptáveis e à carapaça protetora de quitina (exoesqueleto) que requer mudas ou ecdises.', 'médio', 0],
    [80, 'IF-PR 2024', 'Os anfíbios foram os primeiros vertebrados a explorar o ambiente terrestre, porém apresentam dependência da água. Além da reprodução, um dos motivos biológicos pelos quais a maioria dos anfíbios adultos vive perto da água ou em locais úmidos é a sua necessidade de realizar:', 'Respiração cutânea, exigindo pele fina e úmida', 'Excreção de amônia diretamente pelos poros', 'Termorregulação através da evaporação exclusiva', 'Hidratação bebendo água diretamente por fendas branquiais', 'Regeneração contínua das escamas', 'a', 'Apesar de possuírem pulmões, os dos anfíbios são simples (saculiformes). Uma grande parcela das trocas gasosas é feita através da pele, que não possui queratina impermeável e deve ser mantida úmida.', 'difícil', 1],

    // [143] Respiração Celular e Fotossíntese (Revisão Avançada)
    [143, 'UFPR 2023', 'A energia solar captada pelos cloroplastos é estocada em moléculas orgânicas. Na respiração aeróbia, o principal produto final no qual a energia química é transferida para as atividades celulares é:', 'ATP (Adenosina Trifosfato)', 'Glicose', 'NADH e FADH2', 'Oxigênio gasoso', 'Ácido pirúvico', 'a', 'O ATP é a "moeda energética" da célula, cuja quebra de suas ligações de fosfato libera energia utilizável pelo trabalho celular.', 'fácil', 0],
    [143, 'UFMG 2024', 'Durante a etapa química da fotossíntese (Ciclo de Calvin), que não requer luz diretamente, o dióxido de carbono absorvido é convertido em açúcar. Para que essa síntese ocorra, a fase química consome dois produtos diretos da fase fotoquímica, que são:', 'ATP e NADPH', 'ATP e NADH', 'Glicose e O2', 'ADP e NADP+', 'Água e Clorofila ativada', 'a', 'O ATP fornece a energia química e o NADPH fornece o poder redutor (elétrons e prótons) necessários para converter o CO2 em gliceraldeído-3-fosfato (G3P).', 'médio', 0],
    [143, 'UERJ 2023', 'Venenos como o cianeto (cianureto) atuam bloqueando o complexo citocromo c oxidase, o último complexo proteico da cadeia transportadora de elétrons. Isso leva à morte celular muito rapidamente porque:', 'Impede a redução do oxigênio a água e interrompe a fosforilação oxidativa', 'Bloqueia o ciclo de Krebs ao inibir as desidrogenases', 'Causa a ruptura mecânica das membranas mitocondriais e lisossomos', 'Consome rapidamente todo o ATP gerado pela glicólise, gerando lactato tóxico', 'Impede a entrada de piruvato na matriz mitocondrial', 'a', 'Ao bloquear o último passo do transporte de elétrons, o fluxo de elétrons para de acontecer e, com isso, o bombeamento de prótons é cessado. A ATP sintase não pode produzir ATP, levando à asfixia celular.', 'difícil', 1],

    // [144] Ecologia: Cadeias e Teias Alimentares (Revisão)
    [144, 'UFRGS 2024', 'Em uma representação ecológica, a pirâmide de energia nunca pode ser invertida, ao contrário das pirâmides de números e de biomassa. Isso se explica por qual princípio biológico?', 'O fluxo de energia é unidirecional e decrescente a cada nível trófico', 'A energia se reproduz exponencialmente dentro dos herbívoros', 'Os predadores de topo são sempre maiores e retêm mais calor', 'A fotossíntese retém 100% da energia solar incidente', 'Os decompositores reciclam a energia de volta aos produtores', 'a', 'De acordo com a 2ª Lei da Termodinâmica aplicada à ecologia, boa parte da energia é dissipada como calor na respiração e nas funções metabólicas a cada nível trófico; logo, a base produtora deve sempre possuir mais energia que os consumidores.', 'fácil', 0],
    [144, 'UEL 2023', 'A produtividade primária de um ecossistema marinho de mar aberto costuma ser maior em áreas de ressurgência. O termo ressurgência (ou upwelling) refere-se ao fenômeno no qual:', 'Correntes frias profundas, ricas em nutrientes inorgânicos, afloram à superfície iluminada', 'A radiação ultravioleta causa mutações nas algas planctônicas acelerando seu crescimento', 'Ocorrem marés muito altas que inundam manguezais próximos', 'Águas quentes ricas em corais migram para o oceano profundo', 'O excesso de CO2 atmosférico se dissolve massivamente tornando o oceano ácido', 'a', 'A água profunda traz para a zona fótica abundantes nitratos e fosfatos, originados da decomposição no fundo marinho. Ao encontrarem luz na superfície, o fitoplâncton prolifera intensamente.', 'médio', 0],
    [144, 'UEM 2024', 'No estudo das teias alimentares, o conceito de "espécie-chave" (keystone species) descreve espécies cuja remoção causa profundas alterações e até o colapso do ecossistema. Frequentemente, essas espécies atuam como predadores de topo porque:', 'Controlam as populações de herbívoros dominantes, impedindo o sobrepastoreio', 'São as únicas responsáveis pela decomposição de matéria animal', 'Competem diretamente com os produtores por luz e espaço', 'Polinizam todas as flores de uma floresta', 'Produzem a maior parte da biomassa da comunidade local', 'a', 'Predadores como os lobos de Yellowstone (ou lontras marinhas que predam ouriços) regulam as populações de níveis inferiores (controle "top-down"). Sem eles, os herbívoros superpopulosos dizimam os produtores primários.', 'difícil', 1],

    // [145] Relações Ecológicas Harmoniosas e Desarmoniosas (Revisão)
    [145, 'MACKENZIE 2023', 'Carrapatos fixam-se na pele de cachorros para se alimentar de seu sangue, causando coceira e potencialmente transmitindo doenças ao cão, mas dificilmente causando morte imediata. Esta relação interespecífica é chamada de:', 'Ectoparasitismo', 'Endoparasitismo', 'Predação', 'Amensalismo', 'Competição', 'a', 'Por viverem externamente sobre a pele e retirarem nutrientes do hospedeiro, os carrapatos são classificados como ectoparasitas (relação desarmônica + / -).', 'fácil', 0],
    [145, 'PUC-RS 2024', 'O "amensalismo" (ou antibiose) é uma relação desarmônica onde a presença de uma espécie inibe o crescimento da outra, geralmente pela liberação de substâncias tóxicas. Um exemplo clássico dessa interação é:', 'O fungo Penicillium, que secreta substâncias inibitórias impedindo o crescimento de bactérias', 'O cipó-chumbo, que suga a seiva do limoeiro', 'Cupins digerindo madeira com auxílio de protozoários intestinais', 'Corujas devorando ratos no campo', 'Plantas que florescem no mesmo período e atraem a mesma abelha', 'a', 'No amensalismo (0 / -), o fungo Penicillium notatum excreta penicilina natural, matando bactérias ao seu redor (o que não o beneficia diretamente como alimento, sendo um subproduto de defesa).', 'médio', 0],
    [145, 'UFSC 2023', 'O princípio da exclusão competitiva de Gause estabelece que duas espécies simpátricas (que vivem no mesmo local) não podem coexistir permanentemente se seus:', 'Nichos ecológicos forem idênticos, levando a uma competição severa', 'Habitats forem diferentes dentro da mesma floresta', 'Hábitos reprodutivos ocorrerem em estações do ano distintas', 'Nichos ecológicos sofrerem deslocamento de caracteres divergentes', 'Tamanhos populacionais forem regulados por predadores de topo', 'a', 'Duas espécies com nichos ecológicos sobrepostos de forma idêntica irão competir pelos mesmos recursos até que a mais eficiente exclua a outra (morte ou emigração).', 'difícil', 1],

    // [146] Genética: Primeira e Segunda Lei de Mendel (Revisão)
    [146, 'UnB 2024', 'O cruzamento-teste, criado por Mendel, serve para descobrir o genótipo de um indivíduo que apresenta um fenótipo dominante (que pode ser AA ou Aa). Para isso, cruza-se este indivíduo com um de fenótipo:', 'Recessivo (aa)', 'Dominante homozigoto (AA)', 'Dominante heterozigoto (Aa)', 'Co-dominante (AB)', 'Multialélico', 'a', 'Se o descendente possuir apenas traços dominantes, o indivíduo é AA. Se a descendência for 50% dominante e 50% recessiva, o indivíduo testado é Aa.', 'fácil', 0],
    [146, 'FATEC 2023', 'O termo epistasia refere-se a um fenômeno genético complexo onde:', 'Um par de alelos inibe (mascara) a expressão fenotípica de outro par de genes localizado em um locus diferente', 'Um único gene afeta a manifestação de diversas características fenotípicas simultaneamente', 'Dois alelos no mesmo locus se expressam ao mesmo tempo gerando fenótipo intermediário', 'Ocorre mutação numa sequência de DNA e causa a inativação cromossômica', 'Vários genes independentes se somam quantitativamente para determinar a altura da planta', 'a', 'A epistasia é uma interação gênica não-alélica. Um exemplo é a cor da pelagem de labradores, onde um gene de depósito de pigmento (ee) pode "ocultar" a ação do gene que define a cor preta ou marrom.', 'médio', 0],
    [146, 'IF-PR 2024', 'Considere três pares de alelos com segregação independente em indivíduos: Aa, Bb e Cc. Do cruzamento entre dois tri-heterozigotos (AaBbCc x AaBbCc), a probabilidade de nascer um descendente com fenótipo totalmente recessivo (aabbcc) é de:', '1/64', '1/16', '3/64', '9/64', '1/8', 'a', 'Sendo três eventos independentes, a chance de obter (aa) de Aa x Aa é 1/4. O mesmo para (bb) = 1/4 e para (cc) = 1/4. Pela regra do "e", multiplicamos as probabilidades: 1/4 x 1/4 x 1/4 = 1/64.', 'difícil', 1],

    // [147] Sistema ABO e Fator Rh (Revisão)
    [147, 'UFPR 2023', 'No sistema ABO, a ausência de domínio entre o alelo I^A e o alelo I^B resulta em indivíduos portadores de ambos os aglutinogênios (A e B) em suas hemácias, configurando um exemplo clássico de:', 'Codominância', 'Dominância incompleta (intermediária)', 'Epistasia recessiva', 'Pleiotropia', 'Alelo letal', 'a', 'Na codominância (I^A I^B), o fenótipo expressa as características integrais de ambos os alelos (sangue AB), não ocorrendo um fenótipo "intermediário" ou mistura de cores.', 'fácil', 0],
    [147, 'UFMG 2024', 'Um homem do tipo sanguíneo AB e Rh positivo (heterozigoto Rr) casou-se com uma mulher do tipo sanguíneo O e Rh negativo (rr). A probabilidade de terem um filho com tipo sanguíneo A e Rh negativo é de:', '25%', '0%', '12,5%', '50%', '75%', 'a', 'Tipo AB (I^A I^B) x O (ii) gera filhos tipo A (I^A i) com chance de 50% (1/2). Rh positivo heterozigoto (Rr) x Rh negativo (rr) gera filhos Rh negativo com chance de 50% (1/2). Multiplicando: 1/2 x 1/2 = 1/4 ou 25%.', 'médio', 0],
    [147, 'UERJ 2023', 'O fenótipo Bombaim (falso O) é provocado por uma interação epistática. Indivíduos com esse fenótipo genotípico homozigoto recessivo (hh) são incapazes de sintetizar o precursor da molécula de superfície dos grupos sanguíneos, chamado de antígeno H. Se uma mulher O falso (I^A I^B, hh) tiver filhos com um homem tipo O verdadeiro (ii, HH), o fenótipo das crianças poderá ser:', 'Sangue tipo A e sangue tipo B', 'Apenas sangue tipo AB', 'Apenas sangue tipo O', 'Apenas fenótipo Bombaim', 'Sangue tipo A, B e O verdadeiro', 'a', 'A mulher manda para as crianças um alelo H (já que o marido é HH, filhos serão Hh, logo manifestarão a enzima) e enviará o I^A ou o I^B. Os filhos serão portanto Hh I^Ai (tipo A) ou Hh I^Bi (tipo B).', 'difícil', 1],

    // [148] Biotecnologia, Engenharia Genética e DNA (Revisão)
    [148, 'UFRGS 2024', 'O processo celular natural no qual a molécula de DNA serve de molde para fabricar uma molécula de RNA mensageiro é chamado de:', 'Transcrição', 'Tradução', 'Replicação semiconservativa', 'Recombinação genética', 'Transformação bacteriana', 'a', 'A enzima RNA polimerase lê uma das fitas do DNA e forma, por emparelhamento de bases (U-A, C-G), um RNA mensageiro.', 'fácil', 0],
    [148, 'UEL 2023', 'A inserção de um gene produtor de toxina inseticida proveniente da bactéria Bacillus thuringiensis em sementes de milho torna a planta resistente a lagartas pragas. Esse milho é classificado como um organismo:', 'Transgênico (geneticamente modificado)', 'Mutante induzido por radiação', 'Clone in vitro', 'Híbrido natural de espécies intergenéricas', 'Organismo poliplóide', 'a', 'Os transgênicos são organismos que receberam e integraram em seu genoma um gene de uma espécie diferente (tecnologia do DNA recombinante) para exibir características novas.', 'médio', 0],
    [148, 'UEM 2024', 'No código genético humano e na maioria dos seres vivos, uma característica notável é a degenerescência. Isso significa que:', 'Um mesmo aminoácido pode ser codificado por mais de um tipo de códon', 'Um códon pode codificar vários tipos diferentes de aminoácidos aleatoriamente', 'O RNA mensageiro sofre degradação rápida no citoplasma pelos exonucleases', 'Ocorrem mutações frequentes nas bases de uracila', 'A leitura do código é feita na direção 3\' para 5\' nos ribossomos', 'a', 'Como existem 64 combinações possíveis de trincas (códons) para apenas 20 aminoácidos biológicos, a maioria dos aminoácidos apresenta mais de um códon correspondente, oferecendo resiliência a mutações silenciosas.', 'difícil', 1],

    // [149] Fisiologia Humana: Sistemas e Órgãos (Revisão Integrada)
    [149, 'MACKENZIE 2023', 'A urina é formada nos rins a partir da filtração do sangue. A unidade funcional e anatômica dos rins, onde ocorre a filtração glomerular, reabsorção e secreção tubular, é o:', 'Néfron', 'Ureter', 'Alvéolo', 'Corpúsculo pâncreatico', 'Bexiga', 'a', 'Cada rim possui aproximadamente 1 milhão de néfrons, onde glomérulos de Malpighi (filtração) e túbulos renais (reabsorção e secreção) fabricam a urina definitiva.', 'fácil', 0],
    [149, 'PUC-RS 2024', 'O ritmo respiratório basal de um ser humano em repouso é involuntário e controlado automaticamente pelo sistema nervoso central em resposta a alterações químicas no sangue. O principal estímulo para o aumento da frequência respiratória (hiperventilação) é o:', 'Aumento da concentração de dióxido de carbono (CO2) e queda do pH do sangue', 'Diminuição drástica de oxigênio (O2) nos alvéolos pulmonares', 'Aumento de ácido lático na musculatura esquelética', 'Dilatação das artérias coronárias pelo esforço', 'Aumento da concentração de hemoglobina', 'a', 'O centro respiratório localizado no bulbo encefálico é altamente sensível à acidificação do líquor e do sangue, promovida pelo aumento de CO2 em ácido carbônico. Ao detectar o CO2 alto, comanda o diafragma a contrair mais rápido.', 'médio', 0],
    [149, 'UFSC 2023', 'Ao longo do ciclo menstrual da mulher, o pico (aumento súbito) de qual hormônio hipofisário no meio do ciclo (cerca do 14º dia) é o evento fisiológico responsável direto pela indução da ovulação?', 'Hormônio Luteinizante (LH)', 'Hormônio Folículo-Estimulante (FSH)', 'Progesterona', 'Estrogênio (Estradiol)', 'Ocitocina', 'a', 'Sob efeito do estrogênio em alta no fim da fase folicular, a hipófise anterior libera um surto enorme de LH (pico de LH) que enfraquece a parede ovariana e causa o rompimento do folículo maduro liberando o ovócito.', 'difícil', 1],

    // [150] Imunologia, Vacinas e Soros (Revisão e Pandemias)
    [150, 'UnB 2024', 'Os primeiros defensores do sistema imunológico, as células que realizam fagocitose de forma não específica no local de uma ferida, são componentes da nossa imunidade inata. Uma das células fundamentais nesta etapa é o:', 'Macrófago', 'Linfócito B', 'Plasmócito', 'Linfócito T auxiliar (CD4+)', 'Hemácia', 'a', 'Os macrófagos (derivados de monócitos) e os neutrófilos são as principais células fagocíticas inatas do corpo, atuando na linha de frente e gerando inflamação.', 'fácil', 0],
    [150, 'FATEC 2023', 'A tecnologia das vacinas de RNA mensageiro (como algumas usadas contra a COVID-19) envolve a administração de nanopartículas lipídicas contendo o mRNA. O objetivo dessa estratégia vacinal é fazer com que as células do paciente:', 'Traduza o mRNA para produzir temporariamente a proteína viral, gerando antígenos endógenos', 'Integrem o mRNA viral definitivamente em seu núcleo, gerando um gene recombinante', 'Usem o RNA para criar anticorpos anti-vírus diretamente no retículo endoplasmático', 'Transformem-se em linfócitos T virais para matar os vírus circulantes', 'Sofram apoptose preventiva antes do vírus as infectar', 'a', 'O mRNA vacinal serve de molde nos ribossomos das células humanas para criar a proteína Spike do vírus. Esta proteína é exposta, e o sistema imune gera resposta e células de memória. O mRNA é logo degradado sem entrar no núcleo.', 'médio', 0],
    [150, 'IF-PR 2024', 'No contexto do HIV, as infecções oportunistas acometem os pacientes diagnosticados com AIDS devido à supressão grave do sistema imunitário. Qual é a principal célula-alvo destruída ao longo do tempo pela replicação do vírus do HIV?', 'Linfócito T auxiliar (CD4+)', 'Linfócito T citotóxico (CD8+)', 'Linfócito B (Plasmócito produtor de anticorpos)', 'Célula-tronco hematopoiética da medula óssea', 'Megacariócitos plaquetários', 'a', 'O HIV usa o receptor CD4 para entrar nos linfócitos T helper. Como estas células são os "comandantes" centrais da ativação da resposta imune celular e humoral, sua destruição colapsa todo o sistema.', 'difícil', 1],
];

$stmt = $pdo->prepare("INSERT INTO questions (lesson_id, exam_source, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation_text, difficulty, is_boss) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
$inserted = 0;
$errors = 0;
foreach ($questions as $q) {
    try { 
        $stmt->execute($q); 
        $inserted++; 
    } catch (Exception $e) { 
        $errors++; 
        echo "ERRO ao inserir lição {$q[0]}: " . $e->getMessage() . "\n"; 
    }
}
echo "\nInseridas: {$inserted} | Erros: {$errors}\n";
