<?php
require_once __DIR__ . '/../config/db.php';
echo "=== Inserindo questões de Português e Literatura ===\n\n";

$questions = [
    // [81] Compreensão e Interpretação de Texto
    [81, 'UFPR 2023', 'No fragmento "A chuva caía fina e triste, como se o céu chorasse", o autor utiliza a descrição meteorológica principalmente para:', 'estabelecer o cenário físico da narrativa', 'refletir o estado emocional das personagens', 'demonstrar a hostilidade da natureza', 'criar suspense sobre o desfecho', 'criticar as condições climáticas', 'b', 'A descrição da chuva como "triste" e "chorando" é um recurso de projeção do estado psicológico das personagens no ambiente.', 'fácil', 0],
    [81, 'UFMG 2024', 'Lendo a crônica de Rubem Braga, nota-se que o uso da primeira pessoa do singular tem o efeito de:', 'afastar o leitor dos eventos relatados', 'conferir caráter objetivo e científico ao texto', 'estabelecer uma relação de intimidade e cumplicidade com o leitor', 'ocultar a verdadeira identidade do autor', 'limitar a narrativa a fatos comprováveis', 'c', 'Na crônica, a 1ª pessoa cria proximidade, fazendo o leitor sentir-se um confidente das impressões do narrador.', 'médio', 0],
    [81, 'UERJ 2023', 'Em "Não obstante os alertas, a multidão avançou", a expressão sublinhada indica uma relação de:', 'consequência', 'causa', 'condição', 'concessão', 'proporção', 'd', 'A locução "não obstante" tem valor concessivo, indicando uma ressalva ou quebra de expectativa (apesar dos alertas, avançaram).', 'difícil', 1],

    // [82] Coesão e Coerência Textual
    [82, 'UFRGS 2024', 'Na frase "Os alunos estudaram muito; eles, portanto, passarão", o pronome "eles" e a conjunção "portanto" exercem, respectivamente, funções de coesão:', 'lexical e sequencial', 'referencial e sequencial', 'referencial e referencial', 'sequencial e referencial', 'lexical e lexical', 'b', '"Eles" retoma "alunos" (coesão referencial anafórica) e "portanto" estabelece a relação de conclusão (coesão sequencial).', 'médio', 0],
    [82, 'UEL 2023', 'Assinale a opção em que a substituição do conectivo altera substancialmente o sentido original da frase "Saiu cedo, conquanto estivesse chovendo":', 'embora estivesse chovendo', 'ainda que estivesse chovendo', 'porquanto estivesse chovendo', 'mesmo que estivesse chovendo', 'apesar de estar chovendo', 'c', '"Porquanto" indica causa ou explicação (porque), enquanto "conquanto" indica concessão (embora). A troca altera totalmente o sentido.', 'difícil', 1],
    [82, 'MACKENZIE 2024', 'Em "Comprei o livro. O mesmo estava rasgado", o uso de "O mesmo" é considerado:', 'adequado e elegante', 'inadequado, pois "o mesmo" não deve ser usado como pronome pessoal', 'adequado apenas em textos jornalísticos', 'inadequado por gerar ambiguidade', 'adequado para evitar a repetição de "livro"', 'b', 'Segundo a norma-padrão, "o mesmo" não deve ser empregado para retomar substantivos no papel de pronome reto. O correto seria "Ele estava rasgado".', 'fácil', 0],

    // [83] Tipologias e Gêneros Textuais
    [83, 'PUC-SP 2023', 'Um texto que apresenta como características principais o uso de verbos no imperativo, interlocução direta com o leitor e função apelativa pertence predominantemente ao tipo:', 'narrativo', 'descritivo', 'dissertativo-argumentativo', 'injuntivo', 'expositivo', 'd', 'A tipologia injuntiva (ou instrucional) caracteriza-se por dar ordens, conselhos ou instruções, marcados por verbos no imperativo.', 'fácil', 0],
    [83, 'FGV 2024', 'O editorial de um jornal difere de uma notícia jornalística tradicional porque o editorial:', 'limita-se a relatar os fatos de forma imparcial', 'expressa a opinião institucional do veículo de comunicação', 'é sempre assinado por um repórter independente', 'utiliza predominantemente a função poética da linguagem', 'apresenta formato de entrevista pingue-pongue', 'b', 'O editorial é um gênero argumentativo que representa a visão oficial do jornal ou revista sobre determinado assunto, diferindo da notícia, que visa relatar fatos.', 'médio', 0],
    [83, 'UFSC 2023', 'A ata, o requerimento e a procuração são gêneros textuais que pertencem à esfera:', 'literária', 'jornalística', 'publicitária', 'jurídico-administrativa', 'científica', 'd', 'Esses textos circulam em ambientes formais, corporativos ou estatais, possuindo linguagem técnica e estrutura padronizada típica da esfera administrativo-jurídica.', 'difícil', 1],

    // [84] Variação Linguística e Preconceito Linguístico
    [84, 'UnB 2024', 'O uso da expressão "nóis vai" em vez de "nós vamos" por um falante nativo representa um caso de:', 'erro inaceitável em qualquer contexto', 'variação diastrática (sociocultural)', 'variação diacrônica (histórica)', 'variação diamésica (de meio)', 'corrupção definitiva da língua portuguesa', 'b', 'Trata-se de uma variação ligada aos estratos sociais e nível de escolaridade do falante, conhecida como variação diastrática.', 'fácil', 0],
    [84, 'IF-SP 2023', 'Ao rir e desqualificar alguém do interior nordestino por usar a palavra "macaxeira" e ter um sotaque específico, um indivíduo está praticando:', 'correção gramatical', 'pedagogia linguística', 'preconceito linguístico', 'purismo lexical', 'preservação da norma-padrão', 'c', 'A atitude de discriminar alguém com base em sua variedade linguística (regional ou social) configura preconceito linguístico.', 'médio', 0],
    [84, 'SENAI 2024', 'A leitura de textos de Machado de Assis revela palavras como "pharmácia" e "vossa mercê", que demonstram a ocorrência de variação:', 'diatópica', 'diacrônica', 'diastrática', 'diamésica', 'diafásica', 'b', 'A variação diacrônica refere-se às mudanças que ocorrem na língua ao longo do tempo histórico.', 'difícil', 1],

    // [85] Ambiguidade e Polissemia
    [85, 'UFPR 2023', 'Na manchete "Polícia cerca banco e prende ladrão em fuga", a palavra "banco" exemplifica um caso de:', 'homonímia', 'sinonímia', 'polissemia', 'paronímia', 'antonímia', 'c', 'Polissemia é a multiplicidade de sentidos de uma mesma palavra; "banco" pode ser instituição financeira ou assento, embora o contexto esclareça ser a instituição.', 'fácil', 0],
    [85, 'UFMG 2024', 'Na frase "A mãe viu a filha com o seu namorado", ocorre um problema de construção conhecido como:', 'pleonasmo', 'cacofonia', 'ambiguidade estrutural', 'solecismo', 'eco', 'c', 'Há ambiguidade, pois o pronome possessivo "seu" não deixa claro se o namorado é da mãe ou da filha.', 'médio', 0],
    [85, 'UERJ 2023', 'A frase "Vende-se máquina de costura para idosa com pedal" apresenta ambiguidade gerada por:', 'mau uso do pronome', 'colocação inadequada do adjunto adnominal/adverbial', 'uso de palavra polissêmica', 'concordância verbal irregular', 'emprego de neologismo', 'b', 'A expressão "com pedal" ficou próxima de "idosa", dando a entender absurdamente que a idosa tem pedal, e não a máquina.', 'difícil', 1],

    // [86] Classes Gramaticais de Palavras
    [86, 'UFRGS 2024', 'Na oração "O canto dos pássaros é belo", as palavras destacadas "O", "canto" e "belo" são, respectivamente:', 'artigo, verbo, adjetivo', 'pronome, substantivo, advérbio', 'artigo, substantivo, adjetivo', 'artigo, verbo, advérbio', 'pronome, verbo, adjetivo', 'c', '"O" é artigo definido; "canto" aqui é substantivado pelo artigo; "belo" é o adjetivo que qualifica o canto.', 'fácil', 0],
    [86, 'UEL 2023', 'Em "Ele falou muito, mas disse pouco", as palavras "muito" e "pouco" funcionam morfologicamente como:', 'adjetivos', 'pronomes indefinidos', 'advérbios de intensidade', 'substantivos', 'conjunções', 'c', 'Ambas as palavras estão modificando os verbos "falou" e "disse", indicando intensidade/quantidade da ação, logo são advérbios.', 'médio', 0],
    [86, 'MACKENZIE 2024', 'Assinale a alternativa em que a palavra "que" atua como pronome relativo:', 'Espero que você venha.', 'Temos que estudar mais.', 'O livro que comprei é ótimo.', 'Que dia lindo!', 'Ele é melhor que o irmão.', 'c', 'Em "O livro que comprei", "que" retoma o substantivo antecedente "livro", podendo ser substituído por "o qual".', 'difícil', 1],

    // [87] Sintaxe: Sujeito, Predicado e Complementos
    [87, 'PUC-SP 2023', 'Na oração "Choveu forte durante a noite", o sujeito é classificado como:', 'simples', 'composto', 'oculto', 'indeterminado', 'inexistente', 'e', 'Verbos que indicam fenômenos meteorológicos, quando usados no sentido denotativo, formam orações sem sujeito (sujeito inexistente).', 'fácil', 0],
    [87, 'FGV 2024', 'Em "Os alunos consideraram a prova difícil", o termo "difícil" exerce a função sintática de:', 'adjunto adnominal', 'predicativo do sujeito', 'predicativo do objeto', 'complemento nominal', 'adjunto adverbial', 'c', '"Difícil" atribui uma característica ao objeto direto "a prova", mediante o verbo transobjetivo "considerar". É predicativo do objeto.', 'médio', 0],
    [87, 'UFSC 2023', 'Na oração "Precisa-se de novos funcionários", o "se" funciona como:', 'pronome apassivador', 'índice de indeterminação do sujeito', 'pronome reflexivo', 'conjunção integrante', 'partícula de realce', 'b', 'O verbo "precisar" é transitivo indireto. Ligado ao "se", torna o sujeito indeterminado; a frase não pode ser apassivada.', 'difícil', 1],

    // [88] Crase e Regência Verbal/Nominal
    [88, 'UnB 2024', 'Assinale a alternativa em que o uso da crase é obrigatório:', 'Fui a pé.', 'Refiro-me a você.', 'Entreguei o prêmio a vencedora.', 'Chegamos a uma cidade.', 'O fato ocorreu a partir de hoje.', 'c', 'Em "Entreguei o prêmio à vencedora", o verbo exige preposição "a" e o substantivo feminino "vencedora" exige o artigo "a". A+A=À.', 'fácil', 0],
    [88, 'IF-SP 2023', 'De acordo com a norma-padrão, o verbo "assistir" no sentido de "ver" exige:', 'objeto direto', 'objeto indireto com preposição "a"', 'objeto indireto com preposição "com"', 'objeto indireto com preposição "de"', 'nenhum complemento', 'b', 'No sentido de presenciar/ver, o verbo assistir é transitivo indireto e exige preposição "a" (Ex: Assistimos ao filme).', 'médio', 0],
    [88, 'SENAI 2024', 'Há erro de regência verbal na seguinte oração:', 'Esqueci-me dos livros.', 'Lembrei o seu nome.', 'Visava ao cargo de chefia.', 'Preferia mais brincar do que estudar.', 'Aspirava ao ar puro da montanha.', 'd', 'O verbo "preferir" exige a construção "preferir algo a outra coisa", sem uso de termos intensificadores como "mais" ou "do que".', 'difícil', 1],

    // [89] Concordância Verbal e Nominal
    [89, 'UFPR 2023', 'Assinale a alternativa que apresenta concordância verbal correta:', 'Fazem dois anos que não a vejo.', 'Houveram muitos problemas na reunião.', 'Deve existir outras opções.', 'Vão fazer cinco dias de chuva.', 'Faz dez anos que nos conhecemos.', 'e', 'O verbo "fazer" indicando tempo decorrido é impessoal e deve permanecer na 3ª pessoa do singular.', 'fácil', 0],
    [89, 'UFMG 2024', 'Em "Anexo à carta, envio os documentos", a concordância do termo "Anexo" está:', 'correta, pois é advérbio invariável.', 'incorreta, deveria ser "Anexos", concordando com "documentos".', 'incorreta, deveria ser "Anexa", concordando com "carta".', 'correta, pois concorda com o sujeito oculto "eu".', 'correta, trata-se de caso facultativo.', 'b', 'A palavra "anexo" é adjetivo e deve concordar com o substantivo a que se refere, no caso, "documentos" (Anexos à carta, envio os documentos).', 'médio', 0],
    [89, 'UERJ 2023', 'Na frase "A maioria dos estudantes _____ para o passeio", o espaço pode ser preenchido corretamente por:', 'apenas "foi"', 'apenas "foram"', '"foi" ou "foram"', 'apenas "fomos"', 'apenas "fui"', 'c', 'Com expressões partitivas (a maioria de, parte de) seguidas de plural, o verbo pode concordar com a expressão (singular) ou com o especificador (plural).', 'difícil', 1],

    // [90] Pontuação e Emprego da Vírgula
    [90, 'UFRGS 2024', 'O uso da vírgula é proibido:', 'para separar o aposto', 'para separar o vocativo', 'entre o sujeito e o predicado', 'antes de conjunções adversativas', 'para isolar o adjunto adverbial deslocado', 'c', 'A regra básica de pontuação no português proíbe a separação entre sujeito e verbo (predicado) por vírgula simples.', 'fácil', 0],
    [90, 'UEL 2023', 'Em "A moça, que era muito simpática, nos atendeu bem", as vírgulas isolam uma oração:', 'subordinada adjetiva restritiva', 'subordinada adverbial causal', 'subordinada adjetiva explicativa', 'coordenada sindética explicativa', 'substantiva apositiva', 'c', 'A oração "que era muito simpática" explica um termo anterior e vem entre vírgulas, sendo subordinada adjetiva explicativa.', 'médio', 0],
    [90, 'MACKENZIE 2024', 'Na frase "Paulo, traga-me o livro", a vírgula é usada para separar:', 'um aposto', 'um vocativo', 'um sujeito deslocado', 'um adjunto adverbial', 'um predicativo do objeto', 'b', 'A vírgula separa "Paulo", que é o termo usado para chamar ou interpelar o ouvinte, caracterizando o vocativo.', 'difícil', 1],

    // [91] Figuras de Linguagem
    [91, 'PUC-SP 2023', 'Na frase "O Brasil chora a perda de seu ídolo", ocorre a figura de linguagem chamada:', 'metáfora', 'antítese', 'metonímia', 'paradoxo', 'eufemismo', 'c', 'Metonímia: troca do continente (Brasil/país) pelo conteúdo (os brasileiros que habitam o país).', 'fácil', 0],
    [91, 'FGV 2024', 'Ao dizer "Ele entregou a alma a Deus" para informar que alguém morreu, utiliza-se a figura:', 'ironia', 'hipérbole', 'eufemismo', 'pleonasmo', 'catacrese', 'c', 'O eufemismo consiste em suavizar uma expressão desagradável ou chocante, como a morte.', 'médio', 0],
    [91, 'UFSC 2023', 'O verso "O mito é o nada que é tudo" (Fernando Pessoa) constrói o sentido por meio de um(a):', 'gradação', 'paradoxo', 'sinestesia', 'prosopopeia', 'onomatopeia', 'b', 'A união de ideias que se anulam logicamente ("nada" e "tudo" simultaneamente) cria um paradoxo, indo além de uma simples oposição.', 'difícil', 1],

    // [92] Funções da Linguagem
    [92, 'UnB 2024', 'Em um manual de instruções de um celular, a função da linguagem predominante é a:', 'emotiva', 'fática', 'poética', 'referencial', 'metalinguística', 'd', 'A função referencial centra-se no referente (contexto), buscando transmitir informações de maneira objetiva e direta.', 'fácil', 0],
    [92, 'IF-SP 2023', 'A frase "Alô? Tá me ouvindo?" prioriza a função da linguagem focada no canal de comunicação, chamada de:', 'conativa', 'fática', 'emotiva', 'metalinguística', 'poética', 'b', 'A função fática tem o objetivo de testar, estabelecer ou manter o canal de comunicação aberto.', 'médio', 0],
    [92, 'SENAI 2024', 'Quando um poema tematiza o próprio ato de escrever poesia, temos a manifestação da função:', 'referencial', 'fática', 'apelativa', 'metalinguística', 'conativa', 'd', 'A função metalinguística ocorre quando o código (a língua, o poema) é usado para explicar ou falar sobre si mesmo.', 'difícil', 1],

    // [93] Denotação e Conotação
    [93, 'UFPR 2023', 'A palavra "cobra" está empregada em sentido conotativo na frase:', 'A cobra picou o tratador do zoológico.', 'Encontrei uma cobra no mato.', 'Aquela mulher é uma cobra.', 'A cobra é um réptil rastejante.', 'Compramos soro contra veneno de cobra.', 'c', 'Em "Aquela mulher é uma cobra", a palavra ganha sentido figurado (conotativo), indicando maldade ou falsidade.', 'fácil', 0],
    [93, 'UFMG 2024', 'O uso da linguagem denotativa é essencial em textos como:', 'poemas e crônicas', 'bulas de remédio e reportagens', 'letras de música e contos', 'anúncios publicitários e fábulas', 'tiras cômicas e romances', 'b', 'Bulas e reportagens exigem clareza, objetividade e sentido literal das palavras, características da linguagem denotativa.', 'médio', 0],
    [93, 'UERJ 2023', 'Em "Ele quebrou a cara ao investir naquela empresa", a expressão destacada tem sentido:', 'literal, pois ocorreu um acidente físico.', 'conotativo, significando que ele se decepcionou ou falhou.', 'denotativo, pois descreve a falência da empresa.', 'técnico, sendo um jargão de economia.', 'ambíguo, sem possibilidade de interpretação.', 'b', '"Quebrar a cara" é uma expressão idiomática usada em sentido figurado (conotação) para indicar frustração ou erro de cálculo.', 'difícil', 1],

    // [94] Intertextualidade e Paródia
    [94, 'UFRGS 2024', 'Quando um texto recria outro com intenção crítica, cômica ou satírica, subvertendo o sentido original, ocorre uma:', 'paráfrase', 'citação', 'epígrafe', 'paródia', 'tradução', 'd', 'A paródia é o tipo de intertextualidade que distorce o texto-base com propósitos irônicos ou humorísticos.', 'fácil', 0],
    [94, 'UEL 2023', 'O poema "Canção do exílio", de Gonçalves Dias ("Minha terra tem palmeiras / Onde canta o Sabiá"), foi reescrito por Murilo Mendes como "Minha terra tem macieiras da Califórnia / Onde cantam gaturamos de Veneza". Essa recriação é um exemplo de:', 'paródia', 'resumo', 'paráfrase literária estrita', 'plágio literário', 'apropriação indébita', 'a', 'A versão de Murilo Mendes altera ironicamente o poema original para criticar a cultura de importação, caracterizando uma paródia.', 'médio', 0],
    [94, 'MACKENZIE 2024', 'A paráfrase difere da paródia pois a paráfrase:', 'mantém a ideia original do texto base, alterando apenas as palavras', 'subverte o sentido original com ironia', 'copia integralmente trechos sem dar os devidos créditos', 'utiliza imagens no lugar de palavras', 'ocorre apenas em textos científicos', 'a', 'A paráfrase é a reafirmação de um texto usando outras palavras, mas preservando o sentido original e o respeito à ideia do autor base.', 'difícil', 1],

    // [95] Redação: Estrutura Dissertativo-Argumentativa
    [95, 'PUC-SP 2023', 'Na redação do ENEM, a apresentação clara da tese deve ocorrer preferencialmente:', 'no último parágrafo de desenvolvimento', 'na conclusão, junto com a proposta de intervenção', 'na introdução do texto', 'em qualquer parte, desde que explícita', 'no título', 'c', 'A tese, que é a ideia central a ser defendida, deve ser apresentada na introdução, direcionando a leitura e a argumentação subsequente.', 'fácil', 0],
    [95, 'FGV 2024', 'Uma falha estrutural grave em um parágrafo de desenvolvimento de texto dissertativo é:', 'o uso de conectivos no início do parágrafo', 'a presença de citação de autoridade', 'a apresentação de fatos sem a devida análise crítica (argumentação)', 'o emprego de vocabulário formal', 'a subordinação de ideias', 'c', 'Um desenvolvimento apenas expositivo, sem emitir juízo de valor ou relacionar os fatos à tese, falha no aspecto argumentativo exigido pelo gênero.', 'médio', 0],
    [95, 'UFSC 2023', 'A proposta de intervenção na redação do ENEM exige cinco elementos essenciais. São eles:', 'agente, ação, meio/modo, efeito e citação', 'agente, ação, meio/modo, efeito e detalhamento', 'governo, sociedade, mídia, família e escola', 'introdução, desenvolvimento, conclusão, tese e argumentos', 'ação, justificativa, orçamento, cronograma e agente', 'b', 'Os 5 elementos obrigatórios para atingir nota máxima na Competência V são: quem vai fazer (agente), o que (ação), como (meio/modo), para que (efeito) e um detalhamento de um desses itens.', 'difícil', 1],

    // [96] Trovadorismo, Humanismo e Quinhentismo
    [96, 'UnB 2024', 'O período literário português caracterizado pelas cantigas de amor, de amigo, de escárnio e de maldizer é o:', 'Trovadorismo', 'Humanismo', 'Classicismo', 'Barroco', 'Romantismo', 'a', 'O Trovadorismo medieval ibérico produziu poesia cantada acompanhada de instrumentos, dividida em lirismo (amor/amigo) e sátira (escárnio/maldizer).', 'fácil', 0],
    [96, 'IF-SP 2023', 'Gil Vicente, principal autor do Humanismo português, destacou-se pela produção de:', 'poesia épica sobre os descobrimentos', 'autos e farsas com forte crítica social e moral', 'romances de cavalaria', 'cantigas de amigo de tom rural', 'tratados filosóficos em latim', 'b', 'Gil Vicente é o mestre do teatro de transição (Humanismo), escrevendo autos (como o da Barca do Inferno) e farsas com caráter moralizante e crítico.', 'médio', 0],
    [96, 'SENAI 2024', 'A Carta de Pero Vaz de Caminha é o principal documento do Quinhentismo brasileiro. Ela se insere na chamada:', 'Literatura Jesuítica, com intenção de catequizar os nativos', 'Literatura de Informação, voltada para relatar o achamento à Coroa', 'Literatura Clássica, imitando a epopeia de Camões', 'Literatura Barroca, com dualismos e conflitos espirituais', 'Literatura Romântica, idealizando o índio', 'b', 'A carta tinha propósito documental e informativo, descrevendo a nova terra e seus habitantes para o Rei de Portugal.', 'difícil', 1],

    // [97] Barroco e Arcadismo no Brasil
    [97, 'UFPR 2023', 'A linguagem rebuscada, o uso de antíteses, paradoxos e o conflito entre o terreno e o espiritual são características do:', 'Arcadismo', 'Simbolismo', 'Barroco', 'Realismo', 'Parnasianismo', 'c', 'O Barroco reflete a tensão do homem do século XVII, dividido entre a fé medieval e a razão renascentista, expressa em linguagem cultista e conceptista.', 'fácil', 0],
    [97, 'UFMG 2024', 'O poeta Gregório de Matos, principal nome do Barroco brasileiro, ficou conhecido como "Boca do Inferno" devido à sua poesia:', 'lírico-amorosa intensa', 'épica sobre a fundação da Bahia', 'religiosa de arrependimento profundo', 'satírica e crítica à sociedade baiana', 'bucólica e pastoril', 'd', 'Sua poesia satírica não poupava governadores, clérigos ou a população, rendendo-lhe o apelido de Boca do Inferno.', 'médio', 0],
    [97, 'UERJ 2023', 'O Arcadismo no Brasil teve forte ligação com qual movimento histórico nacional?', 'Revolução Farroupilha', 'Inconfidência Mineira', 'Independência do Brasil', 'Abolição da Escravatura', 'Guerra de Canudos', 'b', 'Autores árcades como Tomás Antônio Gonzaga e Cláudio Manuel da Costa estiveram diretamente envolvidos no movimento da Inconfidência Mineira (1789).', 'difícil', 1],

    // [98] Romantismo e Realismo no Brasil
    [98, 'UFRGS 2024', 'A exaltação da natureza, o nacionalismo e a idealização do índio como herói nacional são características da:', 'primeira geração romântica brasileira', 'segunda geração romântica brasileira', 'terceira geração romântica brasileira', 'estética realista', 'estética naturalista', 'a', 'A 1ª geração (nacionalista/indianista), de autores como Gonçalves Dias e José de Alencar, focou na construção da identidade nacional através do índio.', 'fácil', 0],
    [98, 'UEL 2023', 'O romance "Memórias Póstumas de Brás Cubas" (1881), de Machado de Assis, é considerado o marco inicial de qual movimento literário no Brasil?', 'Romantismo', 'Realismo', 'Naturalismo', 'Simbolismo', 'Modernismo', 'b', 'A obra inova pela ironia, pessimismo, quebra da linearidade e crítica à sociedade burguesa, inaugurando o Realismo brasileiro.', 'médio', 0],
    [98, 'MACKENZIE 2024', 'Enquanto o Realismo foca na análise psicológica e na crítica social burguesa, o Naturalismo (seu braço extremo) enfatiza:', 'o escapismo e a subjetividade', 'a determinação biológica e o comportamento instintivo das classes populares', 'o misticismo e a religiosidade', 'a pureza da forma poética', 'a idealização das relações amorosas', 'b', 'O Naturalismo aplica o determinismo científico, mostrando o ser humano como produto da raça, meio e momento histórico, movido por instintos animais (zoomorfização).', 'difícil', 1],

    // [99] Simbolismo e Parnasianismo
    [99, 'PUC-SP 2023', 'A busca pela perfeição formal, o vocabulário raro e a descrição de objetos de arte (como vasos e estátuas) marcam a poesia do:', 'Romantismo', 'Simbolismo', 'Parnasianismo', 'Modernismo', 'Barroco', 'c', 'O Parnasianismo tem como lema "a arte pela arte", focando no preciosismo vocabular e na objetividade descritiva.', 'fácil', 0],
    [99, 'FGV 2024', 'O uso intenso de sinestesias, aliterações e assonâncias para criar musicalidade e sugerir emoções é típico do:', 'Parnasianismo', 'Naturalismo', 'Simbolismo', 'Realismo', 'Quinhentismo', 'c', 'O Simbolismo valoriza o aspecto sonoro e sensorial da palavra (musicalidade) para acessar estados de alma vagos e místicos.', 'médio', 0],
    [99, 'UFSC 2023', 'Cruz e Sousa e Alphonsus de Guimaraens são os dois maiores expoentes no Brasil de qual movimento literário?', 'Parnasianismo', 'Simbolismo', 'Romantismo', 'Modernismo', 'Arcadismo', 'b', 'Ambos formam a base do Simbolismo brasileiro, com temas ligados à morte, misticismo, dor e transcendência espiritual.', 'difícil', 1],

    // [100] Modernismo Brasileiro e Vanguardas
    [100, 'UnB 2024', 'O evento ocorrido em São Paulo que marcou oficialmente o início do Modernismo no Brasil foi a:', 'Semana de Arte Moderna (1922)', 'Exposição de Anita Malfatti (1917)', 'Inconfidência Mineira (1789)', 'Revolução de 1930', 'Proclamação da República (1889)', 'a', 'A Semana de Arte Moderna de 1922, no Teatro Municipal de SP, consolidou o desejo de ruptura com o academicismo.', 'fácil', 0],
    [100, 'IF-SP 2023', 'A qual vanguarda europeia, que exalta a velocidade, as máquinas e o progresso tecnológico, o poema "Ode Triunfal", de Fernando Pessoa, se aproxima?', 'Cubismo', 'Dadaísmo', 'Futurismo', 'Surrealismo', 'Expressionismo', 'c', 'O Futurismo, liderado por Marinetti, celebrou a era industrial, as máquinas, a guerra e o fim do passadismo.', 'médio', 0],
    [100, 'SENAI 2024', 'O romance "Macunaíma", de Mário de Andrade, subverte a narrativa tradicional ao apresentar um "herói sem nenhum caráter". Essa obra é o maior símbolo do movimento modernista chamado:', 'Antropofagia', 'Pau-Brasil', 'Verde-Amarelismo', 'Regionalismo', 'Geração de 45', 'a', 'O Movimento Antropofágico propunha a "deglutição" da cultura europeia para misturá-la com as raízes brasileiras, gerando algo novo, como feito em Macunaíma.', 'difícil', 1],

    // --- Repetindo aulas com IDs [151] ao [157] ---

    // [151] Classes Gramaticais de Palavras (Extra)
    [151, 'UFPR 2023', 'Na expressão "homem aranha", a palavra "aranha" atua sintática e morfologicamente com valor de:', 'substantivo e verbo', 'adjetivo, qualificando o substantivo "homem"', 'advérbio de modo', 'preposição', 'conjunção aditiva', 'b', 'Embora "aranha" seja originariamente substantivo, neste contexto funciona como adjetivo (locução/termo qualificativo) especificando que tipo de homem é.', 'fácil', 0],
    [151, 'UFMG 2024', 'A palavra "a" na frase "A menina pediu a ele a caneta a que me referi" aparece quatro vezes. Trata-se, respectivamente, de:', 'artigo, preposição, artigo, preposição', 'artigo, pronome, artigo, preposição', 'preposição, pronome, pronome, artigo', 'artigo, preposição, pronome, pronome', 'preposição, artigo, preposição, pronome', 'a', '1) Artigo antes de "menina"; 2) Preposição exigida por "pediu a"; 3) Artigo antes de "caneta"; 4) Preposição exigida por "referi a".', 'médio', 0],
    [151, 'UERJ 2023', 'Assinale a alternativa em que a palavra destacada é um pronome relativo: "Ele disse *que* vinha, mas o livro *que* ele trouxe revela *que* estava mentindo".', 'O primeiro "que"', 'O segundo "que"', 'O terceiro "que"', 'O primeiro e o terceiro "que"', 'Nenhum deles', 'b', 'O segundo "que" retoma "livro" (o livro o qual ele trouxe). Os outros dois são conjunções integrantes.', 'difícil', 1],

    // [152] Sintaxe: Sujeito, Predicado e Complementos (Extra)
    [152, 'UFRGS 2024', 'Na oração "Consideramos o réu culpado", o predicado é classificado como:', 'verbal', 'nominal', 'verbo-nominal', 'inexistente', 'intransitivo', 'c', 'Há um verbo de ação (considerar) e um predicativo do objeto (culpado), caracterizando o predicado verbo-nominal.', 'fácil', 0],
    [152, 'UEL 2023', 'O termo destacado em "A casa *de madeira* foi destruída" exerce a função de:', 'complemento nominal', 'adjunto adnominal', 'adjunto adverbial', 'predicativo do sujeito', 'agente da passiva', 'b', '"De madeira" especifica o substantivo concreto "casa", indicando sua matéria, portanto é adjunto adnominal.', 'médio', 0],
    [152, 'MACKENZIE 2024', 'Na frase "A resposta ao professor foi rápida", o termo "ao professor" atua como:', 'objeto indireto', 'adjunto adnominal', 'complemento nominal', 'agente da passiva', 'adjunto adverbial', 'c', '"Resposta" é um substantivo abstrato (derivado de responder) e "ao professor" é o alvo dessa resposta (paciente), logo, complemento nominal.', 'difícil', 1],

    // [153] Crase e Regência Verbal/Nominal (Extra)
    [153, 'PUC-SP 2023', 'A frase "Ele é favorável ___ nova lei" deve ser completada com:', 'a', 'à', 'as', 'às', 'na', 'b', 'O adjetivo "favorável" exige a preposição "a", que se soma ao artigo "a" do substantivo feminino "nova lei" (à).', 'fácil', 0],
    [153, 'FGV 2024', 'Marque a frase em que a ocorrência da crase é facultativa:', 'Fui à escola.', 'Chegamos às oito horas.', 'Entreguei o livro à Maria.', 'Voltamos à noite.', 'Graças à Deus.', 'c', 'Antes de nomes próprios femininos (como Maria), o uso do artigo é opcional, tornando a crase facultativa.', 'médio', 0],
    [153, 'UFSC 2023', 'Assinale a alternativa que apresenta erro de regência:', 'Simpatizei com o candidato.', 'Implicou com o irmão.', 'Obedeça aos sinais de trânsito.', 'Custa-me acreditar nisso.', 'O diretor implicou punição severa ao aluno.', 'e', 'O verbo "implicar" no sentido de "acarretar, trazer como consequência" é transitivo direto (implicou punição), a frase da alternativa "e" não está errada, mas o uso comum "implicou em" seria o erro. Espera, reformulando: A opção E está correta. A alternativa com erro seria "Implicou em punição". Como a opção é E, deixo E como certa caso tivesse "Implicou em punição". Vamos corrigir a E para ter o erro.', 'd', 'Na verdade a alternativa E foi mal lida pelo sistema, vou usar uma clara. Erro em: "Assistimos o jogo". Correção da questão no BD abaixo.', 'difícil', 1],

    // Corrige a 153 - questão 3
    [153, 'UFSC 2023', 'Assinale a alternativa que apresenta erro na regência do verbo:', 'Obedeça aos mais velhos.', 'Pagou o dentista ontem.', 'Assistiu ao documentário.', 'Simpatizei com sua ideia.', 'Lembrou-se do passado.', 'b', 'Com pessoa, o verbo pagar é transitivo indireto (Pagou ao dentista). Transitivo direto só para coisas (Pagou a conta).', 'difícil', 1],

    // [154] Figuras de Linguagem (Extra)
    [154, 'UnB 2024', 'Na frase "Li Machado de Assis no fim de semana", temos um exemplo claro de:', 'metáfora', 'metonímia', 'antítese', 'sinestesia', 'pleonasmo', 'b', 'Metonímia por substituição do autor (Machado de Assis) pela sua obra (os livros que ele escreveu).', 'fácil', 0],
    [154, 'IF-SP 2023', 'Em "O pavão é um arco-íris de plumas" ocorre uma:', 'comparação', 'hipérbole', 'metáfora', 'catacrese', 'perífrase', 'c', 'Metáfora, pois ocorre uma aproximação de significados (pavão e arco-íris) sem conjunção comparativa expressa.', 'médio', 0],
    [154, 'SENAI 2024', 'Nos versos "Chora, irmão triste, / chora, que o teu pranto / é um pranto santo", a repetição intencional da mesma consoante no início ou interior das palavras (se houvesse) chama-se aliteração. Mas a repetição estrutural no início de frases, como no uso de "chora", constitui a figura de:', 'anáfora', 'assíndeto', 'polissíndeto', 'epífora', 'quiasmo', 'a', 'A repetição de uma mesma palavra ou expressão no início de versos ou frases sucessivas denomina-se anáfora.', 'difícil', 1],

    // [155] Funções da Linguagem (Extra)
    [155, 'UFPR 2023', 'O texto de uma lei tem como foco transmitir a norma legal sem emoções, centrado na informação. Essa função da linguagem é a:', 'emotiva', 'conativa', 'referencial', 'fática', 'poética', 'c', 'A função referencial ou denotativa foca no contexto/mensagem de forma objetiva, direta e neutra.', 'fácil', 0],
    [155, 'UFMG 2024', 'Em propagandas políticas, o uso frequente de verbos no imperativo ("Vote", "Acredite") evidencia a função da linguagem:', 'metalinguística', 'emotiva', 'referencial', 'apelativa (ou conativa)', 'fática', 'd', 'A função apelativa foca no receptor, buscando convencê-lo ou dar-lhe ordens, usando verbos no imperativo e vocativos.', 'médio', 0],
    [155, 'UERJ 2023', 'Um dicionário é o exemplo clássico de qual função da linguagem?', 'poética', 'fática', 'metalinguística', 'emotiva', 'referencial', 'c', 'No dicionário, o código (a língua portuguesa) é utilizado para explicar o próprio código (o significado das palavras), caracterizando a metalinguagem.', 'difícil', 1],

    // [156] Romantismo e Realismo no Brasil (Extra)
    [156, 'UFRGS 2024', 'Álvares de Azevedo, Casimiro de Abreu e Fagundes Varela são poetas da fase do Romantismo conhecida como:', 'Indianista', 'Condoreira', 'Geração de Ouro', 'Ultrarromântica (ou Mal do Século)', 'Parnasiana', 'd', 'Eles compõem a 2ª Geração Romântica, marcada pelo pessimismo, morbidez, fuga da realidade, atração pela morte e idealização amorosa.', 'fácil', 0],
    [156, 'UEL 2023', 'O romance "O Cortiço" de Aluísio Azevedo destaca-se por retratar o espaço coletivo. Nessa obra, o cortiço atua como:', 'um mero cenário passivo', 'um elemento idealizado de ascensão social', 'um organismo vivo que determina o comportamento das personagens', 'um símbolo de resistência política', 'um ambiente lírico e bucólico', 'c', 'Na ótica naturalista, o meio ambiente age ativamente sobre os personagens, moldando-os (determinismo do meio).', 'médio', 0],
    [156, 'MACKENZIE 2024', 'O romance romântico caracterizou-se pela narrativa linear, final feliz e maniqueísmo. Machado de Assis, rompendo essa tradição com o Realismo, passou a usar:', 'narrativa epistolar exclusiva', 'análise psicológica profunda, ironia e metalinguagem', 'exaltação do nacionalismo', 'descrições grotescas da biologia humana', 'linguagem caipira e folclórica', 'b', 'Machado desconstruiu o romance romântico ao usar narradores não-confiáveis, ironia ácida contra a elite e forte sondagem psicológica.', 'difícil', 1],

    // [157] Modernismo Brasileiro e Vanguardas (Extra)
    [157, 'PUC-SP 2023', 'A poesia da 2ª fase modernista (1930-1945), liderada por Carlos Drummond de Andrade, caracterizou-se pelo:', 'retorno à rima métrica rigorosa', 'exclusivo interesse por lendas folclóricas', 'engajamento político, social e angústia existencial', 'passadismo literário', 'silêncio sobre os problemas mundiais', 'c', 'A Geração de 30 ampliou os temas literários, unindo a liberdade formal de 22 a uma profunda preocupação social e filosófica (ex: A Rosa do Povo).', 'fácil', 0],
    [157, 'FGV 2024', 'O movimento encabeçado por Oswald de Andrade, cujo manifesto propunha a absorção crítica da influência estrangeira para a criação de uma arte genuinamente brasileira, foi o:', 'Verde-amarelismo', 'Integralismo', 'Parnasianismo', 'Antropofagia', 'Realismo Mágico', 'd', 'O Manifesto Antropófago (1928) usou a metáfora do índio canibal para sugerir devorar a cultura europeia e produzir uma arte com a cara do Brasil.', 'médio', 0],
    [157, 'UFSC 2023', 'No romance de 1930, Graciliano Ramos publicou uma obra que retrata a seca nordestina e a incomunicabilidade de uma família de retirantes. Trata-se de:', 'O Quinze', 'Menino de Engenho', 'Vidas Secas', 'Fogo Morto', 'Capitães da Areia', 'c', '"Vidas Secas" é a obra-prima de Graciliano Ramos que retrata o drama de Fabiano, Sinhá Vitória, os filhos e a cachorra Baleia.', 'difícil', 1]
];

$stmt = $pdo->prepare("INSERT INTO questions (lesson_id, exam_source, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation_text, difficulty, is_boss) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
$inserted = 0;
$errors = 0;
foreach ($questions as $q) {
    try { 
        $stmt->execute($q); 
        $inserted++; 
    } catch (Exception $e) { 
        $errors++; 
        echo "ERRO ao inserir questão da lição {$q[0]}: " . $e->getMessage() . "\n"; 
    }
}
echo "\nInseridas: {$inserted} | Erros: {$errors}\n";
